### PR TITLE
Respect limited opus sampling rates when building trancoding command

### LINKED ISSUE #7635: [10.8.0 - beta2] Transcoding of audio files fails because of incorrect output codec parameter.
### Please describe your bug

Transcoding of audio files does not work correctly in 10.8.0 beta 2 because a parameter in the ffmpeg command line is incorrect. Specifically, setting a sample rate of 44.1kHz while using the opus codec as output will fail, because opus does not support 44.1 kHz sample rates.

Example ffmpeg command line:
`` /usr/lib/jellyfin-ffmpeg/ffmpeg -i file:"/mnt/media/music/Eminem/Relapse (2009)/CD 01/Eminem - Relapse - 05 - Bagpipes from Baghdad.flac" -threads 0 -vn -ab 128000 -ac 2 -ar 44100 -id3v2_version 3 -write_id3v1 1 -y "/mnt/process/transcode/jellyfin/c13649e1959c1d92e29a51b96290c979.opus"``

This fails with the error message:
```
Stream mapping:
  Stream #0:0 -> #0:0 (flac (native) -> opus (libopus))
Press [q] to stop, [?] for help
[libopus @ 0x56309830d1c0] Specified sample rate 44100 is not supported
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
```
The problem is independent of input file format.

Running the command without specifying the option ``-ar 44100``, or changing it to ``-ar 48000`` fixes the problem and transcoding happens as expected:

``/usr/lib/jellyfin-ffmpeg/ffmpeg -i file:"/mnt/media/music/Eminem/Relapse (2009)/CD 01/Eminem - Relapse - 05 - Bagpipes from Baghdad.flac" -threads 0 -vn -ab 128000 -ac 2 -id3v2_version 3 -write_id3v1 1 -y "/mnt/process/transcode/jellyfin/c13649e1959c1d92e29a51b96290c979.opus"``

```
Stream mapping:
  Stream #0:0 -> #0:0 (flac (native) -> opus (libopus))
.
.
size=    4614kB time=00:04:43.05 bitrate= 133.5kbits/s speed=45.8x
```

### Jellyfin Version

10.8.0

### if other:

beta 2

### Environment

```markdown
- OS: Ubuntu 20.04
- Virtualization: None
- Clients: Symfonium (android)
- Browser: N/A
- FFmpeg Version: jellyfin-ffmpeg 4.4.1-4-focal
- Playback Method: transcode
- Hardware Acceleration: N/A
- Reverse Proxy: nginx
```

### Jellyfin logs

_No response_

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Shadowghost**
Opus only supports specific sampling rates, so we need to translate the requested sampling rate to a supported one.

This PR upsamples to the next higher available sampling rate

Fixes #7635

### CODE REVIEW

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 1]
```diff
@@ -5370,12 +5370,33 @@ public string GetProgressiveAudioFullCommandLine(EncodingJobInfo state, Encoding
                 audioTranscodeParams.Add("-ac " + state.OutputAudioChannels.Value.ToString(CultureInfo.InvariantCulture));
             }
 
-            // opus will fail on 44100
+
```
Comment (crobibero) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:5373]:
```suggestion
```

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 2]
```diff
@@ -5370,12 +5370,33 @@ public string GetProgressiveAudioFullCommandLine(EncodingJobInfo state, Encoding
...
+                        case < 24000:
+                            sampleRate = 16000;
+                            break;
+                        case < 48000:
+                            sampleRate = 24000;
+                            break;
+                        default:
+                            sampleRate = 48000;
+                            break;
+                    }
```
Comment (crobibero) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:5397]:
```suggestion
                    sampleRate = sampleRate.Value switch
                    {
                        < 12000 => 8000,
                        < 16000 => 12000,
                        < 24000 => 16000,
                        < 48000 => 24000,
                        _ => 48000
                    };
```

**Review by crobibero — APPROVED** [review]

**Review by nyanmisaka — APPROVED** [review]

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 3]
```diff
@@ -5370,12 +5370,22 @@ public string GetProgressiveAudioFullCommandLine(EncodingJobInfo state, Encoding
...
-            // opus will fail on 44100
             if (!string.Equals(state.OutputAudioCodec, "opus", StringComparison.OrdinalIgnoreCase))
             {
-                if (state.OutputAudioSampleRate.HasValue)
+                // opus only supports specific sampling rates
+                var sampleRate = state.OutputAudioSampleRate;
+                if (sampleRate.HasValue)
                 {
-                    audioTranscodeParams.Add("-ar " + state.OutputAudioSampleRate.Value.ToString(CultureInfo.InvariantCulture));
+                    sampleRate = sampleRate.Value switch
```
Comment (Bond-009) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:5379]: Make a new variable so we don't need to do `.Value` again

**Review by Bond-009 — APPROVED** [review]

**Comment by cjlewis999** [comment]
In my opinion, there is a discussion in the issue from which this pull request originates that should be considered before any changes are made:

https://github.com/jellyfin/jellyfin/issues/7635
