### PR TITLE
Fix recursive children lookup of folders

### LINKED ISSUE #6193: Playback Error when playing/shuffling collections
**Describe the bug**
It seems like collections can't be shuffled properly. (or at all?)
No problems playing back some automated collections, but user made ones don't work.

**System (please complete the following information):**
 - OS: Debian Server
 - Clients: not working on JMP, new vue web, current web, android.
 - Browser: Firefox 89 and Chromium Version 92.0.4503.0 
 - Jellyfin Version: 10.7.5
 - Installed Plugins: <https://volkor.me/gPNU.png>
 - Reverse Proxy: nginx, also tested without it.
 - Base URL: none
 - Networking: direct
 - Storage: local

**To Reproduce**

1. Create a collection (with anything, I tested with TV, and music)
2. Try to shuffle playlist.
3. get Playback Error: This client isn't compatible with the media and the server isn't sending a compatible media format.
4. Cry

**Expected behavior**
It should be shuffle and play the collection.

**Server Logs**
None, I had tail -f running and saw nothing.

**FFmpeg Logs**
None, doesn't seem to get that far.

**Browser Console Logs**
Firefox: `Uncaught (in promise) undefined`
Chromium: `Uncaught (in promise) undefined` - `index.html#!/list.ht…0b2bc3e2998025906:1`

**Screenshots**
https://volkor.me/e0k7.png

**Additional context**
Doesn't just seem to be me, I found this post when looking.
https://old.reddit.com/r/jellyfin/comments/jmw9v3/error_on_audio_collection_shuffle/
I asked on IRC but I'm impatient, and looked through here to see if there had been an issue created.

I've also tested it on another jellyfin server I have access to, and discovered that all the 'system/plugin' created collections work fine, but when I create one myself, it doesn't play. https://volkor.me/16h7.png

### LINKED ISSUE #7226: [Issue]: Unable to Play or Shuffle Music Collections
### Please describe your bug

have 3 music collections,.  all of them will not play from browser or Android client with the same error "Playback Error, The client isn't compatible with the media and the server isn't sending a compatible media format."  individual albums int eh collections play without issue.

tested by making a collection with a single album I'm 100% sure plays without issue, this fails with the same error.

no output is generated on the console, looks like there is no attempt at all to serve the media.

movie collections seem to play fine.

### Jellyfin Version

10.7.7

### if other:

_No response_

### Environment

```markdown
- OS: ubunut 20.04
- Virtualization: docker
- Clients: Windows, Android
- Browser: chrome, firefox
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

_No response_

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by EgorBakanov**
Currently it is impossible to play/shuffle collection unless it directly contains audio tracks or video because albums/collections/etc. are not consider direct children.

**Changes**
- Add recursive lookup for linked children
- Prevent infinite recursive lookup

**Issues**
Fixes #6193
Fixes #7226

**Related reddit posts**
* [Help! Can't play a music collection](https://www.reddit.com/r/jellyfin/comments/vpvnxd/help_cant_play_a_music_collection/)
* [Error on Play or Shuffle Music Collection](https://www.reddit.com/r/jellyfin/comments/s6ltkw/error_on_play_or_shuffle_music_collection/)
* ['Playback Error' when playing Collection/Playlist](https://www.reddit.com/r/jellyfin/comments/qoxc9o/playback_error_when_playing_collectionplaylist/)
* [Problem with playing a collection with just Tv shows in it.](https://www.reddit.com/r/jellyfin/comments/obwkjd/problem_with_playing_a_collection_with_just_tv/)

### CODE REVIEW

File: MediaBrowser.Controller/Entities/Folder.cs [hunk 1]
```diff
@@ -1300,8 +1300,23 @@ protected virtual IEnumerable<BaseItem> GetEligibleChildrenForRecursiveChildren(
...
+            }
+            else
+            {
+                if (visitedFolders.Contains(this))
+                {
+                    return;
+                }
+            }
+
+            visitedFolders.Add(this);
```
Comment (crobibero) [inline MediaBrowser.Controller/Entities/Folder.cs:1318]:
```suggestion
            visitedFolders ??= new HashSet<Folder>();
            if (!visitedFolders.Add(this))
            {
                return;
            }
```

Comment (EgorBakanov) [reply MediaBrowser.Controller/Entities/Folder.cs]: done

**Review by crobibero — APPROVED** [review]

**Comment by silentTeee** [comment]
Is there anything in particular that's stopping this issue from being merged other than needing an additional review? 

It seems like the scope is small enough and the impact is high enough that it would be worth getting this into the next release. Being able to shuffle a playlist or all songs by an artist is quite common and desirable, after all.

**Review by Shadowghost — APPROVED** [review]

**Comment by EgorBakanov** [comment]
Rebased to current master branch to fix merge conflicts.
