### PR TITLE
Fix overwrite of PremierDate with a year-only value

### LINKED ISSUE #13596: Premired/Released Dates in NFO truncated to year only
### Description of the bug

After upgrading to 10.10.6 from 10.10.5, I noticed that the NFO files being written for albums are writing only the year (i.e. 2025-01-01) for all dates, even though it previously was writing the full date (i.e. 2025-02-20). 

Image

The field written for both of these lines is the same, the item's `.PremiereDate` thus I'm pretty sure the issue is actually that the date is truncated somewhere in the metadata fetchers/lookups since the MP3 files' tag has the correct date.

Since I didn't notice this until after the 10.10.6 upgrade, I could have been related to the changes in `AudioFileProber.cs` in PR #11859  (or its backport) [here](https://github.com/jellyfin/jellyfin/pull/11859/files#diff-81f5576e4c1b35f0541e41ee4a0bda47b62121e3c2d2735f448bb6b7c12dcf88R302), but I suspect it's NOT actually caused there.

I also checked the [relevant file changes since 10.8.z label](https://github.com/jellyfin/jellyfin/compare/release-10.10.z...release-10.8.z#diff-aabc278f80067e433b88159d5a8cbf08d416bf0960d073139399d2aee6cd89eeL610) and there was a change for writing the dates to use the format specified in the Dashboard/Libraries/NFO Settings page, however this is NOT the issue (it did cause some changes due to local-time conversions, but meh).

### Reproduction steps

Deep diving into a specific example (diff shown above)

The correct full data of 2010-06-28 is on the [MusicBrainz Release Page](https://musicbrainz.org/release/fc69b01d-7214-4bb3-9074-1b43b981ae6e)

The data shown on [The AudioDB Album Page](https://www.theaudiodb.com/album/2228150) shows only 2010, so perhaps I just happened to have at or around the same time tagged them with the correct AudioDB id?

If that's the cause, then it would possibly be because the metadata from AudioDB (year only) is overriding the data from MusicBrainz (full date).

1. I corrected the date to 2010-06-28 in the Metadata Manager
2. Saved the album.
3. Reloaded the page and it was saved with the correct in the metadate manager AND was written correctly in the NFO file.
4. Then I did a _Refresh Metadata / Search for missing metadata_ and it changed back to 2010-01-01 in the metadata browser and the NFO file.

Note that I have the Metadata downloaders (Music Albums) set to MusicBrainz, Discogs, TheAudioDB so per the documentation on that screen, it should use the data from MusicBrainz first. Even if it falls back

Image

### What is the current _bug_ behavior?

The `PremiereDate` of Music Albums is being overwritten with a Year-only value from TheAudioDB lookups even though it was already set to a more accurate Year-Month-Day value from the MP3 tags (AudioFileProber) AND ALSO the MediaEncoder-prove  AND ALSO the MusicBrainz lookup (via MusicBrainzAlbumProvider) AND ALSO the existing NFO file (via BaseNFOParser).

For the example given, the date should be 2010-06-28 and it being stored in the metadata and NFO as 2010-01-01.

### What is the expected _correct_ behavior?

Do not truncate/discard the Month and Day when a provided date is the same year, but 01-01 (indicating a year-only value...) when reading data from a Metadate downloader.

Additionally it seems that even though the first listed album metadata downloader (in my case MusicBrainz), it still did the other The AudioDB lookup (which may or may not be wrong depending on what you prefer... since it _could_ help fill in missing data).

The comment on the Dashboard/Libraries/Libraries/Music/Manage Library reads:
>Enable and rank your preferred metadata downloaders in order of priority. Lower priority downloaders will only be used to fill in missing information.

So it really shouldn't be overwriting the MP3's tag (see below logs for ffprobe results showing `date` tag), nor should the MusicBrainz value be overwritten.

### Jellyfin Server version

10.10.0+

### Specify commit id

_No response_

### Specify unstable release number

_No response_

### Specify version number

10.10.6

### Specify the build version

Server version 10.10.6 Web version 10.10.6 (c335a3024) Build version 10.10.6

### Environment

```markdown
- OS: Windows 11 (Jellyfin server)
- Clients: Any
- Browser: Chrome & Edge
- FFmpeg Version: ffmpeg version 7.0.2-Jellyfin
- Plugins: MusicBrainz 10.10.6.0, Discogs 1.0.0, AudioDB 10.10.6.0
```

### Jellyfin logs

```shell
[2025-02-20 16:44:22.121 -06:00] [INF] [37] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"\\ZULU\Music\C\The Choir\Burning Like the Midnight Sun\01-Midnight Sun.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
```

### FFmpeg logs

```shell
For the logged call show in Jellyfin logs

{
    "streams": [
        {
            "index": 0,
            "codec_name": "mp3",
            "codec_long_name": "MP3 (MPEG audio layer 3)",
            "codec_type": "audio",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "sample_fmt": "fltp",
            "sample_rate": "44100",
            "channels": 2,
            "channel_layout": "stereo",
            "bits_per_sample": 0,
            "initial_padding": 0,
            "r_frame_rate": "0/0",
            "avg_frame_rate": "0/0",
            "time_base": "1/14112000",
            "start_pts": 353600,
            "start_time": "0.025057",
            "duration_ts": 3485859840,
            "duration": "247.013878",
            "bit_rate": "274529",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 0,
                "timed_thumbnails": 0,
                "non_diegetic": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "encoder": "LAME3.98r"
            },
            "side_data_list": [
                {
                    "side_data_type": "Replay Gain"
                }
            ]
        },
        {
            "index": 1,
            "codec_name": "mjpeg",
            "codec_long_name": "Motion JPEG",
            "profile": "Progressive",
            "codec_type": "video",
            "codec_tag_string": "[0][0][0][0]",
            "codec_tag": "0x0000",
            "width": 700,
            "height": 700,
            "coded_width": 700,
            "coded_height": 700,
            "closed_captions": 0,
            "film_grain": 0,
            "has_b_frames": 0,
            "sample_aspect_ratio": "1:1",
            "display_aspect_ratio": "1:1",
            "pix_fmt": "yuvj420p",
            "level": -99,
            "color_range": "pc",
            "color_space": "bt470bg",
            "chroma_location": "center",
            "refs": 1,
            "r_frame_rate": "90000/1",
            "avg_frame_rate": "0/0",
            "time_base": "1/90000",
            "start_pts": 2255,
            "start_time": "0.025056",
            "duration_ts": 22231249,
            "duration": "247.013878",
            "bits_per_raw_sample": "8",
            "disposition": {
                "default": 0,
                "dub": 0,
                "original": 0,
                "comment": 0,
                "lyrics": 0,
                "karaoke": 0,
                "forced": 0,
                "hearing_impaired": 0,
                "visual_impaired": 0,
                "clean_effects": 0,
                "attached_pic": 1,
                "timed_thumbnails": 0,
                "non_diegetic": 0,
                "captions": 0,
                "descriptions": 0,
                "metadata": 0,
                "dependent": 0,
                "still_image": 0
            },
            "tags": {
                "comment": "Cover (front)"
            }
        }
    ],
    "format": {
        "filename": "file:\\\\ZULU\\Music\\C\\The Choir\\Burning Like the Midnight Sun\\01-Midnight Sun.mp3",
        "nb_streams": 2,
        "nb_programs": 0,
        "nb_stream_groups": 0,
        "format_name": "mp3",
        "format_long_name": "MP2/3 (MPEG audio layer 2/3)",
        "start_time": "0.025056",
        "duration": "247.013878",
        "size": "8592993",
        "bit_rate": "278299",
        "probe_score": 51,
        "tags": {
            "title": "Midnight Sun",
            "artist": "The Choir",
            "track": "1/11",
            "album": "Burning Like the Midnight Sun",
            "disc": "1/1",
            "date": "2010-06-28",
            "genre": "Alternative Rock",
            "TMED": "CD",
            "album_artist": "The Choir",
            "TDOR": "2010-06-28",
            "TSO2": "Choir, The",
            "artist-sort": "Choir, The",
            "SCRIPT": "Latn",
            "publisher": "Galaxy 21 Music",
            "ASIN": "B003TLMTM4",
            "encoder": "MediaMonkey 3.2.0",
            "ARTISTS": "The Choir",
            "originalyear": "2010",
            "BARCODE": "619255315625",
            "CATALOGNUMBER": "[none]",
            "MusicBrainz Album Type": "album",
            "replaygain_album_gain": "-7.37 dB",
            "replaygain_track_gain": "-8.21 dB",
            "replaygain_track_peak": "0.999969",
            "MusicBrainz Album Status": "official",
            "MusicBrainz Album Release Country": "US",
            "ab:genre": "Electronic;Ambient;Rock;Jazz",
            "MusicBrainz Album Id": "fc69b01d-7214-4bb3-9074-1b43b981ae6e",
            "MusicBrainz Artist Id": "1564678d-dbcc-4b3d-9e13-d2c32b3c7bf2",
            "MusicBrainz Album Artist Id": "1564678d-dbcc-4b3d-9e13-d2c32b3c7bf2",
            "MusicBrainz Release Group Id": "4ea6aef2-784b-448e-9839-877e8a589919",
            "MusicBrainz Release Track Id": "46b10dcf-0540-3df4-95de-0fed14413601",
            "ab:mood": "Not acoustic;Not aggressive;Not electronic",
            "Not happy": ";Not happy",
            "Not party": ";Not party",
            "Relaxed": ";Relaxed",
            "Not sad": ";Not sad"
        }
    }
}
```

### Client / Browser logs

N/A

### Relevant screenshots or videos

Image

Image

### Additional information

Going to submit a PR with the needed changes targeting `v10.0.x` branch. Let me know if you would rather it target `master`

### PR DESCRIPTION
**Pull request by IDisposable**
When a update-metadata is processed and the information from one provider gives a full date (e.g. 2025-02-20) and another provider gives only the year (e.g. 2025-01-01), don't overwrite the date unless it's currently a year-only.

This comes up when (for example) The Audio DB has only the year, but MusicBrainz has a full date for the release date. With this change prefer the full date.

**Changes**
Add a test for IsYearOnlyDate, and use that in MetadataService.MergeBaseItemData to ensure we don't replace more-specific dates with less-specific ones.

**Issues**
Fixes #13596

### CODE REVIEW

File: MediaBrowser.Providers/Manager/MetadataService.cs [hunk 1]
```diff
@@ -1142,6 +1142,15 @@ internal static void MergeBaseItemData(
...
         }
 
+        private static bool IsYearOnlyDate(DateTime date)
+        {
+            return date > DateTime.MinValue && date < DateTime.MaxValue
+                && date.Year > 0
+                && date.Month == 1
+                && date.Day == 1
+                && date.TimeOfDay == TimeSpan.Zero;
+        }
```
Comment (crobibero) [inline MediaBrowser.Providers/Manager/MetadataService.cs:1152]:
```suggestion
        => date.Month == 1 && date.Day == 1
```

No reason to check properties that we don't care about

Comment (crobibero) [reply MediaBrowser.Providers/Manager/MetadataService.cs:1152]: `0-0-0` isn't a valid DateTime in C# so no need to validate against it.
`DateTime.MinValue` is `0001-01-01`

Comment (IDisposable) [reply MediaBrowser.Providers/Manager/MetadataService.cs]: Updated, thanks for the review.

**Review by Bond-009 — APPROVED** [review]

**Review by Shadowghost — APPROVED** [review]

**Comment by IDisposable** [comment]
Fixed the unit test to understand the new logic and test each case with expected result being verified.

**Review by crobibero — APPROVED** [review]
