### PR TITLE
SyncPlay for TV series (and Music)

### LINKED ISSUE #3228: Create SyncPlay groups before playback starts
**Describe the bug**

It should probably be possible to create a SyncPlay session before starting playback.  As of right now the process is:

1. Start a playback session
2. Pause the video
3. Create a session
4. Get other members to join
5. Unpause the video

This seems a bit clunky from a UX perspective and seems as though it could be optimized to allow sessions to be created before playback starts.

**System (please complete the following information):**
 - OS: Linux
 - Virtualization: Docker
 - Jellyfin Version: nightly 20200530
 - Reverse Proxy: nginx

cc @OancaAndrei for thoughts

### LINKED ISSUE #3734: SyncPlay disconnected from group in between each item of a playlist
**Describe the bug**
When playing a playlist and using the SyncPlay feature with a remote user, we experienced that syncplay was disconnected (with a left group notification) and we had to re-enable it (both on the our side and remote side) after the start of each entry on the playlist.

I am not sure if this is a bug, per say, but at the very least it is a missing feature which violates the reasonable user expectation that SyncPlay would continue for each item in a playlist (there is no way to discover that this would not be the case from the UI). The current behaviour in this case certainly leads to a suboptimal user experience (for the user perspective, synchronisation is stopped for no obvious reason), and I would imagine this use case is fairly common (watching a playlist of videos with a remote user).

Incidentally, other than this issue, SyncPlay worked perfectly. Thank you for this excellent new feature.

**System (please complete the following information):**
 - OS: Raspbian 
 - Virtualization: None
 - Clients: Browser (Fedora, Windows)
 - Browser: Chrome 84
 - Jellyfin Version: 10.6.1-1
 - Playback: Transcode
 - Installed Plugins: AudioDB, MusicBrainz, OMDb, Playback reporting, TMDb Boxsets, TheTVDB
 - Reverse Proxy: none
 - Base URL: /web/index.html#!/details?id=d5abc4993972a9c52cff9d37963ff8c8&serverId=cfaeb57c900447d5a573e59e50dc4499
 - Networking: N/A
 - Storage: local (Btrfs RAID)

**To Reproduce**
1. Create a Playlist
2. Click on Click on Play for first item (I have not tested if the same behaviour occurs if clicking the play button for the overall playlist).
3. Enable SyncPlay (click on SyncPlay button and create group)
4. Get another user to join group
5. Wait for end of first Playlist item
4. Get SyncPlay ended notification; playback continues for both local and remote user, but playback is no longer synchronised
**Expected behavior**
SyncPlay continues for each subsequent item of the playlist

### LINKED ISSUE #4155: Syncplay does not continue past the first episode when shuffled.
**Describe the bug**
When playing a tv show on shuffle, sync play works fine for the first episode, but sync is turned off after the first episode

**System (please complete the following information):**
 - OS: Linux
 - Virtualization: Docker
 - Clients: Browser
 - Browser: Firefox 80.0.1
 - Jellyfin Version: 10.6.4
 - Playback: Direct Play
 - Installed Plugins: None
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**

1. Play a tv show on shuffle.
2. Create a sync group, and join the group on a second client
3. Wait for the video to move to the  next episode
4. Both clients continue to play, but leave the sync group and play different episodes.

**Expected behavior**
The sync group should be continued, and future episodes played in sync

### PR DESCRIPTION
**Pull request by OancaAndrei**
**Changes**
This PR aims at making SyncPlay more tv-series friendly, by adding new states that handle the transition between one episode and another.

Sketch of proposed internal states can be seen [here (diagrams.net file)](https://drive.google.com/file/d/10KGS5KHmL1f8YRSdycUmGYUzfkLUm9sD/view?usp=sharing).

`jellyfin-web` PR [here](https://github.com/jellyfin/jellyfin-web/pull/1945).
`jellyfin-apiclient-javascript` PR [here](https://github.com/jellyfin/jellyfin-apiclient-javascript/pull/67).

**Docker build**
```
docker pull andreioanca/jellyfin-syncplay-enhanced:latest
```

**Features being tackled in this PR**
- [x] Sync play-queue
    - [x] UI improvements so users know what's going on
    - [x] Next item
    - [x] Previous item
    - [x] Stop
    - [x] Repeat mode
    - [x] Shuffle mode
    - [x] Sort items
    - [x] Edit playlist
- [x] Group-wait when one or more members of a group are buffering

**Proposed features for future PRs**
- Group join by PIN
- APIs for plugins
- Guest users access
- Bypass library access and parental rating
- Share the transcoding process with the members of the group
- Handle multiple tabs of same user (looks like `WebSocketController::SendMessage` sends messages only to the last active socket)

**Implemented features in merged PRs**
- Option to toggle feature for specific user [User edit > Media Playback > Syncplay access]
- Filter groups by library access and parental rating

**Features being implemented in [next PR](https://github.com/jellyfin/jellyfin/pull/4329)**
- WebRTC for peer-to-peer communication (time sync between devices on LAN)
- WebRTC chunks sharing between peers (using [p2p-media-loader](https://github.com/Novage/p2p-media-loader/tree/master/p2p-media-loader-hlsjs#p2p-media-loader---hlsjs-integration))
- Manually adjust delay and tweak sync properties
- Playback and Playlist Access Control
- Group types (public, invite only, private)

**Issues**
Fixes #3228.
Fixes #3734.
Fixes #4155.

### CODE REVIEW

**Comment by Artiume** [comment]
Thanks for the diagram, it makes it very easy to see the process. I've been testing out Gen 1 syncplay, I'm yet to try this one. One thing I've noticed is the create a party process, I think the ability to form a group before playback would help. Starting playback, then create a group which pauses the session. When you initiate a group, if it could bring up the overhead display when the video is paused, it would help people recognize that the video is paused. I kept forgetting that the video pauses and it'd make me think that something broke 😅.

Hopefully it's not an answer in v2 but I was having some jittery behavior on my mobile phone occasionally. If it became slightly out of sync, it'd fight indefinitely trying to recover perfect sync. If I left the group, the behavior would instantly disappear and playback would continue normal as if nothing happened. 

Thanks again for this! It's awesome. For sharing a stream, what's your idea on doing it?

**Comment by barronpm** [comment]
One thing I would look at before you do too much more work on this, the user entities are getting an overhaul with the move to EF Core, so you should familiarize yourself with the new entity objects. For an example of converting from old to new, check https://github.com/jellyfin/jellyfin/pull/3148/commits/7c823464bca70570f2f53f8af6913e53d385b784

**Comment by OancaAndrei** [comment]
> One thing I've noticed is the create a party process, I think the ability to form a group before playback would help.

Indeed, it is a little bit clunky and hopefully the experience should get smoother with the changes I have in mind. I'm trying to make it general enough so that future additions can be added easily.

Basically the first version kinda enforced the playback on clients, with this revision I'm focusing on  mantaining a group state that clients can choose to follow or not. Clients register to a group and are notified of its changes. Then they're free to actually start the media playback or just track time progression, or even just stay updated on the state of the playlist. The goal is to be able to have clients that play the media and clients that function as remote controllers.

So a side effect would be that groups can be created without setting a playlist (or a single item) first.

> When you initiate a group, if it could bring up the overhead display when the video is paused, it would help people recognize that the video is paused.

This is a nice touch I've missed. I'll add it.

> Hopefully it's not an answer in v2 but I was having some jittery behavior on my mobile phone occasionally. If it became slightly out of sync, it'd fight indefinitely trying to recover perfect sync.

I was aware of this behaviour as I encountered it on Safari. The temporary solution that I've implemented is to simply disable active syncing after a certain amount of failed attempts (that client will basically just respond to playback changes but won't care of "accurate" time syncing).

May I ask on what browser this ocurred?

> Thanks again for this! It's awesome. For sharing a stream, what's your idea on doing it?

I remember reading a comment on the old issue where it was suggested that transcoded files are already written to disk and could potentially be shared when codec requirements are met. So instead of starting another __ffmpeg__ process that would create duplicate __chunks__ but with different __ids__, these __chunks__ could be sent directly to the requesting client.

Happy to see that something is working :smile:.

**Comment by dkanada** [comment]
I changed my mind 😄 Playlists are pretty important for music sync so we should try and fit this in before the update if we can.

**Comment by OancaAndrei** [comment]
I'm back. I'm going to quickly see what's new and get back on this feature.

**Comment by sparky8251** [comment]
@OancaAndrei Just in case you havent seen, you got a shoutout in this podcast (https://linuxunplugged.com/363). JF stuff starts at 7:21, runs for about 6 minutes and the first half of it all is dedicated to your awesome work!

It's not related to any of the code stuff, but I just wanted to bring to your attention how much not just we appreciate the work you've done but how much everyone does :)

**Comment by OancaAndrei** [comment]
> @OancaAndrei Just in case you havent seen, you got a shoutout in this podcast _by name_ (https://linuxunplugged.com/363). JF stuff starts at 7:21, runs for about 6 minutes and the first half of it all is dedicated to your awesome work!
> 
> This comment isn't related to any of the code. I just wanted to bring to your attention how much not just we appreciate the work you've done, but how much everyone does :)
> 
> (since you arent on matrix/IRC to my knowledge, this was the only way to tell you)

Insert _"They love me." - Spider-Man_ meme here :laughing:.
Woah, I really wasn't expecting such a warm response, considering that it's still so rough as a feature.

Thanks for letting me know, this made my day.

**Comment by sparky8251** [comment]
Welcome back and glad I could help with making your day then! Can't wait to see where you take this amazing feature :)

**Comment by joshuaboniface** [comment]
@jellyfin/server I think this could use some review and feedback.

**Comment by Artiume** [comment]
I created `artiume/jellyfin-sync-enhanced` but im having a few issues. The wizard doesnt work, I need to verify this issue in unstable. but onto the actual PR, I can't create a syncplay group, whether Im not playing a video or even if I am playing a video

**Comment by OancaAndrei** [comment]
I didn't edit `package.json` in `jellyfin-web` so I suspect that your build is still using the `master` branch of `jellyfin-apiclient-javascript`.
You can either update `package.json` or you can use the following `Dockerfile` file I used last time. I'll upload a build myself later.
```
ARG DOTNET_VERSION=3.1

FROM node:alpine as web-builder
ARG JELLYFIN_SYNCPLAY_VERSION=enhanced
RUN apk add curl git zlib zlib-dev autoconf g++ make libpng-dev gifsicle alpine-sdk automake libtool make gcc musl-dev nasm python \
# install web client
    && curl -L https://github.com/OancaAndrei/jellyfin-web/archive/syncplay-${JELLYFIN_SYNCPLAY_VERSION}.tar.gz | tar zxf - \
    && cd jellyfin-web-* \
    && yarn install \
# patch with custom apiclient
    && cd node_modules \
    && rm -rf jellyfin-apiclient \
    && curl -L https://github.com/OancaAndrei/jellyfin-apiclient-javascript/archive/syncplay-${JELLYFIN_SYNCPLAY_VERSION}.tar.gz | tar zxf - \
    && mv jellyfin-apiclient-* jellyfin-apiclient \
    && cd jellyfin-apiclient \
    && yarn install \
    && yarn dev \
    && cd .. \
    && cd .. \
# build web client
    && yarn build:development \
# dist
    && mv dist /dist

FROM mcr.microsoft.com/dotnet/core/sdk:${DOTNET_VERSION}-buster as builder
WORKDIR /repo
COPY . .
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
# because of changes in docker and systemd we need to not build in parallel at the moment
# see https://success.docker.com/article/how-to-reserve-resource-temporarily-unavailable-errors-due-to-tasksmax-setting
RUN dotnet publish Jellyfin.Server --disable-parallel --configuration Release --output="/jellyfin" --self-contained --runtime linux-x64 "-p:GenerateDocumentationFile=false;DebugSymbols=false;DebugType=none"

FROM debian:buster-slim

# https://askubuntu.com/questions/972516/debian-frontend-environment-variable
ARG DEBIAN_FRONTEND="noninteractive"
# http://stackoverflow.com/questions/48162574/ddg#49462622
ARG APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn
# https://github.com/NVIDIA/nvidia-docker/wiki/Installation-(Native-GPU-Support)
ENV NVIDIA_DRIVER_CAPABILITIES="compute,video,utility"

COPY --from=builder /jellyfin /jellyfin
COPY --from=web-builder /dist /jellyfin/jellyfin-web
# Install dependencies:
#   mesa-va-drivers: needed for AMD VAAPI
RUN apt-get update \
 && apt-get install --no-install-recommends --no-install-suggests -y ca-certificates gnupg wget apt-transport-https \
 && wget -O - https://repo.jellyfin.org/jellyfin_team.gpg.key | apt-key add - \
 && echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release ) $( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release ) main" | tee /etc/apt/sources.list.d/jellyfin.list \
 && apt-get update \
 && apt-get install --no-install-recommends --no-install-suggests -y \
   mesa-va-drivers \
   jellyfin-ffmpeg \
   openssl \
   locales \
 && apt-get remove gnupg wget apt-transport-https -y \
 && apt-get clean autoclean -y \
 && apt-get autoremove -y \
 && rm -rf /var/lib/apt/lists/* \
 && mkdir -p /cache /config /media \
 && chmod 777 /cache /config /media \
 && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && locale-gen

ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en

EXPOSE 8096
VOLUME /cache /config /media
ENTRYPOINT ["./jellyfin/jellyfin", \
    "--datadir", "/config", \
    "--cachedir", "/cache", \
    "--ffmpeg", "/usr/lib/jellyfin-ffmpeg/ffmpeg"]
```

**Comment by Artiume** [comment]
I manually modified the dockerfile to pull your web PR. I can use yours to verify it though, thanks 👌

**Comment by OancaAndrei** [comment]
> I created `artiume/jellyfin-sync-enhanced` but im having a few issues. The wizard doesnt work, I need to verify this issue in unstable. but onto the actual PR, I can't create a syncplay group, whether Im not playing a video or even if I am playing a video

Regarding the wizard not working, I hope it's an issue from `master` as I don't remember touching anything there :sweat_smile:.

**Comment by Artiume** [comment]
Ha, yeah. I honestly felt both bugs were issues with master and not your PRs.

**Comment by BaronGreenback** [comment]
@OancaAndrei  - trying to review, but am being hampered with a bug on github (reported and waiting on them to fix it!).
Have noticed quite a few comments don't end with a period. Given the amount of code, could you add them please - it would make reviewing much quicker?

**Comment by OancaAndrei** [comment]
> @OancaAndrei - trying to review, but am being hampered with a bug on github (reported and waiting on them to fix it!).
> Have noticed quite a few comments don't end with a period. Given the amount of code, could you add them please - it would make reviewing much quicker?

Sure, will start with this then.

File: MediaBrowser.Controller/SyncPlay/PlaybackRequest/BufferGroupRequest.cs [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+        public string PlaylistItemId { get; set; }
+
+        /// <inheritdoc />
+        public PlaybackRequestType GetRequestType()
+        {
+            return PlaybackRequestType.Buffer;
+        }
+
+        /// <inheritdoc />
+        public void Apply(ISyncPlayStateContext context, ISyncPlayState state, SessionInfo session, CancellationToken cancellationToken)
```
Comment (BaronGreenback) [inline MediaBrowser.Controller/SyncPlay/PlaybackRequest/BufferGroupRequest.cs:44]: From the look of the code - this method is identical across all GroupRequests.

using a base class, or interface extension would negate code repetition? Alternatively, could the code in the function be moved up one level?

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 2]
```diff
@@ -0,0 +1,596 @@
...
+        public bool MovePlaylistItem(string playlistItemId, int newIndex)
+        {
+            var list = GetPlaylistAsList();
+            var playingItem = list[PlayingItemIndex];
+
+            var playlistIds = list.Select(queueItem => queueItem.PlaylistItemId).ToList();
+            var oldIndex = playlistIds.IndexOf(playlistItemId);
+            if (oldIndex < 0) {
+                return false;
+            }
```
Comment (BaronGreenback) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:428]:
```suggestion
            if (oldIndex < 0) 
            {
                return false;
            }
```

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 3]
```diff
@@ -0,0 +1,596 @@
...
+            SortedPlaylist.Clear();
+            ShuffledPlaylist.Clear();
+            LastChange = DateTime.UtcNow;
+
+            if (!clearPlayingItem && playingItem != null)
+            {
+                SortedPlaylist.Add(playingItem);
+                if (ShuffleMode.Equals(GroupShuffleMode.Shuffle))
+                {
+                    SortedPlaylist.Add(playingItem);
```
Comment (BaronGreenback) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:249]: Shouldn't this be..
```suggestion
                    ShuffledPlaylist.Add(playingItem);
```

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 4]
```diff
@@ -0,0 +1,596 @@
...
+        {
+            Dispose(true);
+            GC.SuppressFinalize(this);
+        }
+
+        /// <summary>
+        /// Releases unmanaged and optionally managed resources.
+        /// </summary>
+        /// <param name="disposing"><c>true</c> to release both managed and unmanaged resources; <c>false</c> to release only unmanaged resources.</param>
+        protected virtual void Dispose(bool disposing)
```
Comment (BaronGreenback) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:93]: Why does this implement IDisposable as it doesn't seem to free anything.

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 5]
```diff
@@ -0,0 +1,596 @@
...
+        /// <param name="items">The items to add to the playlist.</param>
+        public void Queue(Guid[] items)
+        {
+            var newItems = CreateQueueItemsFromArray(items);
+            SortedPlaylist.AddRange(newItems);
+
+            if (ShuffleMode.Equals(GroupShuffleMode.Shuffle))
+            {
+                newItems.Shuffle();
+                ShuffledPlaylist.AddRange(newItems);
```
Comment (BaronGreenback) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:182]: Wouldn't this better shuffle - as it would mix up the old and the new?

```suggestion
                ShuffledPlaylist.AddRange(newItems);
                ShuffledPlaylist.Shuffle();
```

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 6]
```diff
@@ -0,0 +1,596 @@
...
+            }
+
+            ShuffleMode = GroupShuffleMode.Shuffle;
+            LastChange = DateTime.UtcNow;
+        }
+
+        /// <summary>
+        /// Resets the playlist to sorted mode. Shuffle mode is changed.
+        /// </summary>
+        public void SortShuffledPlaylist()
```
Comment (BaronGreenback) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:219]: Might want to better name this function - as it doesn't really do as described. Its more of a StopUsingShuffledPlaylist

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 7]
```diff
@@ -0,0 +1,596 @@
...
+            LastChange = DateTime.UtcNow;
+        }
+
+        /// <summary>
+        /// Clears the playlist.
+        /// </summary>
+        /// <param name="clearPlayingItem">Whether to remove the playing item as well.</param>
+        public void ClearPlaylist(bool clearPlayingItem)
+        {
+            var playingItem = SortedPlaylist[PlayingItemIndex];
```
Comment (BaronGreenback) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:239]: It is assumed that the sorted playlist is being used - shouldn't this check to see and get the index of the playing item out of the correct playlist - the function is, after all, public.

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 8]
```diff
@@ -0,0 +1,596 @@
...
+        /// <param name="mode">The new mode.</param>
+        public void SetShuffleMode(string mode)
+        {
+            switch (mode)
+            {
+                case "Shuffle":
+                    ShufflePlaylist();
+                    break;
+                default:
+                    SortShuffledPlaylist();
```
Comment (BaronGreenback) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:489]: Whereas if i shuffled again, I would expect it to re-shuffle, not shuffling doesn't have to be repeated.
```suggestion
                if (!ShuffleMode.Equals(mode))
                { 
                    SortShuffledPlaylist();
                }
```

File: MediaBrowser.Controller/SyncPlay/PlaybackRequest/BufferGroupRequest.cs (hunk 1 above)
Comment (OancaAndrei) [reply MediaBrowser.Controller/SyncPlay/PlaybackRequest/BufferGroupRequest.cs:44]: What I did here is try to apply the [Visitor pattern design](https://en.wikipedia.org/wiki/Visitor_pattern) where each **GroupState** is a **Visitor** and each **GroupRequest** is an **Element**. It simplifies the code a lot (by avoiding switch cases) at the cost of having to duplicate this method in every **Element**. It also decouples classes that should not be tied.

This design relies on the type of the class to switch between the right method to call. Creating an abstract class would make the switching always select the base class and not differentiate between the different **GroupRequest**s.

Also, it makes the code cleaner to read IMHO :smile:.

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs (hunk 4 above)
Comment (OancaAndrei) [reply MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:93]: I keep copy/pasting this from other classes, I'll get rid of it.

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs (hunk 5 above)
Comment (OancaAndrei) [reply MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:182]: Right? This class is a translated copy of the client-side one. And lots of things didn't feel right to me either.
Shall we consider the shuffle request as a one time action or as a state?

I should probably review the class with a more server-side focused vision... :thinking: And bridge with the client at an upper level.

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs (hunk 7 above)
Comment (OancaAndrei) [reply MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:239]: Yep, my bad here when translating.

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs (hunk 5 above)
Comment (OancaAndrei) [reply MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:182]: Oh ok, I've checked again. So, in the original code items get pushed to the queue as they are, no shuffling is done.
My implementation diverged from the client-side one because the latter has a bug where items added to the queue are lost when returning to sorted mode.

So your proposed shuffle makes more sense, regardless of how it's implemented on the client.

Comment (OancaAndrei) [reply MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:182]: I've made my mind: the queue methods should not care about whether the playlist is shuffled or not, they just enqueue things and that's it. If the playlist needs to be re-shuffled then `ShufflePlaylist()` can be called again (the new implementation anyway).

What do you think?

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs (hunk 6 above)
Comment (OancaAndrei) [reply MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:219]: What about `RestoreSortedPlaylist`?

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 9]
```diff
@@ -0,0 +1,694 @@
...
+            return Participants.ContainsKey(sessionId);
+        }
+
+        /// <summary>
+        /// Adds the session to the group.
+        /// </summary>
+        /// <param name="session">The session.</param>
+        private void AddSession(SessionInfo session)
+        {
+            if (ContainsSession(session.Id))
```
[the remark this answers is not in the document]
Comment (OancaAndrei) [reply Emby.Server.Implementations/SyncPlay/GroupController.cs]: I was using it to abstract away from how things are stored. But at this state it makes more sense to use the Dictionary directly.

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 10]
```diff
@@ -0,0 +1,694 @@
...
+            return !usersWithNoAccess.Any();
+        }
+
+        /// <inheritdoc />
+        public bool IsGroupEmpty() => Participants.Count == 0;
+
+        /// <inheritdoc />
+        public void CreateGroup(SessionInfo session, NewGroupRequest request, CancellationToken cancellationToken)
+        {
+            GroupName = request.GroupName;
```
[the remark this answers is not in the document]
Comment (OancaAndrei) [reply Emby.Server.Implementations/SyncPlay/GroupController.cs:255]: Looks like we have a new job for `SyncPlayManager`.

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs (hunk 6 above)
Comment (BaronGreenback) [reply MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:219]: reads better

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs (hunk 8 above)
Comment (OancaAndrei) [reply MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs]: The new changes should allow for re-shuffling when requested now.

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs (hunk 5 above)
Comment (BaronGreenback) [reply MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs]: Might be worth adding that as a comment - shuffle is an action and not a state.

**Review by BaronGreenback — APPROVED** [review]

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 11]
```diff
@@ -0,0 +1,706 @@
...
+
+namespace Emby.Server.Implementations.SyncPlay
+{
+    /// <summary>
+    /// Class SyncPlayGroupController.
+    /// </summary>
+    /// <remarks>
+    /// Class is not thread-safe, external locking is required when accessing methods.
+    /// </remarks>
+    public class SyncPlayGroupController : ISyncPlayGroupController, ISyncPlayStateContext
```
Comment (crobibero) [inline Emby.Server.Implementations/SyncPlay/GroupController.cs:24]: Class (or interface) must match filename.

File: MediaBrowser.Controller/SyncPlay/ISyncPlayController.cs [hunk 12]
```diff
@@ -1,39 +1,41 @@
...
 using MediaBrowser.Model.SyncPlay;
 
 namespace MediaBrowser.Controller.SyncPlay
 {
     /// <summary>
-    /// Interface ISyncPlayController.
+    /// Interface ISyncPlayGroupController.
     /// </summary>
-    public interface ISyncPlayController
+    public interface ISyncPlayGroupController
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/ISyncPlayController.cs:12]: Class (or interface) must match filename.

File: Emby.Server.Implementations/SyncPlay/GroupStates/AbstractGroupState.cs [hunk 13]
```diff
@@ -0,0 +1,218 @@
+using System.Threading;
+using MediaBrowser.Controller.Session;
+using MediaBrowser.Model.SyncPlay;
+using Microsoft.Extensions.Logging;
+
+namespace MediaBrowser.Controller.SyncPlay
```
Comment (crobibero) [inline Emby.Server.Implementations/SyncPlay/GroupStates/AbstractGroupState.cs:6]:
```suggestion
using System.Threading;
using MediaBrowser.Controller.Session;
using MediaBrowser.Controller.SyncPlay;
using MediaBrowser.Model.SyncPlay;
using Microsoft.Extensions.Logging;

namespace Emby.Server.Implementations.SyncPlay.GroupStates
```

Wrong namespace for the current location.

File: Emby.Server.Implementations/SyncPlay/GroupStates/AbstractGroupState.cs [hunk 14]
```diff
@@ -0,0 +1,218 @@
...
+    /// </summary>
+    /// <remarks>
+    /// Class is not thread-safe, external locking is required when accessing methods.
+    /// </remarks>
+    public abstract class AbstractGroupState : ISyncPlayState
+    {
+        /// <summary>
+        /// The logger.
+        /// </summary>
+        protected readonly ILogger _logger;
```
Comment (crobibero) [inline Emby.Server.Implementations/SyncPlay/GroupStates/AbstractGroupState.cs:19]:
```suggestion
        private readonly ILogger _logger;
```

File: Emby.Server.Implementations/SyncPlay/GroupStates/AbstractGroupState.cs [hunk 15]
```diff
@@ -0,0 +1,218 @@
...
+
+        /// <summary>
+        /// Default constructor.
+        /// </summary>
+        public AbstractGroupState(ILogger logger)
```
Comment (crobibero) [inline Emby.Server.Implementations/SyncPlay/GroupStates/AbstractGroupState.cs:24]:
```suggestion
        /// <summary>
        /// Initializes a new instance of the <see cref="AbstractGroupState"/> class.
        /// </summary>
        /// <param name="logger">Instance of the <see cref="ILogger"/> interface.</param>
        protected AbstractGroupState(ILogger logger)
```

File: Emby.Server.Implementations/SyncPlay/GroupStates/AbstractGroupState.cs [hunk 16]
```diff
@@ -0,0 +1,218 @@
...
+                if (context.PlayQueue.PlayingItemIndex == -1)
+                {
+                    _logger.LogDebug("HandleRequest: {0} in group {1}, play queue is empty.", request.GetRequestType(), context.GroupId.ToString());
+
+                    ISyncPlayState idleState = new IdleGroupState(_logger);
+                    context.SetState(idleState);
+                    var stopRequest = new StopGroupRequest();
+                    idleState.HandleRequest(context, GetGroupState(), stopRequest, session, cancellationToken);
+                }
+            }
```
Comment (crobibero) [inline Emby.Server.Implementations/SyncPlay/GroupStates/AbstractGroupState.cs:98]:
```suggestion
            if (playingItemRemoved && context.PlayQueue.PlayingItemIndex == -1)
            {
                _logger.LogDebug("HandleRequest: {0} in group {1}, play queue is empty.", request.GetRequestType(), context.GroupId.ToString());

                ISyncPlayState idleState = new IdleGroupState(_logger);
                context.SetState(idleState);
                var stopRequest = new StopGroupRequest();
                idleState.HandleRequest(context, GetGroupState(), stopRequest, session, cancellationToken);
            }
```

File: Emby.Server.Implementations/SyncPlay/GroupStates/AbstractGroupState.cs [hunk 17]
```diff
@@ -0,0 +1,218 @@
...
+        {
+            var result = context.AddToPlayQueue(request.ItemIds, request.Mode);
+
+            if (!result)
+            {
+                _logger.LogError("HandleRequest: {0} in group {1}, unable to add items to play queue.", request.GetRequestType(), context.GroupId.ToString());
+                return;
+            }
+
+            var reason = request.Mode.Equals("next") ? PlayQueueUpdateReason.QueueNext : PlayQueueUpdateReason.Queue;
```
Comment (crobibero) [inline Emby.Server.Implementations/SyncPlay/GroupStates/AbstractGroupState.cs:128]:
```suggestion
            var reason = request.Mode.Equals("next", StringComparison.OrdinalIgnoreCase) ? PlayQueueUpdateReason.QueueNext : PlayQueueUpdateReason.Queue;
```

**Review by crobibero — CHANGES_REQUESTED** [review]

**Comment by crobibero** [comment]
What IDE are you using? It doesn't look like some of the StyleCop requirements are being followed.

**Comment by OancaAndrei** [comment]
> What IDE are you using? It doesn't look like some of the StyleCop requirements are being followed.

@crobibero, I'm using Visual Studio Code on Ubuntu. Is there an extension I can install?

**Comment by crobibero** [comment]
https://marketplace.visualstudio.com/items?itemName=josefpihrt-vscode.roslynator
The roslynator extension shows analyzer warnings for me, should be easier then using lint on build

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 18]
```diff
@@ -0,0 +1,706 @@
...
+    {
+        /// <summary>
+        /// Gets the default ping value used for sessions.
+        /// </summary>
+        public long DefaultPing { get; } = 500;
```
Comment (Bond-009) [inline Emby.Server.Implementations/SyncPlay/GroupController.cs:29]: Maybe make this a const?

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 19]
```diff
@@ -0,0 +1,706 @@
...
+        }
+
+        private bool HasAccessToQueue(User user, Guid[] queue)
+        {
+            if (queue == null || queue.Length == 0)
+            {
+                return true;
+            }
+
+            var items = queue.ToList()
```
Comment (Bond-009) [inline Emby.Server.Implementations/SyncPlay/GroupController.cs:202]: Why the `ToList`?

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 20]
```diff
@@ -0,0 +1,706 @@
...
+
+            // Check ParentalRating access, user must have the minimum required access level.
+            var hasParentalRatingAccess = !user.MaxParentalAgeRating.HasValue
+                || MinParentalRatingAccessRequired <= user.MaxParentalAgeRating;
+
+            // Check that user has access to all required folders.
+            if (!user.HasPermission(PermissionKind.EnableAllFolders) && hasParentalRatingAccess)
+            {
+                // Get list of items that are not accessible.
+                var blockedItems = items.Where(item => !HasAccessToItem(user, item));
```
Comment (Bond-009) [inline Emby.Server.Implementations/SyncPlay/GroupController.cs:218]: You iterate multiple times over `items`

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 21]
```diff
@@ -0,0 +1,706 @@
...
+                waitingState.ResumePlaying = !session.PlayState.IsPaused;
+                SetState(waitingState);
+            }
+
+            var updateSession = NewSyncPlayGroupUpdate(GroupUpdateType.GroupJoined, GetInfo());
+            SendGroupUpdate(session, SyncPlayBroadcastType.CurrentSession, updateSession, cancellationToken);
+
+            State.SessionJoined(this, State.GetGroupState(), session, cancellationToken);
+
+            _logger.LogInformation("InitGroup: {0} created group {1}.", session.Id.ToString(), GroupId.ToString());
```
Comment (Bond-009) [inline Emby.Server.Implementations/SyncPlay/GroupController.cs:280]: Technically no need for these `ToString` calls

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 22]
```diff
@@ -0,0 +1,706 @@
...
+
+            var updateSession = NewSyncPlayGroupUpdate(GroupUpdateType.GroupJoined, GetInfo());
+            SendGroupUpdate(session, SyncPlayBroadcastType.CurrentSession, updateSession, cancellationToken);
+
+            var updateOthers = NewSyncPlayGroupUpdate(GroupUpdateType.UserJoined, session.UserName);
+            SendGroupUpdate(session, SyncPlayBroadcastType.AllExceptCurrentSession, updateOthers, cancellationToken);
+
+            State.SessionJoined(this, State.GetGroupState(), session, cancellationToken);
+
+            _logger.LogInformation("SessionJoin: {0} joined group {1}.", session.Id.ToString(), GroupId.ToString());
```
Comment (Bond-009) [inline Emby.Server.Implementations/SyncPlay/GroupController.cs:297]: Same as above

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 23]
```diff
@@ -0,0 +1,706 @@
...
+        {
+            var updateSession = NewSyncPlayGroupUpdate(GroupUpdateType.GroupJoined, GetInfo());
+            SendGroupUpdate(session, SyncPlayBroadcastType.CurrentSession, updateSession, cancellationToken);
+
+            var updateOthers = NewSyncPlayGroupUpdate(GroupUpdateType.UserJoined, session.UserName);
+            SendGroupUpdate(session, SyncPlayBroadcastType.AllExceptCurrentSession, updateOthers, cancellationToken);
+
+            State.SessionJoined(this, State.GetGroupState(), session, cancellationToken);
+
+            _logger.LogInformation("SessionRestore: {0} re-joined group {1}.", session.Id.ToString(), GroupId.ToString());
```
Comment (Bond-009) [inline Emby.Server.Implementations/SyncPlay/GroupController.cs:311]: Same

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 24]
```diff
@@ -0,0 +1,706 @@
...
+            RemoveSession(session);
+            _syncPlayManager.RemoveSessionFromGroup(session, this);
+
+            var updateSession = NewSyncPlayGroupUpdate(GroupUpdateType.GroupLeft, GroupId.ToString());
+            SendGroupUpdate(session, SyncPlayBroadcastType.CurrentSession, updateSession, cancellationToken);
+
+            var updateOthers = NewSyncPlayGroupUpdate(GroupUpdateType.UserLeft, session.UserName);
+            SendGroupUpdate(session, SyncPlayBroadcastType.AllExceptCurrentSession, updateOthers, cancellationToken);
+
+            _logger.LogInformation("SessionLeave: {0} left group {1}.", session.Id.ToString(), GroupId.ToString());
```
Comment (Bond-009) [inline Emby.Server.Implementations/SyncPlay/GroupController.cs:328]: I think you'll get it, I'll stop here ;)

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 25]
```diff
@@ -0,0 +1,706 @@
...
+        {
+            return dateTime.ToUniversalTime().ToString("o");
+        }
+
+        /// <inheritdoc />
+        public long SanitizePositionTicks(long? positionTicks)
+        {
+            var ticks = positionTicks ?? 0;
+            ticks = Math.Max(ticks, 0);
+            ticks = Math.Min(ticks, RunTimeTicks);
```
Comment (Bond-009) [inline Emby.Server.Implementations/SyncPlay/GroupController.cs:444]: `Math.Clamp` exists

File: MediaBrowser.Controller/SyncPlay/PlaybackRequest/PlayGroupRequest.cs [hunk 26]
```diff
@@ -0,0 +1,43 @@
...
+    /// <summary>
+    /// Class PlayGroupRequest.
+    /// </summary>
+    public class PlayGroupRequest : IPlaybackGroupRequest
+    {
+        /// <summary>
+        /// Gets or sets the playing queue.
+        /// </summary>
+        /// <value>The playing queue.</value>
+        public Guid[] PlayingQueue { get; set; }
```
Comment (Bond-009) [inline MediaBrowser.Controller/SyncPlay/PlaybackRequest/PlayGroupRequest.cs:17]: If possible don't use arrays in properties

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 27]
```diff
@@ -0,0 +1,595 @@
+using System;
+using System.Collections.Generic;
+using System.Linq;
+using MediaBrowser.Model.SyncPlay;
+
+namespace MediaBrowser.Controller.SyncPlay
+{
+    static class ListShuffleExtension
```
Comment (Bond-009) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:8]: Why?

File: MediaBrowser.Model/SyncPlay/GroupStateUpdate.cs [hunk 28]
```diff
@@ -0,0 +1,22 @@
+#nullable disable
```
Comment (Bond-009) [inline MediaBrowser.Model/SyncPlay/GroupStateUpdate.cs:1]: Why?

**Review by Bond-009 — CHANGES_REQUESTED** [review]

File: Emby.Server.Implementations/SyncPlay/GroupController.cs (hunk 18 above)
Comment (OancaAndrei) [reply Emby.Server.Implementations/SyncPlay/GroupController.cs]: My plan was to make this a setting that group admins can tweak. :thinking:

File: Jellyfin.Api/Controllers/SyncPlayController.cs [hunk 29]
```diff
@@ -92,31 +97,137 @@ public ActionResult SyncPlayLeaveGroup()
...
+        /// <param name="playingQueue">The playing queue. Item ids in the playing queue, comma delimited.</param>
+        /// <param name="playingItemPosition">The playing item position from the queue.</param>
+        /// <param name="startPositionTicks">The start position ticks.</param>
         /// <response code="204">Play request sent to all group members.</response>
         /// <returns>A <see cref="NoContentResult"/> indicating success.</returns>
         [HttpPost("Play")]
         [ProducesResponseType(StatusCodes.Status204NoContent)]
-        public ActionResult SyncPlayPlay()
+        public ActionResult SyncPlayPlay(
+            [FromQuery, Required] string playingQueue,
```
Comment (crobibero) [inline Jellyfin.Api/Controllers/SyncPlayController.cs:121]:
```suggestion
            [FromQuery, Required] Guid[] playingQueue,
```

Please avoid using the `RequestHelpers` to parse parameters on new endpoints.

File: MediaBrowser.Controller/SyncPlay/PlaybackRequests/PlayGroupRequest.cs [hunk 30]
```diff
@@ -0,0 +1,41 @@
+using System;
+using System.Collections.Generic;
+using System.Threading;
+using MediaBrowser.Controller.Session;
+using MediaBrowser.Model.SyncPlay;
+
+namespace MediaBrowser.Controller.SyncPlay
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/PlaybackRequests/PlayGroupRequest.cs:7]:
```suggestion
namespace MediaBrowser.Controller.SyncPlay.PlaybackRequests
```

Namespace is incorrect for everything in a SyncPlay subfolder

File: MediaBrowser.Controller/SyncPlay/PlaybackRequests/PlayGroupRequest.cs [hunk 31]
```diff
@@ -0,0 +1,41 @@
...
+    /// <summary>
+    /// Class PlayGroupRequest.
+    /// </summary>
+    public class PlayGroupRequest : IGroupPlaybackRequest
+    {
+        /// <summary>
+        /// Gets the playing queue.
+        /// </summary>
+        /// <value>The playing queue.</value>
+        public List<Guid> PlayingQueue { get; } = new List<Guid>();
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/PlaybackRequests/PlayGroupRequest.cs:18]:
```suggestion
        public IReadOnlyList<Guid> PlayingQueue { get; } 
```

Additionally, set it from constructor

File: MediaBrowser.Model/SyncPlay/QueueItem.cs [hunk 32]
```diff
@@ -0,0 +1,24 @@
+#nullable disable
+
```
Comment (crobibero) [inline MediaBrowser.Model/SyncPlay/QueueItem.cs:2]:
```suggestion
```

All new content should have nullable enabled.
I recommend setting values from a constructor.

File: MediaBrowser.Model/SyncPlay/PlayQueueUpdateReason.cs [hunk 33]
```diff
@@ -0,0 +1,58 @@
...
+        /// </summary>
+        MoveItem = 3,
+
+        /// <summary>
+        /// A user is making changes to the queue.
+        /// </summary>
+        Queue = 4,
+
+        /// <summary>
+        /// A user is making changes to the queue.
```
Comment (crobibero) [inline MediaBrowser.Model/SyncPlay/PlayQueueUpdateReason.cs:34]: What is the difference between `Queue` and `QueueNext`?

File: MediaBrowser.Model/SyncPlay/PlayQueueUpdate.cs [hunk 34]
```diff
@@ -0,0 +1,54 @@
+#nullable disable
+
```
Comment (crobibero) [inline MediaBrowser.Model/SyncPlay/PlayQueueUpdate.cs:2]:
```suggestion
```

New classes should be nullable.

File: MediaBrowser.Model/SyncPlay/PlayQueueUpdate.cs [hunk 35]
```diff
@@ -0,0 +1,54 @@
...
+        /// Gets or sets the request type that originated this update.
+        /// </summary>
+        /// <value>The reason for the update.</value>
+        public PlayQueueUpdateReason Reason { get; set; }
+
+        /// <summary>
+        /// Gets or sets the UTC time of the last change to the playing queue.
+        /// </summary>
+        /// <value>The UTC time of the last change to the playing queue.</value>
+        public string LastUpdate { get; set; }
```
Comment (crobibero) [inline MediaBrowser.Model/SyncPlay/PlayQueueUpdate.cs:22]: Why have this as a `string` instead of a `DateTime`?

File: MediaBrowser.Model/SyncPlay/NewGroupRequest.cs [hunk 36]
```diff
@@ -0,0 +1,16 @@
+#nullable disable
+
```
Comment (crobibero) [inline MediaBrowser.Model/SyncPlay/NewGroupRequest.cs:2]:
```suggestion
```

New classes should be nullable.

File: MediaBrowser.Model/SyncPlay/GroupStateType.cs [hunk 37]
```diff
@@ -0,0 +1,28 @@
...
+{
+    /// <summary>
+    /// Enum GroupState.
+    /// </summary>
+    public enum GroupStateType
+    {
+        /// <summary>
+        /// The group is in idle state. No media is playing.
+        /// </summary>
+        Idle,
```
Comment (crobibero) [inline MediaBrowser.Model/SyncPlay/GroupStateType.cs:11]: New `enum` should have integer representation.

File: MediaBrowser.Model/SyncPlay/GroupRequestType.cs [hunk 38]
```diff
@@ -0,0 +1,33 @@
...
+{
+    /// <summary>
+    /// Enum GroupRequestType.
+    /// </summary>
+    public enum GroupRequestType
+    {
+        /// <summary>
+        /// A user is requesting to create a new group.
+        /// </summary>
+        NewGroup,
```
Comment (crobibero) [inline MediaBrowser.Model/SyncPlay/GroupRequestType.cs:11]: New `enum` should have integer representation.

File: MediaBrowser.Model/SyncPlay/GroupInfoDto.cs [hunk 39]
```diff
@@ -16,27 +16,27 @@ public class GroupInfoView
...
         /// Gets or sets the participants.
         /// </summary>
         /// <value>The participants.</value>
         public IReadOnlyList<string> Participants { get; set; }
+
+        /// <summary>
+        /// Gets or sets the date when this dto has been updated.
+        /// </summary>
+        /// <value>The date when this dto has been updated.</value>
+        public string LastUpdatedAt { get; set; }
```
Comment (crobibero) [inline MediaBrowser.Model/SyncPlay/GroupInfoDto.cs:40]: Why `string` instead of `DateTime`?

File: MediaBrowser.Controller/SyncPlay/PlaybackRequests/SetShuffleModeGroupRequest.cs [hunk 40]
```diff
@@ -0,0 +1,27 @@
...
+    /// <summary>
+    /// Class SetShuffleModeGroupRequest.
+    /// </summary>
+    public class SetShuffleModeGroupRequest : IGroupPlaybackRequest
+    {
+        /// <summary>
+        /// Gets or sets the shuffle mode.
+        /// </summary>
+        /// <value>The shuffle mode.</value>
+        public string Mode { get; set; }
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/PlaybackRequests/SetShuffleModeGroupRequest.cs:16]: Should use the `enum` type instead of a string.

File: MediaBrowser.Controller/SyncPlay/PlaybackRequests/SetRepeatModeGroupRequest.cs [hunk 41]
```diff
@@ -0,0 +1,27 @@
...
+    /// <summary>
+    /// Class SetRepeatModeGroupRequest.
+    /// </summary>
+    public class SetRepeatModeGroupRequest : IGroupPlaybackRequest
+    {
+        /// <summary>
+        /// Gets or sets the repeat mode.
+        /// </summary>
+        /// <value>The repeat mode.</value>
+        public string Mode { get; set; }
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/PlaybackRequests/SetRepeatModeGroupRequest.cs:16]: Should use `enum` type instead of string.

File: Jellyfin.Api/Controllers/SyncPlayController.cs [hunk 42]
```diff
@@ -92,31 +97,137 @@ public ActionResult SyncPlayLeaveGroup()
...
+        /// <param name="playlistItemIds">The playlist ids of the items to remove.</param>
+        /// <response code="204">Queue update request sent to all group members.</response>
+        /// <returns>A <see cref="NoContentResult"/> indicating success.</returns>
+        [HttpPost("RemoveFromPlaylist")]
+        [ProducesResponseType(StatusCodes.Status204NoContent)]
+        public ActionResult SyncPlayRemoveFromPlaylist(
+            [FromQuery, Required] string[] playlistItemIds)
+        {
+            var currentSession = RequestHelpers.GetSession(_sessionManager, _authorizationContext, Request);
+            var syncPlayRequest = new RemoveFromPlaylistGroupRequest();
```
Comment (crobibero) [inline Jellyfin.Api/Controllers/SyncPlayController.cs:168]: Pass playlistItemIds in through constructor, make `PlaylistItemIds` `IReadOnlyList<string>`

File: MediaBrowser.Controller/SyncPlay/PlaybackRequests/QueueGroupRequest.cs [hunk 43]
```diff
@@ -0,0 +1,35 @@
...
+    /// <summary>
+    /// Class QueueGroupRequest.
+    /// </summary>
+    public class QueueGroupRequest : IGroupPlaybackRequest
+    {
+        /// <summary>
+        /// Gets the items to queue.
+        /// </summary>
+        /// <value>The items to queue.</value>
+        public List<Guid> ItemIds { get; } = new List<Guid>();
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/PlaybackRequests/QueueGroupRequest.cs:18]: Prefer `IReadOnlyList`, set in constructor

File: MediaBrowser.Controller/SyncPlay/PlaybackRequests/RemoveFromPlaylistGroupRequest.cs [hunk 44]
```diff
@@ -0,0 +1,28 @@
...
+    /// <summary>
+    /// Class RemoveFromPlaylistGroupRequest.
+    /// </summary>
+    public class RemoveFromPlaylistGroupRequest : IGroupPlaybackRequest
+    {
+        /// <summary>
+        /// Gets the playlist identifiers ot the items.
+        /// </summary>
+        /// <value>The playlist identifiers ot the items.</value>
+        public List<string> PlaylistItemIds { get; } = new List<string>();
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/PlaybackRequests/RemoveFromPlaylistGroupRequest.cs:17]: Prefer `IReadOnlyList`

**Comment by crobibero** [comment]
Additional notes:
I recommend setting all properties for `SyncPlay/PlaybackRequests/{*}Request` in a constructor.
`GroupController.DateToUTCString` doesn't seem needed. The API framework already returns `DateTime` as a UTC string.

File: MediaBrowser.Model/SyncPlay/PlayQueueUpdateReason.cs (hunk 33 above)
Comment (OancaAndrei) [reply MediaBrowser.Model/SyncPlay/PlayQueueUpdateReason.cs]: With `QueueNext` items are added after the playing item instead of the end of the playlist. The docs should be more helpful now.

**Comment by OancaAndrei** [comment]
> The API framework already returns `DateTime` as a UTC string.

This is perfect, I wasn't aware of it so I had to use `DateTime`s as `string`s and `GroupController.DateToUTCString` to be sure.

File: MediaBrowser.Model/SyncPlay/PlayQueueUpdate.cs [hunk 45]
```diff
@@ -0,0 +1,61 @@
...
+{
+    /// <summary>
+    /// Class PlayQueueUpdate.
+    /// </summary>
+    public class PlayQueueUpdate
+    {
+        /// <summary>
+        /// Initializes a new instance of the <see cref="PlayQueueUpdate"/> class.
+        /// </summary>
+        public PlayQueueUpdate()
```
Comment (crobibero) [inline MediaBrowser.Model/SyncPlay/PlayQueueUpdate.cs:14]: Pass the playlist items as a constructor parameter

File: MediaBrowser.Model/SyncPlay/NewGroupRequest.cs [hunk 46]
```diff
@@ -0,0 +1,22 @@
...
+{
+    /// <summary>
+    /// Class NewGroupRequest.
+    /// </summary>
+    public class NewGroupRequest
+    {
+        /// <summary>
+        /// Initializes a new instance of the <see cref="NewGroupRequest"/> class.
+        /// </summary>
+        public NewGroupRequest()
```
Comment (crobibero) [inline MediaBrowser.Model/SyncPlay/NewGroupRequest.cs:11]: Pass `GroupName` in the constructor.

File: MediaBrowser.Model/SyncPlay/GroupInfoDto.cs [hunk 47]
```diff
@@ -0,0 +1,51 @@
...
+{
+    /// <summary>
+    /// Class GroupInfoDto.
+    /// </summary>
+    public class GroupInfoDto
+    {
+        /// <summary>
+        /// Initializes a new instance of the <see cref="GroupInfoDto"/> class.
+        /// </summary>
+        public GroupInfoDto()
```
Comment (crobibero) [inline MediaBrowser.Model/SyncPlay/GroupInfoDto.cs:14]: Pass parameters in constructor instead of using each setter.

File: MediaBrowser.Model/SyncPlay/SendCommand.cs [hunk 48]
```diff
@@ -7,17 +7,32 @@ namespace MediaBrowser.Model.SyncPlay
     /// </summary>
     public class SendCommand
     {
+        /// <summary>
+        /// Initializes a new instance of the <see cref="SendCommand"/> class.
+        /// </summary>
+        public SendCommand()
```
Comment (crobibero) [inline MediaBrowser.Model/SyncPlay/SendCommand.cs:13]: Pass parameters through constructor

File: MediaBrowser.Controller/SyncPlay/PlaybackRequests/RemoveFromPlaylistGroupRequest.cs [hunk 49]
```diff
@@ -0,0 +1,39 @@
...
+    {
+        /// <summary>
+        /// Initializes a new instance of the <see cref="RemoveFromPlaylistGroupRequest"/> class.
+        /// </summary>
+        /// <param name="items">The playlist ids of the items to remove.</param>
+        public RemoveFromPlaylistGroupRequest(string[] items)
+        {
+            var list = new List<string>();
+            list.AddRange(items);
+            PlaylistItemIds = list;
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/PlaybackRequests/RemoveFromPlaylistGroupRequest.cs:21]:
```suggestion
            PlaylistItemIds = items;
```

File: MediaBrowser.Controller/SyncPlay/PlaybackRequests/QueueGroupRequest.cs [hunk 50]
```diff
@@ -0,0 +1,48 @@
...
+        /// <summary>
+        /// Initializes a new instance of the <see cref="QueueGroupRequest"/> class.
+        /// </summary>
+        /// <param name="items">The items to add to the queue.</param>
+        /// <param name="mode">The enqueue mode.</param>
+        public QueueGroupRequest(Guid[] items, GroupQueueMode mode)
+        {
+            var list = new List<Guid>();
+            list.AddRange(items);
+            ItemIds = list;
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/PlaybackRequests/QueueGroupRequest.cs:23]:
```suggestion
            ItemIds = items;
```

File: MediaBrowser.Controller/SyncPlay/PlaybackRequests/PlayGroupRequest.cs [hunk 51]
```diff
@@ -0,0 +1,56 @@
...
+        /// Initializes a new instance of the <see cref="PlayGroupRequest"/> class.
+        /// </summary>
+        /// <param name="playingQueue">The playing queue.</param>
+        /// <param name="playingItemPosition">The playing item position.</param>
+        /// <param name="startPositionTicks">The start position ticks.</param>
+        public PlayGroupRequest(Guid[] playingQueue, int playingItemPosition, long startPositionTicks)
+        {
+            var list = new List<Guid>();
+            list.AddRange(playingQueue);
+            PlayingQueue = list;
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/PlaybackRequests/PlayGroupRequest.cs:24]:
```suggestion
            PlayingQueue = playingQueue;
```

File: MediaBrowser.Controller/SyncPlay/IGroupStateContext.cs [hunk 52]
```diff
@@ -0,0 +1,222 @@
...
+        void SetIgnoreGroupWait(SessionInfo session, bool ignoreGroupWait);
+
+        /// <summary>
+        /// Sets a new play queue.
+        /// </summary>
+        /// <param name="playQueue">The new play queue.</param>
+        /// <param name="playingItemPosition">The playing item position in the play queue.</param>
+        /// <param name="startPositionTicks">The start position ticks.</param>
+        /// <returns><c>true</c> if the play queue has been changed; <c>false</c> if something went wrong.</returns>
+        bool SetPlayQueue(IEnumerable<Guid> playQueue, int playingItemPosition, long startPositionTicks);
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/IGroupStateContext.cs:154]:
```suggestion
        bool SetPlayQueue(IReadOnlyList<Guid> playQueue, int playingItemPosition, long startPositionTicks);
```

File: MediaBrowser.Controller/SyncPlay/IGroupStateContext.cs [hunk 53]
```diff
@@ -0,0 +1,222 @@
...
+        /// <param name="playlistItemId">The new playing item identifier.</param>
+        /// <returns><c>true</c> if the play queue has been changed; <c>false</c> if something went wrong.</returns>
+        bool SetPlayingItem(string playlistItemId);
+
+        /// <summary>
+        /// Removes items from the play queue.
+        /// </summary>
+        /// <param name="playlistItemIds">The items to remove.</param>
+        /// <returns><c>true</c> if playing item got removed; <c>false</c> otherwise.</returns>
+        bool RemoveFromPlayQueue(IEnumerable<string> playlistItemIds);
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/IGroupStateContext.cs:168]:
```suggestion
        bool RemoveFromPlayQueue(IReadOnlyList<string> playlistItemIds);
```

File: MediaBrowser.Controller/SyncPlay/IGroupStateContext.cs [hunk 54]
```diff
@@ -0,0 +1,222 @@
...
+        /// <returns><c>true</c> if item has been moved; <c>false</c> if something went wrong.</returns>
+        bool MoveItemInPlayQueue(string playlistItemId, int newIndex);
+
+        /// <summary>
+        /// Updates the play queue.
+        /// </summary>
+        /// <param name="newItems">The new items to add to the play queue.</param>
+        /// <param name="mode">The mode with which the items will be added.</param>
+        /// <returns><c>true</c> if the play queue has been changed; <c>false</c> if something went wrong.</returns>
+        bool AddToPlayQueue(IEnumerable<Guid> newItems, GroupQueueMode mode);
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/IGroupStateContext.cs:184]:
```suggestion
        bool AddToPlayQueue(IReadOnlyList<Guid> newItems, GroupQueueMode mode);
```

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 55]
```diff
@@ -0,0 +1,609 @@
...
+            PlayingItemIndex--;
+            if (PlayingItemIndex < 0)
+            {
+                if (RepeatMode.Equals(GroupRepeatMode.RepeatAll))
+                {
+                    PlayingItemIndex = SortedPlaylist.Count - 1;
+                }
+                else
+                {
+                    PlayingItemIndex++;
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:522]:
```suggestion
                    PlayingItemIndex = 0;
```

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 56]
```diff
@@ -0,0 +1,609 @@
...
+            PlayingItemIndex++;
+            if (PlayingItemIndex >= SortedPlaylist.Count)
+            {
+                if (RepeatMode.Equals(GroupRepeatMode.RepeatAll))
+                {
+                    PlayingItemIndex = 0;
+                }
+                else
+                {
+                    PlayingItemIndex--;
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:492]:
```suggestion
                    PlayingItemIndex = SortedPlaylist.Count - 1;
```

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 57]
```diff
@@ -0,0 +1,609 @@
...
+            var oldIndex = playlist.FindIndex(item => item.PlaylistItemId.Equals(playlistItemId, StringComparison.OrdinalIgnoreCase));
+            if (oldIndex < 0)
+            {
+                return false;
+            }
+
+            var queueItem = playlist[oldIndex];
+            playlist.RemoveAt(oldIndex);
+            newIndex = Math.Min(newIndex, playlist.Count);
+            newIndex = Math.Max(newIndex, 0);
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:373]:
```suggestion
            newIndex = Math.Clamp(newIndex, 0, playlist.Count);
```

File: Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs [hunk 58]
```diff
@@ -41,14 +39,14 @@ public class SyncPlayManager : ISyncPlayManager, IDisposable
         /// <summary>
         /// The map between sessions and groups.
         /// </summary>
-        private readonly Dictionary<string, ISyncPlayController> _sessionToGroupMap =
-            new Dictionary<string, ISyncPlayController>(StringComparer.OrdinalIgnoreCase);
+        private readonly Dictionary<string, IGroupController> _sessionToGroupMap =
```
[the remark this answers is not in the document]
Comment (OancaAndrei) [reply Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs:42]: It was a `ConcurrentDictionary` once but the use of a lock has been suggested instead in the [previous PR](https://github.com/jellyfin/jellyfin/pull/2733#discussion_r411714459).
These comments reminded me to add some missing locks though. :sweat_smile:

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 59]
```diff
@@ -0,0 +1,607 @@
...
+        /// Placeholder index for when no item is playing.
+        /// </summary>
+        /// <value>The no-playing item index.</value>
+        private const int NoPlayingItemIndex = -1;
+
+        /// <summary>
+        /// Random number generator used to shuffle lists.
+        /// </summary>
+        /// <value>The random number generator.</value>
+        private readonly Random randomNumberGenerator = new Random();
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:23]:
```suggestion
        private readonly Random _randomNumberGenerator = new Random();
```

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 60]
```diff
@@ -0,0 +1,607 @@
...
+        /// <param name="items">The new items of the playlist.</param>
+        public void SetPlaylist(IReadOnlyList<Guid> items)
+        {
+            SortedPlaylist.Clear();
+            ShuffledPlaylist.Clear();
+
+            SortedPlaylist = CreateQueueItemsFromArray(items);
+            if (ShuffleMode.Equals(GroupShuffleMode.Shuffle))
+            {
+                ShuffledPlaylist = SortedPlaylist.ToList();
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:105]:
```suggestion
                ShuffledPlaylist = new List<QueueItem>(SortedPlaylist);
```

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 61]
```diff
@@ -0,0 +1,607 @@
...
+        }
+
+        /// <summary>
+        /// Shuffles the playlist. Shuffle mode is changed. The playlist gets re-shuffled if already shuffled.
+        /// </summary>
+        public void ShufflePlaylist()
+        {
+            if (PlayingItemIndex == NoPlayingItemIndex)
+            {
+                ShuffledPlaylist = SortedPlaylist.ToList();
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:137]:
```suggestion
                ShuffledPlaylist = new List<QueueItem>(SortedPlaylist);
```

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 62]
```diff
@@ -0,0 +1,607 @@
...
+                Shuffle(ShuffledPlaylist);
+            }
+            else if (ShuffleMode.Equals(GroupShuffleMode.Sorted))
+            {
+                // First time shuffle.
+                var playingItem = SortedPlaylist[PlayingItemIndex];
+                ShuffledPlaylist = SortedPlaylist.ToList();
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:144]:
```suggestion
                ShuffledPlaylist = new List<QueueItem>(SortedPlaylist);
```

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 63]
```diff
@@ -0,0 +1,607 @@
...
+                ShuffledPlaylist.RemoveAt(PlayingItemIndex);
+                Shuffle(ShuffledPlaylist);
+                ShuffledPlaylist = ShuffledPlaylist.Prepend(playingItem).ToList();
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:147]:
```suggestion
                ShuffledPlaylist.Insert(0, playingItem);
```

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 64]
```diff
@@ -0,0 +1,607 @@
...
+                PlayingItemIndex = 0;
+            }
+            else
+            {
+                // Re-shuffle playlist.
+                var playingItem = ShuffledPlaylist[PlayingItemIndex];
+                ShuffledPlaylist.RemoveAt(PlayingItemIndex);
+                Shuffle(ShuffledPlaylist);
+                ShuffledPlaylist = ShuffledPlaylist.Prepend(playingItem).ToList();
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:156]:
```suggestion
                ShuffledPlaylist.Insert(0, playingItem);
```

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 65]
```diff
@@ -0,0 +1,607 @@
...
+        {
+            var playingItem = GetPlayingItem();
+            if (playingItem != null)
+            {
+                return playingItem.PlaylistItemId;
+            }
+            else
+            {
+                return null;
+            }
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:246]:
```suggestion
            return playingItem?.PlaylistItemId;
```

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 66]
```diff
@@ -0,0 +1,607 @@
...
+        {
+            var playingItem = GetPlayingItem();
+            if (playingItem != null)
+            {
+                return playingItem.ItemId;
+            }
+            else
+            {
+                return Guid.Empty;
+            }
```
Comment (crobibero) [inline MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:263]:
```suggestion
            return playingItem?.ItemId ?? Guid.Empty;
```

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 67]
```diff
@@ -0,0 +1,662 @@
...
+        /// Gets or sets the last activity.
+        /// </summary>
+        /// <value>The last activity.</value>
+        public DateTime LastActivity { get; set; }
+
+        /// <summary>
+        /// Gets the participants.
+        /// </summary>
+        /// <value>The participants, or members of the group.</value>
+        public Dictionary<string, GroupMember> Participants { get; } =
```
Comment (crobibero) [inline Emby.Server.Implementations/SyncPlay/GroupController.cs:130]: Should probably add a lock for this dictionary
Additionally, please note what the key is (sessionId)

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 68]
```diff
@@ -0,0 +1,662 @@
...
+        /// Checks if a given user can access all items of a given queue, that is,
+        /// the user has the required minimum parental access and has access to all required folders.
+        /// </summary>
+        /// <param name="user">The user.</param>
+        /// <param name="queue">The queue.</param>
+        /// <returns><c>true</c> if the user can access all the items in the queue, <c>false</c> otherwise.</returns>
+        private bool HasAccessToQueue(User user, IReadOnlyList<Guid> queue)
+        {
+            // Check if queue is empty.
+            if (!queue?.Any() ?? true)
```
Comment (crobibero) [inline Emby.Server.Implementations/SyncPlay/GroupController.cs:207]:
```suggestion
            if (queue == null || queue.Count == 0)
```

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 69]
```diff
@@ -0,0 +1,662 @@
...
+                }
+            }
+
+            return true;
+        }
+
+        private bool AllUsersHaveAccessToQueue(IReadOnlyList<Guid> queue)
+        {
+            // Check if queue is empty.
+            if (!queue?.Any() ?? true)
```
Comment (crobibero) [inline Emby.Server.Implementations/SyncPlay/GroupController.cs:232]:
```suggestion
            if (queue == null || queue.Count == 0)
```

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 70]
```diff
@@ -0,0 +1,662 @@
...
+            if (sessionIsPlayingAnItem)
+            {
+                var playlist = session.NowPlayingQueue.Select(item => item.Id).ToList();
+                PlayQueue.Reset();
+                PlayQueue.SetPlaylist(playlist);
+                PlayQueue.SetPlayingItemById(session.FullNowPlayingItem.Id);
+                RunTimeTicks = session.FullNowPlayingItem.RunTimeTicks ?? 0;
+                PositionTicks = session.PlayState.PositionTicks ?? 0;
+
+                // Mantain playstate.
```
Comment (crobibero) [inline Emby.Server.Implementations/SyncPlay/GroupController.cs:271]:
```suggestion
                // Maintain playstate.
```

File: Emby.Server.Implementations/SyncPlay/GroupController.cs (hunk 68 above)
Comment (OancaAndrei) [reply Emby.Server.Implementations/SyncPlay/GroupController.cs]: I'm sorry to be bothering you with these dumb one liners but Roslynator suggested that. That's also why I added that extra comment hahaha, I was like: "If this is the C# way of doing things then be it.". The suggestion pops up only for `IEnumerable`. :man_shrugging:

Comment (crobibero) [reply Emby.Server.Implementations/SyncPlay/GroupController.cs]: Don't know why but the analyzers seem to prefer Linq / IEnumerable.... We're just trying to avoid it unless it makes the code much simpler :)

File: Emby.Server.Implementations/SyncPlay/GroupController.cs (hunk 67 above)
Comment (OancaAndrei) [reply Emby.Server.Implementations/SyncPlay/GroupController.cs]: I made the `Dictionary` private now as it wasn't really needed anywhere else.

My idea is to keep locking related code outside the scope of some classes (all of them actually), and that's why `SyncPlayManager` handles the locks.

> Additionally, please note what the key is (sessionId)

I'm not sure I got this right. You mean that something else should be used as the key?

Comment (crobibero) [reply Emby.Server.Implementations/SyncPlay/GroupController.cs]: External locking sounds good to me

For the comment- I like having a comment when using the dictionary to store items, especially when the key is a plain string

**Comment by OancaAndrei** [comment]
The new locking logic needs more testing.

File: Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs [hunk 71]
```diff
@@ -41,338 +44,412 @@ public class SyncPlayManager : ISyncPlayManager, IDisposable
...
+            new Dictionary<Guid, IGroupController>();
 
         /// <summary>
-        /// Lock used for accesing any group.
+        /// Lock used for accesing the list of groups.
         /// </summary>
         private readonly object _groupsLock = new object();
 
+        /// <summary>
+        /// Lock used for accesing the session-to-group map.
```
Comment (crobibero) [inline Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs:62]:
```suggestion
        /// Lock used for accessing the session-to-group map.
```

File: Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs [hunk 72]
```diff
@@ -41,338 +44,412 @@ public class SyncPlayManager : ISyncPlayManager, IDisposable
...
         /// The groups.
         /// </summary>
-        private readonly Dictionary<Guid, ISyncPlayController> _groups =
-            new Dictionary<Guid, ISyncPlayController>();
+        private readonly Dictionary<Guid, IGroupController> _groups =
+            new Dictionary<Guid, IGroupController>();
 
         /// <summary>
-        /// Lock used for accesing any group.
+        /// Lock used for accesing the list of groups.
```
Comment (crobibero) [inline Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs:57]:
```suggestion
        /// Lock used for accessing the list of groups.
```

**Review by crobibero — APPROVED** [review]
I'm no expert on locking but everything looks good to me

File: Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs (hunk 71 above)
Comment (OancaAndrei) [reply Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs:62]: Can I stuff these into the next PR or should I make a commit here now?

Comment (BaronGreenback) [reply Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs:62]: commit here,

**Comment by OancaAndrei** [comment]
Umh, there's something wrong with WebSockets after #4285: SyncPlay won't receive any message. Browser console shows no error and the `ws` connection is established.

SyncPlay still works after #4261.

I'll investigate.

**Comment by BaronGreenback** [comment]
> WebSockets

Just had a quick glance (not on dev machine). Where is IWebSocketListener registered with the DI?

**Comment by BaronGreenback** [comment]
Cancel that last one.

However

if i have

```
            ServiceCollection.AddScoped<IWebSocketListener, SessionWebSocketListener>();
            ServiceCollection.AddScoped<IWebSocketListener, ActivityLogWebSocketListener>();
            ServiceCollection.AddScoped<IWebSocketListener, ScheduledTasksWebSocketListener>();
            ServiceCollection.AddScoped<IWebSocketListener, SessionInfoWebSocketListener>();
```
How does DI know which one to instantiate?

**Comment by BaronGreenback** [comment]
Got it in the debugger now . Problem is with WebSocketHandlerMiddleware.Invoke.

DI isn't resolving IWebSocketManager.

**Comment by BaronGreenback** [comment]
Ok solved it. Circular reference issue.

issue is here.

ServiceCollection.AddScoped<IWebSocketListener, SessionWebSocketListener>();
ServiceCollection.AddScoped<IWebSocketListener, ActivityLogWebSocketListener>();
ServiceCollection.AddScoped<IWebSocketListener, ScheduledTasksWebSocketListener>();
ServiceCollection.AddScoped<IWebSocketListener, SessionInfoWebSocketListener>();

// TODO fix circular dependency on IWebSocketManager
ServiceCollection.AddScoped(serviceProvider => new Lazy<IEnumerable<IWebSocketListener>>(serviceProvider.GetRequiredService<IEnumerable<IWebSocketListener>>));


**SessionWebSocketListener** sets the **webSocketManager.WebSocketConnected** property.

WebsocketManager.WebSocketRequestHandler attempts to trigger WebSocketConnected, however, since WebsocketManager.webSocketListeners is lazy, the DI constructs have not been created, so the WebSocketConnected is not defined.

**Comment by BaronGreenback** [comment]
If the IWebSocketListener are DI scoped, what happens to the values in WebSocketManager.WebSocketListeners, as that is a Singleton?

**Comment by BaronGreenback** [comment]
@OancaAndrei Could you test again please. Think i've fixed the websockets issue.

**Comment by OancaAndrei** [comment]
> @OancaAndrei Could you test again please. Think i've fixed the websockets issue.

WebSockets are back now, I can also see the KeepAlive messages being exchanged.

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 73]
```diff
@@ -0,0 +1,669 @@
...
+            };
+        }
+
+        /// <summary>
+        /// Checks if a given user can access a given item, that is, the user has access to a folder where the item is stored.
+        /// </summary>
+        /// <param name="user">The user.</param>
+        /// <param name="item">The item.</param>
+        /// <returns><c>true</c> if the user can access the item, <c>false</c> otherwise.</returns>
+        private bool HasAccessToItem(User user, BaseItem item)
```
Comment (cvium) [inline Emby.Server.Implementations/SyncPlay/GroupController.cs:197]: This is basically `BaseItem.IsVisibleStandalone`, right?

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 74]
```diff
@@ -0,0 +1,669 @@
...
+            // Check if queue is empty.
+            if (queue == null || queue.Count == 0)
+            {
+                return true;
+            }
+
+            foreach (var itemId in queue)
+            {
+                var item = _libraryManager.GetItemById(itemId);
+                if (user.MaxParentalAgeRating.HasValue && item.InheritedParentalRatingValue > user.MaxParentalAgeRating)
```
Comment (cvium) [inline Emby.Server.Implementations/SyncPlay/GroupController.cs:222]: This is also basically `This is basically BaseItem.IsVisibleStandalone`.

File: Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs [hunk 75]
```diff
@@ -41,338 +44,396 @@ public class SyncPlayManager : ISyncPlayManager, IDisposable
...
+        private void AddSessionToGroup(SessionInfo session, IGroupController group)
+        {
+            if (session == null)
             {
-                _logger.LogWarning("HandleRequest: {0} does not have access to SyncPlay.", session.Id);
+                throw new InvalidOperationException("Session is null!");
+            }
 
-                var error = new GroupUpdate<string>()
+            lock (_mapsLock)
```
Comment (cvium) [inline Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs:358]: `AddSessionToGroup` is a private function that is always called when `_mapsLock` is already held.

**Comment by joshuaboniface** [comment]
Any movement here? I'm trying to get this into 10.7.0...

**Comment by OancaAndrei** [comment]
I need to address the requested changes but otherwise it's ready. I'll get into it shortly.

File: Emby.Server.Implementations/SyncPlay/GroupController.cs (hunk 73 above)
Comment (OancaAndrei) [reply Emby.Server.Implementations/SyncPlay/GroupController.cs:197]: Oh yes, I knew it had to be somewhere, couldn't find it though.

File: Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs (hunk 75 above)
Comment (OancaAndrei) [reply Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs:358]: Initially I put a remark in the description about locking but then I considered safer the addition of the lock in here as well, in case future devs missed it. I guess I should give more trust to whomever will make changes in here.

**Comment by OancaAndrei** [comment]
> Any movement here? I'm trying to get this into 10.7.0...

Once this gets merged, the next SyncPlay PR should also be ready for review. Is there a way to squeeze that in as well? The number of changes in the next PR should drop a bit as it shares the commits from here.

File: Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs [hunk 76]
```diff
@@ -41,338 +44,415 @@ public class SyncPlayManager : ISyncPlayManager, IDisposable
...
                 {
-                    Type = GroupUpdateType.CreateGroupDenied
-                };
+                    _logger.LogWarning("Session {SessionId} tried to join group {GroupId} that does not exist.", session.Id, request.GroupId);
 
-                _sessionManager.SendSyncPlayGroupUpdate(session.Id, error, CancellationToken.None);
-                return;
-            }
+                    var error = new GroupUpdate<string>(Guid.Empty, GroupUpdateType.GroupDoesNotExist, string.Empty);
+                    _sessionManager.SendSyncPlayGroupUpdate(session, error, CancellationToken.None);
```
Comment (cvium) [inline Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs:152]: I don't like that the syncplay commands are part of the sessionmanager. I'd rather the sessionmanager exposed a generic method for sending commands.

Not a huge deal right now though, but food for thought.

File: MediaBrowser.Controller/SyncPlay/IGroupController.cs [hunk 77]
```diff
@@ -0,0 +1,87 @@
...
+using MediaBrowser.Controller.SyncPlay.Queue;
+using MediaBrowser.Controller.SyncPlay.Requests;
+using MediaBrowser.Model.SyncPlay;
+
+namespace MediaBrowser.Controller.SyncPlay
+{
+    /// <summary>
+    /// Interface IGroupController.
+    /// </summary>
+    public interface IGroupController
```
Comment (cvium) [inline MediaBrowser.Controller/SyncPlay/IGroupController.cs:14]: Will there be more implementations of this? Otherwise I don't think there's any value in having it. As it is right now, GroupController could just be a `Group` class that is in charge of its own state, which the SyncPlayManager manipulates at will.

File: Emby.Server.Implementations/SyncPlay/GroupController.cs [hunk 78]
```diff
@@ -0,0 +1,651 @@
...
+            var updateOthers = NewSyncPlayGroupUpdate(GroupUpdateType.UserJoined, session.UserName);
+            SendGroupUpdate(session, SyncPlayBroadcastType.AllExceptCurrentSession, updateOthers, cancellationToken);
+
+            _state.SessionJoined(this, _state.Type, session, cancellationToken);
+
+            _logger.LogInformation("Session {SessionId} joined group {GroupId}.", session.Id, GroupId.ToString());
+        }
+
+        /// <inheritdoc />
+        public void SessionRestore(SessionInfo session, JoinGroupRequest request, CancellationToken cancellationToken)
```
[the remark this answers is not in the document]
Comment (OancaAndrei) [reply Emby.Server.Implementations/SyncPlay/GroupController.cs:293]: Indeed, forgot about it. This was an attempt to handle multiple sockets of the same session but eventually had to drop it because underneath `WebSocketController::SendMessage` sends messages only to the last active/connected socket. Haven't checked if changes have been made there.

I'll remove the duplicate lines.

File: Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs [hunk 79]
```diff
@@ -41,338 +44,415 @@ public class SyncPlayManager : ISyncPlayManager, IDisposable
...
-                        Type = GroupUpdateType.NotInGroup
-                    };
-                    _sessionManager.SendSyncPlayGroupUpdate(session.Id, error, CancellationToken.None);
-                    return;
-                }
+        /// <summary>
+        /// Checks if a given session has joined a group.
+        /// </summary>
+        /// <remarks>
+        /// Method is not thread-safe, external locking on <see cref="_mapsLock"/> is required.
```
[the remark this answers is not in the document]
Comment (OancaAndrei) [reply Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs:328]: As long as a request is processed singularly for a certain group all should be fine. And the locks on `IGroupController` try to guarantee this. Clients can send updates at their own pace, what matters is that an action is isolated from others pertaining the same group.

The `_groupsLock` and `_mapsLock` locks, on the other hand, control the access flow to `_groups` and `_sessionToGroupMap`, respectively, and these two containers are not thread-safe. The methods that handle them inherit this non thread-safety.

In other words, requests are concurrent between groups and only if they don't make changes to the list of groups/participants.

Finally, to avoid deadlocks, the locks are acquired and released following the same order.

File: Jellyfin.Api/Controllers/SyncPlayController.cs [hunk 80]
```diff
@@ -85,38 +87,124 @@ public ActionResult SyncPlayJoinGroup([FromQuery, Required] Guid groupId)
...
+        /// <response code="204">Queue update request sent to all group members.</response>
+        /// <returns>A <see cref="NoContentResult"/> indicating success.</returns>
+        [HttpPost("RemoveFromPlaylist")]
+        [ProducesResponseType(StatusCodes.Status204NoContent)]
+        public ActionResult SyncPlayRemoveFromPlaylist(
+            [FromBody, Required] RemoveFromPlaylistRequestBody requestData)
+        {
+            var currentSession = RequestHelpers.GetSession(_sessionManager, _authorizationContext, Request);
+            var syncPlayRequest = new RemoveFromPlaylistGroupRequest(requestData.PlaylistItemIds);
+            _syncPlayManager.HandleRequest(currentSession, syncPlayRequest, CancellationToken.None);
```
[the remark this answers is not in the document]
Comment (OancaAndrei) [reply Jellyfin.Api/Controllers/SyncPlayController.cs:159]: Can't find the old comment in which I've explained a bit why these exist, but briefly, I tried to apply the [Visitor pattern](https://en.wikipedia.org/wiki/Visitor_pattern) along with the [State pattern](https://en.wikipedia.org/wiki/State_pattern) to create what basically is a state machine that handles requests.

The `*RequestBody` DTOs are made for accepting data from the clients while the `*GroupRequest` classes exist for the state machine.

Also, I wanted to make `SyncPlayManager` agnostic to the type of request it handles: its job is to pass these requests along to the correct `GroupController`.

All of these reasons led to this result I guess.

Should I drop the overloading with `HandleRequest` and explicit every request type in `SyncPlayManager`? Like `SyncPlayManager.PlayRequest(RequestDTO)` and so on?

File: Jellyfin.Api/Controllers/TimeSyncController.cs [hunk 81]
```diff
@@ -22,18 +22,14 @@ public class TimeSyncController : BaseJellyfinApiController
...
-            // Important to keep the following two lines at the end
-            var responseTransmissionTime = DateTime.UtcNow.ToUniversalTime().ToString("o", DateTimeFormatInfo.InvariantInfo);
-            response.ResponseTransmissionTime = responseTransmissionTime;
+            // Important to keep the following line at the end
+            var responseTransmissionTime = DateTime.UtcNow.ToUniversalTime();
 
             // Implementing NTP on such a high level results in this useless
             // information being sent. On the other hand it enables future additions.
-            return response;
+            return new UtcTimeResponse(requestReceptionTime, responseTransmissionTime);
```
[the remark this answers is not in the document]
Comment (OancaAndrei) [reply Jellyfin.Api/Controllers/TimeSyncController.cs:32]: Exactly, that's what I meant with `high level` in the comment above. Yet, I wanted to maintain both values, even if practically the same, so that client side implementation would still resemble the NTP one.

> We also have a response time middleware now that sets the best estimate for response time in the custom header `X-Response-Time-ms`.

Using this one would definitely make more sense, hoping it's more accurate. Is there also a time for when the request has been received by the server?

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs [hunk 82]
```diff
@@ -0,0 +1,593 @@
...
+        /// Gets or sets the sorted playlist.
+        /// </summary>
+        /// <value>The sorted playlist, or play queue of the group.</value>
+        private List<QueueItem> SortedPlaylist { get; set; } = new List<QueueItem>();
+
+        /// <summary>
+        /// Gets or sets the shuffled playlist.
+        /// </summary>
+        /// <value>The shuffled playlist, or play queue of the group.</value>
+        private List<QueueItem> ShuffledPlaylist { get; set; } = new List<QueueItem>();
```
[the remark this answers is not in the document]
Comment (OancaAndrei) [reply MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:67]: Clients expect to be able to unshuffle a playlist, that is return the playlist to the initial sorted state.

File: Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs (hunk 76 above)
Comment (OancaAndrei) [reply Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs:152]: I totally agree.

File: MediaBrowser.Controller/SyncPlay/IGroupController.cs (hunk 77 above)
Comment (OancaAndrei) [reply MediaBrowser.Controller/SyncPlay/IGroupController.cs:14]: I agree on this one as well, I followed the Java way of passing objects around but `GroupController` will be used internally only by `SyncPlayManager` so yeah, the interface can be dropped.

File: Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs [hunk 83]
```diff
@@ -41,338 +44,415 @@ public class SyncPlayManager : ISyncPlayManager, IDisposable
...
-            else
+
+            // Group lock required as GroupController is not thread-safe.
+            lock (group)
             {
-                // Otherwise show all available groups
-                return _groups.Values.Where(
-                    group => HasAccessToItem(user, group.GetPlayingItemId())).Select(
-                    group => group.GetInfo()).ToList();
+                group.HandleRequest(session, request, cancellationToken);
```
[the remark this answers is not in the document]
Comment (OancaAndrei) [reply Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs:286]: This one's also about the **Visitor pattern**. Instead of having multiple if-else/switch statements to dispatch the request to the right state, overloading is used.

Actually, maybe this one's more about `SyncPlayManager` not having to care about the underneath type of the request.

But I hope you get the idea. Should I write a comment to make this easier to understand?

File: Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs (hunk 79 above)
[the remark this answers is not in the document]
Comment (cvium) [reply Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs:328]: I would need to spend more time looking through the code on my local machine so pardon my asking, but could we not use the Concurrent collections and employ optimistic locking? I assume that individual members can only manipulate their own state and that a potential admin can manipulate them all. But if someone is kicked or leaves the room, then the locking isn't strictly necessary as the 2nd removal will just be a noop.

Which actions require pessimistic locking to not cause unwanted race conditions?

File: Jellyfin.Api/Controllers/TimeSyncController.cs (hunk 81 above)
[the remark this answers is not in the document]
Comment (cvium) [reply Jellyfin.Api/Controllers/TimeSyncController.cs:32]: There's no built-in method for this. Our middleware is the best guesstimation.

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs (hunk 82 above)
[the remark this answers is not in the document]
Comment (cvium) [reply MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:67]: I've never encountered software that did this. Couldn't we just assign an integer value to the queueitem and sort by that as the "original" order?

File: Jellyfin.Api/Controllers/SyncPlayController.cs (hunk 80 above)
[the remark this answers is not in the document]
Comment (cvium) [reply Jellyfin.Api/Controllers/SyncPlayController.cs:159]: I'm not necessarily against either pattern or the relatively thin SyncPlayManager, _but_ it adds a bit of "cruft" and the flow is more complex. For state machines I would probably have opted to use something like https://github.com/dotnet-state-machine/stateless.

For the `HandleRequest` overloads I think that renaming them so that their intent is more visible would go a long way to improve readability. It adds a lot of latency having to look at the request type and then from that infer what the intent is.

**Comment by cvium** [comment]
@OancaAndrei I took the liberty of moving the `IsRequestValid` logic into asp.net auth policies. Can you test it?

**Comment by OancaAndrei** [comment]
> @OancaAndrei I took the liberty of moving the `IsRequestValid` logic into asp.net auth policies. Can you test it?

Sure, later I'll also get back to the other pending code.

File: Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs (hunk 79 above)
[the remark this answers is not in the document]
Comment (OancaAndrei) [reply Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs:303]: I must confess that optimistic locking is one of those obvious solutions/approaches one goes for, if only I wasn't completely oblivious to it. I wasn't aware that the concurrent version of the collections work this way.

> Which actions require pessimistic locking to not cause unwanted race conditions?

I think that the problematic ones are those related to joining/leaving groups.
- Joining a group can potentially change another group's state as well: a user, that has joined a group, wants to join another group without first explicitly leaving the current one. The server allows this and handles the leave-old-group/join-new-group steps in the same request.
- Same goes for creating a new group while being in another one.
- Another edge case that needs to be handled is the following: [last member is leaving a group, which is now about to be destroyed, and another member attempts to join this same group](https://github.com/jellyfin/jellyfin/pull/2733#discussion_r411714459).

I'll try bringing back the concurrent collections and drop one of the two locks in `SyncPlayManager`, probably `_mapsLock`.

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs (hunk 82 above)
[the remark this answers is not in the document]
Comment (OancaAndrei) [reply MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:67]: > I've never encountered software that did this.

The web-client does it hahaha, I guess it's inherited from Emby.

With saved indices it gets tricky when doing `QueueNext` (add items right after the currently playing item). We also have to consider that the playlist can change (items moved around, or removed entirely) while it's shuffled.

File: Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs (hunk 79 above)
[the remark this answers is not in the document]
Comment (OancaAndrei) [reply Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs:303]: > The server allows this and handles the leave-old-group/join-new-group steps in the same request.

Dropping this would simplify things a lot. :thinking:

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs (hunk 82 above)
[the remark this answers is not in the document]
Comment (cvium) [reply MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:67]: Since every group has its own playlist I would just keep an integer in the group controller and increment it whenever a new item is added.

File: Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs (hunk 79 above)
[the remark this answers is not in the document]
Comment (cvium) [reply Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs:303]: > Another edge case that needs to be handled is the following: last member is leaving a group, which is now about to be destroyed, and another member attempts to join this same group.

Valid point and we should indeed be careful when performing actions that affect the others in the group, but I just think the current locking scheme is a little aggressive.

The thing about Concurrent collections is that the guarantee thread safety, _but not_ necessarily safety of the values. Two threads can overwrite each other if you're not careful. That's the pitfall. I do think there's a reasonable middle ground hidden somewhere here though.

File: MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs (hunk 82 above)
[the remark this answers is not in the document]
Comment (OancaAndrei) [reply MediaBrowser.Controller/SyncPlay/Queue/PlayQueueManager.cs:67]: This works when appending at the end of the playlist but `QueueNext` can also insert items in the middle (if the playing item happens to be there). In this case all items after the playing one would need to have their index incremented by the number of new items being added, which is surely doable, but requires additional iteration on these items.

In terms of performance, I don't like it very much :sweat_smile:.

File: Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs (hunk 79 above)
[the remark this answers is not in the document]
Comment (OancaAndrei) [reply Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs:304]: Noticed another "bug" that can happen in the following way:
- A `HandleRequest` get the reference to a Group but does not manage to lock on it.
- A `LeaveGroup` request gets a reference to the same Group and manages to lock it; Group is now empty and will be removed.
- `HandleRequest` now locks on an empty Group.

Nothing too bad per se should happen, but it's not that right either.
I think that I'm going to add a property to `Group` to signal whether it's still active otherwise the requests are dropped (probably checking if it's empty is enough).

[the remark this answers is not in the document]
Comment (OancaAndrei) [reply Emby.Server.Implementations/SyncPlay/SyncPlayManager.cs]: Done. The code should be cleaner now.

File: Jellyfin.Api/Controllers/SyncPlayController.cs [hunk 84]
```diff
@@ -69,6 +69,7 @@ public class SyncPlayController : BaseJellyfinApiController
         /// <returns>A <see cref="NoContentResult"/> indicating success.</returns>
         [HttpPost("Join")]
         [ProducesResponseType(StatusCodes.Status204NoContent)]
+        [Authorize(Policy = Policies.SyncPlayAccess)]
```
Comment (cvium) [inline Jellyfin.Api/Controllers/SyncPlayController.cs:72]: It's already set on a controller level

Comment (OancaAndrei) [reply Jellyfin.Api/Controllers/SyncPlayController.cs:72]: Oh, I see it now. :+1:

Comment (OancaAndrei) [reply Jellyfin.Api/Controllers/SyncPlayController.cs:72]: Actually, this results in a different behaviour. What should happen to sessions that see their permissions revoked while participating in a group?

I was thinking that all request types should be allowed except for the ones that are explicitly marked now, otherwise that session won't be able to leave that group, ever.
Another approach would be to kick that session from the group, but I'm not aware of triggers when user settings are changed.

Comment (cvium) [reply Jellyfin.Api/Controllers/SyncPlayController.cs:72]: True, there's no Event for that. Not ideal. But DefaultAuthorization should only apply to the leave group endpoint then?

File: Jellyfin.Api/Controllers/SyncPlayController.cs (hunk 80 above)
[the remark this answers is not in the document]
Comment (OancaAndrei) [reply Jellyfin.Api/Controllers/SyncPlayController.cs:162]: I've moved the request arguments so they're first, not much but it does help with readability.

I gave a quick look at *Stateless* and seems promising, like it should be able to handle the states I've defined for SyncPlay. Tomorrow I'll see if I can migrate the code to it.

File: Jellyfin.Api/Controllers/SyncPlayController.cs (hunk 84 above)
Comment (joshuaboniface) [reply Jellyfin.Api/Controllers/SyncPlayController.cs:72]: Is this a blocker, or something that can be easily fixed later without significant reorganization of the codebase?

Comment (joshuaboniface) [reply Jellyfin.Api/Controllers/SyncPlayController.cs:72]: If it's the latter as I'm hoping, I'm gonna merge in about 1h so this can make 10.7.0.

**Review by joshuaboniface — APPROVED** [review]

File: Jellyfin.Api/Controllers/SyncPlayController.cs (hunk 84 above)
Comment (OancaAndrei) [reply Jellyfin.Api/Controllers/SyncPlayController.cs:72]: > True, there's no Event for that. Not ideal. But DefaultAuthorization should only apply to the leave group endpoint then?

It would be more restrictive but yeah, it can be a solution as well. I was seeing it more this way: if the user had the permission to join in the past then they might as well keep using the group they're in. In other words, I don't see the need to make the new restriction retroactive.

If a server admin wanted to kick an user from a group (after blocking the access to other/new groups) then a new administration page would fit better IMO.

> Is this a blocker, or something that can be easily fixed later without significant reorganization of the codebase?

Had to get some shuteye. A one liner should fix this.

Comment (cvium) [reply Jellyfin.Api/Controllers/SyncPlayController.cs:72]: Policies can do whatever. If you really want to, you can make a policy that allows the user to call the group related endpoints if they are in that group

Comment (OancaAndrei) [reply Jellyfin.Api/Controllers/SyncPlayController.cs:72]: > If you really want to, you can make a policy that allows the user to call the group related endpoints if they are in that group.

Ok, this one's better. I'll make a `Policies.SyncPlayInGroup` and use it where needed.

> I think we should just create an event when user policies are updated and then kick them.

And this can be a future addition, not strictly related to these policies.

Sounds good?

**Comment by Uatschitchun** [comment]
This maybe related?
https://github.com/jellyfin/jellyfin/issues/5065
