### PR TITLE
Make ReadInputAtNativeFramerate configurable for M3U tuner

### LINKED ISSUE #13772: Owncast livestreams added to Live TV stop randomly when remuxing or transcoding
### Description of the bug

Owncast is popular repository, that allows users to host their own livestreams. It also provides a normal m3u8 playlist so it can be integrated into Jellyfin via the Live TV feature. This works great, but when remuxing or transcoding the stream randomly stops.
I also openend an issue in the owncast repository [owncast/#4263](https://github.com/owncast/owncast/issues/4263).

The solution seems to be that an Owncast livestream when remuxing or transcoding via Jellyfin requires the `-re` - Read input at native frame rate - flag. With this added flag the live stream no longer randomly stops.

### Reproduction steps

1. Add an owncast livestream as a Live TV channel to Jellyfin.
2.  Start watching. To reproduce it cannot be direct playing.
3. The stream randomly stops.

### What is the current _bug_ behavior?

Remuxing/Transocing breaks at some point with "Failed to reload playlist 0" and "Error during demuxing: Invalid data found when processing input".

### What is the expected _correct_ behavior?

FFmpeg should not error out.

### Jellyfin Server version

10.10.0+

### Specify commit id

_No response_

### Specify unstable release number

_No response_

### Specify version number

_No response_

### Specify the build version

10.10.3

### Environment

```markdown
- OS: Windows 11
- Linux Kernel:
- Virtualization:
- Clients: Browser, Android, Fire Stick
- Browser: Chrome 131
- FFmpeg Version: 7.0
- Playback Method: Transcode, Remuxing
- Hardware Acceleration: Nvenc
- GPU Model: Nvidia Geforce GTX 1660 Ti
- Plugins:
- Reverse Proxy:
- Base URL: 
- Networking:
- Storage:
```

### Jellyfin logs

```shell
No relevant Jellyfin logs.
```

### FFmpeg logs

```shell
[http @ 000001de57a34b40] Opening 'http://192.168.1.1:8080/hls/0/stream.m3u8' for reading
[hls @ 000001de57a2ca40] Skip ('#EXT-X-VERSION:6')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-INDEPENDENT-SEGMENTS')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:49:05.332+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:49:13.666+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:49:21.999+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:49:30.332+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:49:38.666+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:49:46.999+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:49:55.332+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:50:03.666+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:50:11.999+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:50:20.332+0000')
[http @ 000001de57a62fc0] Opening 'http://192.168.1.1:8080/hls/0/stream-gy5CXY2NRm-145.ts' for reading
[hls @ 000001de57a70d40] Opening 'R:\jellyfin\cache\transcodes\e5b4ab051a03a619654d0aff2a99b356142.ts' for writing
[hls @ 000001de57a70d40] Opening 'R:\jellyfin\cache\transcodes\e5b4ab051a03a619654d0aff2a99b356.m3u8.tmp' for writing
size=N/A time=00:19:35.00 bitrate=N/A speed=   1x    
size=N/A time=00:19:35.00 bitrate=N/A speed=   1x    
size=N/A time=00:19:35.00 bitrate=N/A speed=0.999x    
size=N/A time=00:19:35.00 bitrate=N/A speed=0.999x    
size=N/A time=00:19:35.00 bitrate=N/A speed=0.998x    
size=N/A time=00:19:35.00 bitrate=N/A speed=0.998x    
size=N/A time=00:19:35.00 bitrate=N/A speed=0.997x    
size=N/A time=00:19:35.00 bitrate=N/A speed=0.997x    
size=N/A time=00:19:35.00 bitrate=N/A speed=0.996x    
size=N/A time=00:19:35.00 bitrate=N/A speed=0.996x    
size=N/A time=00:19:35.00 bitrate=N/A speed=0.996x    
size=N/A time=00:19:35.00 bitrate=N/A speed=0.995x    
size=N/A time=00:19:35.00 bitrate=N/A speed=0.995x    
size=N/A time=00:19:35.00 bitrate=N/A speed=0.994x    
size=N/A time=00:19:35.00 bitrate=N/A speed=0.994x    
size=N/A time=00:19:35.00 bitrate=N/A speed=0.994x    
size=N/A time=00:19:35.00 bitrate=N/A speed=0.993x    
[http @ 000001de57a34b40] Opening 'http://192.168.1.1:8080/hls/0/stream.m3u8' for reading
[hls @ 000001de57a2ca40] Failed to reload playlist 0
[http @ 000001de57a34b40] Opening 'http://192.168.1.1:8080/hls/0/stream.m3u8' for reading
[hls @ 000001de57a2ca40] Skip ('#EXT-X-VERSION:6')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-INDEPENDENT-SEGMENTS')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:49:21.999+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:49:30.332+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:49:38.666+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:49:46.999+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:49:55.332+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:50:03.666+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:50:11.999+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:50:20.332+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:50:28.666+0000')
[hls @ 000001de57a2ca40] Skip ('#EXT-X-PROGRAM-DATE-TIME:2025-03-17T22:50:36.999+0000')
[http @ 000001de57a62fc0] Opening 'http://192.168.1.1:8080/hls/0/stream-gy5CXY2NRm-146.ts' for reading
[http @ 000001de57a38440] Opening 'http://192.168.1.1:8080/hls/0/stream-gy5CXY2NRm-147.ts' for reading
[in#0/hls @ 000001de57a0f880] Error during demuxing: Invalid data found when processing input
[hls @ 000001de57a70d40] Opening 'R:\jellyfin\cache\transcodes\e5b4ab051a03a619654d0aff2a99b356143.ts' for writing
[hls @ 000001de57a70d40] Opening 'R:\jellyfin\cache\transcodes\e5b4ab051a03a619654d0aff2a99b356.m3u8.tmp' for writing
[out#0/hls @ 000001de57a25580] video:879082KiB audio:718KiB subtitle:0KiB other streams:0KiB global headers:0KiB muxing overhead: unknown
size=N/A time=00:19:35.06 bitrate=N/A speed=0.993x
```

### Client / Browser logs

_No response_

### Relevant screenshots or videos

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by timminator**
This PR makes ReadInputAtNativeFramerate configurable for the M3U Tuner and works very similar to PR #7903 that added IgnoreDts as a configurable option.

Changes

Added ReadInputAtNativeFramerate to TunerHostInfo
Added ReadInputAtNativeFramerate checkbox to M3U tuner configuration page: https://github.com/jellyfin/jellyfin-web/pull/6659

Fixes #13772

### CODE REVIEW

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 1]
```diff
@@ -6980,7 +6980,7 @@ public void AttachMediaSourceInfo(
             state.RemoteHttpHeaders = mediaSource.RequiredHttpHeaders;
             state.ReadInputAtNativeFramerate = mediaSource.ReadAtNativeFramerate;
 
-            if (state.ReadInputAtNativeFramerate
+            if ((state.ReadInputAtNativeFramerate && !state.IsSegmentedLiveStream)
```
Comment (Shadowghost) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:6983]: Why this change?

Comment (timminator) [reply MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:6983]: Without this change just by setting ReadInputAtNativeFramerate to true would set  InputVideoSync to "-1". This would trigger getvideosyncoption() to also enbale the argument "-fps_mode auto". This is then applied to the input url, but this argument is actually an output option. So without this change ffmpeg actually errors out and produces:

```
Option fps_mode (set framerate mode for matching video streams; overrides vsync) cannot be applied to input url http://192.168.1.1:8081/hls/stream.m3u8 -- you are trying to apply an input option to an output file or vice versa. Move this option before the file it belongs to.
```

The option InputAudioSync also seems unnecessary because an incoming livestream is already synced. I think this existing code is meant for files like the mentioned "wtv" container and not for livestreams.

So I had to find away that this code does not apply to livestreams and the only added argument to the command line flags is `-re` when this is set in the M3U Tuner and `!state.IsSegmentedLiveStream` was perfect for that.

**Review by Shadowghost — APPROVED** [review]

**Review by crobibero — APPROVED** [review]
