### PR TITLE
Extract and cache all media attachments in bulk

### LINKED ISSUE #3215: Too many ffmpeg processes spawned
**Describe the bug**

I noticed that when i play a H265 video and it needs to be transcoded to play sometimes it spawns alot ffmpeg processes which can eat all system memory and make my system crawl because of the swapping. Strangely enough it does not happen every time but in 1 of 10-15 times such video is played this happens. 

My System Specs are: HP EliteDesk 800G1 USDT, Intel i5-4570S, 8GB RAM (around 3GB is free at all times), 500GB HDD

This system has various things installed on it - nginx, php, mysql, postgre, rtorrent, flood, sonarr, jackett, jellyfin, samba and so on. It is moderately busy but CPU rare climbs to more than 1.5 load average even when transcode is active.

It transcodes with VAAPI, but this cpu can only transcode H264 and when H265 video is played it is transcoded by the CPU. I suppose it starts to extract all this fonts, subs and so on in paralel and spawns alot ffmpeg processes to do to. Maybe it is good idea to limit the number of processes in order to prevent swapping on configurations with lower amount of RAM.

**System (please complete the following information):**
 - OS: Debian Buster 10
 - Virtualization: none
 - Clients: Browser
 - Browser: Chromium 83.0.4103.61 (Official Build) Arch Linux (64-bit)
 - Jellyfin Version: 10.5.5
 - Playback: Transcode 
 - Installed Fanart, Anime
 - Reverse Proxy: nginx
 - Base URL: none
 - Networking: Host
 - Storage: local

**To Reproduce**
1. Start to play a new movie from the begining. It does not happen if you continue to play one you started previously.
2. Look at the console of the linux box
3. Sometimes alot of ffmpeg processes are spawned - more than 10-15. Every one of them eats like 100 - 200 MB RAM.
4. See how all memory is eaten and machine starts to swap, load average gets to more than 20 on a 4 core system.
5. After like 30-60 seconds things go back to normal. Maybe this processes finish their task and release the memory.

**Expected behavior**

Number of ffmpeg processes should be limited.

**Logs**

[Log_jellyfin.txt](https://github.com/jellyfin/jellyfin/files/4711539/Log_jellyfin.txt)
[Log_transcode.txt](https://github.com/jellyfin/jellyfin/files/4711540/Log_transcode.txt)

**Screenshots**

The below screenshot i managed to get, barely avoided the heavy swapping. In this case it went away after 5 seconds. But sometimes i get not so lucky and the system is unresponsive for alot longer.

image

**Additional context**

None.

### PR DESCRIPTION
**Pull request by alltilla**
**Changes**

Similar to #10884

This PR implements the bulk extraction and caching of media attachments.

Jellyfin clients need fonts for subtitles, and each font is a separate attachment, which causes a lot of re-reads of the file. Certain contents, like anime in a lot of cases, contain 10-80 different attachments. Spawning 80 ffmpeg processes at the same time on the same file might cause swapping on slower HDDs and can bring disk subsystem to a crawl. (For more info, see #3215)

This change helps a lot in this scenario.

#### jellyfin logs

<details>

```
[12:36:11] [INF] [24] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: /usr/lib/jellyfin-ffmpeg/ffmpeg  -dump_attachment:3 "/config/data/attachments/4/4620c369-78e0-ad26-163f-e41bb399167d" -dump_attachment:4 "/config/data/attachments/1/161a24bc-5176-a53a-4543-230b41c5f58d" -dump_attachment:5 "/config/data/ttachments/a/a0b00a6f-f488-fb0a-19da-51f3ee01a846" -dump_attachment:6 "/config/data/attachments/1/114d4a64-8663-2adc-c85b-32723d01d4a2" -dump_attachment:7 "/config/data/attachments/c/c12ff5af-f94e-bb89-e83f-536d905c14dd" -dump_attachment:8 "/config/data/attachments/7/785cd524-6664-0342-cd64-66079d42db56" -dump_attachment:9 "/config/data/attachments/3/3d7be44d-e716-9d54-9ff0-d0719236db3b" -dump_attachment:10 "/config/data/attachments/9/9c1a5ee2-11c8-e77f-99fd-62f67ae56369" -dump_attachment:11 "/config/data/attachments/e/e635eb28-d5d1-fe67-2e58-92e3584daaac" -dump_attachment:12 "/config/data/attachments/0/048c0e62-b960-de8a-26c9-9009060f5648" -dump_attachment:13 "/config/data/attachments/2/2f030b3c-8923-7232-90fd-22ef264359ed" -dump_attachment:14 "/config/data/attachments/8/8691c8be-7c29-bd2e-e10c-eb3e3e772a87" -i "/data/Shingeki no Kyojin - The Final Season - Part 01 - 01 720p.mkv" -t 0 -f null null
[12:36:11] [INF] [6] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: ffmpeg media attachment extraction completed for /data/Shingeki no Kyojin - The Final Season - Part 01 - 01 720p.mkv to /config/data/attachments/4/4620c369-78e0-ad26-163f-e41bb399167d
[12:36:11] [INF] [6] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: ffmpeg media attachment extraction completed for /data/Shingeki no Kyojin - The Final Season - Part 01 - 01 720p.mkv to /config/data/attachments/1/161a24bc-5176-a53a-4543-230b41c5f58d
[12:36:11] [INF] [6] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: ffmpeg media attachment extraction completed for /data/Shingeki no Kyojin - The Final Season - Part 01 - 01 720p.mkv to /config/data/attachments/a/a0b00a6f-f488-fb0a-19da-51f3ee01a846
[12:36:11] [INF] [6] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: ffmpeg media attachment extraction completed for /data/Shingeki no Kyojin - The Final Season - Part 01 - 01 720p.mkv to /config/data/attachments/1/114d4a64-8663-2adc-c85b-32723d01d4a2
[12:36:11] [INF] [6] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: ffmpeg media attachment extraction completed for /data/Shingeki no Kyojin - The Final Season - Part 01 - 01 720p.mkv to /config/data/attachments/c/c12ff5af-f94e-bb89-e83f-536d905c14dd
[12:36:11] [INF] [6] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: ffmpeg media attachment extraction completed for /data/Shingeki no Kyojin - The Final Season - Part 01 - 01 720p.mkv to /config/data/attachments/7/785cd524-6664-0342-cd64-66079d42db56
[12:36:11] [INF] [6] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: ffmpeg media attachment extraction completed for /data/Shingeki no Kyojin - The Final Season - Part 01 - 01 720p.mkv to /config/data/attachments/3/3d7be44d-e716-9d54-9ff0-d0719236db3b
[12:36:11] [INF] [6] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: ffmpeg media attachment extraction completed for /data/Shingeki no Kyojin - The Final Season - Part 01 - 01 720p.mkv to /config/data/attachments/9/9c1a5ee2-11c8-e77f-99fd-62f67ae56369
[12:36:11] [INF] [6] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: ffmpeg media attachment extraction completed for /data/Shingeki no Kyojin - The Final Season - Part 01 - 01 720p.mkv to /config/data/attachments/e/e635eb28-d5d1-fe67-2e58-92e3584daaac
[12:36:11] [INF] [6] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: ffmpeg media attachment extraction completed for /data/Shingeki no Kyojin - The Final Season - Part 01 - 01 720p.mkv to /config/data/attachments/0/048c0e62-b960-de8a-26c9-9009060f5648
[12:36:11] [INF] [6] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: ffmpeg media attachment extraction completed for /data/Shingeki no Kyojin - The Final Season - Part 01 - 01 720p.mkv to /config/data/attachments/2/2f030b3c-8923-7232-90fd-22ef264359ed
[12:36:11] [INF] [6] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: ffmpeg media attachment extraction completed for /data/Shingeki no Kyojin - The Final Season - Part 01 - 01 720p.mkv to /config/data/attachments/8/8691c8be-7c29-bd2e-e10c-eb3e3e772a87
```

</details>

#### ffmpeg logs

<details>

```
ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --
enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Input #0, matroska,webm, from '/data/Shingeki no Kyojin - The Final Season - Part 01 - 01 720p.mkv':
  Metadata:
    encoder         : no_variable_data
    creation_time   : 1970-01-01T00:00:00.000000Z
  Duration: 00:24:02.54, start: 0.000000, bitrate: 4137 kb/s
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS-eng         : 3996648
      DURATION-eng    : 00:23:55.019000000
      NUMBER_OF_FRAMES-eng: 34406
      NUMBER_OF_BYTES-eng: 716908262
      _STATISTICS_WRITING_APP-eng: no_variable_data
      _STATISTICS_WRITING_DATE_UTC-eng: 1970-01-01 00:00:00
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(jpn): Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      BPS-eng         : 128000
      DURATION-eng    : 00:23:55.086000000
      NUMBER_OF_FRAMES-eng: 61804
      NUMBER_OF_BYTES-eng: 22961378
      _STATISTICS_WRITING_APP-eng: no_variable_data
      _STATISTICS_WRITING_DATE_UTC-eng: 1970-01-01 00:00:00
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: ass (default)
    Metadata:
      title           : English subs
      BPS-eng         : 78
      DURATION-eng    : 00:23:53.890000000
      NUMBER_OF_FRAMES-eng: 238
      NUMBER_OF_BYTES-eng: 14087
      _STATISTICS_WRITING_APP-eng: no_variable_data
      _STATISTICS_WRITING_DATE_UTC-eng: 1970-01-01 00:00:00
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3: Attachment: ttf
    Metadata:
      filename        : Roboto-Medium.ttf
      mimetype        : application/x-truetype-font
  Stream #0:4: Attachment: ttf
    Metadata:
      filename        : Roboto-MediumItalic.ttf
      mimetype        : application/x-truetype-font
  Stream #0:5: Attachment: ttf
    Metadata:
      filename        : arial.ttf
      mimetype        : application/x-truetype-font
  Stream #0:6: Attachment: ttf
    Metadata:
      filename        : arialbd.ttf
      mimetype        : application/x-truetype-font
  Stream #0:7: Attachment: ttf
    Metadata:
      filename        : comic.ttf
      mimetype        : application/x-truetype-font
  Stream #0:8: Attachment: ttf
    Metadata:
      filename        : comicbd.ttf
      mimetype        : application/x-truetype-font
  Stream #0:9: Attachment: ttf
    Metadata:
      filename        : times.ttf
      mimetype        : application/x-truetype-font
  Stream #0:10: Attachment: ttf
    Metadata:
      filename        : timesbd.ttf
      mimetype        : application/x-truetype-font
  Stream #0:11: Attachment: ttf
    Metadata:
      filename        : trebuc.ttf
      mimetype        : application/x-truetype-font
  Stream #0:12: Attachment: ttf
    Metadata:
      filename        : trebucbd.ttf
      mimetype        : application/x-truetype-font
  Stream #0:13: Attachment: ttf
    Metadata:
      filename        : verdana.ttf
      mimetype        : application/x-truetype-font
  Stream #0:14: Attachment: ttf
    Metadata:
      filename        : verdanab.ttf
      mimetype        : application/x-truetype-font
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> wrapped_avframe (native))
  Stream #0:1 -> #0:1 (aac (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, null, to 'null':
  Metadata:
    encoder         : Lavf60.3.100
  Stream #0:0: Video: wrapped_avframe, yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 200 kb/s, 23.98 fps, 23.98 tbn (default)
    Metadata:
      BPS-eng         : 3996648
      DURATION-eng    : 00:23:55.019000000
      NUMBER_OF_FRAMES-eng: 34406
      NUMBER_OF_BYTES-eng: 716908262
      _STATISTICS_WRITING_APP-eng: no_variable_data
      _STATISTICS_WRITING_DATE_UTC-eng: 1970-01-01 00:00:00
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      encoder         : Lavc60.3.100 wrapped_avframe
  Stream #0:1(jpn): Audio: pcm_s16le, 44100 Hz, stereo, s16, 1411 kb/s (default)
    Metadata:
      BPS-eng         : 128000
      DURATION-eng    : 00:23:55.086000000
      NUMBER_OF_FRAMES-eng: 61804
      NUMBER_OF_BYTES-eng: 22961378
      _STATISTICS_WRITING_APP-eng: no_variable_data
      _STATISTICS_WRITING_DATE_UTC-eng: 1970-01-01 00:00:00
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      encoder         : Lavc60.3.100 pcm_s16le
frame=    0 fps=0.0 q=0.0 Lsize=N/A time=-577014:32:22.77 bitrate=N/A speed=N/A    /s speed=N/A
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)
```

</details>

#### Extracted files

<details>

```
find config/data/attachments -type f | xargs ls -algh
-rw-r--r-- 1 root 202K febr  18 13:36 config/data/attachments/0/048c0e62-b960-de8a-26c9-9009060f5648
-rw-r--r-- 1 root 835K febr  18 13:36 config/data/attachments/1/114d4a64-8663-2adc-c85b-32723d01d4a2
-rw-r--r-- 1 root 370K febr  18 13:36 config/data/attachments/1/161a24bc-5176-a53a-4543-230b41c5f58d
-rw-r--r-- 1 root 235K febr  18 13:36 config/data/attachments/2/2f030b3c-8923-7232-90fd-22ef264359ed
-rw-r--r-- 1 root 953K febr  18 13:36 config/data/attachments/3/3d7be44d-e716-9d54-9ff0-d0719236db3b
-rw-r--r-- 1 root 344K febr  18 13:36 config/data/attachments/4/4620c369-78e0-ad26-163f-e41bb399167d
-rw-r--r-- 1 root 220K febr  18 13:36 config/data/attachments/7/785cd524-6664-0342-cd64-66079d42db56
-rw-r--r-- 1 root 204K febr  18 13:36 config/data/attachments/8/8691c8be-7c29-bd2e-e10c-eb3e3e772a87
-rw-r--r-- 1 root 958K febr  18 13:36 config/data/attachments/9/9c1a5ee2-11c8-e77f-99fd-62f67ae56369
-rw-r--r-- 1 root 872K febr  18 13:36 config/data/attachments/a/a0b00a6f-f488-fb0a-19da-51f3ee01a846
-rw-r--r-- 1 root 235K febr  18 13:36 config/data/attachments/c/c12ff5af-f94e-bb89-e83f-536d905c14dd
-rw-r--r-- 1 root 214K febr  18 13:36 config/data/attachments/e/e635eb28-d5d1-fe67-2e58-92e3584daaac
```

</details>

**Issues**

Fixes #3215

### CODE REVIEW

File: MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs [hunk 1]
```diff
@@ -230,13 +231,166 @@ public async Task<(MediaAttachment Attachment, Stream Stream)> GetAttachment(Bas
...
+            var locks = new List<AsyncKeyedLockReleaser<string>>();
+            var extractableAttachmentIds = new List<int>();
+
+            try
+            {
+                foreach (var attachment in mediaSource.MediaAttachments)
+                {
+                    var outputPath = GetAttachmentCachePath(mediaPath, mediaSource, attachment.Index);
+
+                    var @lock = _semaphoreLocks.GetOrAdd(outputPath);
```
Comment (JPVenson) [inline MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs:258]: Please rename this variable into something more descriptive

File: MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs [hunk 2]
```diff
@@ -230,13 +231,166 @@ public async Task<(MediaAttachment Attachment, Stream Stream)> GetAttachment(Bas
...
+
+                foreach (var outputPath in outputPaths)
+                {
+                    try
+                    {
+                        _logger.LogWarning("Deleting extracted media attachment due to failure: {Path}", outputPath);
+                        _fileSystem.DeleteFile(outputPath);
+                    }
+                    catch (FileNotFoundException)
+                    {
```
Comment (JPVenson) [inline MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs:364]: Dont drop exceptions without logging and explanation

File: MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs [hunk 3]
```diff
@@ -230,13 +231,166 @@ public async Task<(MediaAttachment Attachment, Stream Stream)> GetAttachment(Bas
...
+            foreach (var attachmentId in extractableAttachmentIds)
+            {
+                var outputPath = GetAttachmentCachePath(mediaPath, mediaSource, attachmentId);
+
+                Directory.CreateDirectory(Path.GetDirectoryName(outputPath) ?? throw new FileNotFoundException($"Calculated path ({outputPath}) is not valid."));
+
+                outputPaths.Add(outputPath);
+                processArgs += string.Format(
+                    CultureInfo.InvariantCulture,
+                    " -dump_attachment:{0} \"{1}\"",
```
Comment (nyanmisaka) [inline MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs:308]: Maybe add `:t`, like `-dump_attachment:t:{0}`? As per https://ffmpeg.org/ffmpeg-all.html#toc-Main-options

> stream_type[:additional_stream_specifier]
> stream_type is one of following: ’v’ or ’V’ for video, ’a’ for audio, ’s’ for subtitle, ’d’ for data, and ’t’ for attachments. ’v’ matches all video streams, ’V’ only matches video streams which are not attached pictures, video thumbnails or cover arts. If additional_stream_specifier is used, then it matches streams which both have this type and match the additional_stream_specifier. Otherwise, it matches all streams of the specified type.

**Review by nyanmisaka — APPROVED** [review]
LGTM, only from the perspective of using the FFmpeg CLI.

File: MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs (hunk 1 above)
Comment (alltilla) [reply MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs]: Thanks, fixed.

File: MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs (hunk 2 above)
Comment (alltilla) [reply MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs:364]: I don't think we should notify the user about this case. `ffmpeg` failed, so it is normal that one or more expected output files do not exist. Added a comment to the code stating this, but if you would like me to log a warning anyways, sure, I'll do that, just let me know what the message should be.

**Review by Shadowghost — APPROVED** [review]

**Review by crobibero — APPROVED** [review]
