### PR TITLE
Determine tv image type by extension if content-type is unavailable

### LINKED ISSUE #13075: LiveTV icons throws an excpetion when image Content-Type is not set
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Images from Zap2It do not directly expose the Content-Type header in their response, which causes the below exception seen in the logs. 

### Reproduction steps

Import xml guide data from Zap2It.

### What is the current _bug_ behavior?

Sstem.Net.Http.HttpRequestException: Invalid image received: contentType not set.
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, Boolean removeOnFailure)
   at Jellyfin.LiveTv.Guide.GuideManager.<>c__DisplayClass21_0.<<PrecacheImages>b__2>d.MoveNext()

### What is the expected _correct_ behavior?

Determine image type by extension if Content-Type is not available.

### Jellyfin Server version

Master

### Specify commit id

_No response_

### Specify unstable release number

_No response_

### Specify version number

_No response_

### Specify the build version

Current

### Environment

```markdown
- OS: Windows
- Virtualization: NO
- FFmpeg Version: 7.0
- Plugins: None
- Reverse Proxy: No
```

### Jellyfin logs

```shell
[2024-11-19 13:41:09.889 -05:00] [WRN] [39] Jellyfin.LiveTv.Guide.GuideManager: Unable to precache "https://zap2it.tmsimg.com/assets/p8679870_b_v9_ad.jpg"
System.Net.Http.HttpRequestException: Invalid image received: contentType not set.
   at MediaBrowser.Providers.Manager.ProviderManager.SaveImage(BaseItem item, String url, ImageType type, Nullable`1 imageIndex, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.ConvertImageToLocal(BaseItem item, ItemImageInfo image, Int32 imageIndex, Boolean removeOnFailure)
   at Jellyfin.LiveTv.Guide.GuideManager.<>c__DisplayClass21_0.<<PrecacheImages>b__2>d.MoveNext()
[2024-11-19 13:41:10.508 -05:00] [INF] [69] Jellyfin.LiveTv.Listings.XmlTvListingsProvider: xmltv path: "C:\Programs\zapit\xmltv.xml"
```

### FFmpeg logs

```shell

```

### Client / Browser logs

_No response_

### Relevant screenshots or videos

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by theguymadmax**
**Changes**

Added logic to determine the TV image type based on the file extension if the Content-Type header is null or empty.

**Issues**
 Fixes #13075 #11703 #11824

### CODE REVIEW

File: MediaBrowser.Providers/Manager/ProviderManager.cs [hunk 1]
```diff
@@ -200,11 +200,25 @@ await SaveImage(
                 // TODO: Isolate this hack into the tvh plugin
                 if (string.IsNullOrEmpty(contentType))
                 {
+                    // First, check for imagecache special case
                     if (url.Contains("/imagecache/", StringComparison.OrdinalIgnoreCase))
                     {
-                        contentType = MediaTypeNames.Image.Png;
+                        contentType = "image/png";
```
Comment (crobibero) [inline MediaBrowser.Providers/Manager/ProviderManager.cs:206]: Why change from the .net provided constant?

Comment (theguymadmax) [reply MediaBrowser.Providers/Manager/ProviderManager.cs:206]: Since .NET doesn't offer a constant for the webp MIME type, I chose to use raw strings for consistency. I'll go ahead and replace them with the .NET constants.

**Review by JPVenson — APPROVED** [review]

File: MediaBrowser.Providers/Manager/ProviderManager.cs [hunk 2]
```diff
@@ -200,11 +200,25 @@ await SaveImage(
...
+                    // Deduce content type from file extension
+                    var fileExtension = Path.GetExtension(url)?.ToLowerInvariant();
+                    contentType = fileExtension switch
+                    {
+                        ".jpg" or ".jpeg" => MediaTypeNames.Image.Jpeg,
+                        ".png" => MediaTypeNames.Image.Png,
+                        ".gif" => MediaTypeNames.Image.Gif,
+                        ".webp" => "image/webp",
+                        _ => null
+                    };
```
Comment (Bond-009) [inline MediaBrowser.Providers/Manager/ProviderManager.cs:219]:
```suggestion
                    var fileExtension = MimeTypes.GetMimeType(url, null);
```

**Review by Bond-009 — CHANGES_REQUESTED** [review]

File: MediaBrowser.Providers/Manager/ProviderManager.cs [hunk 3]
```diff
@@ -200,11 +200,18 @@ await SaveImage(
                 // TODO: Isolate this hack into the tvh plugin
                 if (string.IsNullOrEmpty(contentType))
                 {
+                    // First, check for imagecache special case
                     if (url.Contains("/imagecache/", StringComparison.OrdinalIgnoreCase))
                     {
                         contentType = MediaTypeNames.Image.Png;
+                        return;
```
Comment (Bond-009) [inline MediaBrowser.Providers/Manager/ProviderManager.cs:207]: This isn't right

File: MediaBrowser.Providers/Manager/ProviderManager.cs [hunk 4]
```diff
@@ -200,11 +200,18 @@ await SaveImage(
...
                     }
-                    else
+
+                    // Deduce content type from file extension
+                    var fileExtension = MimeTypes.GetMimeType(new Uri(url).GetLeftPart(UriPartial.Path));
+                    contentType = fileExtension;
```
Comment (Bond-009) [inline MediaBrowser.Providers/Manager/ProviderManager.cs:212]: Why even have this extra var?

**Review by Bond-009 — CHANGES_REQUESTED** [review]

**Review by Bond-009 — APPROVED** [review]
Some useless comments and the TODO should be moved, but I'm not going to block it based on those things.
