### PR TITLE
Skip allowed tags check for parents of an item

### LINKED ISSUE #11869: [Issue]: Allow items with tags breaks media access and playback when movies placed in subfolders
### Please describe your bug

Thank you for your great application! I am new user to Jellyfin, just recently switched from Emby after several years of usage. So far I am happy but I encountered an issue that I want to report.

I am setting up access for my child and I want to control through Parental Control "Allow items with tags" option which movies they can access and watch. I want to use whitelist approach to gradually allow more and more movies while having strict control on which movies I allow.

First thing I do is add a custom tag to a movie:

Screenshot 2024-05-28 at 23 28 41

After that, I go to their user and configure the Parental Control, Allow items with tags and set that same tag value there:

Screenshot 2024-05-28 at 23 48 04

When I log in to their account I correctly see the library and only this movie in that library that has the configured tag:

Screenshot 2024-05-28 at 23 29 29

However, when I click on that movie the page never loads with the movie info:

Screenshot 2024-05-28 at 23 30 14

The same errors in the console are shown if I try to play the movie directly from the library movie list or try to change the Watched status.

If I go back and clear the Allow items with tags settings, the movie page loads as expected, and I can play the video without any further issues:

Screenshot 2024-05-28 at 23 35 42

I noticed this initially on 10.9.2 but since then I upgraded to 10.9.3 and still the same behaviour. This deployment is an Debian LXC container fully updated running on Proxmox host. The same issue manifests both in Chrome as well as in Android Jellyfin app. Other than this, all clients and server work perfectly fine.

```
root@jellyfin:~# uname -a
Linux jellyfin 6.8.4-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.4-2 (2024-04-10T17:36Z) x86_64 GNU/Linux
root@jellyfin:~# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@jellyfin:~# jellyfin --version
Jellyfin.Server 10.9.3.0
```

Based on the behaviour it seems related to how tags are being handled on the server side. I saw in existing issues #11407 but that seems different than what I am experiencing.

### Reproduction Steps

See description above.

### Jellyfin Version

10.9.0

### if other:

_No response_

### Environment

```markdown
- OS: Debian GNU/Linux 12 (bookworm)
- Linux Kernel: 6.8.4-2-pve
- Virtualization: Proxmox
- Clients: Android Jellyfin 
- Browser: Chrome 125.0.6422.77
- FFmpeg Version: ffmpeg version 6.0.1-Jellyfin
- Playback Method: N/A
- Hardware Acceleration: no
- GPU Model: N/A
- Plugins: none
- Reverse Proxy: no
- Base URL: N/A
- Networking: N/A
- Storage: N/A
```

### Jellyfin logs

```shell
No relevant logs found.
```

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by elfalem**
The current logic is described in [this comment](https://github.com/jellyfin/jellyfin/issues/11869#issuecomment-2332871326). In short, the allowed tags check traverses the hierarchy of an item and checks all parents. This is usually desirable for blocked tags since an item shouldn't be visible if it or any of its parents are blocked. However, similar logic makes it cumbersome/impractical to use allowed tags because they would have to be applied to all parents of an item in addition to the item.

**Changes**
The changes skip checking allowed tags on parents of an item. The item itself is still checked. No changes are made to blocked tags or parental ratings logic.

**Issues**
Fixes #11869

### CODE REVIEW

File: MediaBrowser.Controller/Entities/BaseItem.cs [hunk 1]
```diff
@@ -1299,7 +1299,7 @@ protected bool IsVisibleStandaloneInternal(User user, bool checkFolders)
                 return false;
             }
 
-            if (GetParents().Any(i => !i.IsVisible(user)))
+            if (GetParents().Any(i => !i.IsVisible(user, true)))
```
Comment (elfalem) [inline MediaBrowser.Controller/Entities/BaseItem.cs:1302]: This is the primary change of the PR.

**Review by Shadowghost — APPROVED** [review]

**Review by JPVenson — APPROVED** [review]

**Review by JPVenson — CHANGES_REQUESTED** [review]
new features may not target the current release branch

**Comment by elfalem** [comment]
> new features may not target the current release branch

@JPVenson I'm not sure I understand. This is a bug fix for #11869, not a new feature.

**Comment by elfalem** [comment]
@JPVenson if you could please take a look at my message above. I'm not sure there is a change to be made.

**Review by JPVenson — APPROVED** [review]

**Review by crobibero — APPROVED** [review]
