### PR TITLE
Fix season handling

### LINKED ISSUE #11575: [Issue]: season no longer created during initial scan
### Please describe your bug

10.8.x and even the first few unstable builds of 10.9 would correct create the 'Season 1' when scanning, this no longer seems to be the case in 10.9.0 stable.

It might be related to https://github.com/jellyfin/jellyfin/pull/11472, as doing a replace all on the show seems to 'fix' the issue.

It's probably related to using nfo's to help with my anime shows as I follow the anidb naming (so no S#E#) but I provide an tvshow.nfo and episode.nfo (which set the correct season and episode)

**I'm OK with this being closed immediately as not supported, but this did work fine before without needing to do a 2nd replace all metadata. So I would consider this a regression. The NFO's used to be enough to get all the info jellyfin required**

Log attached of the scan that picks it up and 2nd scan with refresh that actually creates the season 1 entry.

### Reproduction Steps

1. add a new show to the file system
2. generate `tvshow.nfo` and `<episode filename>.nfo`
3. Dashboard -> Libraries -> <my library> -> ... -> Scan library, select "Scan for new and updates files"

The show gets added, it even finds the provided anidb and anilist IDs from tvshow.nfo and fetches metadata.
I can even play episode 1 from the show view (and after than the next unplayed ...) But I do not have an entry under season.

File layout
```
sjorge@mars:/archive/anime/G/Gasaraki$ cd /archive/anime/G/Gasaraki
sjorge@mars:/archive/anime/G/Gasaraki$ ls
Gasaraki - 01 - On the Ancient Stage of Stone (4A945BB5).mkv  Gasaraki - 09 - Storehouse (E7A44290).nfo                     Gasaraki - 18 - Rear Window (D5640415).mkv
Gasaraki - 01 - On the Ancient Stage of Stone (4A945BB5).nfo  Gasaraki - 10 - Kugai (AA4EE962).mkv                          Gasaraki - 18 - Rear Window (D5640415).nfo
Gasaraki - 02 - Opening Movements (0CA0EDF5).mkv              Gasaraki - 10 - Kugai (AA4EE962).nfo                          Gasaraki - 19 - Wails (60B8E17C).mkv
Gasaraki - 02 - Opening Movements (0CA0EDF5).nfo              Gasaraki - 11 - Ties (6EDE0DBE).mkv                           Gasaraki - 19 - Wails (60B8E17C).nfo
Gasaraki - 03 - Tantric Circle (378CA4A2).mkv                 Gasaraki - 11 - Ties (6EDE0DBE).nfo                           Gasaraki - 20 - Upheaval (FDFBAC98).mkv
Gasaraki - 03 - Tantric Circle (378CA4A2).nfo                 Gasaraki - 12 - Unravel (AA085BC6).mkv                        Gasaraki - 20 - Upheaval (FDFBAC98).nfo
Gasaraki - 04 - Mirage (37E27AB9).mkv                         Gasaraki - 12 - Unravel (AA085BC6).nfo                        Gasaraki - 21 - Run (BF42ED11).mkv
Gasaraki - 04 - Mirage (37E27AB9).nfo                         Gasaraki - 13 - Disembark (E5359B52).mkv                      Gasaraki - 21 - Run (BF42ED11).nfo
Gasaraki - 05 - The Touching (682971F5).mkv                   Gasaraki - 13 - Disembark (E5359B52).nfo                      Gasaraki - 22 - Personification (1DF5552D).mkv
Gasaraki - 05 - The Touching (682971F5).nfo                   Gasaraki - 14 - Companions (A110758F).mkv                     Gasaraki - 22 - Personification (1DF5552D).nfo
Gasaraki - 06 - The Puppet (219620D4).mkv                     Gasaraki - 14 - Companions (A110758F).nfo                     Gasaraki - 23 - Eternal (8880AA1F).mkv
Gasaraki - 06 - The Puppet (219620D4).nfo                     Gasaraki - 15 - The Threshold (1C91221F).mkv                  Gasaraki - 23 - Eternal (8880AA1F).nfo
Gasaraki - 07 - Return (F4FF572B).mkv                         Gasaraki - 15 - The Threshold (1C91221F).nfo                  Gasaraki - 24 - Punctuation (8E87E40E).mkv
Gasaraki - 07 - Return (F4FF572B).nfo                         Gasaraki - 16 - Karma (036C6A72).mkv                          Gasaraki - 24 - Punctuation (8E87E40E).nfo
Gasaraki - 08 - Harsh Worlds (E570F0D2).mkv                   Gasaraki - 16 - Karma (036C6A72).nfo                          Gasaraki - 25 - Gasara (A0E62DA4).mkv
Gasaraki - 08 - Harsh Worlds (E570F0D2).nfo                   Gasaraki - 17 - Chaos (CCA83905).mkv                          Gasaraki - 25 - Gasara (A0E62DA4).nfo
Gasaraki - 09 - Storehouse (E7A44290).mkv                     Gasaraki - 17 - Chaos (CCA83905).nfo                          tvshow.nfo
```

#### tvshow.nfo

```xml
<?xml version="1.0" encoding="utf-8"?>
<tvshow>
  <title>Gasaraki</title>
  <originaltitle>ガサラキ</originaltitle>
  <uniqueid type="AniDB" default="true">240</uniqueid>
  <uniqueid type="AniList" default="false">782</uniqueid>
  <uniqueid type="Tmdb" default="false">34782</uniqueid>
  <premiered>1998-10-04</premiered>
</tvshow>
```

#### Gasaraki - 01 - On the Ancient Stage of Stone (4A945BB5).nfo

```xml
<?xml version="1.0" encoding="utf-8"?>
<episodedetails>
  <title>On the Ancient Stage of Stone</title>
  <uniqueid type="AniDB" default="true">2800</uniqueid>
  <originaltitle>石舞台</originaltitle>
  <premiered>1998-10-04</premiered>
  <season>1</season>
  <episode>1</episode>
</episodedetails>
```

### Jellyfin Version

10.9.0

### if other:

_No response_

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- Linux Kernel: GNU/Linux 6.5.0-26-generic x86_64 (for ARC support)
- Virtualization: BHYVE
- Clients: Browser
- Browser: Firefox 126.0b8 (64-bit)
- FFmpeg Version: jellyfin-ffmpeg6 - 6.0.1-6-jammy
- Playback Method: Transcode (Ends up playing without subs transcoded to AV1)
- Hardware Acceleration: QSV (also tried without, no difference)
- GPU Model: Intel Arc A310 Low Profile 4GB (ASRock)
- Plugins: AniDB, AniList, AudioDB, Cover Art Archive, Fanart, MusicBrainz, OMDb, Session Cleaner, Studio Images, TMDb, TMDb Box Sets, Trakt, Webhook
- Reverse Proxy: apache
- Base URL: /jellyfin
- Networking: vnic
- Storage: local (config) + NFS (media)
```

### Jellyfin logs

```shell
May 12 20:43:04 fqdn jellyfin[270236]: [20:43:04] [INF] Timer elapsed - processing queued items
May 12 20:43:04 fqdn jellyfin[270236]: [20:43:04] [INF] No events... stopping queue timer
May 12 20:43:08 fqdn jellyfin[270236]: [20:43:08] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 closed
May 12 20:43:08 fqdn jellyfin[270236]: [20:43:08] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 request
May 12 20:43:11 fqdn jellyfin[270236]: [20:43:11] [INF] Creating Season Season Unknown entry for Gasaraki
May 12 20:43:11 fqdn jellyfin[270236]: [20:43:11] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 08 - Harsh Worlds (E570F0D2).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:11 fqdn jellyfin[277793]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:11 fqdn jellyfin[277793]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:11 fqdn jellyfin[270236]: [20:43:11] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 05 - The Touching (682971F5).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:12 fqdn jellyfin[277856]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:12 fqdn jellyfin[277856]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:12 fqdn jellyfin[270236]: [20:43:12] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 22 - Personification (1DF5552D).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:12 fqdn jellyfin[277918]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:12 fqdn jellyfin[277918]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:12 fqdn jellyfin[270236]: [20:43:12] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 23 - Eternal (8880AA1F).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:12 fqdn jellyfin[277980]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:12 fqdn jellyfin[277980]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:12 fqdn jellyfin[277980]: Unsupported codec with id 98304 for input stream 10
May 12 20:43:12 fqdn jellyfin[270236]: [20:43:12] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 06 - The Puppet (219620D4).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:12 fqdn jellyfin[278042]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:12 fqdn jellyfin[278042]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:13 fqdn jellyfin[270236]: [20:43:13] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 24 - Punctuation (8E87E40E).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:13 fqdn jellyfin[278104]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:13 fqdn jellyfin[278104]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:13 fqdn jellyfin[270236]: [20:43:13] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 25 - Gasara (A0E62DA4).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:13 fqdn jellyfin[278166]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:13 fqdn jellyfin[278166]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:14 fqdn jellyfin[270236]: [20:43:14] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 21 - Run (BF42ED11).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:14 fqdn jellyfin[278228]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:14 fqdn jellyfin[278228]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:14 fqdn jellyfin[270236]: [20:43:14] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 01 - On the Ancient Stage of Stone (4A945BB5).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:14 fqdn jellyfin[278290]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:14 fqdn jellyfin[278290]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:14 fqdn jellyfin[270236]: [20:43:14] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 07 - Return (F4FF572B).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:14 fqdn jellyfin[278352]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:14 fqdn jellyfin[278352]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:15 fqdn jellyfin[270236]: [20:43:15] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 14 - Companions (A110758F).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:15 fqdn jellyfin[278414]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:15 fqdn jellyfin[278414]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:15 fqdn jellyfin[270236]: [20:43:15] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 04 - Mirage (37E27AB9).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:15 fqdn jellyfin[278476]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:15 fqdn jellyfin[278476]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:15 fqdn jellyfin[270236]: [20:43:15] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 19 - Wails (60B8E17C).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:15 fqdn jellyfin[278538]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:15 fqdn jellyfin[278538]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:15 fqdn jellyfin[270236]: [20:43:15] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 10 - Kugai (AA4EE962).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:16 fqdn jellyfin[278600]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:16 fqdn jellyfin[278600]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:16 fqdn jellyfin[270236]: [20:43:16] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 16 - Karma (036C6A72).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:16 fqdn jellyfin[278662]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:16 fqdn jellyfin[278662]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:16 fqdn jellyfin[278662]: Unsupported codec with id 98304 for input stream 10
May 12 20:43:16 fqdn jellyfin[270236]: [20:43:16] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 15 - The Threshold (1C91221F).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:16 fqdn jellyfin[278724]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:16 fqdn jellyfin[278724]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:16 fqdn jellyfin[278724]: Unsupported codec with id 98304 for input stream 10
May 12 20:43:16 fqdn jellyfin[270236]: [20:43:16] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 03 - Tantric Circle (378CA4A2).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:16 fqdn jellyfin[278786]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:16 fqdn jellyfin[278786]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:17 fqdn jellyfin[270236]: [20:43:17] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 09 - Storehouse (E7A44290).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:17 fqdn jellyfin[278848]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:17 fqdn jellyfin[278848]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:17 fqdn jellyfin[270236]: [20:43:17] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 11 - Ties (6EDE0DBE).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:17 fqdn jellyfin[278910]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:17 fqdn jellyfin[278910]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:18 fqdn jellyfin[270236]: [20:43:18] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 18 - Rear Window (D5640415).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:18 fqdn jellyfin[278972]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:18 fqdn jellyfin[278972]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:18 fqdn jellyfin[270236]: [20:43:18] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 20 - Upheaval (FDFBAC98).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:18 fqdn jellyfin[279034]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:18 fqdn jellyfin[279034]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:18 fqdn jellyfin[270236]: [20:43:18] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 02 - Opening Movements (0CA0EDF5).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:18 fqdn jellyfin[279096]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:18 fqdn jellyfin[279096]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:19 fqdn jellyfin[270236]: [20:43:19] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 12 - Unravel (AA085BC6).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:19 fqdn jellyfin[279158]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:19 fqdn jellyfin[279158]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:19 fqdn jellyfin[270236]: [20:43:19] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 13 - Disembark (E5359B52).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:19 fqdn jellyfin[279220]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:19 fqdn jellyfin[279220]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:19 fqdn jellyfin[270236]: [20:43:19] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 17 - Chaos (CCA83905).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:43:19 fqdn jellyfin[279282]: Unsupported codec with id 98304 for input stream 8
May 12 20:43:19 fqdn jellyfin[279282]: Unsupported codec with id 98304 for input stream 9
May 12 20:43:19 fqdn jellyfin[270236]: [20:43:19] [INF] Removing virtual season null in series Gasaraki
May 12 20:43:19 fqdn jellyfin[270236]: [20:43:19] [INF] Removing item, Type: Season, Name: Season Unknown, Path: , Id: a9a97055-15c6-0c0c-e656-32681d15d1c6
May 12 20:43:19 fqdn jellyfin[270236]: [20:43:19] [INF] Creating Season Season 1 entry for Gasaraki
May 12 20:43:29 fqdn jellyfin[270236]: [20:43:29] [INF] Timer elapsed - processing queued items
May 12 20:43:29 fqdn jellyfin[270236]: [20:43:29] [INF] No events... stopping queue timer
May 12 20:43:54 fqdn jellyfin[270236]: [20:43:54] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 closed
May 12 20:43:54 fqdn jellyfin[270236]: [20:43:54] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 request
May 12 20:44:04 fqdn jellyfin[270236]: [20:44:04] [INF] Removing virtual season 1 in series Gasaraki
May 12 20:44:04 fqdn jellyfin[270236]: [20:44:04] [INF] Removing item, Type: Season, Name: Season 1, Path: , Id: 15b6e36b-b841-b8c8-c196-c2038a8fc542
May 12 20:44:04 fqdn jellyfin[270236]: [20:44:04] [INF] Creating Season Season 1 entry for Gasaraki
May 12 20:44:04 fqdn jellyfin[270236]: [20:44:04] [INF] Removing virtual season 1 in series Gasaraki
May 12 20:44:04 fqdn jellyfin[270236]: [20:44:04] [INF] Removing item, Type: Season, Name: Season 1, Path: , Id: 15b6e36b-b841-b8c8-c196-c2038a8fc542
May 12 20:44:04 fqdn jellyfin[270236]: [20:44:04] [INF] Creating Season Season 1 entry for Gasaraki
May 12 20:44:04 fqdn jellyfin[270236]: [20:44:04] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 08 - Harsh Worlds (E570F0D2).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:04 fqdn jellyfin[279383]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:04 fqdn jellyfin[279383]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:04 fqdn jellyfin[270236]: [20:44:04] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 05 - The Touching (682971F5).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:04 fqdn jellyfin[279395]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:04 fqdn jellyfin[279395]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:04 fqdn jellyfin[270236]: [20:44:04] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 22 - Personification (1DF5552D).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:04 fqdn jellyfin[279405]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:04 fqdn jellyfin[279405]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:04 fqdn jellyfin[270236]: [20:44:04] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 23 - Eternal (8880AA1F).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:04 fqdn jellyfin[279415]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:04 fqdn jellyfin[279415]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:04 fqdn jellyfin[279415]: Unsupported codec with id 98304 for input stream 10
May 12 20:44:04 fqdn jellyfin[270236]: [20:44:04] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 06 - The Puppet (219620D4).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:05 fqdn jellyfin[279425]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:05 fqdn jellyfin[279425]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:05 fqdn jellyfin[270236]: [20:44:05] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 24 - Punctuation (8E87E40E).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:05 fqdn jellyfin[279436]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:05 fqdn jellyfin[279436]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:05 fqdn jellyfin[270236]: [20:44:05] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 25 - Gasara (A0E62DA4).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:05 fqdn jellyfin[279446]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:05 fqdn jellyfin[279446]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:05 fqdn jellyfin[270236]: [20:44:05] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 21 - Run (BF42ED11).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:05 fqdn jellyfin[279456]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:05 fqdn jellyfin[279456]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:05 fqdn jellyfin[270236]: [20:44:05] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 01 - On the Ancient Stage of Stone (4A945BB5).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:05 fqdn jellyfin[279466]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:05 fqdn jellyfin[279466]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:05 fqdn jellyfin[270236]: [20:44:05] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 07 - Return (F4FF572B).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:05 fqdn jellyfin[279476]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:05 fqdn jellyfin[279476]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:05 fqdn jellyfin[270236]: [20:44:05] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 14 - Companions (A110758F).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:05 fqdn jellyfin[279486]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:05 fqdn jellyfin[279486]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:05 fqdn jellyfin[270236]: [20:44:05] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 04 - Mirage (37E27AB9).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:05 fqdn jellyfin[279496]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:05 fqdn jellyfin[279496]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:05 fqdn jellyfin[270236]: [20:44:05] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 19 - Wails (60B8E17C).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:05 fqdn jellyfin[279506]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:05 fqdn jellyfin[279506]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:05 fqdn jellyfin[270236]: [20:44:05] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 10 - Kugai (AA4EE962).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:05 fqdn jellyfin[279516]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:05 fqdn jellyfin[279516]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:05 fqdn jellyfin[270236]: [20:44:05] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 16 - Karma (036C6A72).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:05 fqdn jellyfin[279526]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:05 fqdn jellyfin[279526]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:05 fqdn jellyfin[279526]: Unsupported codec with id 98304 for input stream 10
May 12 20:44:05 fqdn jellyfin[270236]: [20:44:05] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 15 - The Threshold (1C91221F).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:05 fqdn jellyfin[279536]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:05 fqdn jellyfin[279536]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:05 fqdn jellyfin[279536]: Unsupported codec with id 98304 for input stream 10
May 12 20:44:05 fqdn jellyfin[270236]: [20:44:05] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 03 - Tantric Circle (378CA4A2).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:05 fqdn jellyfin[279546]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:05 fqdn jellyfin[279546]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:05 fqdn jellyfin[270236]: [20:44:05] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 09 - Storehouse (E7A44290).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:05 fqdn jellyfin[279556]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:05 fqdn jellyfin[279556]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:05 fqdn jellyfin[270236]: [20:44:05] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 11 - Ties (6EDE0DBE).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:05 fqdn jellyfin[279566]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:05 fqdn jellyfin[279566]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:05 fqdn jellyfin[270236]: [20:44:05] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 18 - Rear Window (D5640415).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:06 fqdn jellyfin[279576]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:06 fqdn jellyfin[279576]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:06 fqdn jellyfin[270236]: [20:44:06] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 20 - Upheaval (FDFBAC98).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:06 fqdn jellyfin[279586]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:06 fqdn jellyfin[279586]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:06 fqdn jellyfin[270236]: [20:44:06] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 02 - Opening Movements (0CA0EDF5).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:06 fqdn jellyfin[279596]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:06 fqdn jellyfin[279596]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:06 fqdn jellyfin[270236]: [20:44:06] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 12 - Unravel (AA085BC6).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:06 fqdn jellyfin[279606]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:06 fqdn jellyfin[279606]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:06 fqdn jellyfin[270236]: [20:44:06] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 13 - Disembark (E5359B52).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:06 fqdn jellyfin[279616]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:06 fqdn jellyfin[279616]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:06 fqdn jellyfin[270236]: [20:44:06] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 17 - Chaos (CCA83905).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:06 fqdn jellyfin[279626]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:06 fqdn jellyfin[279626]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:08 fqdn jellyfin[270236]: [20:44:08] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 closed
May 12 20:44:08 fqdn jellyfin[270236]: [20:44:08] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 request
May 12 20:44:10 fqdn jellyfin[270236]: [20:44:10] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 closed
May 12 20:44:10 fqdn jellyfin[270236]: [20:44:10] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 request
May 12 20:44:11 fqdn jellyfin[270236]: [20:44:11] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 closed
May 12 20:44:11 fqdn jellyfin[270236]: [20:44:11] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 request
May 12 20:44:15 fqdn jellyfin[270236]: [20:44:15] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 closed
May 12 20:44:15 fqdn jellyfin[270236]: [20:44:15] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 request
May 12 20:44:16 fqdn jellyfin[270236]: [20:44:16] [INF] Timer elapsed - processing queued items
May 12 20:44:16 fqdn jellyfin[270236]: [20:44:16] [INF] No events... stopping queue timer
May 12 20:44:17 fqdn jellyfin[270236]: [20:44:17] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 closed
May 12 20:44:17 fqdn jellyfin[270236]: [20:44:17] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 request
May 12 20:44:18 fqdn jellyfin[270236]: [20:44:18] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 closed
May 12 20:44:18 fqdn jellyfin[270236]: [20:44:18] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 request
May 12 20:44:19 fqdn jellyfin[270236]: [20:44:19] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 closed
May 12 20:44:20 fqdn jellyfin[270236]: [20:44:20] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 request
May 12 20:44:30 fqdn jellyfin[270236]: [20:44:30] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 08 - Harsh Worlds (E570F0D2).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:30 fqdn jellyfin[279648]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:30 fqdn jellyfin[279648]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:30 fqdn jellyfin[270236]: [20:44:30] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 05 - The Touching (682971F5).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:30 fqdn jellyfin[279659]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:30 fqdn jellyfin[279659]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:30 fqdn jellyfin[270236]: [20:44:30] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 22 - Personification (1DF5552D).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:30 fqdn jellyfin[279669]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:30 fqdn jellyfin[279669]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:31 fqdn jellyfin[270236]: [20:44:31] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 23 - Eternal (8880AA1F).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:31 fqdn jellyfin[279679]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:31 fqdn jellyfin[279679]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:31 fqdn jellyfin[279679]: Unsupported codec with id 98304 for input stream 10
May 12 20:44:31 fqdn jellyfin[270236]: [20:44:31] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 06 - The Puppet (219620D4).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:31 fqdn jellyfin[279689]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:31 fqdn jellyfin[279689]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:31 fqdn jellyfin[270236]: [20:44:31] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 24 - Punctuation (8E87E40E).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:31 fqdn jellyfin[279699]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:31 fqdn jellyfin[279699]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:31 fqdn jellyfin[270236]: [20:44:31] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 25 - Gasara (A0E62DA4).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:31 fqdn jellyfin[279709]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:31 fqdn jellyfin[279709]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:31 fqdn jellyfin[270236]: [20:44:31] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 21 - Run (BF42ED11).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:31 fqdn jellyfin[279719]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:31 fqdn jellyfin[279719]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:31 fqdn jellyfin[270236]: [20:44:31] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 01 - On the Ancient Stage of Stone (4A945BB5).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:31 fqdn jellyfin[279729]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:31 fqdn jellyfin[279729]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:31 fqdn jellyfin[270236]: [20:44:31] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 07 - Return (F4FF572B).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:31 fqdn jellyfin[279739]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:31 fqdn jellyfin[279739]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:31 fqdn jellyfin[270236]: [20:44:31] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 14 - Companions (A110758F).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:31 fqdn jellyfin[279749]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:31 fqdn jellyfin[279749]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:31 fqdn jellyfin[270236]: [20:44:31] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 04 - Mirage (37E27AB9).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:31 fqdn jellyfin[279759]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:31 fqdn jellyfin[279759]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:31 fqdn jellyfin[270236]: [20:44:31] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 19 - Wails (60B8E17C).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:31 fqdn jellyfin[279769]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:31 fqdn jellyfin[279769]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:31 fqdn jellyfin[270236]: [20:44:31] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 10 - Kugai (AA4EE962).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:31 fqdn jellyfin[279779]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:31 fqdn jellyfin[279779]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:31 fqdn jellyfin[270236]: [20:44:31] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 16 - Karma (036C6A72).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:31 fqdn jellyfin[279789]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:31 fqdn jellyfin[279789]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:31 fqdn jellyfin[279789]: Unsupported codec with id 98304 for input stream 10
May 12 20:44:31 fqdn jellyfin[270236]: [20:44:31] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 15 - The Threshold (1C91221F).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:31 fqdn jellyfin[279799]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:31 fqdn jellyfin[279799]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:31 fqdn jellyfin[279799]: Unsupported codec with id 98304 for input stream 10
May 12 20:44:31 fqdn jellyfin[270236]: [20:44:31] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 03 - Tantric Circle (378CA4A2).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:31 fqdn jellyfin[279809]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:31 fqdn jellyfin[279809]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:31 fqdn jellyfin[270236]: [20:44:31] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 09 - Storehouse (E7A44290).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:31 fqdn jellyfin[279819]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:31 fqdn jellyfin[279819]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:32 fqdn jellyfin[270236]: [20:44:32] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 11 - Ties (6EDE0DBE).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:32 fqdn jellyfin[279829]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:32 fqdn jellyfin[279829]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:32 fqdn jellyfin[270236]: [20:44:32] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 18 - Rear Window (D5640415).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:32 fqdn jellyfin[279839]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:32 fqdn jellyfin[279839]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:32 fqdn jellyfin[270236]: [20:44:32] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 20 - Upheaval (FDFBAC98).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:32 fqdn jellyfin[279849]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:32 fqdn jellyfin[279849]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:32 fqdn jellyfin[270236]: [20:44:32] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 02 - Opening Movements (0CA0EDF5).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:32 fqdn jellyfin[279859]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:32 fqdn jellyfin[279859]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:32 fqdn jellyfin[270236]: [20:44:32] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 12 - Unravel (AA085BC6).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:32 fqdn jellyfin[279869]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:32 fqdn jellyfin[279869]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:32 fqdn jellyfin[270236]: [20:44:32] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 13 - Disembark (E5359B52).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:32 fqdn jellyfin[279879]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:32 fqdn jellyfin[279879]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:32 fqdn jellyfin[270236]: [20:44:32] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mm/anime/G/Gasaraki/Gasaraki - 17 - Chaos (CCA83905).mkv" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
May 12 20:44:32 fqdn jellyfin[279889]: Unsupported codec with id 98304 for input stream 8
May 12 20:44:32 fqdn jellyfin[279889]: Unsupported codec with id 98304 for input stream 9
May 12 20:44:42 fqdn jellyfin[270236]: [20:44:42] [INF] Timer elapsed - processing queued items
May 12 20:44:42 fqdn jellyfin[270236]: [20:44:42] [INF] No events... stopping queue timer
May 12 20:46:15 fqdn jellyfin[270236]: [20:46:15] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 closed
May 12 20:46:15 fqdn jellyfin[270236]: [20:46:15] [INF] WS 2a02:578:470f:10:9593:5162:18f4:8ae0 request
May 12 20:47:03 fqdn jellyfin[270236]: [20:47:03] [INF] Timer elapsed - processing queued items
May 12 20:47:03 fqdn jellyfin[270236]: [20:47:03] [INF] No events... stopping queue timer
May 12 20:49:54 fqdn jellyfin[270236]: [20:49:54] [INF] Webhook Item Added Notifier Completed after 0 minute(s) and 0 seconds
```
```


### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #12045: [Issue]: TV show not listing any seasons because season is flagged as virtual
### Please describe your bug

I'm using locally generated NFO files for TV recordings: when the recording is completed then NFO file is created for the episode.

The problem is that when first episode for the show is recorded Jellyfin should create 1) show 2) season and 3) episode which it does according to database items, but the season is flagged as "IsVirtualItem" and because of this not listed in the user interface.

I am able "fix" this by forcing full metadata update for the show but it is annoying workaround and should work without it. After the season is "fixed" all episodes for this season work fine, until next new season which also needs "fix".

Looking at the code SeasonMetadataService SaveIsVirtualItem has some logic related to episode count, maybe episode does yet not "exist" at this point which would explain metadata update "fixing" it later? This problem also existed in 10.8.x.

EDIT: It seems that for master I need to refresh metadata twice until episode count is correct (1) and virtual flag is set to false for season.

### Reproduction Steps

1. Create a show folder including episode video file and NFO file for episode with title, season, seasonnumber and episode tags.
2. After automatic scan database information is correct for show, season and episode but season is marked as virtual
3. Do full metadata fresh for the show, now season is no longer marked as virtual and displayed in UI

### Jellyfin Version

Master branch

### if other:

_No response_

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
<recording started>

[12:50:30] [DBG] [18] Emby.Server.Implementations.IO.LibraryMonitor: New file refresher created for /mnt/Recordings/Show Name
...
[13:02:01] [DBG] [39] Emby.Server.Implementations.IO.LibraryMonitor: Timer stopped.
[13:02:01] [INF] [39] Emby.Server.Implementations.IO.LibraryMonitor: Recordings (/mnt/Recordings) will be refreshed.
[13:02:01] [DBG] [40] MediaBrowser.Providers.TV.SeriesMetadataService: Running SeriesNfoProvider for /mnt/Recordings/Show Name
[13:02:01] [DBG] [40] MediaBrowser.Providers.TV.SeriesMetadataService: SeriesNfoProvider returned no metadata for /mnt/Recordings/Show Name
[13:02:01] [INF] [40] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season Season Unknown entry for Show Name
[13:02:01] [DBG] [40] MediaBrowser.Providers.TV.EpisodeMetadataService: Running ProbeProvider for /mnt/Recordings/Show Name/Show Name.ts
..
[13:02:02] [INF] [40] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season null in series Show Name
[13:02:02] [INF] [40] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Season, Name: Season Unknown, Path: , Id: dd218b9c-42a8-8644-d251-8b9f781d424f
[13:02:02] [INF] [40] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season Season 1 entry for Show Name


<manual full metadata refresh>

[13:11:42] [DBG] [71] MediaBrowser.Providers.TV.SeriesMetadataService: Running SeriesNfoProvider for /mnt/Recordings/Show Name
[13:11:42] [DBG] [71] MediaBrowser.Providers.TV.SeriesMetadataService: SeriesNfoProvider returned no metadata for /mnt/Recordings/Show Name
[13:11:42] [INF] [71] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season 1 in series Show Name
[13:11:42] [INF] [71] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Season, Name: Season 1, Path: , Id: f2e7f59e-53fe-8836-60db-1fe0188e3678
[13:11:42] [INF] [71] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season Season 1 entry for Show Name
[13:11:42] [DBG] [71] MediaBrowser.Providers.TV.SeriesMetadataService: Running SeriesNfoProvider for /mnt/Recordings/Show Name
[13:11:42] [DBG] [71] MediaBrowser.Providers.TV.SeriesMetadataService: SeriesNfoProvider returned no metadata for /mnt/Recordings/Show Name
[13:11:42] [INF] [71] MediaBrowser.Providers.TV.SeriesMetadataService: Removing virtual season 1 in series Show Name
[13:11:42] [INF] [71] Emby.Server.Implementations.Library.LibraryManager: Removing item, Type: Season, Name: Season 1, Path: , Id: f2e7f59e-53fe-8836-60db-1fe0188e3678
[13:11:42] [INF] [71] MediaBrowser.Providers.TV.SeriesMetadataService: Creating Season Season 1 entry for Show Name
[13:11:42] [DBG] [71] MediaBrowser.Providers.TV.EpisodeMetadataService: Running ProbeProvider for /mnt/Recordings/Show Name/Show Name.ts
...
[13:12:40] [DBG] [65] MediaBrowser.Providers.TV.SeriesMetadataService: SeriesNfoProvider returned no metadata for /mnt/Recordings/Show Name
```

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Shadowghost**
See linked issue for details. For some reason `DisplaySpecialsWithinSeasons` breaks season creation if there are no season folders. I still don't really understand how, but this fixes it.

**Changes**
* Remove optimization which breaks season checks
* Re-add saving existing seasons forcefully as non-virtual if they are virtual

**Issues**
Fixes #11575
Fixes #12045

### CODE REVIEW

File: MediaBrowser.Controller/Entities/Folder.cs [hunk 1]
```diff
@@ -194,7 +194,7 @@ public override bool RequiresRefresh()
         /// </summary>
         /// <param name="item">The item.</param>
         /// <exception cref="InvalidOperationException">Unable to add  + item.Name.</exception>
-        public void AddChild(BaseItem item)
+        public virtual void AddChild(BaseItem item)
```
Comment (cvium) [inline MediaBrowser.Controller/Entities/Folder.cs:197]: big change for a patch release

Comment (Shadowghost) [reply MediaBrowser.Controller/Entities/Folder.cs:197]: I can revert it and put the logic back into the service if you prefer. This is cleaner though.

**Review by crobibero — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]
