### PR TITLE
Fix network binding

### LINKED ISSUE #11627: [Issue]: Jellyfin not binding to all addresses after update from 10.8.13 to 10.9.1
### Please describe your bug

After updating from 10.8.13 to 10.9.1 Jellyifn no longer binds to my local 19.2.168.1.109 address. It still binds to my vpn 10.1.1.2 address and localhost. Networking is set to bind to all addresses and I have tried removing networking.xml to force a recreation of the file.

**A workaround is to specify all the relevant addresses in "Networking > Bind to local network address" but this was not required with 10.8.13 and shouldn't be necessary.**

### Reproduction Steps

1. In Ubuntu Jammy x86-64 sudo apt upgrade to latest jellyfin
2. Check startup logs
3. Using bind addresses is not the same as defned lan addresses despite networking.xml set to bind to 0.0.0.0.

[2024-05-14 07:57:44.452 +00:00] [INF] Defined LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-05-14 07:57:44.452 +00:00] [INF] Defined LAN exclusions: []
[2024-05-14 07:57:44.452 +00:00] [INF] Using LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-05-14 07:57:44.453 +00:00] [INF] Using bind addresses: ["127.0.0.1", "1.2.3.4", "10.1.1.2"]
[2024-05-14 07:57:44.453 +00:00] [INF] Remote IP filter is "Allowlist"
[2024-05-14 07:57:44.453 +00:00] [INF] Filter list: []

### Jellyfin Version

10.9.0

### if other:

_No response_

### Environment

```markdown
- OS: Ubuntu Jammy
- Linux Kernel: GNU/Linux 6.5.0-28-generic x86_64
- Virtualization: Bare metal
- Clients: Web
- Browser: Chrome
- FFmpeg Version: 6.0.1 jellyfin
- Playback Method: Web
- Hardware Acceleration: QSV
- GPU Model: i5-1340p
- Plugins: None
- Reverse Proxy: Caddy
- Base URL: None
```

### Jellyfin logs

```shell
[2024-05-14 07:57:44.051 +00:00] [INF] Jellyfin version: "10.9.1"
[2024-05-14 07:57:44.068 +00:00] [INF] Environment Variables: ["[JELLYFIN_USER, jellyfin]", "[JELLYFIN_LOG_DIR, /var/log/jellyfin]", "[JELLYFIN_CACHE_DIR, /var/cache/jellyfin]", "[JELLYFIN_FFMPEG_OPT, --ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg]", "[JELLYFIN_ADDITIONAL_OPTS, ]", "[JELLYFIN_CONFIG_DIR, /etc/jellyfin]", "[JELLYFIN_ARGS, $JELLYFIN_WEB_OPT $JELLYFIN_FFMPEG_OPT $JELLYFIN_SERVICE_OPT $JELLYFIN_NOWEBAPP_OPT $JELLFIN_ADDITIONAL_OPTS --datadir $JELLYFIN_DATA_DIR --configdir $JELLYFIN_CONFIG_DIR --logdir $JELLYFIN_LOG_DIR --cachedir $JELLYFIN_CACHE_DIR]", "[JELLYFIN_DATA_DIR, /var/lib/jellyfin]", "[JELLYFIN_WEB_OPT, --webdir=/usr/share/jellyfin/web]"]
[2024-05-14 07:57:44.069 +00:00] [INF] Arguments: ["/usr/lib/jellyfin/bin/jellyfin.dll", "--webdir=/usr/share/jellyfin/web", "--ffmpeg=/usr/lib/jellyfin-ffmpeg/ffmpeg"]
[2024-05-14 07:57:44.069 +00:00] [INF] Operating system: "Ubuntu 22.04.4 LTS"
[2024-05-14 07:57:44.069 +00:00] [INF] Architecture: X64
[2024-05-14 07:57:44.070 +00:00] [INF] 64-Bit Process: True
[2024-05-14 07:57:44.070 +00:00] [INF] User Interactive: True
[2024-05-14 07:57:44.070 +00:00] [INF] Processor count: 16
[2024-05-14 07:57:44.070 +00:00] [INF] Program data path: "/var/lib/jellyfin"
[2024-05-14 07:57:44.070 +00:00] [INF] Log directory path: "/var/log/jellyfin"
[2024-05-14 07:57:44.070 +00:00] [INF] Config directory path: "/etc/jellyfin"
[2024-05-14 07:57:44.070 +00:00] [INF] Cache path: "/var/cache/jellyfin"
[2024-05-14 07:57:44.070 +00:00] [INF] Web resources path: "/usr/share/jellyfin/web"
[2024-05-14 07:57:44.070 +00:00] [INF] Application directory: "/usr/lib/jellyfin/bin/"
[2024-05-14 07:57:44.271 +00:00] [INF] Setting cache path: "/var/cache/jellyfin"
[2024-05-14 07:57:44.339 +00:00] [INF] Loading assemblies
[2024-05-14 07:57:44.452 +00:00] [INF] Defined LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-05-14 07:57:44.452 +00:00] [INF] Defined LAN exclusions: []
[2024-05-14 07:57:44.452 +00:00] [INF] Using LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-05-14 07:57:44.453 +00:00] [INF] Using bind addresses: ["127.0.0.1", "1.2.3.4", "10.1.1.2"]
[2024-05-14 07:57:44.453 +00:00] [INF] Remote IP filter is "Allowlist"
[2024-05-14 07:57:44.453 +00:00] [INF] Filter list: []
[2024-05-14 07:57:45.847 +00:00] [INF] Loaded plugin: "TMDb" "10.9.1.0"
[2024-05-14 07:57:45.848 +00:00] [INF] Loaded plugin: "Studio Images" "10.9.1.0"
[2024-05-14 07:57:45.848 +00:00] [INF] Loaded plugin: "OMDb" "10.9.1.0"
[2024-05-14 07:57:45.860 +00:00] [INF] Loaded plugin: "MusicBrainz" "10.9.1.0"
[2024-05-14 07:57:45.861 +00:00] [INF] Loaded plugin: "AudioDB" "10.9.1.0"
[2024-05-14 07:57:45.895 +00:00] [INF] Kestrel is listening on "127.0.0.1"
[2024-05-14 07:57:45.896 +00:00] [INF] Kestrel is listening on "1.2.3.4"
[2024-05-14 07:57:45.896 +00:00] [INF] Kestrel is listening on "10.1.1.2"
[2024-05-14 07:57:46.274 +00:00] [WRN] The WebRootPath was not found: "/var/lib/jellyfin/wwwroot". Static files may be unavailable.
[2024-05-14 07:57:46.305 +00:00] [INF] Running startup tasks
[2024-05-14 07:57:46.310 +00:00] [INF] Watching directory "/var/lib/jellyfin/data/collections"
[2024-05-14 07:57:46.323 +00:00] [INF] Daily trigger for "Generate Trickplay Images" set to fire at 2024-05-15 04:00:00.000 +00:00, which is 20:02:13.6764463 from now.
[2024-05-14 07:57:46.327 +00:00] [INF] Daily trigger for "Extract Chapter Images" set to fire at 2024-05-15 02:00:00.000 +00:00, which is 18:02:13.6727235 from now.
[2024-05-14 07:57:46.331 +00:00] [INF] Daily trigger for "Keyframe Extractor" set to fire at 2024-05-15 04:00:00.000 +00:00, which is 20:02:13.6684509 from now.
[2024-05-14 07:57:46.384 +00:00] [INF] Found ffmpeg version "6.0.1"
[2024-05-14 07:57:46.430 +00:00] [INF] Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
[2024-05-14 07:57:46.442 +00:00] [INF] Available "encoders": ["libsvtav1", "av1_nvenc", "av1_qsv", "av1_amf", "av1_vaapi", "libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mjpeg_qsv", "mjpeg_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "alac", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[2024-05-14 07:57:46.455 +00:00] [INF] Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_cuda", "hwupload_vaapi", "libplacebo", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_vulkan", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "scale_vulkan", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[2024-05-14 07:57:46.533 +00:00] [INF] Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
[2024-05-14 07:57:46.645 +00:00] [INF] FFmpeg: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
[2024-05-14 07:57:46.646 +00:00] [INF] ServerId: "bdb6cde9f2d046f59c4a340e02fb7bbf"
[2024-05-14 07:57:46.646 +00:00] [INF] Core startup complete
[2024-05-14 07:57:46.646 +00:00] [INF] Startup complete 0:00:02.8619289
```

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Shadowghost**
**Changes**
* Let Kestrel bind to all IPs by default if no `LocalNetworkAddresses` are set.

**Issues**
Fixes #11627

### CODE REVIEW

File: src/Jellyfin.Networking/Manager/NetworkManager.cs [hunk 1]
```diff
@@ -739,7 +738,9 @@ public IReadOnlyList<IPData> GetLoopbacks()
     /// <inheritdoc/>
     public IReadOnlyList<IPData> GetAllBindInterfaces(bool individualInterfaces = false)
     {
-        if (_interfaces.Count > 0 || individualInterfaces)
+        var config = _configurationManager.GetNetworkConfiguration();
+        var localNetworkAddresses = config.LocalNetworkAddresses;
+        if ((localNetworkAddresses.Length > 0 && !string.IsNullOrWhiteSpace(localNetworkAddresses[0]) && _interfaces.Count > 0) || individualInterfaces)
```
Comment (crobibero) [inline src/Jellyfin.Networking/Manager/NetworkManager.cs:743]: `!string.IsNullOrWhiteSpace(localNetworkAddresses[0])`

What is this check for?

Comment (oddstr13) [reply src/Jellyfin.Networking/Manager/NetworkManager.cs:743]: Looks like a test for whether the list contains items, and if so, if the first item isn't just an empty string or null.
That is, testing whether the config option is set or not.

Comment (crobibero) [reply src/Jellyfin.Networking/Manager/NetworkManager.cs:743]: I think a better test would be to see if any address is set, rather than just the first one?

Comment (oddstr13) [reply src/Jellyfin.Networking/Manager/NetworkManager.cs:743]: I'd have to find where the parsing is done to be able to tell whether that would make any difference.
Ideally it should be enough to check that the list is empty, but if the parser is naive, this kind of check is indeed needed.

Comment (Shadowghost) [reply src/Jellyfin.Networking/Manager/NetworkManager.cs:743]: I don't remember if this check came from Em by (it's copied over from the interface init) or if I had issues in my local environment back then which required it.

I do agree though, ideally we wouldn't need it

Comment (kevinklinkmuller) [reply src/Jellyfin.Networking/Manager/NetworkManager.cs:743]: hey, thanks for this fix! Is there an ETA when it'll be available on the stable release?

**Review by crobibero — APPROVED** [review]

**Review by nielsvanvelzen — APPROVED** [review]
