### PR TITLE
Correctly handle audio number tag fallbacks

### LINKED ISSUE #13484: Matroska music scanner ignores the PART_NUMBER/track metadata.
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our [forum or chat rooms](https://jellyfin.org/contact/) first to troubleshoot with volunteers, before creating a report.
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

When scanning Matroska music files (mka) Jellyfin ignores their metadata tags used for album sorting. As per [Matroska spec](https://www.matroska.org/technical/tagging.html), quote:

> PART_NUMBER 	UTF-8 	Number of the current part of the current level. (e.g., if TargetType is TRACK, the track number of an audio CD)

An example file metadata:
```text
Input #0, matroska,webm, from '01_Life.mka':
  Metadata:
    title           : Life
    ALBUM           : Kletka
    ARTIST          : Kletka
    ALBUM_ARTIST    : Kletka
    DATE            : 2024
    YEAR            : 2024
    track           : 1
    DATE_RELEASED   : 2024
    PURL            : https://www.youtube.com/watch?v=4LXce0YdyVY
    COMMENT         : https://www.youtube.com/watch?v=4LXce0YdyVY
    COMPATIBLE_BRANDS: iso6avc1mp41
    MAJOR_BRAND     : dash
    MINOR_VERSION   : 0
    ENCODER         : Lavf61.7.100
  Duration: 00:02:18.71, start: 0.000000, bitrate: 101 kb/s
  Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
      Metadata:
        ENCODER         : Lavc61.19.100 libopus
        DURATION        : 00:02:18.707000000
  Stream #0:1: Video: mjpeg (Progressive), yuvj444p(pc, bt470bg/unknown/unknown), 1080x1080 [SAR 300:300 DAR 1:1], 25 fps, 25 tbr, 1k tbn
      Metadata:
        title           : Album cover
        COMMENT         : Cover (front)
        DURATION        : 00:00:00.040000000
```

Results in missing sorting for an album:
Image

How it should be (flac in this example):
Image

### Reproduction steps

1. Create an example `mka` audio file with album metadata using `ffmpeg` with something like `-metadata "part_number=10"`.
2. Add example audio file to Jellyfin Music library.
3. At an album view observe no track number for `mka` files.

### What is the current _bug_ behavior?

-

### What is the expected _correct_ behavior?

-

### Jellyfin Server version

10.10.0+

### Specify commit id

_No response_

### Specify unstable release number

_No response_

### Specify version number

_No response_

### Specify the build version

Release

### Environment

```markdown
- OS:
- Linux Kernel:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
-
```

### FFmpeg logs

```shell

```

### Client / Browser logs

_No response_

### Relevant screenshots or videos

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gnattu**
Although the number type is nullable from the type definition of ATL, the lib might still normalize all unknown values to 0 which makes doing null check only not enough. Fallback to ffprobe results when the number is 0 as well.

**Changes**

**Issues**

Fixes #13484 without upstream changes so that the limited tags are falling back to ffprobe results. The complete fix is awaiting upstream release.

### CODE REVIEW

File: MediaBrowser.Providers/MediaInfo/AudioFileProber.cs [hunk 1]
```diff
@@ -172,9 +172,9 @@ private async Task FetchDataFromTags(Audio audio, Model.MediaInfo.MediaInfo medi
 
             track.Title = string.IsNullOrEmpty(track.Title) ? mediaInfo.Name : track.Title;
             track.Album = string.IsNullOrEmpty(track.Album) ? mediaInfo.Album : track.Album;
-            track.Year ??= mediaInfo.ProductionYear;
-            track.TrackNumber ??= mediaInfo.IndexNumber;
-            track.DiscNumber ??= mediaInfo.ParentIndexNumber;
+            track.Year = track.Year is null or 0 ? mediaInfo.ProductionYear : track.Year;
+            track.TrackNumber = track.TrackNumber is null or 0 ? mediaInfo.IndexNumber : track.TrackNumber;
+            track.DiscNumber = track.DiscNumber is null or 0 ? mediaInfo.ParentIndexNumber : track.DiscNumber;
```
Comment (Shadowghost) [inline MediaBrowser.Providers/MediaInfo/AudioFileProber.cs:177]: We usually don't use inline-linq like `or` in the code

Comment (gnattu) [reply MediaBrowser.Providers/MediaInfo/AudioFileProber.cs:177]: But in this case it is much cleaner than having nested assignments.

**Comment by voronind-com** [comment]
Doesnt't it also affect other fields? Like DATE?

**Comment by gnattu** [comment]
We are only doing fallbacks for those limited fields for basic metadata as ffprobe has its own limitations.

**Review by Bond-009 — APPROVED** [review]

**Review by crobibero — APPROVED** [review]
