### PR TITLE
Fix missing music genre metadata

### LINKED ISSUE #6036: Music genres missing
**Describe the bug**
The "Genres" tab under my Music Library is empty:
Untitled1

My music is tagged with [beets](https://github.com/beetbox/beets) and/or [picard](https://picard.musicbrainz.org/).

You can see the Genre tags on my albums like so:
Untitled2

That is to say, all my music is tagged properly with musicbrainz ids, etc. Jellyfin has all the metadata populated for my music, yet doesn't show anything under genres tab, despite that it has generes tagged for my music as you can see in the image.

How do I get the genres tab to populate? This installation is only a couple days old. Afaik, the music genres tab has never showed anything.

P.S.
The Genres tab is populated just fine for both my Movie and Show Libraries. It's only bugged under the Music Library.

**System (please complete the following information):**
 - OS: Arch Linux
 - Virtualization: docker - jellyfin/jellyfin:latest
 - Clients: Browser, Jellyfin Media Player 
 - Browser: Firefox 88.0.1
 - Jellyfin Version: 10.7.5
 - Playback: N/A
 - Installed Plugins: AudioDB 10.7.5.0 Bookshelf 5.0.0.0, MusicBrainz 10.7.5.0, OMDb 10.7.5.0, TMDb Box Sets 7.0.0.0, TheTVDB 4.0.0.0
 - Reverse Proxy: none
 - Base URL: none
 - Networking: bridge
 - Storage: local

**To Reproduce**
1. Go to `Music` >> `Genres`
2. The page is empty

**Expected behavior**
1. Go to `Music` >> `Genres`
2. The page is populated with the Genres i already have tagged.

**Logs**
`grep -i genre *.log` doesn't show anything other than a couple lines that look like this:
```
log_20210510.log:   at Jellyfin.Api.Controllers.ItemsController.GetItemsByUserId(Guid userId, String maxOfficialRating, Nullable`1 hasThemeSong, Nullable`1 hasThemeVideo, Nullable`1 hasSubtitles, Nullable`1 hasSpecialFeature, Nullable`1 hasTrailer, String adjacentTo, Nullable`1 parentIndexNumber, Nullable`1 hasParentalRating, Nullable`1 isHd, Nullable`1 is4K, LocationType[] locationTypes, LocationType[] excludeLocationTypes, Nullable`1 isMissing, Nullable`1 isUnaired, Nullable`1 minCommunityRating, Nullable`1 minCriticRating, Nullable`1 minPremiereDate, Nullable`1 minDateLastSaved, Nullable`1 minDateLastSavedForUser, Nullable`1 maxPremiereDate, Nullable`1 hasOverview, Nullable`1 hasImdbId, Nullable`1 hasTmdbId, Nullable`1 hasTvdbId, Guid[] excludeItemIds, Nullable`1 startIndex, Nullable`1 limit, Nullable`1 recursive, String searchTerm, SortOrder[] sortOrder, Nullable`1 parentId, ItemFields[] fields, String[] excludeItemTypes, String[] includeItemTypes, ItemFilter[] filters, Nullable`1 isFavorite, String[] mediaTypes, ImageType[] imageTypes, String[] sortBy, Nullable`1 isPlayed, String[] genres, String[] officialRatings, String[] tags, Int32[] years, Nullable`1 enableUserData, Nullable`1 imageTypeLimit, ImageType[] enableImageTypes, String person, Guid[] personIds, String[] personTypes, String[] studios, String[] artists, Guid[] excludeArtistIds, Guid[] artistIds, Guid[] albumArtistIds, Guid[] contributingArtistIds, String[] albums, Guid[] albumIds, Guid[] ids, VideoType[] videoTypes, String minOfficialRating, Nullable`1 isLocked, Nullable`1 isPlaceHolder, Nullable`1 hasOfficialRating, Nullable`1 collapseBoxSetItems, Nullable`1 minWidth, Nullable`1 minHeight, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 is3D, SeriesStatus[] seriesStatus, String nameStartsWithOrGreater, String nameStartsWith, String nameLessThan, Guid[] studioIds, Guid[] genreIds, Boolean enableTotalRecordCount, Nullable`1 enableImages)
```

That doesn't seem useful, though I wouldn't know for certain.

EDIT:
Here is the error history in my logs:
```
# grep '\[ERR\]' *.log
log_20210510.log:[2021-05-10 02:20:45.718 -04:00] [ERR] [64] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
log_20210510.log:[2021-05-10 14:20:46.375 -04:00] [ERR] [30] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
log_20210510.log:[2021-05-10 18:10:48.413 -04:00] [ERR] [48] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Users/41fca8fb2ae047ad81329e10c74ede8f/Items".
log_20210510.log:[2021-05-10 18:12:27.600 -04:00] [ERR] [24] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Users/41fca8fb2ae047ad81329e10c74ede8f/Items".
log_20210510.log:[2021-05-10 21:28:11.386 -04:00] [ERR] [69] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Users/41fca8fb2ae047ad81329e10c74ede8f/Items/12372e0cb0a648ed21490db6d6316aa2".
log_20210511.log:[2021-05-11 11:35:21.111 -04:00] [ERR] [4] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
log_20210511.log:[2021-05-11 20:48:56.746 -04:00] [ERR] [21] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/Users/e4314fe143444dddb5360c80bb355b79/Images/Primary".
log_20210511.log:[2021-05-11 23:35:11.475 -04:00] [ERR] [65] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
log_20210512.log:[2021-05-12 11:35:15.748 -04:00] [ERR] [36] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
log_20210512.log:[2021-05-12 13:53:23.622 -04:00] [ERR] [51] Jellyfin.Api.Controllers.DisplayPreferencesController: Invalid ViewType: ""
log_20210512.log:[2021-05-12 13:53:23.623 -04:00] [ERR] [51] Jellyfin.Api.Controllers.DisplayPreferencesController: Invalid ViewType: ""
log_20210512.log:[2021-05-12 13:53:23.624 -04:00] [ERR] [51] Jellyfin.Api.Controllers.DisplayPreferencesController: Invalid ViewType: ""
log_20210512.log:[2021-05-12 14:03:43.993 -04:00] [ERR] [7] Jellyfin.Api.Controllers.DisplayPreferencesController: Invalid ViewType: ""
log_20210512.log:[2021-05-12 14:03:43.995 -04:00] [ERR] [7] Jellyfin.Api.Controllers.DisplayPreferencesController: Invalid ViewType: ""
log_20210512.log:[2021-05-12 14:03:43.995 -04:00] [ERR] [7] Jellyfin.Api.Controllers.DisplayPreferencesController: Invalid ViewType: ""
```

### LINKED ISSUE #14041: Music Grenes missing for new media on 10.11
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our [forum or chat rooms](https://jellyfin.org/contact/) first to troubleshoot with volunteers, before creating a report.
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

Music Genres don't populate for new music added on 10.11. Migrated music works just fine, but the genre tab will be empty for any new music added. 

### Reproduction steps

1. Run a 10.11 server instance
2. Add a new music library.
3. Replace all metadata, then refresh for missing metadata (replace all doesn't seem to pull music genres in 10.11, so a search for missing is required)
4. Go to a Music album, and see that it has metadata including genre.
5. View the Genre tab or click on the genre in the item details. 

### What is the current _bug_ behavior?

The Genre tab will be empty.  If you click on the genre from the item details page, it will load an infinite blue spinning wheel. 

### What is the expected _correct_ behavior?

Grenes are displayed. 

### Jellyfin Server version

Master

### Specify commit id

https://github.com/jellyfin/jellyfin/commit/055d466d16fd61b89c4b7c88a0e57da615e86ec1

### Specify unstable release number

_No response_

### Specify version number

_No response_

### Specify the build version

10.11 Master (2025042805)

### Environment

```markdown
- OS: Windows 11
- Plugins: Default
```

### Jellyfin logs

```shell
N/A
```

### FFmpeg logs

```shell

```

### Client / Browser logs

_No response_

### Relevant screenshots or videos

Image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by theguymadmax**
**Changes**

-  Genre tags from audio files are now applied during initial scanning. Previously, these tags were ignored unless a Replace all Metadata scan was performed or the genre field was empty.

- Applied `string.IsNullOrWhiteSpace() `checks before splitting Genres and Tags to prevent arrays from containing empty string entries.

**Issues**
Fixes #14041
Fixes #6036

### CODE REVIEW

File: MediaBrowser.Providers/MediaInfo/AudioFileProber.cs [hunk 1]
```diff
@@ -340,9 +340,10 @@ private async Task FetchDataFromTags(Audio audio, Model.MediaInfo.MediaInfo medi
 
                 genres = genres.Trimmed().Distinct(StringComparer.OrdinalIgnoreCase).ToArray();
 
-                audio.Genres = options.ReplaceAllMetadata || audio.Genres is null || audio.Genres.Length == 0
-                    ? genres
-                    : audio.Genres;
+                if (options.ReplaceAllMetadata || audio.Genres is null || audio.Genres.All(string.IsNullOrWhiteSpace))
```
Comment (crobibero) [inline MediaBrowser.Providers/MediaInfo/AudioFileProber.cs]: I think we should keep the `audio.Genres.Length == 0` check here also

**Review by Shadowghost — APPROVED** [review]

**Comment by theguymadmax** [comment]
My second commit resolves the issue. Genres and tags were being initialized with empty strings, so the additional condition introduced in the first commit is no longer necessary. However, I don't see any downside to leaving it in
