### PR TITLE
Fix format normalizer for multiple input formats

### LINKED ISSUE #10046: [Issue]: Matroska Direct Play is broken
### Please describe your bug

Matroska Direct Play is broken with following commit:  [47aa07c3424ce0041e0a79eea1ab7f6621485b94](https://github.com/jellyfin/jellyfin/commit/47aa07c3424ce0041e0a79eea1ab7f6621485b94)

Matroska container name normalization was changed from:

```
format = format.Replace("matroska", "mkv", StringComparison.OrdinalIgnoreCase);
```

to:

```
if (string.Equals(format, "matroska", StringComparison.OrdinalIgnoreCase))
{
    return "mkv";
}
```

ffmpeg reports `matroska,webm` for all mkv files. With old code it will be transformed to `mkv,webm` and it's good and with new code it will remain as `matroska,webm`.

### Jellyfin Version

10.8.z

### if other:

_No response_

### Environment

_No response_

### Jellyfin logs

_No response_

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Shadowghost**
Seems like FFprobe can return a list of formats.

**Changes**
* Split format input before running normalization and run normalization on all input formats

**Issues**
Fixes #10046

### CODE REVIEW

File: MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs [hunk 1]
```diff
@@ -20,6 +19,9 @@
 
 namespace MediaBrowser.MediaEncoding.Probing
 {
+    /// <summary>
+    /// Class ProbeResultNormalizer.
```
Comment (cvium) [inline MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs:23]: Kind of pointless, no?

File: MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs [hunk 2]
```diff
@@ -73,6 +80,15 @@ public ProbeResultNormalizer(ILogger logger, ILocalizationManager localization)
             "Smith/Kotzen",
         };
 
+        /// <summary>
+        /// Function to transform a FFprobe response into its <see cref="MediaInfo"/> equivalent.
```
Comment (cvium) [inline MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs:84]:
```suggestion
        /// Transforms a FFprobe response into its <see cref="MediaInfo"/> equivalent.
```

File: MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs [hunk 3]
```diff
@@ -252,25 +268,37 @@ private string NormalizeFormat(string format)
                 return null;
             }
 
-            // Handle MPEG-1 container
-            if (string.Equals(format, "mpegvideo", StringComparison.OrdinalIgnoreCase))
+            var formatString = string.Empty;
+            var splitFormat = format.Split(',');
+            for (var i = 0; i < splitFormat.Length; i++)
```
Comment (cvium) [inline MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs:273]: This feels overly complicated. Can't we just use string.Replace?

Comment (Shadowghost) [reply MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs:273]: I think we can, not sure why I didn't use it initially...

Comment (Shadowghost) [reply MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs]: As mentioned by @dmitrylyzo in chat there can be collisions if we use replace, so I opted to not change the approach.

**Review by crobibero — COMMENTED** [review]
This is a bit cleaner:
```c#
// Input can be a list of multiple, comma-delimited formats - each of them needs to be checked
var splitFormat = format.Split(',');
for (var i = 0; i < splitFormat.Length; i++)
{
    // Handle MPEG-1 container
    if (string.Equals(splitFormat[i], "mpegvideo", StringComparison.OrdinalIgnoreCase))
    {
        splitFormat[i] = "mpeg";
    }

    // Handle MPEG-2 container
    else if (string.Equals(splitFormat[i], "mpeg", StringComparison.OrdinalIgnoreCase))
    {
        splitFormat[i] = "ts";
    }

    // Handle matroska container
    else if (string.Equals(splitFormat[i], "matroska", StringComparison.OrdinalIgnoreCase))
    {
        splitFormat[i] = "mkv";
    }
}

return string.Join(',', splitFormat);
```

**Review by crobibero — APPROVED** [review]

File: MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs [hunk 4]
```diff
@@ -73,6 +80,15 @@ public ProbeResultNormalizer(ILogger logger, ILocalizationManager localization)
             "Smith/Kotzen",
         };
 
+        /// <summary>
+        /// Transforms a FFprobe response into its <see cref="MediaInfo"/> equivalent.
+        /// </summary>
+        /// <param name="data">The <see cref="InternalMediaInfoResult"/>.</param>
+        /// <param name="videoType">The <see cref="VideoType"/>.</param>
+        /// <param name="isAudio">A boolean indicatin wether the media is audio.</param>
```
Comment (cvium) [inline MediaBrowser.MediaEncoding/Probing/ProbeResultNormalizer.cs:88]:
```suggestion
        /// <param name="isAudio">A boolean indicating whether the media is audio.</param>
```

**Review by cvium — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]
