### PR TITLE
Change Win32 AMF flag to d3d11va

### LINKED ISSUE #1807: AMD AMF not working when running as Windows service
**Describe the bug**
Hello.

I have been having trouble getting AMD AMF to work with Jellyfin as a Windows service.
Whenever I run Jellyfin as service and enable AMD AMF i get a "Failed to create Direct3D device" error from FFMPEG in the transcode log.

**To Reproduce**
1. Run Jellyfin as service
2. Enable AMD AMF
3. Try to play a video file

**Expected behavior**
Video getting transcoded

**Logs**
[Pastebin](https://pastebin.com/GpsUGtgi)

**System (please complete the following information):**
 - OS: Windows 10 LTSB 2016
 - Jellyfin Version: At least 10.3.x and 10.4.0

**Possible solution**
As per [this thread](https://stackoverflow.com/questions/56268560/using-directx-from-subprocess-executed-by-windows-service) on stackoverflow I've tried downloading the source of Jellyfin and editing:
Line 2551 in MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs 
from
`-hwaccel dxva2`
to
`-hwaccel d3d11va`

When compiled this seems to run fine and my files all play properly.
I do not know how to submit a PR for Jellyfin, nor can I argue whether or not this is a good solution, but it seems to work :)

### PR DESCRIPTION
**Pull request by joshuaboniface**
**Changes**
Use DirectX 11 hardware acceleration for AMF on Windows 8 or newer.

**Issues**
Fixes #1807

### CODE REVIEW

**Comment by LogicalPhallacy** [comment]
Will this break compat on win7? A few threads I turned up seem to think it does.

https://github.com/mpv-player/mpv/issues/3285

**Comment by joshuaboniface** [comment]
@LogicalPhallacy That's what I'm not too sure about since I don't use Windows. Do you know if there's a conditional we can use to avoid this on Win7 and only for Win8+?

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 1]
```diff
@@ -2548,7 +2548,7 @@ public string GetHardwareAcceleratedVideoDecoder(VideoType videoType, MediaStrea
                 {
                     if (Environment.OSVersion.Platform == PlatformID.Win32NT)
                     {
-                        return "-hwaccel dxva2";
+                        return "-hwaccel d3d11va";
```
Comment (LogicalPhallacy) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs]:
```suggestion
                        if( Environment.OSVersion.Version.Major > 6 || ( Environment.OSVersion.Version.Major == 6 && Environment.OSVersion.Version.Minor > 1 ) )
                            return "-hwaccel d3d11va";
                        else
                            return "-hwaccel dxva2";```
```


We can check if we are above Windows 8 by adding an extra version check here. It is recommended (moving forward) to use RunTimeInformation methods for OS detection, but that's a problem for later I think.

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 2]
```diff
@@ -2548,7 +2548,10 @@ public string GetHardwareAcceleratedVideoDecoder(VideoType videoType, MediaStrea
                 {
                     if (Environment.OSVersion.Platform == PlatformID.Win32NT)
                     {
-                        return "-hwaccel dxva2";
+                        if( Environment.OSVersion.Version.Major > 6 || ( Environment.OSVersion.Version.Major == 6 && Environment.OSVersion.Version.Minor > 1 ) )
+                            return "-hwaccel d3d11va";
+                        else
+                            return "-hwaccel dxva2";```
```
Comment (LogicalPhallacy) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs]: Suggest changes somehow left my markdown ending charcter in there. That need to go but then approved
```suggestion
                            return "-hwaccel dxva2";
```

**Comment by joshuaboniface** [comment]
OK @LogicalPhallacy and @jellyfin/backend - cleaned up the commits, should be good to go!

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 3]
```diff
@@ -2548,7 +2548,10 @@ public string GetHardwareAcceleratedVideoDecoder(VideoType videoType, MediaStrea
                 {
                     if (Environment.OSVersion.Platform == PlatformID.Win32NT)
                     {
-                        return "-hwaccel dxva2";
+                        if( Environment.OSVersion.Version.Major > 6 || ( Environment.OSVersion.Version.Major == 6 && Environment.OSVersion.Version.Minor > 1 ) )
```
Comment (Bond-009) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs]:
```suggestion
                        if(Environment.OSVersion.Version.Major > 6 || (Environment.OSVersion.Version.Major == 6 && Environment.OSVersion.Version.Minor > 1))
```

Comment (joshuaboniface) [reply MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs]: The conditional above has a space after if - do we want that as the standard, or directly together like this? I can fix up one or the other.
