### PR TITLE
Force plugin config location

### LINKED ISSUE #3653: All the built-in plugins claim MediaBrowser.Providers.xml as their config file, overwriting each other.
**Describe the bug**

All the built-in plugins claim `plugins/configurations/MediaBrowser.Providers.xml` as their config file, overwriting each other.

**System (please complete the following information):**
 - OS: Ubuntu bionic
 - Jellyfin Version: 10.6.0

**To Reproduce**

1. Save the configuration of one of the built-in plugins
2. Check the contents of the file
3. Save the configuration of a different plugin
4. Check the file contents again

**Expected behavior**

Separate config files.

### PR DESCRIPTION
**Pull request by crobibero**
Fixes #3653

Sets the plugin configuration file to be the future namespace

Note: Plugins won't save correctly until #3634 is merged

### CODE REVIEW

File: MediaBrowser.Providers/Plugins/AudioDb/Plugin.cs [hunk 1]
```diff
@@ -19,6 +19,9 @@ public class Plugin : BasePlugin<PluginConfiguration>, IHasWebPages
 
         public override string Description => "Get artist and album metadata or images from AudioDB.";
 
+        // TODO remove when plugin removed from server.
+        public override string ConfigurationFileName => "Jellyfin.Plugin.AudioDb.xml";
```
Comment (cvium) [inline MediaBrowser.Providers/Plugins/AudioDb/Plugin.cs:23]: Do any of these have existing configs? And does this change affect anything in that respect?

Comment (crobibero) [reply MediaBrowser.Providers/Plugins/AudioDb/Plugin.cs:23]: I'm not sure where they were stored in 10.5, but as of 10.6 all of the configurations were reset and save to the same file.
