### PR TITLE
Make priority class setting more robust

### LINKED ISSUE #14901: [10.11.0 RC7/RC8] Error in Probe Provider
### Description of the bug

Since I updated from rc5 currently running rc8 observed issue in scans. 
The library scan is successful but media information on Audio or Video content has no information for newly added media.

I tried to a scan and used replace all metadata for some media to test but the logs give error as Permission Denied.

I even did a full scan of library but only the media scanned before has the media information rest just shows the same error.

### Reproduction steps

After update ro rc7 or rc8 add new media and run scan. 
The media will be show in home but won't have the metadata of media.

### What is the current _bug_ behavior?

The media will be show in home but won't have the metadata of media.

### What is the expected _correct_ behavior?

Media information should be generated.

### Jellyfin Server version

Unstable

### Specify commit id

_No response_

### Specify unstable release number

_No response_

### Specify version number

_No response_

### Specify the build version

10.11.0-rc8

### Environment

```markdown
- OS:Pop!_OS 24.04 LTS
- Linux Kernel: Linux pop-os 6.16.3-76061603-generic
- Virtualization: Docker
- Clients:[Browsers, Android TV, Kodi]
- Browser:[Brave, firefox]
- FFmpeg Version: ffmpeg version 7.1.2-Jellyfin Copyright
- Playback Method:[Transcode, Direct Play]
- Hardware Acceleration:[Nvenc]
- GPU Model: rtx 2060 Super
- Plugins: [only the basic ones]
- Reverse Proxy: [nginx]
- Base URL: []
- Networking: []
- Jellyfin Data Storage: []
- Media Storage: []
- External Integrations: []
```

### Jellyfin logs

```shell
[15:18:28] [ERR] [49] MediaBrowser.Providers.Music.AudioMetadataService: Error in Probe Provider
System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.StartProcess(ProcessWrapper process)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioFileProber.Probe[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)

   
   [15:21:29] [ERR] [22] MediaBrowser.Providers.Movies.MovieMetadataService: Error in Probe Provider
System.ComponentModel.Win32Exception (13): Permission denied
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.StartProcess(ProcessWrapper process)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

### FFmpeg logs

```shell

```

### Client / Browser logs

_No response_

### Relevant screenshots or videos

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gnattu**
Currently the tasks simply crashes because the user running jellyfin server does not have the permission to change priority of a process. The below normal is a best-effort optimization and should not crash the task entirely. Add a try catch to make the task to move on even when priority cannot be set.

**Changes**

**Issues**

Fixes #14901

### CODE REVIEW

File: MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs [hunk 1]
```diff
@@ -1122,7 +1122,15 @@ public string GetTimeParameter(TimeSpan time)
         private void StartProcess(ProcessWrapper process)
         {
             process.Process.Start();
-            process.Process.PriorityClass = ProcessPriorityClass.BelowNormal;
+
+            try
+            {
+                process.Process.PriorityClass = ProcessPriorityClass.BelowNormal;
+            }
+            catch (Exception ex)
```
Comment (nielsvanvelzen) [inline MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs:1130]: Could be more specific to just the exception type we expect

Comment (gnattu) [reply MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs:1130]: But we don't really care? This operation only throws 4 types of exceptions and 3 of them means the process cannot be set to the desired priority, due to different reasons, and 1 is due to a parameter error, which should not occur for our hardcoded value.

It throws:

```
System.ComponentModel.Win32Exception
NotSupportedException
InvalidOperationException
```

all the above are due to external reasons that the priority cannot be set.

It also throws `InvalidEnumArgumentException`, but this would not happen for our hardcoded value.

Comment (JPVenson) [reply MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs:1130]: also we dont really act upon the exception types. So having a blank catch is fine here
