### PR TITLE
fix copy&paste error for requestedRangeTypes preventing stream copy

### LINKED ISSUE #7880: [Issue]: file always being transcoded for audio channels
When playing a media, i'ts now being always transcoded for audio.
I feel this is due to some changes made to match the transcoded channel to the player audio channels.

This prevents a lot of files to be directly played, wich consume ressources and delay the stream play.

This was not the case under Jellyfin 10.7 and never leaded to any problems on all my clients.

Is there any informations about the intentions behind this?
Is there a way to avoid the files being transcoded just for audio channel layout related things?

Thanks to every Jellyfin contributors!

### Jellyfin Version

10.8.0

### if other:

_No response_

### Environment

_No response_

### Jellyfin logs

```shell
"/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -fflags +genpts  -i file:\"/media/films/The Unbearable Weight of Massive Talent (2022)/The Unbearable Weight of Massive Talent (2022).mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 copy -start_at_zero -codec:a:0 libfdk_aac -ac 2 -ab 384000 -ar 48000 -af \"volume=2\" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename \"/transcodes/51424adcee47c049c92f786ab9e07d78%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/transcodes/51424adcee47c049c92f786ab9e07d78.m3u8\""
```

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #8070: Reason for transcoding: The number of audio channels is not supported
**Brief**
testvid123.mp4 plays on google pixel 4a without transcoding. I expect the same when casting to the Google Chromecast Ultra

**Expected Behaviour**
testvid123.mp4 casting to the Google Chromecast Ultra should use "Direct Play"

**What actually happens**
testvid123.mp4 casting to the Google Chromecast Ultra transcodes 

**Media Info of the file**
```
ffprobe testvid123.mp4
ffprobe version 4.3.4-0+deb11u1+rpt1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1+rpt1 --toolchain=hardened --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --disable-mmal --enable-neon --enable-v4l2-request --enable-libudev --enable-epoxy --enable-sand --libdir=/usr/lib/aarch64-linux-gnu --arch=arm64 --enable-pocketsphinx --enable-libdc1394 --enable-libdrm --enable-vout-drm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'testvid123.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    creation_time   : 2021-07-04T02:46:47.000000Z
    title           : testvid123
    encoder         : Lavf58.20.100
    comment         : testvid123
  Duration: 01:57:12.20, start: 0.000000, bitrate: 2230 kb/s
    Stream #0:0(und): Video: hevc (Main 10) (hev1 / 0x31766568), yuv420p10le(tv), 1920x1038 [SAR 1:1 DAR 320:173], 1999 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 23.98 tbc (default)
    Metadata:
      creation_time   : 2021-07-04T02:46:47.000000Z
      handler_name    : VideoHandler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 224 kb/s (default)
    Metadata:
      creation_time   : 2021-07-04T02:46:47.000000Z
      handler_name    : SoundHandler
```

**Logs**
```
<!-- Please paste any log messages from during the playback issue. -->
[06:58:23] [WRN] [29] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS 192.168.1.114 error receiving data: The remote party closed the WebSocket connection without completing the close handshake.
[06:58:23] [INF] [29] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.1.114 closed
[06:58:28] [INF] [25] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.1.114 request
[06:58:35] [WRN] [22] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.1.136:8096/Sessions/Playing/Progress to 192.168.1.111 in 0:00:00.7438076 with Status Code 204
[06:58:39] [INF] [11] Jellyfin.Api.Helpers.TranscodingJobHelper: Stopping ffmpeg process with q command for /config/data/transcodes/cd941c05e8e3c8556fc4aefaa4a70653.mkv
[06:58:40] [INF] [11] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 0
[06:58:40] [INF] [11] Jellyfin.Api.Helpers.TranscodingJobHelper: Deleting partial stream file(s) /config/data/transcodes/cd941c05e8e3c8556fc4aefaa4a70653.mkv
[06:58:41] [INF] [11] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Chromecast 2.1.0 playing testvid123. Stopped at 2423824 ms
[06:58:41] [WRN] [11] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.1.136:8096/Sessions/Playing/Stopped to 192.168.1.111 in 0:00:02.4000372 with Status Code 204
[06:58:42] [INF] [13] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for dewi. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[06:58:42] [INF] [13] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Anonymous Profile, Path=/data/movies/testvid123/testvid123.mp4, AudioStreamIndex=2, SubtitleStreamIndex=-1 ) => ( PlayMethod=Transcode, TranscodeReason=AudioChannelsNotSupported ) media:/videos/cc451022-b773-967a-b5ec-1dfce0566421/stream.mkv?MediaSourceId=cc451022b773967ab5ec1dfce0566421&VideoCodec=h264,h265,hevc,vp8,vp9,hevc&AudioCodec=aac&AudioStreamIndex=2&VideoBitrate=10616000&AudioBitrate=384000&AudioSampleRate=48000&MaxFramerate=23.976025&api_key=<token>&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&CopyTimestamps=true&RequireAvc=false&Tag=bd9ff22ecec76d308626743f7b80a460&hevc-level=120&hevc-videobitdepth=10&hevc-profile=main10&hevc-audiochannels=6&aac-profile=lc&h264-profile=high,main,baseline,constrainedbaseline&h264-level=42&aac-audiochannels=2&TranscodeReasons=AudioChannelsNotSupported
[06:58:43] [WRN] [13] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.1.136:8096/Items/cc451022b773967ab5ec1dfce0566421/PlaybackInfo?UserId=27e3f965cb354d5782b7076455eabfa7&StartTimeTicks=24190493880&MaxStreamingBitrate=11000000&AudioStreamIndex=2&SubtitleStreamIndex=-1&MediaSourceId=cc451022b773967ab5ec1dfce0566421 to 192.168.1.111 in 0:00:00.7879663 with Status Code 200
[06:58:43] [INF] [13] Jellyfin.Api.Helpers.TranscodingJobHelper: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -ss 00:40:19.049 -f mov,mp4,m4a,3gp,3g2,mj2 -autorotate 0 -i file:"/data/movies/testvid123/testvid123.mp4" -map 0:0 -map 0:1 -map -0:s -codec:v:0 libx264 -force_key_frames "expr:gte(t,n_forced*5)" -vf "setparams=color_primaries=bt709:color_trc=bt709:colorspace=bt709,scale=trunc(min(max(iw\,ih*a)\,min(1920\,1038*a))/2)*2:trunc(min(max(iw/a\,ih)\,min(1920/a\,1038))/2)*2,format=yuv420p" -copyts -avoid_negative_ts disabled -start_at_zero -preset superfast -crf 23 -maxrate 8332737 -bufsize 16665474 -profile:v:0 high -level 42 -x264opts:0 subme=0:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 libfdk_aac -ac 2 -ab 384000 -ar 48000 -af "volume=2" -y "/config/data/transcodes/094c0d744732277af9f5dbe371b4b076.mkv"
[06:58:54] [WRN] [27] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://192.168.1.136:8096/videos/cc451022-b773-967a-b5ec-1dfce0566421/stream.mkv?DeviceId=chromecast_1657050967555&MediaSourceId=cc451022b773967ab5ec1dfce0566421&VideoCodec=h264,h265,hevc,vp8,vp9,hevc&AudioCodec=aac&AudioStreamIndex=2&VideoBitrate=10616000&AudioBitrate=384000&AudioSampleRate=48000&MaxFramerate=23.976025&StartTimeTicks=24190493880&PlaySessionId=cb4dfed8d28a4a85abf12e07d1f021c2&api_key=125d17fa704f4c5586eb4c69be4fb748&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&CopyTimestamps=true&RequireAvc=false&Tag=bd9ff22ecec76d308626743f7b80a460&hevc-level=120&hevc-videobitdepth=10&hevc-profile=main10&hevc-audiochannels=6&aac-profile=lc&h264-profile=high,main,baseline,constrainedbaseline&h264-level=42&aac-audiochannels=2&TranscodeReasons=AudioChannelsNotSupported to 192.168.1.111 in 0:00:11.2817439 with Status Code 200
[06:59:01] [INF] [30] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.1.121 request
[06:59:01] [INF] [8] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.1.121 closed
[06:59:02] [INF] [13] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 192.168.1.121 request
```

**Stats for Nerds Screenshots**

**Server System (please complete the following information):**
 - OS: Linux - docker
 - Jellyfin Version: Linuxserver.io version:- 10.8.1-1-ls168 Build-date:- 2022-06-30T05:46:05+02:00
 - Hardware settings & device: Raspberry pi 4 8GB RAM
 - Reverse proxy: no
 - Other hardware notes: N/A
 
**Client System (please complete the following information):**
 - Device: Chromecast Ultra

### PR DESCRIPTION
**Pull request by Andy2244**
**Changes**
- fix copy&paste error for `requestedRangeTypes` preventing stream copy
- fix invalid _(-1)_ SubtitleStreamIndex preventing stream copy

Negative/invalid SubtitleStreamIndex values should also be ignored and allow stream copy.

fixes #8070 
fixes #7880 _(probably)_

### CODE REVIEW

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 1]
```diff
@@ -1764,10 +1765,10 @@ public bool CanStreamCopyVideo(EncodingJobInfo state, MediaStream videoStream)
             {
                 if (string.IsNullOrEmpty(videoStream.VideoRangeType))
                 {
-                    return false;
+                    // return false;
```
Comment (nyanmisaka) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:1768]: The default value of VideoRangeType is SDR. This can’t be missing.
And actually remuxing/direct streaming works fine for me in both SDR and HDR/DV content.
What are you trying to fix here?
https://github.com/jellyfin/jellyfin/blob/84a1674f391d344c251c2c949cb227a9318536eb/MediaBrowser.Model/Entities/MediaStream.cs#L692

Comment (Andy2244) [reply MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs]: @nyanmisaka ah yes, the actual issues is the copy&paste error for the check!
Updated the PR

The issues is that if you send a stream request and have no "rangetype" this always triggers a transcode.

**Comment by cvium** [comment]
Please re-target the `release-10.8.z` branch

**Comment by Andy2244** [comment]
@cvium done

**Review by cvium — APPROVED** [review]

**Review by crobibero — APPROVED** [review]

**Review by nyanmisaka — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]
