### PR TITLE
Fix tvdb guest stars with multiple roles

### LINKED ISSUE #1586: TVDB incorrectly parse Actor with multiple roles
**Describe the bug**

When an actor has multiple roles credited in TVDB they get parsed weirdly in JF.

**To Reproduce**

1. Go to https://www.thetvdb.com/series/the-venture-bros/episodes/369501
2. View Guest star list. multiple roles listed 

**Expected behavior**

One actor item should be presented in JF with the list of roles.

**Screenshots**

TVDB
image
JF
image

**System (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Jellyfin Version: 10.3.7
 - Reverse proxy: no

### PR DESCRIPTION
**Pull request by cvium**
**Changes**
I'm not sure if it's TvdbSharper or the v2 api, but guest stars don't follow the pipe delimited format that the rest of the "persons" objects do.

**Issues**
Fixes #1586

### CODE REVIEW

File: MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs [hunk 1]
```diff
@@ -193,17 +193,43 @@ private static MetadataResult<Episode> MapEpisodeToResult(EpisodeInfo id, Episod
...
-                var index = person.IndexOf('(');
-                string role = null;
-                var name = person;
+                var currentActor = episode.GuestStars[i];
+                var roleStartIndex = currentActor.IndexOf('(');
 
-                if (index != -1)
+                string name = currentActor;
+                string role = "";
+                if (roleStartIndex != -1)
```
Comment (Bond-009) [inline MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs]: Is this ever true? i.e can you have an actor without a role?

File: MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs [hunk 2]
```diff
@@ -193,17 +193,43 @@ private static MetadataResult<Episode> MapEpisodeToResult(EpisodeInfo id, Episod
...
+            for (var i = 0; i < episode.GuestStars.Length; ++i)
             {
-                var index = person.IndexOf('(');
-                string role = null;
-                var name = person;
+                var currentActor = episode.GuestStars[i];
+                var roleStartIndex = currentActor.IndexOf('(');
 
-                if (index != -1)
+                string name = currentActor;
```
Comment (Bond-009) [inline MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs]: This isn't really needed, as you never assign a new value to `currentActor`

File: MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs [hunk 3]
```diff
@@ -193,17 +193,43 @@ private static MetadataResult<Episode> MapEpisodeToResult(EpisodeInfo id, Episod
...
+                    name = name.Substring(0, roleStartIndex).Trim();
 
-                    name = person.Substring(0, index).Trim();
+                    // Fetch all roles
+                    for (var j = i + 1; j < episode.GuestStars.Length; ++j)
+                    {
+                        var currentRole = episode.GuestStars[j];
+                        var roleEndIndex = currentRole.IndexOf(')');
+
+                        if (roleEndIndex != -1)
```
Comment (Bond-009) [inline MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs]: I'd invert this if statement.

File: MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs (hunk 1 above)
Comment (cvium) [reply MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs]: Yes

File: MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs [hunk 4]
```diff
@@ -193,17 +193,43 @@ private static MetadataResult<Episode> MapEpisodeToResult(EpisodeInfo id, Episod
...
             {
-                var index = person.IndexOf('(');
-                string role = null;
-                var name = person;
+                var currentActor = episode.GuestStars[i];
+                var roleStartIndex = currentActor.IndexOf('(');
 
-                if (index != -1)
+                string name = currentActor;
+                string role = "";
```
Comment (Bond-009) [inline MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs]:
```suggestion
                string role = string.Empty;
```

File: MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs (hunk 2 above)
Comment (cvium) [reply MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs]: I do assign a new value to name though
