### PR TITLE
Multiple HLS codec and bitrate fixes

### LINKED ISSUE #9270: [Issue]: DTS (DCA) transcoding fails due to bitrate
### Please describe your bug

I have a mkv file with the following streams:
```
   Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS-eng         : 14580982
      DURATION-eng    : 00:42:36.513000000
      NUMBER_OF_FRAMES-eng: 61295
      NUMBER_OF_BYTES-eng: 4659559031
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-30 11:06:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: dts (DTS-HD MA), 48000 Hz, 5.1(side), s32p (24 bit) (default)
    Metadata:
      title           : DTS-HD MA 5.1
      BPS-eng         : 3376525
      DURATION-eng    : 00:41:56.595000000
      NUMBER_OF_FRAMES-eng: 235931
      NUMBER_OF_BYTES-eng: 1062168328
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-30 11:06:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```
The file plays fine via direct play on android.
If the file is transcoded to reduce the bitrate however, the transcoding fails:
```
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (dts (dca) -> dts (dca))
Press [q] to stop, [?] for help
Error initializing output stream 0:1 -- Error while opening encoder for output stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```
The ffmpeg command used is:
```
/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -ss 00:37:18.000 -init_hw_device cuda=cu:0 -filter_hw_device cu -autorotate 0 -i file:"/mnt/cluster_storage/Videos/TVShows/English/the.expanse.2015/01/the.expanse.2015.s01e06.rock.bottom.webdl-2160p.HEVC.DTS-HD.MA.5.1-safety.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -preset p3 -b:v 3360000 -maxrate 3360000 -bufsize 6720000 -g:v:0 72 -keyint_min:v:0 72 -vf "setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,scale=trunc(min(max(iw\,ih*a)\,1280)/2)*2:trunc(ow/a/2)*2,format=yuv420p10le,hwupload=derive_device=cuda,tonemap_cuda=format=yuv420p:p=bt709:t=bt709:m=bt709:tonemap=bt2390:peak=100:desat=0" -codec:a:0 dts -strict -2 -ac 6 -ab 128000 -ar 48000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 746 -hls_segment_filename "/config/transcodes/8536854ddb96a2bf68155af8044ddf85%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/8536854ddb96a2bf68155af8044ddf85.m3u8"
```

The problem seems to be the audio bitrate, if I remove the parameter `-ab 128000` the transcode works fine: 
```
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (dts (dca) -> dts (dca))
Press [q] to stop, [?] for help
Output #0, hls, to '/config/transcodes/8536854ddb96a2bf68155af8044ddf85.m3u8':
  Metadata:
    encoder         : Lavf59.27.100
  Stream #0:0: Video: h264 (Main), cuda(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 3360 kb/s, 23.98 fps, 90k tbn (default)
    Metadata:
      encoder         : Lavc59.37.100 h264_nvenc
    Side data:
      cpb: bitrate max/min/avg: 3360000/0/3360000 buffer size: 6720000 vbv_delay: N/A
  Stream #0:1: Audio: dts, 48000 Hz, 5.1(side), s32, 1411 kb/s (default)
    Metadata:
      encoder         : Lavc59.37.100 dca
```

### Jellyfin Version

10.8.0

### if other:

10.8.9

### Environment

```markdown
- OS: Docker on Ubuntu
- Virtualization: Docker
- Clients: Android
- Browser: n.a.
- FFmpeg Version: 5.1.2-Jellyfin
- Playback Method: Transcode
- Hardware Acceleration: NVENC
- Plugins: n.a.
- Reverse Proxy: nginx
- Base URL: none
- Networking: macvlan
- Storage: local
```

### Jellyfin logs

```shell
[2023-02-07 08:45:56.074 +01:00] [INF] [67] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "Andreas". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2023-02-07 08:45:56.074 +01:00] [INF] [67] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="Jellyfin Android", Path="\\HTPC\media\TVShows\English\the.expanse.2015\01\the.expanse.2015.s01e06.rock.bottom.webdl-2160p.HEVC.DTS-HD.MA.5.1-safety.mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=ContainerBitrateExceedsLimit ) "media:/videos/261b796e-95b6-7600-8e3e-6c0c8b4d3283/master.m3u8?MediaSourceId=261b796e95b676008e3e6c0c8b4d3283&VideoCodec=h264&AudioCodec=dts&AudioStreamIndex=3&VideoBitrate=3360000&AudioBitrate=640000&AudioSampleRate=48000&MaxFramerate=23.976025&api_key=<token>&RequireAvc=false&Tag=7058d97c86772b2e2fc4a556da9f8c38&SegmentContainer=ts&BreakOnNonKeyFrames=False&hevc-level=150&hevc-videobitdepth=10&hevc-profile=main10&hevc-audiochannels=6&dts-profile=dts-hdma&TranscodeReasons=ContainerBitrateExceedsLimit"
[2023-02-07 08:45:56.498 +01:00] [INF] [143] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Existing tracker found! : 7eb056e6cacd22b8fd7872eb472a4ee0bd10052894d2289e-fd7872eb472a4ee0bd10052894d2289e-261b796e95b676008e3e6c0c8b4d3283
[2023-02-07 08:45:56.498 +01:00] [INF] [143] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Removing existing tracker : 7eb056e6cacd22b8fd7872eb472a4ee0bd10052894d2289e-fd7872eb472a4ee0bd10052894d2289e-261b796e95b676008e3e6c0c8b4d3283
[2023-02-07 08:45:56.498 +01:00] [INF] [143] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Adding playback tracker : 7eb056e6cacd22b8fd7872eb472a4ee0bd10052894d2289e-fd7872eb472a4ee0bd10052894d2289e-261b796e95b676008e3e6c0c8b4d3283
[2023-02-07 08:45:56.498 +01:00] [INF] [143] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 02/07/2023 08:45:56
[2023-02-07 08:45:56.498 +01:00] [INF] [143] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[2023-02-07 08:45:56.498 +01:00] [INF] [143] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[2023-02-07 08:45:57.297 +01:00] [INF] [34] Jellyfin.Api.Helpers.TranscodingJobHelper: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -ss 00:37:18.000 -init_hw_device cuda=cu:0 -filter_hw_device cu -autorotate 0 -i file:\"/mnt/cluster_storage/Videos/TVShows/English/the.expanse.2015/01/the.expanse.2015.s01e06.rock.bottom.webdl-2160p.HEVC.DTS-HD.MA.5.1-safety.mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -preset p3 -b:v 3360000 -maxrate 3360000 -bufsize 6720000 -g:v:0 72 -keyint_min:v:0 72 -vf \"setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,scale=trunc(min(max(iw\,ih*a)\,1280)/2)*2:trunc(ow/a/2)*2,format=yuv420p10le,hwupload=derive_device=cuda,tonemap_cuda=format=yuv420p:p=bt709:t=bt709:m=bt709:tonemap=bt2390:peak=100:desat=0\" -codec:a:0 dts -strict -2 -ac 6 -ab 128000 -ar 48000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 746 -hls_segment_filename \"/config/transcodes/8536854ddb96a2bf68155af8044ddf85%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/config/transcodes/8536854ddb96a2bf68155af8044ddf85.m3u8\""
[2023-02-07 08:45:57.518 +01:00] [ERR] [157] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 1
[2023-02-07 08:45:57.531 +01:00] [ERR] [157] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL "GET" "/videos/261b796e-95b6-7600-8e3e-6c0c8b4d3283/hls1/main/746.ts".
MediaBrowser.Common.FfmpegException: FFmpeg exited with code 1
   at Jellyfin.Api.Helpers.TranscodingJobHelper.StartFfMpeg(StreamState state, String outputPath, String commandLineArguments, HttpRequest request, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource, String workingDirectory)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetDynamicSegment(StreamingRequestDto streamingRequest, Int32 segmentId)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetHlsVideoSegment(Guid itemId, String playlistId, Int32 segmentId, String container, Int64 runtimeTicks, Int64 actualSegmentLengthTicks, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions)
   at lambda_method1070(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### FFmpeg logs

```shell
/videos/261b796e-95b6-7600-8e3e-6c0c8b4d3283/hls1/main/746.ts

{"Protocol":0,"Id":"261b796e95b676008e3e6c0c8b4d3283","Path":"/mnt/cluster_storage/Videos/TVShows/English/the.expanse.2015/01/the.expanse.2015.s01e06.rock.bottom.webdl-2160p.HEVC.DTS-HD.MA.5.1-safety.mkv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"mkv,webm","Size":5722961627,"Name":"the.expanse.2015.s01e06.rock.bottom.webdl-2160p.HEVC.DTS-HD.MA.5.1-safety","IsRemote":false,"ETag":"7058d97c86772b2e2fc4a556da9f8c38","RunTimeTicks":25565130000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":0,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"subrip","CodecTag":null,"Language":"ger","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","DisplayTitle":"Ger - SUBRIP - External","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":0,"Score":null,"IsExternal":true,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":"/mnt/cluster_storage/Videos/TVShows/English/the.expanse.2015/01/the.expanse.2015.s01e06.rock.bottom.webdl-2160p.HEVC.DTS-HD.MA.5.1-safety.de.srt","PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"subrip","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":"Undefined","LocalizedDefault":"Default","LocalizedForced":"Forced","LocalizedExternal":"External","DisplayTitle":"Eng - SUBRIP - External","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":null,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":2,"AspectRatio":null,"Index":1,"Score":null,"IsExternal":true,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":"/mnt/cluster_storage/Videos/TVShows/English/the.expanse.2015/01/the.expanse.2015.s01e06.rock.bottom.webdl-2160p.HEVC.DTS-HD.MA.5.1-safety.en.srt","PixelFormat":null,"Level":0,"IsAnamorphic":null},{"Codec":"hevc","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":"bt2020nc","ColorTransfer":"smpte2084","ColorPrimaries":"bt2020","DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":null,"VideoRange":"HDR","VideoRangeType":"HDR10","VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"4K HEVC HDR","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":17908648,"BitDepth":10,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":true,"IsForced":false,"Height":2160,"Width":3840,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"Main 10","Type":1,"AspectRatio":"16:9","Index":2,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p10le","Level":150,"IsAnamorphic":null},{"Codec":"dts","CodecTag":null,"Language":"eng","ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/1000","CodecTimeBase":null,"Title":"DTS-HD MA 5.1","VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"DTS-HD MA 5.1 - Eng - Default","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"5.1","BitRate":3376525,"BitDepth":24,"RefFrames":null,"PacketLength":null,"Channels":6,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":"DTS-HD MA","Type":0,"AspectRatio":null,"Index":3,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":21285173,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M -ss 00:37:18.000 -init_hw_device cuda=cu:0 -filter_hw_device cu -autorotate 0 -i file:"/mnt/cluster_storage/Videos/TVShows/English/the.expanse.2015/01/the.expanse.2015.s01e06.rock.bottom.webdl-2160p.HEVC.DTS-HD.MA.5.1-safety.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -preset p3 -b:v 3360000 -maxrate 3360000 -bufsize 6720000 -g:v:0 72 -keyint_min:v:0 72 -vf "setparams=color_primaries=bt2020:color_trc=smpte2084:colorspace=bt2020nc,scale=trunc(min(max(iw\,ih*a)\,1280)/2)*2:trunc(ow/a/2)*2,format=yuv420p10le,hwupload=derive_device=cuda,tonemap_cuda=format=yuv420p:p=bt709:t=bt709:m=bt709:tonemap=bt2390:peak=100:desat=0" -codec:a:0 dts -strict -2 -ac 6 -ab 128000 -ar 48000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 746 -hls_segment_filename "/config/transcodes/8536854ddb96a2bf68155af8044ddf85%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/8536854ddb96a2bf68155af8044ddf85.m3u8"


ffmpeg version 5.1.2-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, matroska,webm, from 'file:/mnt/cluster_storage/Videos/TVShows/English/the.expanse.2015/01/the.expanse.2015.s01e06.rock.bottom.webdl-2160p.HEVC.DTS-HD.MA.5.1-safety.mkv':
  Metadata:
    title           : The Expanse S01E06 Rock Bottom
    encoder         : libebml v1.3.10 + libmatroska v1.5.2
    creation_time   : 2020-04-30T11:06:55.000000Z
    TVDB            : 280619
    TMDB            : tv/63639
    track           : 1
    TOTAL_PARTS     : 10
    IMDB            : tt3983500
  Duration: 00:42:36.51, start: 0.000000, bitrate: 17908 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 103.186000
      Metadata:
        title           : 1. One good turn deserves another
    Chapter #0:1: start 103.186000, end 253.920000
      Metadata:
        title           : 2. The Rocinante docks at Tycho Station
    Chapter #0:2: start 253.920000, end 415.624000
      Metadata:
        title           : 3. Miller is roughed up by his captors
    Chapter #0:3: start 415.624000, end 532.866000
      Metadata:
        title           : 4. Two can play at that game
    Chapter #0:4: start 532.866000, end 676.050000
      Metadata:
        title           : 5. Anderson interrogates Miller
    Chapter #0:5: start 676.050000, end 908.032000
      Metadata:
        title           : 6. Diogo and Mateo run into some touble
    Chapter #0:6: start 908.032000, end 1352.434000
      Metadata:
        title           : 7. Betrayal
    Chapter #0:7: start 1352.434000, end 1577.826000
      Metadata:
        title           : 8. Amos gets hit on
    Chapter #0:8: start 1577.826000, end 1669.877000
      Metadata:
        title           : 9. Naomi rigs the fail-safe
    Chapter #0:9: start 1669.877000, end 1834.958000
      Metadata:
        title           : 10. A man's gotta stand up
    Chapter #0:10: start 1834.958000, end 2150.815000
      Metadata:
        title           : 11. Naomi and Holden toast to Shed, Miller gives Muss some sage advice
    Chapter #0:11: start 2150.815000, end 2241.906000
      Metadata:
        title           : 12. A proper christening
    Chapter #0:12: start 2241.906000, end 2494.742000
      Metadata:
        title           : 13. Miller presents his evidence to Shaddid, Holden and the others depart
    Chapter #0:13: start 2494.742000, end 2556.513000
      Metadata:
        title           : 14. End Credits
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS-eng         : 14580982
      DURATION-eng    : 00:42:36.513000000
      NUMBER_OF_FRAMES-eng: 61295
      NUMBER_OF_BYTES-eng: 4659559031
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-30 11:06:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: dts (DTS-HD MA), 48000 Hz, 5.1(side), s32p (24 bit) (default)
    Metadata:
      title           : DTS-HD MA 5.1
      BPS-eng         : 3376525
      DURATION-eng    : 00:41:56.595000000
      NUMBER_OF_FRAMES-eng: 235931
      NUMBER_OF_BYTES-eng: 1062168328
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-30 11:06:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: subrip
    Metadata:
      title           : English
      BPS-eng         : 66
      DURATION-eng    : 00:40:59.066000000
      NUMBER_OF_FRAMES-eng: 631
      NUMBER_OF_BYTES-eng: 20469
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-30 11:06:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(eng): Subtitle: subrip
    Metadata:
      title           : English (SDH)
      BPS-eng         : 68
      DURATION-eng    : 00:41:24.439000000
      NUMBER_OF_FRAMES-eng: 666
      NUMBER_OF_BYTES-eng: 21314
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-30 11:06:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(fre): Subtitle: subrip
    Metadata:
      title           : French
      BPS-eng         : 69
      DURATION-eng    : 00:40:59.082000000
      NUMBER_OF_FRAMES-eng: 552
      NUMBER_OF_BYTES-eng: 21497
      _STATISTICS_WRITING_APP-eng: mkvmerge v43.0.0 ('The Quartermaster') 64-bit
      _STATISTICS_WRITING_DATE_UTC-eng: 2020-04-30 11:06:55
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> h264 (h264_nvenc))
  Stream #0:1 -> #0:1 (dts (dca) -> dts (dca))
Press [q] to stop, [?] for help
Error initializing output stream 0:1 -- Error while opening encoder for output stream #0:1 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #9509: [Issue]: Server 10.8.9 crashing with stack trace when transcode w/ DTS-HD audio is requested by Android TV client.
### Please describe your bug

When attempting to play content with a DTS-HD audio track, if the Android TV client requests a transcode, the server will crash, providing a stack trace. See below for log snippet with relevant error. 

### Jellyfin Version

10.8.0

### if other:

_No response_

### Environment

```markdown
- OS: Linux
- Virtualization: None
- Clients: Android TV
- Browser: N/A
- FFmpeg Version: 5.1.2-Jellyfin
- Playback Method: Transcode
- Hardware Acceleration: QSV
- Plugins: N/A
- Reverse Proxy: Nginx
- Base URL: N/A
- Networking: Host
- Storage: cloud
```

### Jellyfin logs

```shell
[2023-03-16 22:28:44.110 -04:00] [ERR] Error processing request. URL "GET" "/videos/d0e3e164-aa95-3646-b6b7-12a789d0974f/master.m3u8".
System.InvalidOperationException: Nullable object must have a value.
   at MediaBrowser.Controller.MediaEncoding.EncodingHelper.CanStreamCopyAudio(EncodingJobInfo state, MediaStream audioStream, IEnumerable`1 supportedAudioCodecs)
   at MediaBrowser.Controller.MediaEncoding.EncodingHelper.TryStreamCopy(EncodingJobInfo state)
   at Jellyfin.Api.Helpers.StreamingHelpers.GetStreamingState(StreamingRequestDto streamingRequest, HttpRequest httpRequest, IAuthorizationContext authorizationContext, IMediaSourceManager mediaSourceManager, IUserManager userManager, ILibraryManager libraryManager, IServerConfigurationManager serverConfigurationManager, IMediaEncoder mediaEncoder, EncodingHelper encodingHelper, IDlnaManager dlnaManager, IDeviceManager deviceManager, TranscodingJobHelper transcodingJobHelper, TranscodingJobType transcodingJobType, CancellationToken cancellationToken)
   at Jellyfin.Api.Helpers.DynamicHlsHelper.GetMasterPlaylistInternal(StreamingRequestDto streamingRequest, Boolean isHeadRequest, Boolean enableAdaptiveBitrateStreaming, TranscodingJobType transcodingJobType, CancellationTokenSource cancellationTokenSource)
   at Jellyfin.Api.Helpers.DynamicHlsHelper.GetMasterHlsPlaylist(TranscodingJobType transcodingJobType, StreamingRequestDto streamingRequest, Boolean enableAdaptiveBitrateStreaming)
   at Jellyfin.Api.Controllers.DynamicHlsController.GetMasterHlsVideoPlaylist(Guid itemId, Nullable`1 static, String params, String tag, String deviceProfileId, String playSessionId, String segmentContainer, Nullable`1 segmentLength, Nullable`1 minSegments, String mediaSourceId, String deviceId, String audioCodec, Nullable`1 enableAutoStreamCopy, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, Nullable`1 breakOnNonKeyFrames, Nullable`1 audioSampleRate, Nullable`1 maxAudioBitDepth, Nullable`1 audioBitRate, Nullable`1 audioChannels, Nullable`1 maxAudioChannels, String profile, String level, Nullable`1 framerate, Nullable`1 maxFramerate, Nullable`1 copyTimestamps, Nullable`1 startTimeTicks, Nullable`1 width, Nullable`1 height, Nullable`1 maxWidth, Nullable`1 maxHeight, Nullable`1 videoBitRate, Nullable`1 subtitleStreamIndex, Nullable`1 subtitleMethod, Nullable`1 maxRefFrames, Nullable`1 maxVideoBitDepth, Nullable`1 requireAvc, Nullable`1 deInterlace, Nullable`1 requireNonAnamorphic, Nullable`1 transcodingMaxAudioChannels, Nullable`1 cpuCoreLimit, String liveStreamId, Nullable`1 enableMpegtsM2TsMode, String videoCodec, String subtitleCodec, String transcodeReasons, Nullable`1 audioStreamIndex, Nullable`1 videoStreamIndex, Nullable`1 context, Dictionary`2 streamOptions, Boolean enableAdaptiveBitrateStreaming)
   at lambda_method1995(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

### FFmpeg logs

```shell
No ffmpeg log was generated.
```

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Shadowghost**
**Changes**
* Rebase #8703 on master
* Add automatic DTS bitrate selection based on output channel count
* Calculate fallback bitrate based on output channel count
* Fix encoder check for DTS
* Add encoder check for TrueHD
* Add decoder check for DTS and TrueHD
* Fix condition check in `CanStreamCopyAudio`
* Enforce HLS audio and video codec restrictions on transcoding profiles

**Issues**
Fixes #9270
Fixes #9509
Supersedes #8703

### CODE REVIEW

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 1]
```diff
@@ -2111,56 +2116,117 @@ private static int ScaleBitrate(int bitrate, string inputVideoCodec, string outp
...
-            // Default audio bitrate to 128K if it is not being requested
+            // Default audio bitrate to 128K per channel if we don't have codec specific defaults
             // https://ffmpeg.org/ffmpeg-codecs.html#toc-Codec-Options
-            return 128000;
+            return 128000 * (outputAudioChannels ?? audioStream.Channels ?? 1);
+        }
+
+        public string GetAudioVbrModeParam(string encoder, int bitratePerChannel)
+        {
+            if (encoder == "libfdk_aac")
```
Comment (crobibero) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2193]:
```suggestion
            if (string.Equals(encoder, "libfdk_aac", StringComparison.OrdinalIgnoreCase))
```

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 2]
```diff
@@ -2111,56 +2116,117 @@ private static int ScaleBitrate(int bitrate, string inputVideoCodec, string outp
...
+                {
+                    < 32000 => "1",
+                    < 48000 => "2",
+                    < 64000 => "3",
+                    < 96000 => "4",
+                    _ => "5"
+                };
+            }
+
+            if (encoder == "libmp3lame")
```
Comment (crobibero) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2205]:
```suggestion
            if (string.Equals(encoder, "libmp3lame", StringComparison.Ordinal))
```

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 3]
```diff
@@ -2111,56 +2116,117 @@ private static int ScaleBitrate(int bitrate, string inputVideoCodec, string outp
...
+                {
+                    < 48000 => "8",
+                    < 64000 => "6",
+                    < 88000 => "4",
+                    < 112000 => "2",
+                    _ => "0"
+                };
+            }
+
+            if (encoder == "libvorbis")
```
Comment (crobibero) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2217]:
```suggestion
            if (string.Equals(encoder, "libvorbis", StringComparison.Ordinal))
```

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 4]
```diff
@@ -5822,13 +5896,22 @@ public string GetProgressiveAudioFullCommandLine(EncodingJobInfo state, Encoding
             var audioTranscodeParams = new List<string>();
 
             var bitrate = state.OutputAudioBitrate;
+            var channels = state.OutputAudioChannels;
 
             if (bitrate.HasValue)
             {
-                audioTranscodeParams.Add("-ab " + bitrate.Value.ToString(CultureInfo.InvariantCulture));
+                string vbrParam;
+                if (encodingOptions.EnableAudioVbr && (vbrParam = GetAudioVbrModeParam(state.OutputAudioCodec, bitrate.Value / channels ?? 2)) != null)
```
Comment (crobibero) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:5904]: same

File: MediaBrowser.Model/Dlna/StreamBuilder.cs [hunk 5]
```diff
@@ -834,6 +842,22 @@ private void BuildStreamVideoItem(StreamInfo playlistItem, MediaOptions options,
 
             // Prefer matching audio codecs, could do better here
             var audioCodecs = ContainerProfile.SplitValue(audioCodec);
+
+            // Enforce HLS audio codec restrictions
+            if (string.Equals(playlistItem.SubProtocol, "hls", StringComparison.OrdinalIgnoreCase))
+            {
+                var supportedHlsAudioCodecs = new List<string> { "aac", "ac3", "eac3", "mp3" };
```
Comment (crobibero) [inline MediaBrowser.Model/Dlna/StreamBuilder.cs:849]: this should be pulled out to be `static`

Create `supportedHlsAudioCodecs` and `supportedHlsAudioCodecsMp4`

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 6]
```diff
@@ -2111,56 +2116,117 @@ private static int ScaleBitrate(int bitrate, string inputVideoCodec, string outp
...
         {
             if (audioStream is null)
             {
                 return null;
             }
 
-            if (audioBitRate.HasValue && string.IsNullOrEmpty(audioCodec))
+            var inputChannels = audioStream.Channels ?? 0;
+            var outputChannels = outputAudioChannels ?? 0;
+            var bitrate = audioBitRate.HasValue ? audioBitRate.Value : int.MaxValue;
```
Comment (crobibero) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2133]:
```suggestion
            var bitrate = audioBitRate ?? int.MaxValue;
```

File: Jellyfin.Api/Controllers/DynamicHlsController.cs [hunk 7]
```diff
@@ -1685,14 +1685,25 @@ private string GetAudioArguments(StreamState state)
...
 
-            if (state.OutputAudioBitrate.HasValue)
+            var audioBitrate = state.OutputAudioBitrate;
+            var audioChannels = state.OutputAudioChannels;
+
+            if (audioBitrate.HasValue)
             {
-                audioTranscodeParams += " -ab " + state.OutputAudioBitrate.Value.ToString(CultureInfo.InvariantCulture);
+                string vbrParam;
+                if (_encodingOptions.EnableAudioVbr && (vbrParam = _encodingHelper.GetAudioVbrModeParam(state.OutputAudioCodec, audioBitrate.Value / audioChannels ?? 2)) != null)
```
[the remark this answers is not in the document]
Comment (crobibero) [reply Jellyfin.Api/Controllers/DynamicHlsController.cs:1694]: @Shadowghost in case you missed this comment

(also fix on L1762)

**Comment by holow29** [comment]
Does bitrate flag do anything for lossless codecs like TrueHD? My assumption was that passing -ab while encoding a lossless codec using ffmpeg does not actually affect output bitrate. Is it only for metadata purposes/bitrate restriction purposes?

**Comment by Shadowghost** [comment]
Do you have any source for that? I asked myself the same thing because a lossless codec should not require a bitrate (or even be able to set a bitrate)

**Comment by holow29** [comment]
I'm not sure about it. Could probably test by encoding a few things to FLAC, TrueHD, ALAC using different bitrate arguments and then comparing the outputs or raw PCM, but I'm not sure I'll have time. I don't think it really affects this PR as much anyway, but I thought someone might know better than I.

**Comment by nyanmisaka** [comment]
> @nyanmisaka is it reqired that `GetAudioBitrateParam` returns a bitrate for all codecs? I'm currently planning on excluding the `-ab` parameter for any lossless codecs but the function is also used to set the bitrate value in the HLS playlist.
> 
> If we need to return a value for all codecs we'll always have invalid bitrates for any lossless codec either by returning `null` or using the worst possible case (meaning we return something like `1152000 * channels` assuming that 24bit 48 kHz is a well enough refrence).

Can't we read the exact bitrate of lossless audio with ffprobe? If possible we can use it directly in the HLS playlist in audio streamCopy instead of using a dummy value.

**Review by Bond-009 — APPROVED** [review]
