### PR TITLE
Move NFO series season name parsing to own local provider

### LINKED ISSUE #11656: Jellyfin v10.9.1 isn't respecting the metadata lock for Season names in Show libraries causing custom season names to be lost.
**Describe The Bug**
For a Show library that contains series with seasons, you're allowed to manually overwrite the title names for each season. You can then lock the metadata for the name so that its title will not change upon a future scan. This is how it worked before v10.9.0.

However, since upgrading to v10.9.0 (and v10.9.1), Jellyfin doesn't respect the metadata lock for the season name/title. With v10.9, a rescan of any season will prompt the server to change the name of any season to be "Season x" where x is the season number in the metadata.

**Steps To Reproduce**
1. Go to a show that has at least one season.
2. Edit the season's metadata and change its title to be anything. After changing the name, make sure to scroll to the bottom of the metadata edit popup to lock the name. Either uncheck the "Name" box, or select the "Lock this item to prevent future changes" box.
3. Reload the client, then navigate to the same show to see your change to the season's name.
4. Refresh the metadata for the whole show (to capture the season(s) as well), and select the "Scan for new and updated files" option. You can also go to the dashboard and use the "Scan All Libraries" button to get this same result.
5. Wait a short while to let the scan do its work.
6. Reload the client again, then navigate to the same show. You'll notice the client changed the custom name you gave the season back to "Season x" despite you locking it.

**Expected Behavior**
Jellyfin should respect the metadata lock and not change any season's name if you set a custom name for the season.

**System (please complete the following information):**
 - Platform: Linux
 - Browser: Any
 - Jellyfin Version: v10.9.1

**Additional Context**
The names seem to be pulled from the .nfo files I have saved next to the media files. If the .nfo has a season number stored with it, doing the above will show the error as I describe. I found that if I remove the season number from the season's .nfo files, this bug doesn't happen.

### LINKED ISSUE #11706: [Issue]: Season names from NFOs are overridden by season metadata providers
### Please describe your bug

NFO season names do not have precedence over the ones coming from metadata providers

### Reproduction Steps

1. Enable any season metadata provider
2. Add `namedseason` entry to `tvshow.nfo`
3. Force refresh
Does not use season name from NFO

4. Disable allseason metadata providers
5. Force rescan series
6. Season name shows up

### Jellyfin Version

10.9.0

### if other:

10.9.2

### Environment

```markdown
- OS: Debian
- Linux Kernel: 6.6.13+bpo-amd64
- Virtualization: None
- Clients: -
- Browser: -
- FFmpeg Version: jellyfin-ffmpeg 6.0.1
- Playback Method: -
- Hardware Acceleration: -
- GPU Model: -
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Jellyfin logs

```shell
None since metadta matching is not logged
```

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #11709: [Issue]: Season names overwritten when scanning library
### Please describe your bug

It looks like this should have been fixed in #11647 but at least for me it's still broken. I have Jellyfin Server 10.9.2 and a Shows library, all metadata providers disabled and no updating from Internet allowed, with a directory structure admittedly not what's recommended for TV Shows. 

```
Topic 1
-- Sub-topic
-- Another sub-topic
Topic 2
-- Third Subtopic
```

For what I'm doing, "Season X" makes absolutely no sense, but there's nothing else that gives me this organization and works in Swiftfin. I could use Music Videos, if Swiftfin would allow me to use that library type, but it doesn't so I'm stuck with Shows. However, either way, I do expect that if I rename a season and select the option to lock it to prevent changes that it won't be reverted. But just now in 10.9.2 it's still reverting the names of the seasons to "Season Unknown" even when locked and when the desired name has been saved to the NFO file before scanning the library.

### Reproduction Steps

Environment: Jellyfin 10.9.2 (the version dropdown in GitHub doesn't show that as an option), Docker container, on Fedora 39.

1. Create a TV Shows library type
2. Disable all metadata options, save data to NFO, do not allow any updating from Internet
3. In the library, create a directory structure similar to what I described above. Add some video files so it gets scanned and appears in the library.
4. See all seasons are named "Season Unknown". I expect this since the directories are not following the recommended naming scheme.
5. Rename the seasons. Choose "Lock this item to prevent future changes".
6. Verify the NFO file has been updated with the new season name and that `lockdata` is set to `true`.
7. Rescan the library, either manually from the admin dashboard or wait for the next regularly scheduled full library scan.
8. See the seasons have all been changed to "Season Unknown", including in the NFO file, but they're all still locked.

### Jellyfin Version

10.9.0

### if other:

10.9.2

### Environment

```markdown
- OS: Fedora 39
- Linux Kernel: 6.8.9
- Virtualization: Docker
- Clients: Web, official Jellyfin app, official Swiftfin app
- Browser: Chrome, Vivaldi, Firefox, MS Edge
- FFmpeg Version: 6.0.1, as provided in the official Docker container
- Playback Method: Browser and official apps, but not relevant (this is not a playback issue)
- Hardware Acceleration: None
- GPU Model: N/A
- Plugins: LDAP auth
- Reverse Proxy: Caddy
- Base URL: https://media.jgoguen.ca
- Networking: Docker, host networking
- Storage: External disk
```

### Jellyfin logs

```shell
[2024-05-17 23:06:56.969 -04:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/music/Heilung/Lifa/05 Krigsgaldr.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:56.973 -04:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/music/Heilung/Futha/04 Traust.flac\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:56.977 -04:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/music/Heilung/Drif/01 Asja.flac\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:57.021 -04:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/music/Heilung/Futha/06 Svanrand.flac\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:57.026 -04:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/music/Heilung/Lifa/03 Alfadhirhaiti.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:57.033 -04:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/music/Heilung/Drif/02 Anoana.flac\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:57.074 -04:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/music/Heilung/Futha/02 Norupo.flac\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:57.138 -04:00] [INF] [8] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/2024-01-01_1563540364183747.MP4\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:57.167 -04:00] [INF] [21] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/music/Disturbed/Immortalized/11 - The Sound of Silence.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:57.173 -04:00] [INF] [31] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/music/Lilith Max/Birds of a Feather - Single/Birds of a Feather.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:57.183 -04:00] [INF] [31] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/music/Lilith Max/Peasants Throne - Single/Peasants Throne.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:57.189 -04:00] [INF] [21] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Satisfying/Laser Cleaning/2024-04-01_1405136000207234.MP4\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:57.281 -04:00] [INF] [8] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/2024-01-01_1563540364183747.MP4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:57.290 -04:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Animals/Foxes/Laughing Fox.MP4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:57.293 -04:00] [INF] [21] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Satisfying/Laser Cleaning/2024-04-01_1405136000207234.MP4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:57.407 -04:00] [INF] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Misc/Languages/2024-05-11_1875305612895714.MP4\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:57.551 -04:00] [INF] [21] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Animals/Foxes/Foxes Try To Make Cat Noises.mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:57.553 -04:00] [INF] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Misc/Languages/2024-05-11_1875305612895714.MP4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:57.561 -04:00] [INF] [31] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/Asteroid Apophis Will Come Close to Earth.mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:57.671 -04:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Satisfying/Laser Cleaning/2024-04-01_439573015215205.MP4\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:57.715 -04:00] [INF] [21] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Animals/Foxes/Juniper's 9th Birthday.mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:57.725 -04:00] [INF] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Misc/Random Thoughts/Random Thoughts 1.mp4\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:57.754 -04:00] [INF] [32] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Misc/Random Thoughts/Random Thoughts 1.mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:57.787 -04:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Satisfying/Laser Cleaning/2024-04-01_439573015215205.MP4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:57.801 -04:00] [INF] [19] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/Galaxies Orbit the Milky Way.mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:57.896 -04:00] [INF] [19] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Satisfying/Laser Cleaning/2024-03-27_346693611596634.MP4\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:57.937 -04:00] [INF] [21] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Animals/Foxes/@fox_.lovers 2024-05-10__212501.MP4\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:57.991 -04:00] [INF] [21] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Animals/Foxes/@fox_.lovers 2024-05-10__212501.MP4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:57.996 -04:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/2024-03-28_940232507413961.MP4\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:58.018 -04:00] [INF] [19] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Satisfying/Laser Cleaning/2024-03-27_346693611596634.MP4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:58.127 -04:00] [INF] [19] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Animals/Foxes/Kiki Wants Belly Rubs.mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:58.145 -04:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/2024-03-28_940232507413961.MP4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:58.169 -04:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Comedy/Abbott and Costello/Abbott and Costello - Who's on First.mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:58.302 -04:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/Can we colonize Titan.mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:58.343 -04:00] [INF] [20] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Comedy/Abbott and Costello/Abbott and Costello - Volts are Watts.MP4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:58.353 -04:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/2024-03-13_1112809216408846.MP4\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:58.433 -04:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/2024-03-13_1112809216408846.MP4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:58.473 -04:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/Dwarf Planet With Impossible Rings.mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:58.529 -04:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/2023-12-28_1472261906665349.MP4\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:58.581 -04:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/2023-12-28_1472261906665349.MP4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:58.628 -04:00] [INF] [21] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/2024-04-10_412391298081278.MP4\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:58.679 -04:00] [INF] [21] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/2024-04-10_412391298081278.MP4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:58.715 -04:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/2024-04-29_768042008764641.MP4\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:58.789 -04:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/2024-04-29_768042008764641.MP4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:58.827 -04:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/2024-01-24_402045042279149.MP4\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:58.895 -04:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/2024-01-24_402045042279149.MP4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:58.930 -04:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/4 Crazy Science Facts 1.mp4\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:58.979 -04:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/4 Crazy Science Facts 1.mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:59.044 -04:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Space/JWST Images Titan.mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:59.106 -04:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Physics/Antimatter.mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:59.147 -04:00] [INF] [10] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Physics/Statue of Liberty Gets Hit by Lightning Lots.mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:59.192 -04:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Physics/Demonstration of Gravity in Pure Form.mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:59.229 -04:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Physics/2024-05-09_1626770754530415.MP4\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:59.270 -04:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Physics/2024-05-09_1626770754530415.MP4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:59.300 -04:00] [INF] [21] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Physics/Teleportation is kinda horriffic.mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:59.338 -04:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Earth Science/Why Not Solar Panels in Sahara.mp4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-05-17 23:06:59.377 -04:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Earth Science/2024-02-15_1613971456079379.MP4\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-17 23:06:59.431 -04:00] [INF] [18] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/media/interesting_clips/Science/Earth Science/2024-02-15_1613971456079379.MP4\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
```
```


### FFmpeg logs

```shell
N/A
```

### Please attach any browser or client logs here

N/A

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Shadowghost**
Removes all the hackery around season name parsing on series level and moves it to a dedicated NFO reader. This should prevent any conflicts with actual season metadata providers.

Additionally, we now set the path for season folders if the folder was recognized as season folder. This allows proper updating of local season metadata because the logic depends on a media type check which will always fail without a path.

**Changes**
* Move NFO series season name parsing to own local provider
* Set the path for season folders

**Issues**
Fixes #11706
Fixes #11656
Fixes #11709 (potentially)

### CODE REVIEW

File: MediaBrowser.XbmcMetadata/Parsers/SeriesNfoParser.cs [hunk 1]
```diff
@@ -100,19 +100,8 @@ protected override void FetchDataFromXmlNode(XmlReader reader, MetadataResult<Se
                         break;
                     }
 
+                // Season names are processed by SeasonFromSeriesNfoParser
                 case "namedseason":
-                    {
```
Comment (revam) [inline MediaBrowser.XbmcMetadata/Parsers/SeriesNfoParser.cs:104]: maybe add a `break` here so it doesn't re-check the key inside the base parser?
```suggestion
                case "namedseason":
                    break;
```

**Comment by revam** [comment]
Also, can confirm it works as expected during local testing conducted with @Shadowghost.

File: MediaBrowser.XbmcMetadata/Providers/SeasonFromSeriesNfoProvider.cs [hunk 2]
```diff
@@ -63,6 +63,16 @@ protected override void Fetch(MetadataResult<Season> result, string path, Cancel
         /// <inheritdoc />
         protected override FileSystemMetadata? GetXmlFile(ItemInfo info, IDirectoryService directoryService)
         {
+            var seasonPath = info.Path;
+            if (seasonPath is not null)
+            {
+                var path = Path.Combine(seasonPath, "tvshow.nfo");
```
Comment (revam) [inline MediaBrowser.XbmcMetadata/Providers/SeasonFromSeriesNfoProvider.cs:69]: isn't the season nfo file named differently?

Comment (revam) [reply MediaBrowser.XbmcMetadata/Providers/SeasonFromSeriesNfoProvider.cs:69]: also, will this interfere with the normal season nfo parsing? or will the other season parser work independently from this parser?

Comment (Shadowghost) [reply MediaBrowser.XbmcMetadata/Providers/SeasonFromSeriesNfoProvider.cs]: Season NFOs have their own provider and are parsed separately. I checked it and apparently we the returned list is sorted alphabetically, so I renamed the new provider to be run after the existing season provider.

**Review by crobibero — APPROVED** [review]

File: MediaBrowser.XbmcMetadata/Parsers/SeriesNfoSeasonParser.cs [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+        /// <param name="userManager">Instance of the <see cref="IUserManager"/> interface.</param>
+        /// <param name="userDataManager">Instance of the <see cref="IUserDataManager"/> interface.</param>
+        /// <param name="directoryService">Instance of the <see cref="IDirectoryService"/> interface.</param>
+        public SeriesNfoSeasonParser(
+            ILogger logger,
+            IConfigurationManager config,
+            IProviderManager providerManager,
+            IUserManager userManager,
+            IUserDataManager userDataManager,
+            IDirectoryService directoryService)
```
Comment (cvium) [inline MediaBrowser.XbmcMetadata/Parsers/SeriesNfoSeasonParser.cs:31]: I really dislike the NfoParsers having so many dependencies. They are doing way too much.

File: MediaBrowser.XbmcMetadata/Providers/SeriesNfoSeasonProvider.cs [hunk 4]
```diff
@@ -0,0 +1,89 @@
...
+        protected override void Fetch(MetadataResult<Season> result, string path, CancellationToken cancellationToken)
+        {
+            new SeriesNfoSeasonParser(_logger, _config, _providerManager, _userManager, _userDataManager, _directoryService).Fetch(result, path, cancellationToken);
+        }
+
+        /// <inheritdoc />
+        protected override FileSystemMetadata? GetXmlFile(ItemInfo info, IDirectoryService directoryService)
+        {
+            var seasonPath = info.Path;
+            if (seasonPath is not null)
```
Comment (cvium) [inline MediaBrowser.XbmcMetadata/Providers/SeriesNfoSeasonProvider.cs:67]: It's fine if they are empty?

**Review by cvium — APPROVED** [review]

File: MediaBrowser.XbmcMetadata/Providers/SeriesNfoSeasonProvider.cs [hunk 5]
```diff
@@ -0,0 +1,89 @@
...
+            {
+                var path = Path.Combine(seasonPath, "tvshow.nfo");
```
Comment (cvium) [inline MediaBrowser.XbmcMetadata/Providers/SeriesNfoSeasonProvider.cs:69]: Kodi doesn't seem to allow tvshow.nfo in the season folder. I kind of prefer doing it like that as well to simplify it.

Comment (Shadowghost) [reply MediaBrowser.XbmcMetadata/Providers/SeriesNfoSeasonProvider.cs:69]: Season path can also be the series folder if the season hasn't their own folder. Though this would also be caught by the next check.
Without having a season path set, you can't refresh metadata from a season though.

File: MediaBrowser.XbmcMetadata/Parsers/SeriesNfoSeasonParser.cs (hunk 3 above)
Comment (Shadowghost) [reply MediaBrowser.XbmcMetadata/Parsers/SeriesNfoSeasonParser.cs:31]: Mainly caused by the base NFO parser - but we should be able to slim it down (not here ofc).

File: Emby.Server.Implementations/Library/Resolvers/TV/SeasonResolver.cs [hunk 6]
```diff
@@ -54,7 +54,8 @@ protected override Season Resolve(ItemResolveArgs args)
                 {
                     IndexNumber = seasonParserResult.SeasonNumber,
                     SeriesId = series.Id,
-                    SeriesName = series.Name
+                    SeriesName = series.Name,
+                    Path = seasonParserResult.IsSeasonFolder ? path : args.Parent.Path
```
Comment (nielsvanvelzen) [inline Emby.Server.Implementations/Library/Resolvers/TV/SeasonResolver.cs:58]: This line is causing issues for folder structures with season names. E.g. `/Drive/Show/Season 3 - Season Name` will end up with `isSeasonDirectory=false`. In 10.9.3<= this worked perfectly fine, now is uses the series path causing all episodes to merge into the last season.

You can add `[InlineData("/Drive/Show/Season 3 - Season Name", 3, true)]` to the SeasonFolderTests to reproduce the issue.
