### PR TITLE
Sort trailers before teasers 

### LINKED ISSUE #14712: Trailers for movies pulls teasers before trailers from TMDB
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our [forum or chat rooms](https://jellyfin.org/contact/) first to troubleshoot with volunteers, before creating a report.
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

This has been reported on several help forums but I have never actually seen a formal report for this.
It appears that the TMDB metadata pulled for a movie will use the teasers links rather than the trailers links.

The following is an example:
Jellyfin Server 10.10.7 docker image
Web client, Firefox 134.0.2 (64-bit)
Navigate to a Movie page (ie http://192.168.0.2:8096/web/#/details?id=...)
When you press the trailer button on the movie page for this film on Jellyfin, you get one of the 6 teasers from 

https://www.themoviedb.org/movie/1239655-friendship/videos?active_nav_item=Teasers&language=en-US 

instead of the 1 trailer from 

https://www.themoviedb.org/movie/1239655-friendship/videos?active_nav_item=Trailers&language=en-US

Users should expect the trailer, which should happen since it is after all a trailer button and not a teaser button. 

Either the metadata parsing needs to be updated or there needs to be a configuration option added.

### Reproduction steps

Navigate to a Movie page (ie http://192.168.0.2:8096/web/#/details?id=...)
Press the trailer button in the upper right.

### What is the current _bug_ behavior?

When you press the trailer button on the movie page, you get the teasers, followed by the trailers

### What is the expected _correct_ behavior?

When you press the trailer button on the movie page, you get the trailers, followed by the teasers if the youtube player isnt closed

### Jellyfin Server version

10.10.0+

### Specify commit id

_No response_

### Specify unstable release number

_No response_

### Specify version number

10.10.7

### Specify the build version

docker

### Environment

```markdown
- OS: Ubuntu Server 24.04
- Linux Kernel: 6.8.0-64-generic
- Virtualization: Docker
- Clients: Web
- Browser: Firefox 134.0.2 (64-bit)
- FFmpeg Version: 6.1.1-3ubuntu5+esm3
- Playback Method: NA
- Hardware Acceleration: Yes
- GPU Model: Intel Arc
- Plugins: 
- Reverse Proxy:
- Base URL:
- Networking:
- Jellyfin Data Storage:
- Media Storage:
- External Integrations:
```

### Jellyfin logs

```shell
[2025-08-27 03:02:20.259 +00:00] [INF] No libraries selected for analysis. To enable, check library configuration > Media Segment Providers.
[2025-08-27 03:13:50.525 +00:00] [ERR] InPlayerEpisodePreviewPlugin: "Namo.Plugin.InPlayerEpisodePreview.Web.InPlayerPreview.js"
[2025-08-27 03:13:51.124 +00:00] [INF] WS "192.168.0.235" request
[2025-08-27 03:13:57.640 +00:00] [INF] WS "192.168.0.235" closed
[2025-08-27 03:16:31.370 +00:00] [ERR] Object Disposed
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at MediaBrowser.Controller.Net.BasePeriodicWebSocketListener`2.DisposeConnection(ValueTuple`3 connection)
[2025-08-27 03:16:46.763 +00:00] [INF] WS "192.168.0.235" closed
[2025-08-27 03:16:46.925 +00:00] [ERR] InPlayerEpisodePreviewPlugin: "Namo.Plugin.InPlayerEpisodePreview.Web.InPlayerPreview.js"
[2025-08-27 03:16:47.372 +00:00] [INF] WS "192.168.0.235" request
[2025-08-27 03:16:50.950 +00:00] [WRN] PlaybackStart reported with null media info.
[2025-08-27 03:16:54.137 +00:00] [WRN] PlaybackStopped reported with null media info.
[2025-08-27 03:16:54.137 +00:00] [INF] Playback stop did not have a tracker : "TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjoxMzQuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC8xMzQuMHwxNzQxMzcxMDIxNjcy-8bc0531070904dc78952fa2831768f4b-"
[2025-08-27 03:16:55.688 +00:00] [WRN] PlaybackStart reported with null media info.
[2025-08-27 03:17:12.534 +00:00] [INF] WS "192.168.0.235" closed
[2025-08-27 03:17:12.670 +00:00] [ERR] InPlayerEpisodePreviewPlugin: "Namo.Plugin.InPlayerEpisodePreview.Web.InPlayerPreview.js"
[2025-08-27 03:17:13.223 +00:00] [INF] WS "192.168.0.235" request
```

### FFmpeg logs

```shell

```

### Client / Browser logs

_No response_

### Relevant screenshots or videos

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by theguymadmax**
**Changes**
Sort trailers to be played before teasers 

**Issues**
Fixes #14712

### CODE REVIEW

**Review by Shadowghost — APPROVED** [review]

File: MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs [hunk 1]
```diff
@@ -340,9 +340,14 @@ public async Task<MetadataResult<Movie>> GetMetadata(MovieInfo info, Cancellatio
             if (movieResult.Videos?.Results is not null)
             {
                 var trailers = new List<MediaUrl>();
-                for (var i = 0; i < movieResult.Videos.Results.Count; i++)
+
+                var sortedVideos = movieResult.Videos.Results
+                    .OrderByDescending(video => string.Equals(video.Type, "trailer", StringComparison.OrdinalIgnoreCase))
+                    .ToList();
```
Comment (Bond-009) [inline MediaBrowser.Providers/Plugins/Tmdb/Movies/TmdbMovieProvider.cs]: No need for ToList, right? Just use foreach on the enumerable directly.
