### PR TITLE
Fix TMDb search name containing year

### LINKED ISSUE #5161: [10.7.0 RC3] Not able to fetch Shows metadata because of an issue with images fetching (I suppose ?)
**Describe the bug**
Jellyfin is not able to fetch Shows metadata, at least from TheMovieDB (no details nor images).

https://i.imgur.com/HKBs1oe.png

**System (please complete the following information):**
 - OS: Windows Server 2019
 - Virtualization: Hyper-V VM
 - Clients: na
 - Browser: na
 - Jellyfin Version: 10.7.0 RC3
 - Playback: na
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: na
 - Storage: local

**Expected behavior**
Correct metadata fetching from TheMovieDB, data and images (right now having none).

**Logs**
Only a piece since all lines are identical for all Shows.

```
[09:20:31] [ERR] [78] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at J:\Séries\Altered Carbon (2018)
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[09:20:33] [ERR] [78] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at J:\Séries\Black Mirror (2011)
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[09:20:33] [ERR] [22] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at J:\Séries\The Mandalorian (2019)
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[09:20:35] [ERR] [78] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at J:\Séries\Stranger Things (2016)
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[09:20:35] [ERR] [22] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at J:\Séries\Umbrella Academy (2019)
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[09:20:36] [ERR] [22] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at J:\Séries\Rick and Morty (2013)
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[09:20:37] [ERR] [22] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at J:\Séries\She-Ra and the Princesses of Power (2018)
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
[09:20:39] [ERR] [22] MediaBrowser.Providers.Manager.ProviderManager: TmdbSeriesImageProvider failed in GetImageInfos for type Series at J:\Séries\BoJack Horseman (2014)
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, IReadOnlyCollection`1 preferredLanguages, CancellationToken cancellationToken, Nullable`1 type)
```

**EDIT 1:** After unchecking all fetch images options for my Show library, Jellyfin is now able to fetch Shows detailds and metadata, without images so.

**EDIT 2:** After numerous testings, I came to a conclusion: the issue happens ONLY if the library DOESN'T have yet images or metadata AT ALL. When I started to add manually metadata and then retried to fetch auto metadata, it finally worked for everything. And the issue is only on TheMovieDB fetcher.

### PR DESCRIPTION
**Pull request by Ullmie02**
**Changes**

**Issues**
Fixes #5161

### CODE REVIEW

File: MediaBrowser.Providers/Plugins/Tmdb/TmdbClientManager.cs [hunk 1]
```diff
@@ -279,8 +279,9 @@ public async Task<Person> GetPersonAsync(int personTmdbId, CancellationToken can
         /// <param name="name">The name of the tv show.</param>
         /// <param name="language">The tv show's language.</param>
         /// <param name="cancellationToken">The cancellation token.</param>
+        /// <param name="year">The year the tv show first aired.</param>
         /// <returns>The TMDb tv show information.</returns>
-        public async Task<IReadOnlyList<SearchTv>> SearchSeriesAsync(string name, string language, CancellationToken cancellationToken)
+        public async Task<IReadOnlyList<SearchTv>> SearchSeriesAsync(string name, string language, CancellationToken cancellationToken, int year = 0)
```
Comment (Bond-009) [inline MediaBrowser.Providers/Plugins/Tmdb/TmdbClientManager.cs:284]: cancellationToken should be the last parameter

**Review by Bond-009 — CHANGES_REQUESTED** [review]

**Review by cvium — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]
