### PR TITLE
Set Parent to current query Item if ParentId is empty

### LINKED ISSUE #673: Item Count is Incorrect/Track Count is Incorrect
**Describe the bug**
When viewing an album in the music library, a track count is displayed. Currently, this track count is not how many tracks are in the album, but rather a total count of _all items in your library_, even if they are video.

**To Reproduce**
1. Add Music to your Library (if not already there)
2. Go to the Music view, click on an artist, then album
3. Observe that the track count is larger than the actual album track count

**Expected behavior**
The track count should be the correct number of tracks for the displayed album.

**Logs**
None at the moment.

**Screenshots**
Will add later.

**System (please complete the following information):**
 - OS: Debian, macOS
 - Browser: Safari, Chrome, Firefox (all are affected)
 - Jellyfin Version: 10.0.1, 10.0.2, 10.1.0 (pre-release)

**Additional context**
This issue is similar to #536, where an empty collection/library is created, and this is populated with a total item count as "unwatched items".

### PR DESCRIPTION
**Pull request by cvium**
**Changes**
Fixed a faulty change in logic that occurred during the Christmas GPL nightmare.

I stepped through Emby 3.5.2 and stumbled over a difference in the query between Jellyfin and Emby, where in Emby, query.ParentId was set to the item itself. So I did a little digging in the old GPLv2 source and found this https://github.com/MediaBrowser/Emby/blob/3.4.1.8/MediaBrowser.Controller/Entities/Folder.cs#L720

**Issues**
Fixes #673

### CODE REVIEW

File: MediaBrowser.Controller/Entities/Folder.cs [hunk 1]
```diff
@@ -644,12 +644,9 @@ public QueryResult<BaseItem> QueryRecursive(InternalItemsQuery query)
                 return PostFilterAndSort(items, query, true);
             }
 
-            if (!(this is UserRootFolder) && !(this is AggregateFolder))
+            if (!(this is UserRootFolder) && !(this is AggregateFolder) && query.ParentId.Equals(Guid.Empty))
```
Comment (JustAMan) [inline MediaBrowser.Controller/Entities/Folder.cs]: If C# allows `==` for `Guid`s, maybe do
```suggestion
            if (!(this is UserRootFolder) && !(this is AggregateFolder) && query.ParentId == Guid.Empty)
```
