### PR TITLE
Fixed SMI Encoding Bug

### LINKED ISSUE #1539: SMI Subtitles does not work
**Describe the bug**
A *.smi subtitle (SAMI Subtitle) doesn't appear with video.
Here is an example of sami subtitle. [Link](https://drive.google.com/file/d/1jVhzgMlC9EhWm9QOeqk0iUuW_DJOX_3v)

**To Reproduce**
1. Upload video with *.smi Subtitle.
2. Watch the video
3. The subtitle doesn't appear and there's a ffmpeg error in log

**Expected behavior**
The subtitle should appear.

**Logs**
```
Jul 14 20:21:53 ubuntu jellyfin[29088]: [sami @ 0xaaaad79e65f0] UTF16 is automatically converted to UTF8, do not specify a character encoding
Jul 14 20:21:53 ubuntu jellyfin[29088]: Input #0, sami, from '/media/hdd1/cloud/ubuntu/files/공용 파일/1. 애니/2. ㅂ-ㅊ/일주일간 프렌드/[Leopard-Raws] Isshuukan Friends. - 01 RAW (MX 1280x720 x264 AAC).smi':
Jul 14 20:21:53 ubuntu jellyfin[29088]:   Duration: N/A, bitrate: N/A
Jul 14 20:21:53 ubuntu jellyfin[29088]:     Stream #0:0: Subtitle: sami
Jul 14 20:21:53 ubuntu jellyfin[29088]: Output #0, srt, to '/var/lib/jellyfin/data/subtitles/4/4b314b0c-e7f0-efa7-1e69-65443f1ff0a2.srt':
Jul 14 20:21:53 ubuntu jellyfin[29088]:   Metadata:
Jul 14 20:21:53 ubuntu jellyfin[29088]:     encoder         : Lavf58.12.100
Jul 14 20:21:53 ubuntu jellyfin[29088]:     Stream #0:0: Subtitle: subrip (srt)
Jul 14 20:21:53 ubuntu jellyfin[29088]:     Metadata:
Jul 14 20:21:53 ubuntu jellyfin[29088]:       encoder         : Lavc58.18.100 srt
Jul 14 20:21:53 ubuntu jellyfin[29088]: Stream mapping:
Jul 14 20:21:53 ubuntu jellyfin[29088]:   Stream #0:0 -> #0:0 (sami (native) -> subrip (srt))
Jul 14 20:21:53 ubuntu jellyfin[29088]: Press [q] to stop, [?] for help
Jul 14 20:21:53 ubuntu jellyfin[29088]: [sami @ 0xaaaad7a0f1f0] Unable to recode subtitle event "<Sync Start=8039><P Class=KRCC>
```

**System (please complete the following information):**
 - OS: Ubuntu 18.04 LTS on RPi3
 - Browser: Chrome
 - Jellyfin Version: 10.3.6
 - Reverse proxy: no

### PR DESCRIPTION
**Pull request by HelloWorld017**
**Changes**
* Disabled `-sub_charenc` flag for `*.smi` and `*.sami` subtitles when it is determined as UTF-16.

If we specify character encoding to sami subtitles, FFmpeg rejects it with "do not specify a character encoding" and "Unable to recode subtitle event" error.

It is because ffmpeg converts UTF-16 into UTF-8 in `ff_text_r8`. `ff_text_r8` is called from `ff_text_read` and `samidec.c` uses `ff_text_read`.

When I tested with UTF-16LE, UTF-16BE, CP949, UTF-8 the FFmpeg automatically did the conversion without the `-sub_charenc` flag.

**Issues**
Fixes #1539

### CODE REVIEW

File: MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs [hunk 1]
```diff
@@ -425,7 +425,13 @@ private async Task ConvertTextSubtitleToSrtInternal(string inputPath, string lan
 
             var encodingParam = await GetSubtitleFileCharacterSet(inputPath, language, inputProtocol, cancellationToken).ConfigureAwait(false);
 
-            if (!string.IsNullOrEmpty(encodingParam))
+            // FFmpeg automatically convert character encoding when it is UTF-16
+            // If we specify character encoding, it rejects with "do not specify a character encoding" and "Unable to recode subtitle event"
+            if ((inputPath.EndsWith(".smi") || inputPath.EndsWith(".sami")) && (encodingParam == "UTF-16BE" || encodingParam == "UTF-16LE"))
```
Comment (EraYaN) [inline MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs]: Might be worth it to link to the issue #1539 in this comment, so when someone later sees this hack they know not to touch it. Not sure how @jellyfin/core feels about that?

Comment (HelloWorld017) [reply MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs]: Would it better to add a new commit or force-push after amending, to make issue number in comments?

Comment (dkanada) [reply MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs]: I think it would be fine without tagging the issue. Does this change make sense for any subtitle format or only those two?

Comment (HelloWorld017) [reply MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs]: Actually, the srt subtitles are affected when I see the code of ffmpeg and tested with ffmpeg. 
But srt subtitles aren't converted to srt (as it is already srt), so in jellyfin, it works.  
So I didn't added srt to the extensions list.
