### PR TITLE
Fix subtitle saving if file already exists

### LINKED ISSUE #10696: Downloading 2 subtitle files of the same language throws an exception "already exists"
**Steps to reproduce:**

1. Download a subtitle file
2. Download another subtitle file of the same language
3. They will both try to be saved as the same filename, this throws an error:

```
<first download, this one is successful>
jellyfin  | [22:19:35] [INF] [9] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: Remaining downloads: 990
jellyfin  | [22:19:35] [INF] [27] MediaBrowser.Providers.Subtitles.SubtitleManager: Saving subtitles to /media/Films/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA[TGx]/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt

<second download of a different file, it saves it to the same name:>
jellyfin  | [22:20:00] [INF] [9] Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader: Remaining downloads: 989
jellyfin  | [22:20:00] [INF] [7] MediaBrowser.Providers.Subtitles.SubtitleManager: Saving subtitles to /media/Films/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA[TGx]/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt
jellyfin  | [22:20:00] [INF] [7] MediaBrowser.Providers.Subtitles.SubtitleManager: Saving subtitles to /config/data/metadata/library/74/740d4a178cfb9617569a81266cdba99d/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt
jellyfin  | [22:20:00] [ERR] [7] Jellyfin.Api.Controllers.SubtitleController: Error downloading subtitles
jellyfin  | System.AggregateException: One or more errors occurred. (The file '/media/Films/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA[TGx]/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt' already exists.) (The file '/config/data/metadata/library/74/740d4a178cfb9617569a81266cdba99d/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt' already exists.)
jellyfin  |  ---> System.IO.IOException: The file '/media/Films/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA[TGx]/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt' already exists.
jellyfin  |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
jellyfin  |    at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
jellyfin  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
jellyfin  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin  |    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin  |    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
jellyfin  |    at System.IO.FileStream..ctor(String path, FileStreamOptions options)
jellyfin  |    at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveToFiles(Stream stream, List`1 savePaths)
jellyfin  |    --- End of inner exception stack trace ---
jellyfin  |    at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveToFiles(Stream stream, List`1 savePaths)
jellyfin  |    at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveSubtitle(Video video, LibraryOptions libraryOptions, SubtitleResponse response)
jellyfin  |    at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveSubtitle(Video video, LibraryOptions libraryOptions, SubtitleResponse response)
jellyfin  |    at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveSubtitle(Video video, LibraryOptions libraryOptions, SubtitleResponse response)
jellyfin  |    at MediaBrowser.Providers.Subtitles.SubtitleManager.DownloadSubtitles(Video video, LibraryOptions libraryOptions, String subtitleId, CancellationToken cancellationToken)
jellyfin  |    at Jellyfin.Api.Controllers.SubtitleController.DownloadRemoteSubtitles(Guid itemId, String subtitleId)
jellyfin  |  ---> (Inner Exception jellyfin/jellyfin-plugin-opensubtitles#1) System.IO.IOException: The file '/config/data/metadata/library/74/740d4a178cfb9617569a81266cdba99d/Equilibrium.2002.1080p.BluRay.H264.AAC-LAMA.eng.srt' already exists.
jellyfin  |    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
jellyfin  |    at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
jellyfin  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
jellyfin  |    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin  |    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
jellyfin  |    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
jellyfin  |    at System.IO.FileStream..ctor(String path, FileStreamOptions options)
jellyfin  |    at MediaBrowser.Providers.Subtitles.SubtitleManager.TrySaveToFiles(Stream stream, List`1 savePaths)<---
```

**Expected behavior:** 
The 2nd subtitle file should also be downloaded, but be saved with something like `<mediafile-name>.<language>.<number>.srt` as the filename.

**Setup:**
Running in docker:

```
version: '3.5'
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
      - "8920:8920"
    networks:
      - proxy
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /media/pi/Elements:/media
    restart: 'unless-stopped'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Brussels
    mem_limit: 1200M
    memswap_limit: 512M
  
  caddy:
    image: caddy
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - "proxy"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

networks:
  proxy:
    driver: bridge

volumes: # these lines are necessary for creating the volumes
  jellyfin-config:
  jellyfin-cache:
  caddy_data:
  caddy_config:
```

### PR DESCRIPTION
**Pull request by Shadowghost**
Subs currently fail to download if another subtitle with the same name (usually previously downloaded) exists. This change now modifies the saving filename before saving so it does not fail anymore.

**Issues**
Fixes #10696

### CODE REVIEW

File: MediaBrowser.Providers/Subtitles/SubtitleManager.cs [hunk 1]
```diff
@@ -251,7 +249,7 @@ private async Task TrySaveToFiles(Stream stream, List<string> savePaths)
                     Directory.CreateDirectory(Path.GetDirectoryName(savePath) ?? throw new InvalidOperationException("Path can't be a root directory."));
 
                     var fileOptions = AsyncFile.WriteOptions;
-                    fileOptions.Mode = FileMode.CreateNew;
+                    fileOptions.Mode = FileMode.Create;
```
Comment (zjeffer) [inline MediaBrowser.Providers/Subtitles/SubtitleManager.cs:252]: I'm not very experienced with C#, but according to [the docs](https://learn.microsoft.com/en-us/dotnet/api/system.io.filemode?view=net-8.0#fields), `FileMode.Create` means "If the file already exists, it will be overwritten". 
Is this what we want? 

If I remember correctly, a long time ago downloading multiple subtitles of the same language would create multiple files, in the format of `<subtitle-name>.<lang>.<number>.srt` (e.g. MovieTitle.en.1.srt). I liked this solution as it meant it was easy to test multiple subtitles of the same language without exiting out of the player to download another subtitle. After testing, I can then simply only keep the one that works best.

**Review by zjeffer — CHANGES_REQUESTED** [review]

File: MediaBrowser.Providers/Subtitles/SubtitleManager.cs (hunk 1 above)
Comment (zjeffer) [reply MediaBrowser.Providers/Subtitles/SubtitleManager.cs:252]: I just read the PR title and description again and realize now that you already mention this :laughing: 

I would personally prefer the alternative approach of appending a number if the file already exists.

File: MediaBrowser.Providers/Subtitles/SubtitleManager.cs [hunk 2]
```diff
@@ -48,9 +48,7 @@ public class SubtitleManager : ISubtitleManager
             _monitor = monitor;
             _mediaSourceManager = mediaSourceManager;
             _localization = localizationManager;
-            _subtitleProviders = subtitleProviders
-                .OrderBy(i => i is IHasOrder hasOrder ? hasOrder.Order : 0)
-                .ToArray();
+            _subtitleProviders = [.. subtitleProviders.OrderBy(i => i is IHasOrder hasOrder ? hasOrder.Order : 0)];
```
Comment (Bond-009) [inline MediaBrowser.Providers/Subtitles/SubtitleManager.cs:51]: Keep the `ToArray`
https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABATARgLABQGADAAQY4oDchJ5OAdADICWAdgI41EDM5WpAMKkA3oVITyfCsQDaAXVIBZABSsAzgBcAPDIB8pTQEpR4yeYwB2UrIYNNDAOoALGLBUJSAXgMIGgiDZNAEN2dRUAIk0YLQijI3lucwBfM3N0jMyJNIxpHDlFJSw1Fi1dfINjUwIsq0MnV3dPH1I/AKDQtnComM04owYAFQgAQSgoYIBPFSMkyVSCZKA==

**Review by Bond-009 — CHANGES_REQUESTED** [review]

File: MediaBrowser.Providers/Subtitles/SubtitleManager.cs [hunk 3]
```diff
@@ -236,24 +234,34 @@ await using (stream.ConfigureAwait(false))
...
         {
             List<Exception>? exs = null;
 
             foreach (var savePath in savePaths)
             {
-                _logger.LogInformation("Saving subtitles to {SavePath}", savePath);
-
-                _monitor.ReportFileSystemChangeBeginning(savePath);
-
+                var path = savePath;
```
Comment (Bond-009) [inline MediaBrowser.Providers/Subtitles/SubtitleManager.cs:243]: This needs the extension, right?

**Review by Bond-009 — CHANGES_REQUESTED** [review]

File: MediaBrowser.Providers/Subtitles/SubtitleManager.cs [hunk 4]
```diff
@@ -205,72 +205,71 @@ await using (stream.ConfigureAwait(false))
...
+                    var counter = 0;
+
+                    while (fileExists)
+                    {
+                        counter++;
+                        path = string.Format(CultureInfo.InvariantCulture, "{0}.{1}.{2}", savePath, counter, extension);
+                        fileExists = File.Exists(path);
+                    }
+
+                    if (path.StartsWith(video.ContainingFolderPath, StringComparison.Ordinal)
```
Comment (cvium) [inline MediaBrowser.Providers/Subtitles/SubtitleManager.cs:241]: There's no reason to check for file existence if the path is invalid

**Review by cvium — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]

**Comment by zjeffer** [comment]
@Shadowghost Thank you for this!
