### PR TITLE
Fix: parsing of xbmc style multi episode nfo files

### LINKED ISSUE #12243: [Issue]: Title for Multi-Episode files includes Actors when using NFO
### Please describe your bug

After adding a Multi-Episode file (including an NFO generated with MediaElch) to the library, I noticed the episode title to be "slightly" off:

> 12-13. **Traveling Salesmen** / **The Return** / Ed Helms / Rashida Jones / Creed Bratton / Mindy Kaling / Kate Flannery / Leslie David Baker / Brian Baumgartner / Phyllis Smith / Óscar Núñez / Angela Kinsey / Paul Lieberstein / Yvette Nicole Brown / Charlotte Stewart / Eric Christie / Susie Geiser / Steve Carell / Rainn Wilson / John Krasinski / Jenna Fischer / B.J. Novak

You'll notice in addition to the actual episode titles (bold) it also lists every actor contained in the NFO.
I had a theory why this is and my testing seems to confirm this.

Here's the relevant NFO:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<episodedetails>
    <title>Traveling Salesmen</title>
    <showtitle>The Office</showtitle>
    <uniqueid type="tmdb" default="true">170168</uniqueid>
    <ratings>
        <rating name="tmdb" default="true" max="10">
            <value>8.25</value>
            <votes>28</votes>
        </rating>
    </ratings>
    <userrating>0</userrating>
    <top250>0</top250>
    <season>3</season>
    <episode>12</episode>
    <plot>Michael decided to send his employees out into the field for sales calls. He paired himself up with Andy. He let the veterans choose who they wanted their partners to be. Phyllis chose Karen, Stanley chose Ryan and that left Jim and Dwight paired together. This wasn't the first time Dwight and Jim had done sales calls together.</plot>
    <mpaa>TV-14</mpaa>
    <playcount>0</playcount>
    <lastplayed></lastplayed>
    <aired>2007-01-11</aired>
    <studio>NBC</studio>
    <credits>Michael Schur</credits>
    <credits>Lee Eisenberg</credits>
    <credits>Gene Stupnitsky</credits>
    <director>Greg Daniels</director>
    <thumb>https://image.tmdb.org/t/p/original/tcX5S2g51hqHd7cp2OMMKPEhzwt.jpg</thumb>
    <actor>
        <name>Ed Helms</name>
        <role>Andy Bernard</role>
        <order>0</order>
        <thumb>https://image.tmdb.org/t/p/original/j6xXlXdLXH2ifgWqLcLnplbbeS2.jpg</thumb>
    </actor>
    <actor>
        <name>Rashida Jones</name>
        <role>Karen Filippelli</role>
        <order>1</order>
        <thumb>https://image.tmdb.org/t/p/original/jjp33eRM6oavyesW0UM6XBCxQSa.jpg</thumb>
    </actor>
    <actor>
        <name>Melora Hardin</name>
        <role>Jan Levinson</role>
        <order>2</order>
        <thumb>https://image.tmdb.org/t/p/original/w8yg5ZPXelD47sfDRQFvGHD7jP0.jpg</thumb>
    </actor>
    <actor>
        <name>Creed Bratton</name>
        <role>Creed Bratton</role>
        <order>3</order>
        <thumb>https://image.tmdb.org/t/p/original/72hNnta4igAn2cE6fDyKElHcZ09.jpg</thumb>
    </actor>
    <actor>
        <name>Mindy Kaling</name>
        <role>Kelly Kapoor</role>
        <order>4</order>
        <thumb>https://image.tmdb.org/t/p/original/zd3sxyCKUTIWgvf8tcGo1Gur2By.jpg</thumb>
    </actor>
    <actor>
        <name>Kate Flannery</name>
        <role>Meredith Palmer</role>
        <order>5</order>
        <thumb>https://image.tmdb.org/t/p/original/wFXWKB2IUyB6Cu08PyovyBAm9WT.jpg</thumb>
    </actor>
    <actor>
        <name>Leslie David Baker</name>
        <role>Stanley Hudson</role>
        <order>6</order>
        <thumb>https://image.tmdb.org/t/p/original/9h3xlV5IYqKinlQCW1ouU7sjwWF.jpg</thumb>
    </actor>
    <actor>
        <name>Brian Baumgartner</name>
        <role>Kevin Malone</role>
        <order>7</order>
        <thumb>https://image.tmdb.org/t/p/original/1O7ECkD4mOKAgMAbQADBpTKBzOP.jpg</thumb>
    </actor>
    <actor>
        <name>Phyllis Smith</name>
        <role>Phyllis Lapin</role>
        <order>8</order>
        <thumb>https://image.tmdb.org/t/p/original/h9w9pQbiderRWAC2mi7spjzuIGz.jpg</thumb>
    </actor>
    <actor>
        <name>Angela Kinsey</name>
        <role>Angela Martin</role>
        <order>9</order>
        <thumb>https://image.tmdb.org/t/p/original/qHFidnMcFqUWdMFyjmXufBlYckd.jpg</thumb>
    </actor>
    <actor>
        <name>Gil Glasgow</name>
        <role>Dwight and Jim's Customer</role>
        <order>10</order>
        <thumb>https://image.tmdb.org/t/p/original/fEaLdsNue0zMV4PEiWDim6RtcuG.jpg</thumb>
    </actor>
    <actor>
        <name>Mark Tomesek</name>
        <role>Kenny</role>
        <order>11</order>
    </actor>
    <actor>
        <name>Warren Sweeney</name>
        <role>Richard Corey</role>
        <order>12</order>
        <thumb>https://image.tmdb.org/t/p/original/hLIO4DGw0SNydLn7GI2EEgkx3zQ.jpg</thumb>
    </actor>
    <actor>
        <name>Leon Simmons</name>
        <role>Julius</role>
        <order>13</order>
    </actor>
    <actor>
        <name>Landon H. Lewis Jr.</name>
        <role></role>
        <order>14</order>
    </actor>
    <actor>
        <name>Steve Carell</name>
        <role>Michael Scott</role>
        <order>15</order>
        <thumb>https://image.tmdb.org/t/p/original/dA6n0qpnlMFBlTr8SBULsZbWkvn.jpg</thumb>
    </actor>
    <actor>
        <name>Rainn Wilson</name>
        <role>Dwight Schrute</role>
        <order>16</order>
        <thumb>https://image.tmdb.org/t/p/original/rEDRAFYX5n2JKJh9EKILX42klA5.jpg</thumb>
    </actor>
    <actor>
        <name>John Krasinski</name>
        <role>Jim Halpert</role>
        <order>17</order>
        <thumb>https://image.tmdb.org/t/p/original/pmVGDb6Yl6OyFcHVGbu1EYNfyFK.jpg</thumb>
    </actor>
    <actor>
        <name>Jenna Fischer</name>
        <role>Pam Beesly</role>
        <order>18</order>
        <thumb>https://image.tmdb.org/t/p/original/qaWWHqpRg8PmM7vChUCv6k6C2Bg.jpg</thumb>
    </actor>
    <actor>
        <name>B.J. Novak</name>
        <role>Ryan Howard</role>
        <order>19</order>
        <thumb>https://image.tmdb.org/t/p/original/o8Xf1khxhKGTz3QAplXD35opRA8.jpg</thumb>
    </actor>
    <fileinfo>
        <streamdetails>
            <video>
                <durationinseconds>2564</durationinseconds>
                <codec>h264</codec>
                <aspect>1.778</aspect>
                <width>1920</width>
                <height>1080</height>
                <scantype>progressive</scantype>
            </video>
            <audio>
                <language>deu</language>
                <codec>ac3</codec>
                <channels>6</channels>
            </audio>
            <audio>
                <language>eng</language>
                <codec>dts</codec>
                <channels>6</channels>
            </audio>
            <subtitle>
                <language>eng</language>
            </subtitle>
        </streamdetails>
    </fileinfo>
    <generator>
        <appname>MediaElch</appname>
        <appversion>2.10.6</appversion>
        <kodiversion>20</kodiversion>
        <datetime>2024-07-07T22:33:46Z</datetime>
    </generator>
</episodedetails>
<episodedetails>
    <title>The Return</title>
    <showtitle>The Office</showtitle>
    <uniqueid type="tmdb" default="true">170169</uniqueid>
    <ratings>
        <rating name="tmdb" default="true" max="10">
            <value>8.31</value>
            <votes>29</votes>
        </rating>
    </ratings>
    <userrating>0</userrating>
    <top250>0</top250>
    <season>3</season>
    <episode>13</episode>
    <plot>Since Dwight's departure, Andy had been clinging to Michael. Andy's antics had been wearing very thin on his co-workers. In fact, Andy left Jim actually wishing Dwight would come back.</plot>
    <mpaa>TV-14</mpaa>
    <playcount>0</playcount>
    <lastplayed></lastplayed>
    <aired>2007-01-18</aired>
    <studio>NBC</studio>
    <credits>Michael Schur</credits>
    <credits>Lee Eisenberg</credits>
    <credits>Gene Stupnitsky</credits>
    <director>Greg Daniels</director>
    <thumb>https://image.tmdb.org/t/p/original/41EKAvwyjrnO3TNVy66por6T6QZ.jpg</thumb>
    <actor>
        <name>Ed Helms</name>
        <role>Andy Bernard</role>
        <order>0</order>
        <thumb>https://image.tmdb.org/t/p/original/j6xXlXdLXH2ifgWqLcLnplbbeS2.jpg</thumb>
    </actor>
    <actor>
        <name>Rashida Jones</name>
        <role>Karen Filippelli</role>
        <order>1</order>
        <thumb>https://image.tmdb.org/t/p/original/jjp33eRM6oavyesW0UM6XBCxQSa.jpg</thumb>
    </actor>
    <actor>
        <name>Creed Bratton</name>
        <role>Creed Bratton</role>
        <order>2</order>
        <thumb>https://image.tmdb.org/t/p/original/72hNnta4igAn2cE6fDyKElHcZ09.jpg</thumb>
    </actor>
    <actor>
        <name>Mindy Kaling</name>
        <role>Kelly Kapoor</role>
        <order>3</order>
        <thumb>https://image.tmdb.org/t/p/original/zd3sxyCKUTIWgvf8tcGo1Gur2By.jpg</thumb>
    </actor>
    <actor>
        <name>Kate Flannery</name>
        <role>Meredith Palmer</role>
        <order>4</order>
        <thumb>https://image.tmdb.org/t/p/original/wFXWKB2IUyB6Cu08PyovyBAm9WT.jpg</thumb>
    </actor>
    <actor>
        <name>Leslie David Baker</name>
        <role>Stanley Hudson</role>
        <order>5</order>
        <thumb>https://image.tmdb.org/t/p/original/9h3xlV5IYqKinlQCW1ouU7sjwWF.jpg</thumb>
    </actor>
    <actor>
        <name>Brian Baumgartner</name>
        <role>Kevin Malone</role>
        <order>6</order>
        <thumb>https://image.tmdb.org/t/p/original/1O7ECkD4mOKAgMAbQADBpTKBzOP.jpg</thumb>
    </actor>
    <actor>
        <name>Phyllis Smith</name>
        <role>Phyllis Lapin</role>
        <order>7</order>
        <thumb>https://image.tmdb.org/t/p/original/h9w9pQbiderRWAC2mi7spjzuIGz.jpg</thumb>
    </actor>
    <actor>
        <name>Óscar Núñez</name>
        <role>Óscar Martínez</role>
        <order>8</order>
        <thumb>https://image.tmdb.org/t/p/original/UBILHiRphJdlshvsyH920QSAhk.jpg</thumb>
    </actor>
    <actor>
        <name>Angela Kinsey</name>
        <role>Angela Martin</role>
        <order>9</order>
        <thumb>https://image.tmdb.org/t/p/original/qHFidnMcFqUWdMFyjmXufBlYckd.jpg</thumb>
    </actor>
    <actor>
        <name>Paul Lieberstein</name>
        <role>Toby Flenderson</role>
        <order>10</order>
        <thumb>https://image.tmdb.org/t/p/original/oLCaNVAw5cfE5q4e0PRsmHTuHfd.jpg</thumb>
    </actor>
    <actor>
        <name>Yvette Nicole Brown</name>
        <role>Paris</role>
        <order>11</order>
        <thumb>https://image.tmdb.org/t/p/original/ghdt5K3noAdmWV2YFLWegLRuK3T.jpg</thumb>
    </actor>
    <actor>
        <name>Charlotte Stewart</name>
        <role>Woman</role>
        <order>12</order>
        <thumb>https://image.tmdb.org/t/p/original/2q8O8fpP5e0yvKJkrR45qbHCq6n.jpg</thumb>
    </actor>
    <actor>
        <name>Eric Christie</name>
        <role>Al</role>
        <order>13</order>
        <thumb>https://image.tmdb.org/t/p/original/bJN1xYwyh0UH1xEfqJKOm70JLVP.jpg</thumb>
    </actor>
    <actor>
        <name>Susie Geiser</name>
        <role>Marcy (uncredited)</role>
        <order>14</order>
    </actor>
    <actor>
        <name>Steve Carell</name>
        <role>Michael Scott</role>
        <order>15</order>
        <thumb>https://image.tmdb.org/t/p/original/dA6n0qpnlMFBlTr8SBULsZbWkvn.jpg</thumb>
    </actor>
    <actor>
        <name>Rainn Wilson</name>
        <role>Dwight Schrute</role>
        <order>16</order>
        <thumb>https://image.tmdb.org/t/p/original/rEDRAFYX5n2JKJh9EKILX42klA5.jpg</thumb>
    </actor>
    <actor>
        <name>John Krasinski</name>
        <role>Jim Halpert</role>
        <order>17</order>
        <thumb>https://image.tmdb.org/t/p/original/pmVGDb6Yl6OyFcHVGbu1EYNfyFK.jpg</thumb>
    </actor>
    <actor>
        <name>Jenna Fischer</name>
        <role>Pam Beesly</role>
        <order>18</order>
        <thumb>https://image.tmdb.org/t/p/original/qaWWHqpRg8PmM7vChUCv6k6C2Bg.jpg</thumb>
    </actor>
    <actor>
        <name>B.J. Novak</name>
        <role>Ryan Howard</role>
        <order>19</order>
        <thumb>https://image.tmdb.org/t/p/original/o8Xf1khxhKGTz3QAplXD35opRA8.jpg</thumb>
    </actor>
    <generator>
        <appname>MediaElch</appname>
        <appversion>2.10.6</appversion>
        <kodiversion>20</kodiversion>
        <datetime>2024-07-07T22:33:46Z</datetime>
    </generator>
</episodedetails>
```

I think the issue here is two-fold.
My theory is that the NFO parser matches the opening `<episodedetails>` at the top of the file to the closing `</episodedetails>` at the bottom of the file. But in addition to that, it also appears that `<name>` in the `<actors>` section is getting picked up as an alias for `<title>` ? I'm not entirely sure why that wouldn't be the case for single-episode files though...
But regardless, when I replaced the `<name></name>` tags with `<testing></testing>` (which of course makes them invalid), the title was corrected:
> 12-13. Traveling Salesmen / The Return

Of course it also removes the actors from the episodes, but that's expected.

### Reproduction Steps

1. Prepare some dummy video file with an NFO (example above)
2. Add to library
3. Check the newly added episode's title

### Jellyfin Version

10.9.0

### if other:

10.9.7

### Environment

```markdown
- OS: TrueNAS Scale
- Linux Kernel: Linux truenas 6.6.29-production+truenas #1 SMP PREEMPT_DYNAMIC Wed May 29 15:05:57 UTC 2024 x86_64 GNU/Linux
- Virtualization: Docker/Kubernetes (TrueNAS official App)
- Clients: Browser
- Browser: Vivaldi
- FFmpeg Version: 6.0.1-Jellyfin
- Playback Method: -
- Hardware Acceleration: -
- GPU Model: -
- Plugins: -
- Reverse Proxy: -
- Base URL: -
- Networking: whatever Docker does by default 😅
- Storage: local
```

### Jellyfin logs

```shell
[2024-07-09 02:44:30.782 +02:00] [INF] [10] Emby.Server.Implementations.IO.LibraryMonitor: "Season 3" ("/mnt/media/tvshows/The Office [tmdbid-2316]/Season 03") will be refreshed.
[2024-07-09 02:44:30.784 +02:00] [INF] [10] Emby.Server.Implementations.IO.LibraryMonitor: "Traveling Salesmen / The Return / Ed Helms / Rashida Jones / Creed Bratton / Mindy Kaling / Kate Flannery / Leslie David Baker / Brian Baumgartner / Phyllis Smith / Óscar Núñez / Angela Kinsey / Paul Lieberstein / Yvette Nicole Brown / Charlotte Stewart / Eric Christie / Susie Geiser / Steve Carell / Rainn Wilson / John Krasinski / Jenna Fischer / B.J. Novak" ("/mnt/media/tvshows/The Office [tmdbid-2316]/Season 03/The.Office.US.S03E12E13.Amazing.Race.Die.Rueckkehr.GERMAN.DUBBED.DL.1080p.BluRay.x264-TSCC.mkv") will be refreshed.
[2024-07-09 02:44:50.861 +02:00] [INF] [26] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.0.10" closed
[2024-07-09 02:44:51.117 +02:00] [INF] [40] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.0.10" request
[2024-07-09 02:46:09.703 +02:00] [INF] [42] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: Deleting partial stream file(s) "/cache/transcodes/ae5ffa1c8a15fa50307caabaab9954e8.m3u8"
[2024-07-09 02:46:09.802 +02:00] [INF] [45] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.9.7" playing "The Fire". Stopped at "0" ms
[2024-07-09 02:46:09.804 +02:00] [INF] [42] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "tarulia". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2024-07-09 02:46:09.880 +02:00] [INF] [41] Jellyfin.Api.Controllers.DynamicHlsController: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[2024-07-09 02:46:09.880 +02:00] [INF] [41] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-analyzeduration 200M -probesize 1G -fflags +genpts -f matroska  -i file:\"/mnt/media/tvshows/The Office [tmdbid-2316]/Season 02/The.Office.US.S02E05.Halloween.GERMAN.DUBBED.DL.1080p.BluRay.x264-TSCC.mkv\" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:2 -map -0:s -codec:v:0 copy -bsf:v h264_mp4toannexb -start_at_zero -codec:a:0 libfdk_aac -ac 2 -ab 256000 -af \"volume=2\" -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 6 -hls_segment_type mpegts -start_number 0 -hls_segment_filename \"/cache/transcodes/dd653fead70122e1be009ba641840ff1%d.ts\" -hls_playlist_type vod -hls_list_size 0 -y \"/cache/transcodes/dd653fead70122e1be009ba641840ff1.m3u8\""
[2024-07-09 02:46:10.303 +02:00] [INF] [42] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: Started user data sync
[2024-07-09 02:46:10.860 +02:00] [INF] [42] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: User Data Sync: User "tarulia" ("ff9a7a977560419caa150df824634ad9") posted 2 updates
[2024-07-09 02:46:10.860 +02:00] [INF] [42] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: Finished user data sync, taking "00:00:00.5576185"
[2024-07-09 02:46:11.299 +02:00] [INF] [42] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.9.7" playing "The Fire". Stopped at "1238677" ms
[2024-07-09 02:46:11.856 +02:00] [INF] [65] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: Started user data sync
[2024-07-09 02:46:12.186 +02:00] [INF] [65] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: User Data Sync: User "tarulia" ("ff9a7a977560419caa150df824634ad9") posted 2 updates
[2024-07-09 02:46:12.186 +02:00] [INF] [65] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: Finished user data sync, taking "00:00:00.3300490"
[2024-07-09 02:46:14.859 +02:00] [INF] [41] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: Started user data sync
[2024-07-09 02:46:14.960 +02:00] [INF] [41] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: User Data Sync: User "tarulia" ("ff9a7a977560419caa150df824634ad9") posted 2 updates
[2024-07-09 02:46:14.960 +02:00] [INF] [41] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.UserSyncNotification: Finished user data sync, taking "00:00:00.1008376"
[2024-07-09 02:46:38.502 +02:00] [INF] [19] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2024-07-09 02:47:54.088 +02:00] [INF] [42] MediaBrowser.MediaEncoding.Transcoding.TranscodeManager: FFmpeg exited with code 0
[2024-07-09 02:48:06.858 +02:00] [INF] [45] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/mnt/media/tvshows/The Office [tmdbid-2316]/Season 03/The.Office.US.S03E12E13.Amazing.Race.Die.Rueckkehr.GERMAN.DUBBED.DL.1080p.BluRay.x264-TSCC.mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-07-09 02:48:12.496 +02:00] [INF] [42] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Started library sync
[2024-07-09 02:48:13.861 +02:00] [INF] [42] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Library Sync: Updated 1 items
[2024-07-09 02:48:13.861 +02:00] [INF] [42] Jellyfin.Plugin.KodiSyncQueue.EntryPoints.LibrarySyncNotification: Finished library sync, taking "00:00:01.3652258"
[2024-07-09 02:48:29.756 +02:00] [INF] [41] Jellyfin.Server.Implementations.Trickplay.TrickplayManager: Finished creation of trickplay files for "/mnt/media/tvshows/The Office [tmdbid-2316]/Season 03/The.Office.US.S03E12E13.Amazing.Race.Die.Rueckkehr.GERMAN.DUBBED.DL.1080p.BluRay.x264-TSCC.mkv"
[2024-07-09 02:48:53.732 +02:00] [INF] [70] Emby.Server.Implementations.IO.LibraryMonitor: "Season 3" ("/mnt/media/tvshows/The Office [tmdbid-2316]/Season 03") will be refreshed.
```

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by TheMelmacian**
Fixing the `EpisodeNfoParser` so it no longer picks up fields of sub elements (like actor/name) and appending it to the title of the combined Episode object, if a xbmc style multi episode nfo file (multiple `<episodedetails>` blocks) is parsed.
The old implementation iterated over all elements searching for specific tag names without checking the level or parent element.

I didn't test the code in a productive environment but simply extended the test file and fixed the code so the test passes again.

**Changes**
- replaced the current parser implementation that was used for all blocks but the first with the standard episode xml parser
- extracted the parser code to it's own method to prevent code duplication
- extended the test file to include actors so this case is covered by a test in the future

**Issues**
Fixes #12243

### CODE REVIEW

File: MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs [hunk 1]
```diff
@@ -91,44 +71,20 @@ protected override void Fetch(MetadataResult<Episode> item, string metadataFile,
...
+                    var additionalEpisode = new MetadataResult<Episode>()
+                    {
+                        Item = new Episode()
+                    };
+
+                    // Extract episode details from additional episodedetails block
+                    ReadEpisodeDetailsFromXml(additionalEpisode, xml, settings, cancellationToken);
+
+                    name.Append(" / ").Append(additionalEpisode.Item.Name);
+                    overview.Append(" / ").Append(additionalEpisode.Item.Overview);
```
Comment (crobibero) [inline MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs:83]: I think these should only be appended if not null or empty
```suggestion
                    if (!string.IsNullOrEmpty(additionalEpisode.Item.Name))
                    {
                        name.Append(" / ").Append(additionalEpisode.Item.Name);
                    }

                    if (!string.IsNullOrEmpty(additionalEpisode.Item.Overview))
                    {
                        overview.Append(" / ").Append(additionalEpisode.Item.Overview);
                    }
```

Comment (TheMelmacian) [reply MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs:83]: Should they be completely ignored? If the nfo contains three episodes and the second has no title, the combined title would be `Title 1 / Title 3`.
On the other hand this would allow to create nfo files in which a simple (not combined) title can be defined without using the metadata editor (empty except for first entry) and still provide the overview for all entries.

Comment (crobibero) [reply MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs:83]: I think the end result of `Title 1 / Title 3` is correct (and ideal?)
Sounds like a good candidate for an extra test

Comment (Shadowghost) [reply MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs:83]: Since 10.9 this is what our TMDB provider does too: Append title and description, separated by a ` / `

Comment (TheMelmacian) [reply MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs:83]: I think it makes sense to also combine the <originaltitle> for multi episodes. As a user I would expect that the shown title and original title for an episode match each other (except for the language).
If you agree I, will add it to both the NfoParser and the TMDB provider.

**Comment by mihawk90** [comment]
Hey, thanks for working on this.

I know this is not strictly related to the fix, however since the code is being touched anyway, might it be worth exploring a different concatenation-string for the plot/overview? The `/` in the title makes sense because it is a single-line item, however in a flow of text like the overview, a single slash is easily lost.

My proposal would be using a markdown-style "horizontal rule/line" element, i.e.:

> Plot 1
> 
> ---
> 
> Plot 2

As in:
```markdown
Plot 1

---

Plot 2
```

This is a clear break for each episode's plot as it is easily distinguishable with (e.g. webUI) or without markdown parsing on the client.

Thoughts? :)

File: MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs (hunk 1 above)
Comment (TheMelmacian) [reply MediaBrowser.XbmcMetadata/Parsers/EpisodeNfoParser.cs:83]: TMDB doesn't provide the original title directly and the original language is only available on the series/show level.
I'm not familiar with the code but the only way I see to implement it on the TmdbEpisodeProvider is
- fetch series
- extract original_language
- check if metadata language differ
  - no: OriginalTitle = Title
  - yes: either fetch Episode again with original_language or fetch Translations and search for entry with original_language

Let me know if this is OK or if there is another way to achieve this.

**Comment by TheMelmacian** [comment]
I like the idea to use markdown to have a clear separator between the overviews of different episodes.

**Comment by mihawk90** [comment]
On another note, since this is a bugfix for a feature introduced in 10.9, this should probably target the `release-10.9.z` branch

**Review by crobibero — APPROVED** [review]

**Comment by TheMelmacian** [comment]
> On another note, since this is a bugfix for a feature introduced in 10.9, this should probably target the `release-10.9.z` branch

Possible. I'm not sure how the backports work.

**Comment by TheMelmacian** [comment]
Please let me know if I should switch the target branch to `release-10.9.z`.

**Comment by crobibero** [comment]
We're going to move ahead with holding off on this until 10.10
