### PR TITLE
Fix exception when saving user data to NFO files

### LINKED ISSUE #14507: 10.11.0-rc3 - Library scan repeatedly reporting existing media as new after playing the title
### Description of the bug

I'm running 10.11.0-rc3 on docker installed over the latest stable version (trying to help the project testing the release candidate). I've upgraded to rc3 from the latest stable version last week (July 18th).

There's a funny behavior happening: whenever I start playing any movie or tv show that was already scanned (my media library has over 2 years on the same server), after a couple of seconds I get a notification saying that this title is new - as if recently added it to my collection.

This issue creates no other problem playing the media, nor any other undesirable effect.

### Reproduction steps

- Play any title on the collection
- Stop playing, exit media reproduction
- Wait a couple of seconds. On Firefox, if notifications are enabled for jellyfin, a message will pop out saying that title has been recently added to the collection. Didn't test this on google chrome

### What is the current _bug_ behavior?

Recently played title is reported as being a new addition to media library

### What is the expected _correct_ behavior?

No notification at all

### Jellyfin Server version

Unstable

### Specify commit id

_No response_

### Specify unstable release number

_No response_

### Specify version number

_No response_

### Specify the build version

10.11.0-rc3

### Environment

```markdown
- OS:Linux Ubuntu 24.04LTS
- Linux Kernel: Linux saturno 6.1.0-32-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.129-1 (2025-03-06) x86_64 GNU/Linux
- Virtualization: No
- Clients: Firefox ESR (not tested on google chrome)
- Browser: Firefox ESR (not tested on google chrome)
- FFmpeg Version: jellyfin docker ffmpeg library (sorry, I don't know there to find this info)
- Jellyfin Data Storage: ext4 docker volume bind to server's file system
- Media Storage: ext4 docker volume bind to server's file system
```

### Jellyfin logs

```shell
[2025-07-21 00:24:40.132 -03:00] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/local/music_shows"
[2025-07-21 00:24:40.133 -03:00] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/local/movies"
[2025-07-21 00:24:40.135 -03:00] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/local/documentaries_brazil"
[2025-07-21 00:24:40.135 -03:00] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/local/series"
[2025-07-21 00:24:40.136 -03:00] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/local/animation"
[2025-07-21 00:24:40.136 -03:00] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/local/movies_fast_food"
[2025-07-21 00:24:40.136 -03:00] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/local/series_kids"
[2025-07-21 00:24:40.137 -03:00] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/local/movies_kids"
[2025-07-21 00:24:40.137 -03:00] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/local/movies_brazil"
[2025-07-21 00:24:40.137 -03:00] [INF] [17] Emby.Server.Implementations.IO.LibraryMonitor: Stopping directory watching for path "/media/local/documentaries"
[2025-07-21 00:24:40.137 -03:00] [INF] [17] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2025-07-21 00:24:42.135 -03:00] [INF] [20] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Media Segment Scan" Completed after 0 minute(s) and 1 seconds
[2025-07-21 00:24:44.100 -03:00] [ERR] [88] MediaBrowser.Providers.Subtitles.SubtitleManager: Error downloading subtitles from "Open Subtitles"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.GetLanguage(String language, CancellationToken cancellationToken)
   at Jellyfin.Plugin.OpenSubtitles.OpenSubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)
[2025-07-21 00:24:44.927 -03:00] [ERR] [88] Microsoft.EntityFrameworkCore.Update: An exception occurred in the database while saving changes for context type '"Jellyfin.Database.Implementations.JellyfinDbContext"'."
""System.InvalidOperationException: The value of 'UserData.ItemId' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)"
System.InvalidOperationException: The value of 'UserData.ItemId' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Database.Implementations.JellyfinDbContext.<>n__1(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Database.Implementations.JellyfinDbContext.<>c__DisplayClass63_1.<SaveChanges>b__0()
   at Jellyfin.Database.Implementations.Locking.NoLockBehavior.OnSaveChanges(JellyfinDbContext context, Action saveChanges)
   at Jellyfin.Database.Implementations.JellyfinDbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
[2025-07-21 00:24:44.928 -03:00] [ERR] [88] Jellyfin.Database.Implementations.JellyfinDbContext: Error trying to save changes.
System.InvalidOperationException: The value of 'UserData.ItemId' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Database.Implementations.JellyfinDbContext.<>n__1(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Database.Implementations.JellyfinDbContext.<>c__DisplayClass63_1.<SaveChanges>b__0()
   at Jellyfin.Database.Implementations.Locking.NoLockBehavior.OnSaveChanges(JellyfinDbContext context, Action saveChanges)
   at Jellyfin.Database.Implementations.JellyfinDbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
[2025-07-21 00:24:44.929 -03:00] [ERR] [88] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "Nfo"
System.InvalidOperationException: The value of 'UserData.ItemId' is unknown when attempting to save changes. This is because the property is also part of a foreign key for which the principal entity in the relationship is not known.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave(Boolean cascadeChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Database.Implementations.JellyfinDbContext.<>n__1(Boolean acceptAllChangesOnSuccess)
   at Jellyfin.Database.Implementations.JellyfinDbContext.<>c__DisplayClass63_1.<SaveChanges>b__0()
   at Jellyfin.Database.Implementations.Locking.NoLockBehavior.OnSaveChanges(JellyfinDbContext context, Action saveChanges)
   at Jellyfin.Database.Implementations.JellyfinDbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Emby.Server.Implementations.Library.UserDataManager.SaveUserData(User user, BaseItem item, UserItemData userData, UserDataSaveReason reason, CancellationToken cancellationToken)
   at MediaBrowser.XbmcMetadata.Parsers.BaseNfoParser`1.FetchDataFromXmlNode(XmlReader reader, MetadataResult`1 itemResult)
   at MediaBrowser.XbmcMetadata.Parsers.MovieNfoParser.FetchDataFromXmlNode(XmlReader reader, MetadataResult`1 itemResult)
   at MediaBrowser.XbmcMetadata.Parsers.BaseNfoParser`1.Fetch(MetadataResult`1 item, String metadataFile, XmlReaderSettings settings, CancellationToken cancellationToken)
   at MediaBrowser.XbmcMetadata.Parsers.BaseNfoParser`1.Fetch(MetadataResult`1 item, String metadataFile, CancellationToken cancellationToken)
   at MediaBrowser.XbmcMetadata.Providers.BaseVideoNfoProvider`1.Fetch(MetadataResult`1 result, String path, CancellationToken cancellationToken)
   at MediaBrowser.XbmcMetadata.Providers.BaseNfoProvider`1.GetMetadata(ItemInfo info, IDirectoryService directoryService, CancellationToken cancellationToken)
   at
```

### FFmpeg logs

```shell

```

### Client / Browser logs

_No response_

### Relevant screenshots or videos

_No response_

### Additional information

_No response_

### LINKED ISSUE #14534: [10.11.0] Exception when scanning in music library when watch status set to save in NFO
### Description of the bug

Enabling NFO watched status causes errors when scanning in a music library

Logs: https://gist.github.com/theguymadmax/1e54745e03c3cfc54b737e707e18ea4b

### Reproduction steps

1. In Dashboard->Libraries->NFO Settings - Enable Save User watch data to NFO files for your user account
2. Add in a Music library (default settings)

### What is the current _bug_ behavior?

Exception errors

### What is the expected _correct_ behavior?

No errors

### Jellyfin Server version

Master

### Specify commit id

f37347c66c9f1480f20ef90f37e40ab06596fa89

### Specify unstable release number

_No response_

### Specify version number

_No response_

### Specify the build version

10.11.0 (Master)

### Environment

```markdown
- OS: Windows 11
- Virtualization: NO
- Plugins: None
```

### Jellyfin logs

```shell
Linked above
```

### FFmpeg logs

```shell

```

### Client / Browser logs

_No response_

### Relevant screenshots or videos

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by theguymadmax**
**Changes**

Fixed an exception caused during metadata import when save watch data to NFO was enabled. The NFO parser now checks if an item has been saved to the database before attempting to save user data.

**Issues**
 
Fixes #14534
Fixes #14507

### CODE REVIEW

File: MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs [hunk 1]
```diff
@@ -316,7 +316,11 @@ protected virtual void FetchDataFromXmlNode(XmlReader reader, MetadataResult<T>
                             if (userData is not null)
                             {
                                 userData.Played = played;
-                                _userDataManager.SaveUserData(user, item, userData, UserDataSaveReason.Import, CancellationToken.None);
+
+                                if (!item.Id.Equals(Guid.Empty))
```
Comment (crobibero) [inline MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs]:
```suggestion
                                if (!item.Id.IsEmpty())
```

File: MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs [hunk 2]
```diff
@@ -333,7 +337,11 @@ protected virtual void FetchDataFromXmlNode(XmlReader reader, MetadataResult<T>
                             if (userData is not null)
                             {
                                 userData.PlayCount = count;
-                                _userDataManager.SaveUserData(user, item, userData, UserDataSaveReason.Import, CancellationToken.None);
+
+                                if (!item.Id.Equals(Guid.Empty))
```
Comment (crobibero) [inline MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs]:
```suggestion
                                if (!item.Id.IsEmpty())
```

File: MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs [hunk 3]
```diff
@@ -350,7 +358,11 @@ protected virtual void FetchDataFromXmlNode(XmlReader reader, MetadataResult<T>
                             if (userData is not null)
                             {
                                 userData.LastPlayedDate = lastPlayed;
-                                _userDataManager.SaveUserData(user, item, userData, UserDataSaveReason.Import, CancellationToken.None);
+
+                                if (!item.Id.Equals(Guid.Empty))
```
Comment (crobibero) [inline MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs]:
```suggestion
                                if (!item.Id.IsEmpty())
```
