### PR TITLE
Fix blocking in async context in LimitedConcurrencyLibraryScheduler

### LINKED ISSUE #15661: [10.11.3] High bitrate movies causing server freezes during transcoding
### Description of the bug

When playing high bitrate movies, regardless of the device (tested on mobile, desktop browser, and jellyfin-tizen on my S95C), the server freezes intermittently during transcoding. Transcoding is necessary because the movie file is Dolby Vision which is not supported on any of my tested devices. Ffmpeg still proceeds in the background but the entire jellyfin server and webui is unresponsive when the freezes occur. Initially I thought it was a corrupted file, but I tested with other similar versions and the same problem occurred. Next, I thought it was just the video stream buffer under-running, but it isn't, the transcoding continues at a normal pace and my CPU/GPU is not pegged at 100%. The actual jellyfin server process appears to be blocked. Process prioritization and affinity has no impact on the problem. This is all running on a 12-gen i7 processor with 64GB DDR5 and an Arc 770 GPU, so it should be able to handle all of this with no problems. I observe no anomalies or error messages in the server logs and ffmpeg logs before, during, and after the freezing behavior.

### Reproduction steps

1. Start playback of a high-bitrate movie on Jellyfin using any device (e.g., mobile browser, desktop browser, or Jellyfin-Tizen on an S95C TV).
2. Ensure the movie requires transcoding due to containing a Dolby Vision video stream unsupported by the playback device(s).
3. Observe that FFmpeg begins transcoding normally in the background on the server.
4. During playback, note that the Jellyfin server and WebUI intermittently freeze while transcoding continues in the background (observe that ffmpeg log files continue to be generated as well).
5. Verify that the issue is not file-specific by testing multiple similar Dolby Vision movie files and reproducing the same freeze behavior.
6. Confirm that video buffer underrun is not the cause by checking that transcoding proceeds at normal speed without CPU or GPU saturation.
7. Observe that the Jellyfin server process itself becomes blocked or unresponsive during these freezes, testing by using multiple browsers and the Android app, all on the same network segment as the server to ensure network performance is not the problem.
8. Attempt adjusting process prioritization or CPU/GPU affinity and note that these changes have no effect on the issue.

### What is the current _bug_ behavior?

The jellyfin server and webui are completely unresponsive during the transcoding operation, intermittently. Video playback freezes on client devices during this intermittent unresponsiveness, but playback and responsiveness returns after a short time. The freezing behavior occurs seemingly at random, for several seconds. The timing of the freezing behavior and the duration of the freeze is not consistent.

### What is the expected _correct_ behavior?

The server should be responsive, and video playback should proceed normally.

### Jellyfin Server version

10.11.3

### Specify commit id

_No response_

### Specify unstable release number

_No response_

### Specify version number

_No response_

### Specify the build version

10.11.3

### Environment

```markdown
- OS: Windows 11
- Virtualization: None, bare metal
- Clients: Jellyfin Android (latest), Jellyfin-Web, jellyfin-tizen (latest)
- Browser: Mozilla Firefox
- FFmpeg Version: ffmpeg version 7.1.2-Jellyfin
- Playback Method:Transcode
- Hardware Acceleration: QSV
- GPU Model: Arc A770
- Plugins: AudioDB, Chapter Segments Provider, Intro Skipper, Local Intros, MusicBrainz, OMDb, Playback Reporting, Reports, Session Cleaner, Studio Images, Theme Songs, TMDb, TMDb Box Sets
- Reverse Proxy: nginx
- Base URL: none
- Networking: Host
- Jellyfin Data Storage: Local NVMe SSD
- Media Storage: Local HDD array transcoding to local NVMe SSD
- External Integrations: None
```

### Jellyfin logs

```shell
There are no errors in the logs, log activity appears completely normal.
```

### FFmpeg logs

```shell
Uploaded separately.
```

### Client / Browser logs

_No response_

### Relevant screenshots or videos

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by SapientGuardian**
**Changes**
* Replace `BlockingCollection` with `Channel` in `LimitedConcurrencyLibraryScheduler` to avoid blocking in an async context
* Add SapientGuardian to `CONTRIBUTORS.MD`

**Issues**
Fixes #15661

### CODE REVIEW

**Comment by drspangle** [comment]
I can confirm that the updated MediaBrowser.Controller.dll fixes #15661. Tested with parallel library scan tasks limit and parallel image encoding limit set to 1, 2, 4, and null (default). The freezing behavior is gone.

File: MediaBrowser.Controller/LibraryTaskScheduler/LimitedConcurrencyLibraryScheduler.cs [hunk 1]
```diff
@@ -295,6 +296,28 @@ void UpdateProgress()
...
 
+    /// <summary>
+    /// Waits for for the specified interval OR CancellationToken to retrieve an item from the channel reader. Returns null if either condition elapses.
+    /// </summary>
+    /// <typeparam name="T">Type of item.</typeparam>
+    /// <param name="channelReader">Channel reader from which to read.</param>
+    /// <param name="interval">Interval to wait before aborting.</param>
+    /// <param name="linkedToken">CancellationToken to trigger abort.</param>
+    /// <returns>Retrieved item, or null if one of the supplied conditions elapses.</returns>
+    private static async Task<T?> ChannelTryTake<T>(ChannelReader<T> channelReader, TimeSpan interval, CancellationToken linkedToken)
```
Comment (cvium) [inline MediaBrowser.Controller/LibraryTaskScheduler/LimitedConcurrencyLibraryScheduler.cs]: This is pretty much what WaitAsync does

Comment (SapientGuardian) [reply MediaBrowser.Controller/LibraryTaskScheduler/LimitedConcurrencyLibraryScheduler.cs]: `WaitAsync` doesn't return the value if available, it only tells you if/when a value becomes available. In a multi-threaded context like this, one of the other readers could take the item between `WaitAsync` telling you one was available and you attempting to retrieve it with `WaitAsync`, so it doesn't really get the job done here. You'd have to implement some sort of double-checked locking pattern, which would only increase the complexity.

Comment (cvium) [reply MediaBrowser.Controller/LibraryTaskScheduler/LimitedConcurrencyLibraryScheduler.cs]: I think you may be thinking of [`WaitToReadAsync`](https://learn.microsoft.com/en-us/dotnet/api/system.threading.channels.channelreader-1.waittoreadasync?view=net-9.0#system-threading-channels-channelreader-1-waittoreadasync(system-threading-cancellationtoken)). I am talking about [Task.WaitAsync](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.waitasync?view=net-9.0#system-threading-tasks-task-waitasync(system-timespan-system-threading-cancellationtoken)).

Image

Comment (SapientGuardian) [reply MediaBrowser.Controller/LibraryTaskScheduler/LimitedConcurrencyLibraryScheduler.cs]: Sorry, I misread your comment. I don't believe we can use `WaitAsync` here because the time-based cancellation is not forwarded to the inner `ReadAsync` call, which would result in the value still getting read from the channel, but then discarded.

image

**Comment by theguymadmax** [comment]
This should target the release branch. Please rebase and drop all commits that are not part of this PR.

**Comment by SapientGuardian** [comment]
> This should target the release branch. Please rebase and drop all commits that are not part of this PR.

Done. It would be helpful if https://jellyfin.org/docs/general/contributing/development#official-branches reflected that as standard procedure (unless of course you're considering this an emergency hotfix).

**Comment by crobibero** [comment]
@SapientGuardian There are now merge conflicts after merging a different PR

File: MediaBrowser.Controller/LibraryTaskScheduler/LimitedConcurrencyLibraryScheduler.cs (hunk 1 above)
Comment (SapientGuardian) [reply MediaBrowser.Controller/LibraryTaskScheduler/LimitedConcurrencyLibraryScheduler.cs]: With the latest changes in the release branch, this method is no longer necessary and has been removed.

**Comment by SapientGuardian** [comment]
> @SapientGuardian There are now merge conflicts after merging a different PR

I have re-rebased.

**Comment by drspangle** [comment]
Any updates on the progress of this PR being reviewed?

**Review by cvium — APPROVED** [review]
