### PR TITLE
Fix external LRC files being incorrectly overwritten during the initial scan

### LINKED ISSUE #11454: [Issue]: existent LRC files overwritten by Jellyfin
### Please describe your bug

My song collection has embedded unsynced lyrics and synced lyrics as `.lrc` files

Upon scanning the library, Jellyfin overwrites the `.lrc` file with the unsynced lyrics and the original synced lyrics are lost

Mediainfo:
```
General
Complete name               : C:\Users\device\Music\Drake - Toosie Slide\Toosie Slide - Drake.mp3
Format                      : MPEG Audio
File size                   : 11.6 MiB
Duration                    : 4 min 7 s
Overall bit rate            : 320 kb/s
Album                       : Toosie Slide
Album/Performer             : Drake
Part/Position               : 1
Part/Total                  : 1
Track name                  : Toosie Slide
Track name/Position         : 1
Track name/Total            : 1
Performer                   : Drake
Composer                    : Aubrey Graham
Publisher                   : OVO
Genre                       : Rap/Hip Hop
Recorded date               : 2020-04-03
Writing library             : LAME3.99r
ISRC                        : USUG12001281
Copyright                   : © 2020 OVO, under exclusive license to Republic Records, a division of UMG Recordings, Inc.
Cover                       : Yes
Cover description           : cover
Cover type                  : Cover (front)
Cover MIME                  : image/jpeg
Lyrics                      : Black leather gloves, no sequins / Buckles on the jacket, it's Alyx shit  / Nike crossbody, got a piece in it / Got a dance, but it's really on some street shit / I'ma show you how to get it /  / It go, right foot up, left foot slide / Left foot up, right foot slide / Basically, I'm saying either way, we 'bout to slide, ayy / Can't let this one slide, ayy /  / Don't you wanna dance with me? No? / I could dance like Michael Jackson / I could give you thug passion / It's a Thriller in the trap where we from / Baby, don't you want to dance with me? No? / I could dance like Michael Jackson / I could give you satisfaction / And you know we out here everyday with it / I'ma show you how to get it /  / It go, right foot up, left foot slide / Left foot up, right foot slide / Basically, I'm saying either way, we 'bout to slide, ayy / Can't let this one slide, ayy (who's bad?) /  / Two thousand shorties wanna tie the knot, ayy, yeah / Two hundred shooters on my brother's block, whoa, yeah / Petal off a rose like, I love her not, maybe not / I don't know what's wrong with me, I can't stop, whoa, yeah / Won't stop, whoa, yeah, never stop / Got so many opps, I be mistakin' opps for other opps / Got so many people that I love out of troubled spots / Other than the family I got, it's either you or me / That's just how I think, it's either you or me / This life got too deep for you, baby / Two or three of us about to creep where they stayin' /  / Black leather gloves, no sequins / Buckles on the jacket, it's Alyx shit / Nike crossbody, got a piece in it / Got a dance, but it's really on some street shit / I'ma show you how to get it /  / It go, right foot up, left foot slide / Left foot up, right foot slide / Basically, I'm sayin' either way, we 'bout to slide, ayy / Can't let this one slide, ayy (who's bad?) /  / Toosie slide, then I hit it double time / Then I hit a spin 'cause we spun their block a couple times / If it's not the right time, there'll always be another time / I'm not even trippin', we'll just see 'em in the summertime, whoa, yeah / Can't describe the pressure I be puttin' on myself, yeah / Really I just can't afford to lose nobody else, yeah / If they movin' shaky, we'll just do this shit ourselves, whoa / If I'm movin' shaky, Chubbs'll do this shit himself, yeah / Solo niggas, on they YOLO, for real / Heard a lot about you, but we don't know for real / Next time, guarantee the truth'll get revealed /  / Black leather gloves, no sequins, yeah / Buckles on the jacket, it's Alyx shit / Nike crossbody, got a piece in it / Got a dance, but it's really on some street shit / I'ma show you how /  / It go, right foot up, left foot slide / Left foot up, right foot slide / Basically, I'm saying either way, we 'bout to slide, ayy / Can't let this one slide, ayy /  / Don't you wanna dance with me? No? / I could dance like Michael Jackson (Jackson) / I could give you thug passion (passion) / It's a Thriller in the trap where we from (where we from) / Baby, don't you want to dance with me? No? / I could dance like Michael Jackson (Jackson) / I could give you satisfaction ('faction) / And you know we out here everyday with it / I'ma show you how to get it /  / It go, right foot up, left foot slide / Left foot up, right foot slide / Basically, I'm sayin' either way, we 'bout to slide / (Who's bad?)
BARCODE                     : 602508991455
ITUNESADVISORY              : 1
REPLAYGAIN_TRACK_GAIN       : -7.5 dB
SOURCE                      : Deezer
SOURCEID                    : 919708552

Audio
Format                      : MPEG Audio
Format version              : Version 1
Format profile              : Layer 3
Format settings             : Joint stereo
Duration                    : 4 min 7 s
Bit rate mode               : Constant
Bit rate                    : 320 kb/s
Channel(s)                  : 2 channels
Sampling rate               : 44.1 kHz
Frame rate                  : 38.281 FPS (1152 SPF)
Compression mode            : Lossy
Stream size                 : 9.43 MiB (81%)
Writing library             : LAME3.99r
Encoding settings           : -m j -V 4 -q 3 -lowpass 20.5

Image
Format                      : JPEG
Width                       : 1 200 pixels
Height                      : 1 200 pixels
Color space                 : YUV
Chroma subsampling          : 4:4:4
Bit depth                   : 8 bits
Compression mode            : Lossy
Stream size                 : 2.13 MiB (18%)
```

### Reproduction Steps

1. Add a song with embedded unsynced lyrics and a matching `.lrc` file with synced lyrics to a specific folder
2. Have jellyfin scan that folder as a Music library
3. Access the `.lrc` file and all timestamps will be lost.

### Jellyfin Version

Unstable (master branch)

### if other:

10.9 unstable (jellyfin_2024042215-amd64)

### Environment

```markdown
- OS: Windows 11 Enterprise
- FFmpeg Version: 7.0
- Plugins: none
- Storage: local
```

### Jellyfin logs

```shell
[2024-04-27 20:38:41.255 -03:00] [INF] [1] Main: Jellyfin version: "10.9.0"
[2024-04-27 20:38:41.271 -03:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, C:\Users\device\AppData\Local\jellyfin\log]"]
[2024-04-27 20:38:41.274 -03:00] [INF] [1] Main: Arguments: ["C:\Users\device\Downloads\jellyfin\jellyfin.dll"]
[2024-04-27 20:38:41.275 -03:00] [INF] [1] Main: Operating system: "Microsoft Windows 10.0.22631"
[2024-04-27 20:38:41.276 -03:00] [INF] [1] Main: Architecture: X64
[2024-04-27 20:38:41.277 -03:00] [INF] [1] Main: 64-Bit Process: True
[2024-04-27 20:38:41.278 -03:00] [INF] [1] Main: User Interactive: True
[2024-04-27 20:38:41.279 -03:00] [INF] [1] Main: Processor count: 16
[2024-04-27 20:38:41.280 -03:00] [INF] [1] Main: Program data path: "C:\Users\device\AppData\Local\jellyfin"
[2024-04-27 20:38:41.280 -03:00] [INF] [1] Main: Log directory path: "C:\Users\device\AppData\Local\jellyfin\log"
[2024-04-27 20:38:41.281 -03:00] [INF] [1] Main: Config directory path: "C:\Users\device\AppData\Local\jellyfin\config"
[2024-04-27 20:38:41.282 -03:00] [INF] [1] Main: Cache path: "C:\Users\device\AppData\Local\jellyfin\cache"
[2024-04-27 20:38:41.283 -03:00] [INF] [1] Main: Web resources path: "C:\Users\device\Downloads\jellyfin\jellyfin-web"
[2024-04-27 20:38:41.284 -03:00] [INF] [1] Main: Application directory: "C:\Users\device\Downloads\jellyfin\"
[2024-04-27 20:38:41.374 -03:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "C:\Users\device\AppData\Local\jellyfin\cache"
[2024-04-27 20:38:41.405 -03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-04-27 20:38:41.552 -03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-04-27 20:38:41.554 -03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions: []
[2024-04-27 20:38:41.555 -03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
[2024-04-27 20:38:41.558 -03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: ["192.168.1.140", "192.168.56.1", "192.168.195.160", "127.0.0.1"]
[2024-04-27 20:38:41.559 -03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Remote IP filter is "Allowlist"
[2024-04-27 20:38:41.560 -03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Filter list: []
[2024-04-27 20:38:42.378 -03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.9.0.0"
[2024-04-27 20:38:42.380 -03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.9.0.0"
[2024-04-27 20:38:42.381 -03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.9.0.0"
[2024-04-27 20:38:42.395 -03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.9.0.0"
[2024-04-27 20:38:42.397 -03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.9.0.0"
[2024-04-27 20:38:42.441 -03:00] [INF] [1] Main: Kestrel is listening on "192.168.1.140"
[2024-04-27 20:38:42.442 -03:00] [INF] [1] Main: Kestrel is listening on "192.168.56.1"
[2024-04-27 20:38:42.443 -03:00] [INF] [1] Main: Kestrel is listening on "192.168.195.160"
[2024-04-27 20:38:42.444 -03:00] [INF] [1] Main: Kestrel is listening on "127.0.0.1"
[2024-04-27 20:38:42.829 -03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[2024-04-27 20:38:42.839 -03:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Generate Trickplay Images" set to fire at 2024-04-28 03:00:00.000 -03:00, which is 06:21:17.1608096 from now.
[2024-04-27 20:38:42.842 -03:00] [INF] [1] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for "Extract Chapter Images" set to fire at 2024-04-28 02:00:00.000 -03:00, which is 05:21:17.1571338 from now.
[2024-04-27 20:38:42.933 -03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version "7.0"
[2024-04-27 20:38:43.015 -03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "decoders": ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "dca", "flac", "mp3", "truehd"]
[2024-04-27 20:38:43.104 -03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available "encoders": ["libsvtav1", "av1_nvenc", "av1_qsv", "av1_amf", "av1_vaapi", "libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "alac", "dca", "flac", "libmp3lame", "libopus", "truehd", "libvorbis", "srt"]
[2024-04-27 20:38:43.182 -03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_cuda", "libplacebo", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_vulkan", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_qsv", "scale_vaapi", "scale_vulkan", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "yadif_cuda", "zscale"]
[2024-04-27 20:38:43.321 -03:00] [WRN] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Filter: "tonemap_cuda" with option "GPU accelerated HDR to SDR tonemapping" is not available
[2024-04-27 20:38:43.662 -03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "vaapi", "dxva2", "qsv", "d3d11va", "opencl", "vulkan", "d3d12va"]
[2024-04-27 20:38:43.849 -03:00] [INF] [1] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: "ffmpeg"
[2024-04-27 20:38:43.851 -03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: ServerId: "d53db628b9b04056a87977e35a910f37"
[2024-04-27 20:38:43.852 -03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Core startup complete
[2024-04-27 20:38:43.853 -03:00] [INF] [1] Main: Startup complete 0:00:02.7137369
[2024-04-27 20:38:45.860 -03:00] [INF] [9] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Clean up collections and playlists" Completed after 0 minute(s) and 0 seconds
[2024-04-27 20:38:47.370 -03:00] [INF] [9] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 1 seconds
[2024-04-27 20:38:50.749 -03:00] [INF] [23] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "127.0.0.1" request
[2024-04-27 20:43:07.580 -03:00] [WRN] [43] MediaBrowser.Controller.Entities.BaseItem: Library folder "C:\Users\device\AppData\Local\jellyfin\data\playlists" is inaccessible or empty, skipping
[2024-04-27 20:43:07.740 -03:00] [INF] [43] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[2024-04-27 20:43:07.840 -03:00] [WRN] [48] MediaBrowser.Controller.Entities.BaseItem: Library folder "C:\Users\device\AppData\Local\jellyfin\data\playlists" is inaccessible or empty, skipping
[2024-04-27 20:43:07.850 -03:00] [WRN] [48] MediaBrowser.Controller.Entities.BaseItem: Library folder "C:\Users\device\AppData\Local\jellyfin\data\playlists" is inaccessible or empty, skipping
[2024-04-27 20:43:07.900 -03:00] [INF] [17] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"C:\Users\device\Music\Drake - Toosie Slide\Toosie Slide - Drake.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-04-27 20:43:08.042 -03:00] [INF] [43] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"C:\Users\device\Music\Drake - Toosie Slide\Toosie Slide - Drake.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-04-27 20:43:08.132 -03:00] [INF] [48] MediaBrowser.Providers.Lyric.LyricManager: Saving lyrics to "C:\Users\device\Music\Drake - Toosie Slide\Toosie Slide - Drake.lrc"
[2024-04-27 20:43:12.253 -03:00] [INF] [17] Jellyfin.Drawing.ImageProcessor: Creating image collage and saving to "C:\Users\device\AppData\Local\jellyfin\cache\temp\d70418fcd293458e9bd94cf4f055a4ae.png"
[2024-04-27 20:43:12.377 -03:00] [INF] [17] Jellyfin.Drawing.ImageProcessor: Completed creation of image collage and saved to "C:\Users\device\AppData\Local\jellyfin\cache\temp\d70418fcd293458e9bd94cf4f055a4ae.png"
[2024-04-27 20:43:12.394 -03:00] [INF] [48] Jellyfin.Drawing.ImageProcessor: Creating image collage and saving to "C:\Users\device\AppData\Local\jellyfin\cache\temp\9817a21aeebe4498a90e2bf64d84b44e.png"
[2024-04-27 20:43:12.511 -03:00] [INF] [48] Jellyfin.Drawing.ImageProcessor: Completed creation of image collage and saved to "C:\Users\device\AppData\Local\jellyfin\cache\temp\9817a21aeebe4498a90e2bf64d84b44e.png"
[2024-04-27 20:43:12.530 -03:00] [INF] [46] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Scan Media Library" Completed after 0 minute(s) and 4 seconds
[2024-04-27 20:43:12.530 -03:00] [INF] [42] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "C:\Users\device\Music\Drake - Toosie Slide"
[2024-04-27 20:43:16.081 -03:00] [INF] [31] Jellyfin.Api.Controllers.UniversalAudioController: GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, MaxStreamingBitrate: 8000000, MaxStaticBitrate: 8000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: 8000000, DirectPlayProfiles: [DirectPlayProfile { Container: "opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "opus", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mp3", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "webma", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "mp4", Type: Audio, VideoCodec: "", AudioCodec: "aac", Protocol: hls, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False, Conditions: [] }], ContainerProfiles: [], CodecProfiles: [], SubtitleProfiles: [] }
[2024-04-27 20:43:16.146 -03:00] [INF] [31] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "device". EnableAudioPlaybackTranscoding: True
[2024-04-27 20:43:16.182 -03:00] [INF] [31] Jellyfin.Api.Controllers.UniversalAudioController: GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, MaxStreamingBitrate: 8000000, MaxStaticBitrate: 8000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: 8000000, DirectPlayProfiles: [DirectPlayProfile { Container: "opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "opus", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mp3", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "webma", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "mp4", Type: Audio, VideoCodec: "", AudioCodec: "aac", Protocol: hls, EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False, Conditions: [] }], ContainerProfiles: [], CodecProfiles: [], SubtitleProfiles: [] }
[2024-04-27 20:43:16.216 -03:00] [INF] [31] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "device". EnableAudioPlaybackTranscoding: True
[2024-04-27 20:43:28.714 -03:00] [INF] [17] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Jellyfin Web" "10.9.0" playing "Toosie Slide". Stopped at "49043" ms
```

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

Before scanning with Jellyfin:
image

After scanning with Jellyfin:
image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gnattu**
**Changes**

The external LRC should be added to the current stream first; otherwise, the initial scan will always overwrite the external LRC if that audio file also has an embedded lyric.

Now, such overwrite will no longer happen even if the user requested full replacement metadata.

If users want to get rid of the current external lrc and use the embedded version instead, they should manually remove that lrc file and do a find missing metadata library scan.

**Issues**

Fixes #11454

### CODE REVIEW

File: MediaBrowser.Providers/MediaInfo/AudioFileProber.cs [hunk 1]
```diff
@@ -321,9 +323,9 @@ private async Task FetchDataFromTags(Audio audio, Model.MediaInfo.MediaInfo medi
                 }
 
                 // Save extracted lyrics if they exist,
-                // and if we are replacing all metadata or the audio doesn't yet have lyrics.
+                // and if the audio doesn't yet have lyrics.
                 if (!string.IsNullOrWhiteSpace(tags.Lyrics)
```
Comment (Shadowghost) [inline MediaBrowser.Providers/MediaInfo/AudioFileProber.cs:327]: Instead of passing all streams you could also just check if any is an LRC stream and only pass a bool

**Review by Shadowghost — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]

**Comment by NicholasFlamy** [comment]
Why does it make a .lrc file from the embedded lyrics?
