### PR TITLE
Fix subtitle converter misinterpreting 0 valued endTimeTicks

### LINKED ISSUE #254: SRT subtitles not working
As a non native english speaker we enjoy the original sound with subtitles based on the SRT format.

Currently jellyfin is not able to display the subtitles. When enabling a subtitle in the web app, the network analyzer shows a 500 http error code immediately.

I noticed this on the earlier versions too, but I though it might be caused by the migrated emby 3.5.3 database I used. Retried this with a new jellyfin database and current docker image.

jellyfin log:
```
[...]
2018-12-21 10:28:14.803 Info HttpServer: HTTP GET http://example.com:8096/emby/Videos/43d37ad42dcebfc89a5fbde518b84277/43d37ad42dcebfc89a5fbde518b84277/Subtitles/3/0/Stream.vtt. Host=example.com, User-Agent=Mozilla/5.0 (X11; Linux x86_64; rv:60.0) 
2018-12-21 10:28:14.817 Error HttpServer: Error processing request
	*** Error Report ***
	Version: 3.5.2.0
	Command line: /jellyfin/jellyfin.dll -programdata /config
	Operating system: Unix 4.9.0.8
	64-Bit OS: True
	64-Bit Process: True
	User Interactive: True
	Processor count: 2
	Program data path: /config
	Application directory: /jellyfin
	System.NullReferenceException: Object reference not set to an instance of an object.
	   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken) in /repo/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 131
	   at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request) in /repo/MediaBrowser.Api/Subtitles/SubtitleService.cs:line 228
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 114
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660
	System.NullReferenceException
	   at MediaBrowser.MediaEncoding.Subtitles.SubtitleEncoder.MediaBrowser.Controller.MediaEncoding.ISubtitleEncoder.GetSubtitles(BaseItem item, String mediaSourceId, Int32 subtitleStreamIndex, String outputFormat, Int64 startTimeTicks, Int64 endTimeTicks, Boolean preserveOriginalTimestamps, CancellationToken cancellationToken) in /repo/MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:line 131
	   at MediaBrowser.Api.Subtitles.SubtitleService.Get(GetSubtitle request) in /repo/MediaBrowser.Api/Subtitles/SubtitleService.cs:line 228
	   at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /repo/Emby.Server.Implementations/Services/ServiceExec.cs:line 114
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/Services/ServiceHandler.cs:line 96
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /repo/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 660
2018-12-21 10:28:14.817 Info HttpServer: HTTP Response 500 to 10.79.64.42. Time: 14ms. http://example.com:8096/emby/Videos/43d37ad42dcebfc89a5fbde518b84277/43d37ad42dcebfc89a5fbde518b84277/Subtitles/3/0/Stream.vtt 
[...]
```

### PR DESCRIPTION
**Pull request by cvium**
**Changes**
Changed a nullable long to a non-nullable.

Problem was that endTimeTicks was always 0 for (at least) direct streams and then it filtered out any timestamps that were not before the endtime...
**Issues**
Fixes #254

### CODE REVIEW

**Comment by cvium** [comment]
This PR should be merged with #598, BUT if #598 is postponed, we should cherry pick this line: https://github.com/jellyfin/jellyfin/pull/598/files#diff-fec17a889e496ad8426f3388eeabf537R201

The code page provider fix is _high priority_ since .NET Core by default has a LOT LESS code pages enabled than standard .NET.

File: MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs [hunk 1]
```diff
@@ -94,16 +94,16 @@ public class SubtitleEncoder : ISubtitleEncoder
...
             // Drop subs that are earlier than what we're looking for
             track.TrackEvents = track.TrackEvents
                 .SkipWhile(i => (i.StartPositionTicks - startPositionTicks) < 0 || (i.EndPositionTicks - startPositionTicks) < 0)
                 .ToArray();
 
-            if (endTimeTicks.HasValue)
+            if (endTimeTicks > 0)
             {
-                long endTime = endTimeTicks.Value;
+                long endTime = endTimeTicks;
```
Comment (nvllsvm) [inline MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs]: The `endTime` variable is redundant now that `endTimeTicks` is no longer `long?`. Please remove it.

Comment (cvium) [reply MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs]: Yes. I guess I wasn't being super critical when I submitted this PR lol.

**Comment by nvllsvm** [comment]
Nice fix, thank you!
