### PR TITLE
Fix the wrong logic in HEVC VP9 10bit hwdec boxes

### LINKED ISSUE #6606: CUDA/NVDEC Hardware Acceleration not being applied to transcode command
**Describe the bug**

When a stream that requires transcoding starts, hwaccel or decode flags are not applied to the ffmpeg command. This is with an HEVC 10-bit video (1080p and 4K) on a GTX 1070, which supports HEVC 10-bit decoding.

**System (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS Server
 - Virtualization: QEMU Linux KVM on Proxmox
 - GPU: EVGA GTX 1070 FTW 2
 - Clients:  Web
 - Browser: Chrome 93.0.4577.82
 - Jellyfin Version: 10.7.7
 - FFmpeg Version: 4.3.1-Jellyfin
 - Playback: Transcode
 - Hardware Acceleration: NVENC
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host (I'm not sure if this correct)
 - Storage: Boot is Linux LVM in Proxmox, video file is served via SMB

**To Reproduce**

1. Enable Nvidia NVENC hardware acceleration under Dashboard > Playback
2. Enable H264, HEVC, and all others under "Enable hardware decoding for"
3. Check "Enable 10-Bit hardware decoding for HEVC"
4. Check "Enable hardware encoding"
5. Click Save
6. Play video in Chrome browser that is HEVC 10 bit source
7. Transcoding works, but the ffmpeg log file doesn't show `-hwaccel` as a flag.

**Expected behavior**

Since the GTX 1070 supports HEVC 8, 10, and 12 bit decoding according to the NVIDIA Encode/Decode matrix, the ffmpeg command should include `-hwaccel` and the video should be decoded with NVDEC.

**Server Logs**

No log errors, but here is what it says about decoders, encoders, and hardware acceleration:
```
[2021-09-24 08:09:55.521 +00:00] [INF] Found ffmpeg version "4.3.1"
[2021-09-24 08:09:55.546 +00:00] [INF] Available "decoders": ["h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8_cuvid", "vp8_qsv", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[2021-09-24 08:09:55.556 +00:00] [INF] Available "encoders": ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[2021-09-24 08:09:55.565 +00:00] [INF] Available hwaccel types: ["vdpau", "cuda", "vaapi", "qsv", "drm", "opencl"]
[2021-09-24 08:09:55.566 +00:00] [INF] FFmpeg: Custom: "/usr/lib/jellyfin-ffmpeg/ffmpeg"
```

**FFmpeg Logs**

No errors, but here is the command line example for one video:
```
/usr/lib/jellyfin-ffmpeg/ffmpeg -ss 00:16:06.000 -noaccurate_seek \
-i file:"/[1080p HEVCvideo].mkv" -map_metadata -1 -map_chapters \
-1 -threads 2 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc \
-pix_fmt yuv420p -preset fast -b:v 5547988 -maxrate 5547988 \
-bufsize 11095976 -profile:v:0 high -g:v:0 72 -keyint_min:v:0 72 \
-sc_threshold:v:0 0 \
-vf "scale=trunc(min(max(iw\,ih*dar)\,min(1920\,816*dar))/2)*2:trunc(min(max(iw/dar\,ih)\,min(1920/dar\,816))/2)*2" \
-start_at_zero -vsync -1 -codec:a:0 copy -strict -2 -copyts \
-avoid_negative_ts disabled -max_muxing_queue_size 4096 \
-f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts \
-start_number 322 \
-hls_segment_filename "/var/lib/jellyfin/transcodes/7c9fe8fafe4e929fe13c802d8557e6e6%d.ts" \
-hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/7c9fe8fafe4e929fe13c802d8557e6e6.m3u8"
```

**Browser Console Logs**

No browser log errors.

**Screenshots**

**Additional context**

I have also tried without Tone Mapping, as well as turning off the advanced NVDEC checkbox.

I also tried a 1080p H264 8 bit source to see what would happen. It seems to have applied cuda hwaccel, but I don't believe it applied nvdec. Though, it managed only 10% CPU on 10 cores and was transcoding at about 400 FPS.

```
/usr/lib/jellyfin-ffmpeg/ffmpeg -hwaccel cuda -hwaccel_output_format cuda \
-extra_hw_frames 3 -autorotate 0 -i file:"/var/archive/.data/Movies/h264_8bit_movie.mkv" \
-map_metadata -1 -map_chapters -1 -threads 2 -map 0:0 -map 0:1 -map -0:s \
-codec:v:0 h264_nvenc -preset fast -b:v 2616000 -maxrate 2616000 \
-bufsize 5232000 -profile:v:0 high -g:v:0 72 -keyint_min:v:0 72 -sc_threshold:v:0 0 \
-vf "scale_cuda=w=1280:h=720:format=nv12" -start_at_zero -vsync -1 \
-codec:a:0 aac -ac 2 -ab 384000 -copyts -avoid_negative_ts disabled \
-max_muxing_queue_size 4096 -f hls -max_delay 5000000 -hls_time 3 \
-hls_segment_type mpegts -start_number 0 -hls_segment_filename "/var/lib/jellyfin/transcodes/faeebdfe492ed7caadcc1d7c0882c842%d.ts" \
-hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/faeebdfe492ed7caadcc1d7c0882c842.m3u8"
```

### PR DESCRIPTION
**Pull request by nyanmisaka**
The two boxes should be independent of each other according to the codec.

**Changes**
- Fix the wrong logic in HEVC VP9 10bit hwdec boxes

**Issues**
Fixes #6606

### CODE REVIEW

**Review by 1337joe — APPROVED** [review]

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 1]
```diff
@@ -4305,8 +4305,16 @@ public string GetHwDecoderName(EncodingOptions options, string decoderPrefix, st
             var isCodecAvailable = _mediaEncoder.SupportsDecoder(decoderName) && options.HardwareDecodingCodecs.Contains(videoCodec, StringComparer.OrdinalIgnoreCase);
             if (bitDepth == 10 && isCodecAvailable)
             {
-                if ((options.HardwareDecodingCodecs.Contains("hevc", StringComparer.OrdinalIgnoreCase) && !options.EnableDecodingColorDepth10Hevc)
-                    || (options.HardwareDecodingCodecs.Contains("vp9", StringComparer.OrdinalIgnoreCase) && !options.EnableDecodingColorDepth10Vp9))
+                if (string.Equals(videoCodec, "hevc", StringComparison.OrdinalIgnoreCase)
+                    && options.HardwareDecodingCodecs.Contains("hevc", StringComparer.OrdinalIgnoreCase)
```
Comment (cvium) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:4309]: You should use our extension method that uses StringComparison

**Review by cvium — CHANGES_REQUESTED** [review]

**Review by cvium — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]

**Review by crobibero — APPROVED** [review]
