### PR TITLE
Fix track MBID in audio metadata

### LINKED ISSUE #11020: [Issue]: Invalid MusicBrainz track ID values in song/track metadata
### Please describe your bug

During file scan, Jellyfin incorrectly sets a MusicBrainz `recording` ID to a `track` ID field in song/track metadata (these are not the same, the hierarchy is explained [here](https://musicbrainz.org/doc/Recording)).

In Jellyfin `10.8.x`, the value is set correctly, as that one uses older method of getting the metadata, which was then refactored for `10.9.x` in https://github.com/jellyfin/jellyfin/pull/7514

After looking into it, it seems that `TagLib` incorrectly reads the values from the file and then returns a MusicBrainz `recording` ID value as a `track` ID. This can be seen when debugging `AudioFileProber`, specifically looking into the `tags` variable just after `TagLib` reads the metadata:

https://github.com/jellyfin/jellyfin/blob/2bd85df383ec70251a8cdf9802963e29b52b60a4/MediaBrowser.Providers/MediaInfo/AudioFileProber.cs#L231-L264

And there's an [issue report](https://github.com/mono/taglib-sharp/issues/304) in the taglib-sharp repository as well - which looks like has a pull request with a fix, but as the repository does not seem very active, I guess there's not much hope getting the fix merged.

### Reproduction Steps

1. Have an audio file with MusicBrainz ID metadata
2. Add file to a Jellyfin Music library
3. Scan for metadata
4. Compare MusicBrainz IDs in Jellyfin with the ones written in the file
5. Observe invalid track MBID value (matching recording MBID) - see attached screenshot

### Jellyfin Version

Unstable (master branch)

### if other:

commit 03ef9aebfd5b41d444172aab5a21e0d6671c90b1

### Environment

```markdown
- OS:Linux
- Linux Kernel: 6.7.4-zen1-1-zen
- Virtualization: None
- Clients: Browser
- Browser: Firefox 115.7.0esr
- FFmpeg Version: n6.1.1
- Playback Method: Direct
- Hardware Acceleration: No
- GPU Model: Radeon RX 6700 XT
- Plugins: Built-in + ListenBrainz
- Reverse Proxy: No
- Base URL: None
- Networking: Host
- Storage: Local
```

### Jellyfin logs

There's not much to show, apart from scanning the file, which does not produce any errors.
```shell
[11:20:49] [DBG] [23] MediaBrowser.Providers.Music.AudioMetadataService: Running ProbeProvider for /mnt/data/stash/moozik/Binärpilot/Promo/01 Thunderdays.mp3
[11:20:49] [INF] [23] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mnt/data/stash/moozik/Binärpilot/Promo/01 Thunderdays.mp3" -threads 0 -v warning -print_format json -show_streams -show_format
[11:20:50] [DBG] [23] MediaBrowser.Providers.MediaInfo.AudioFileProber: LUFS for Thunderdays is -9.3.
```

### FFmpeg logs

Issue is not related to playback.

### Please attach any browser or client logs here

Issue is not related to UI/UX or playback.

### Please attach any screenshots here

Side-by-side view of values in Jellyfin in comparison to what's written in the file metadata:
image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

Edit: formatting

### PR DESCRIPTION
**Pull request by lyarenei**
**Changes**

Fall back to ffprobe to get a correct value for track MBID.

**Issues**

Fixes #11020

### CODE REVIEW

File: MediaBrowser.Providers/MediaInfo/AudioFileProber.cs [hunk 1]
```diff
@@ -407,7 +407,13 @@ private async Task FetchDataFromTags(Audio audio, MetadataRefreshOptions options
 
                 if (options.ReplaceAllMetadata || !audio.TryGetProviderId(MetadataProvider.MusicBrainzTrack, out _))
                 {
-                    audio.SetProviderId(MetadataProvider.MusicBrainzTrack, tags.MusicBrainzTrackId);
+                    // Fallback to ffprobe as TagLib incorrectly provides recording MBID in `tags.MusicBrainzTrackId`.
```
Comment (Shadowghost) [inline MediaBrowser.Providers/MediaInfo/AudioFileProber.cs:410]: Can you please link the issue on taglib for future reference?

**Review by Shadowghost — APPROVED** [review]

**Review by crobibero — APPROVED** [review]
