### PR TITLE
Always fetch episode id as EpisodeInfo does not contain it

### LINKED ISSUE #1467: Using "Identify" on a series with the "TheTvDB" provider sets wrong episode description/name/image
**Describe the bug**
Incorrect episode name/description/image for TheTvDB metadata provider

**To Reproduce**
 - add a TV Shows library with a folder structure like
  Love.Death.and.Robots.S01.1080p.NF.WEB-DL.DDP5.1.x264-NTG/Love.Death.and.Robots.S01E01.Sonnies.Edge.1080p.NF.WEB-DL.DDP5.1.x264-NTG.mkv
 Love.Death.and.Robots.S01.1080p.NF.WEB-DL.DDP5.1.x264-NTG/Love.Death.and.Robots.S01E02.Three.Robots.1080p.NF.WEB-DL.DDP5.1.x264-NTG.mkv
 - browse to the show in the library and call identify with the TvDB id 357888 and replace all existing images
 - the show description and image are correct since the correct series id 357888 was used
 - the episodes all show the name "Avsnitt 2" as the series id 357888 was used instead of actually resolving each episode id

**Code version**
master branch with latest commit SHA-1: 2baddc17092ed466c84faf7a02ab1b5321e664a0
release 10.3.5
release 10.3.3

**Additional context**
In 3 locations a pattern of code exists that uses the series ID ( searchInfo.GetProviderId(MetadataProviders.Tvdb); ) instead of resolving the episode ID.

> MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeProvider.cs
```
public async Task<IEnumerable<RemoteSearchResult>> GetSearchResults(EpisodeInfo searchInfo, CancellationToken cancellationToken)
public async Task<MetadataResult<Episode>> GetMetadata(EpisodeInfo searchInfo, CancellationToken cancellationToken)
```

> MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeImageProvider.cs
```
public async Task<IEnumerable<RemoteImageInfo>> GetImages(BaseItem item, CancellationToken cancellationToken)
```

> Code where tvdbId is "357888" from the searchInfo instead of resolving the actual episode ID
```
                var tvdbId = searchInfo.GetProviderId(MetadataProviders.Tvdb);
                try
                {
                    if (string.IsNullOrEmpty(tvdbId))
                    {
                        tvdbId = await _tvDbClientManager
                            .GetEpisodeTvdbId(searchInfo, searchInfo.MetadataLanguage, cancellationToken)
                            .ConfigureAwait(false);
                        if (string.IsNullOrEmpty(tvdbId))
                        {
                            _logger.LogError("Episode {SeasonNumber}x{EpisodeNumber} not found for series {SeriesTvdbId}",
                                 searchInfo.ParentIndexNumber, searchInfo.IndexNumber, tvdbId);
                            return result;
                        }
                    }
```

### PR DESCRIPTION
**Pull request by cvium**
**Changes**
Apparently, EpisodeInfo.ProviderIds == EpisodeInfo.SeriesProviderIds because who doesn't love duplicated data...

Credit goes to @marius-luca-87
**Issues**
Fixes #1467

### CODE REVIEW

File: MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeImageProvider.cs [hunk 1]
```diff
@@ -50,27 +50,22 @@ public async Task<IEnumerable<RemoteImageInfo>> GetImages(BaseItem item, Cancell
...
-                        };
-                        episodeTvdbId = await _tvDbClientManager
-                            .GetEpisodeTvdbId(episodeInfo, language, cancellationToken).ConfigureAwait(false);
-                        if (string.IsNullOrEmpty(episodeTvdbId))
-                        {
-                            _logger.LogError("Episode {SeasonNumber}x{EpisodeNumber} not found for series {SeriesTvdbId}",
-                                episodeInfo.ParentIndexNumber, episodeInfo.IndexNumber, series.GetProviderId(MetadataProviders.Tvdb));
-                            return imageResult;
-                        }
+                        _logger.LogError("Episode {SeasonNumber}x{EpisodeNumber} not found for series {SeriesTvdbId}",
```
Comment (Bond-009) [inline MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeImageProvider.cs]: When splitting parameters into multiple lines every parameter should get its own line.

Comment (cvium) [reply MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeImageProvider.cs]: Also the first one?

Comment (Bond-009) [reply MediaBrowser.Providers/TV/TheTVDB/TvdbEpisodeImageProvider.cs]: Yes, or the analyzers will scream at you.
