### PR TITLE
Fix explicit stream selection in MediaEncoder.ExtractImageInternal

### LINKED ISSUE #6424: [Bug] "Image Extractor" fails for some audio files with embedded images
**Describe the bug**
I was looking at the server logs and saw errors when Jellyfin was trying to extract images from a lot of my audio files:

```
[2021-08-14 07:02:25.428 +00:00] [ERR] [73] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: ffmpeg image extraction failed for file:"/path/to/audio/file.m4a"
[2021-08-14 07:02:25.428 +00:00] [ERR] [73] MediaBrowser.Providers.Books.AudioBookMetadataService: Error in "Image Extractor"
System.Exception: ffmpeg image extraction failed for file:"/path/to/audio/file.m4a"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String[] inputFiles, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaProtocol protocol, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioImageProvider.GetImage(Audio item, List`1 imageStreams, CancellationToken cancellationToken)
```

I did some digging and it seems like the MediaEncoder logic for selecting the image stream from an audio file is wrong. The ffmpeg argument string it builds leads to an error in FFmpeg:

```
Stream map '0:v:1' matches no streams.
To ignore this, add a trailing '?' to the map.
```

The file in question has the image stream at absolute index 2. If you look through the logic for selecting the stream, that absolute index is passed in to `ExtractImage`, then 1 is subtracted for some reason if the index is greater than 0, and then that resulting number is used to build the `map` parameter that's passed to FFmpeg (`0:v:1`).

Looking at the syntax for the `map` parameter, though, when the stream specifier is included, the stream index should be the index *of that type of stream*. So in the above example (`0:v:1`), FFmpeg is looking for the 2nd **v**ideo stream, but there is only one video stream in the file, thus the failure.

The problem is masked somewhat for any audio files where the image is in stream 0 or 1, because of the extra subtraction, both of those will result in `0:v:0`, so FFmpeg finds the first video stream in the file and the image is extracted from that.

I'll add that, for video files, the `imageStreamIndex` passed in to `ExtractImage` is the Nth **video stream** in the file, not the absolute stream index, so I believe that should currently work.

I intend to open a Pull Request with what I believe to be a fix to this issue, which removes the stream specifier from the `map` parameter and just passes the absolute index for both audio and video files to `ExtractImage`.

**System (please complete the following information):**
 - OS: Windows & Ubuntu
 - Virtualization: None on Windows; Docker on Ubuntu
 - Clients: Browser
 - Browser: Firefox 91.0
 - Jellyfin Version: master & 10.6.4.0
 - Playback: N/A
 - Hardware Acceleration: none
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: none
 - Networking: Host
 - Storage: SMB share

**To Reproduce**
Add an audio file with the first image stream at index 2 or greater in the file to an audiobook/music library

**Expected behavior**
The cover image is extracted successfully

**Server Logs**
```
[2021-08-14 07:02:25.428 +00:00] [ERR] [73] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: ffmpeg image extraction failed for file:"/path/to/audio/file.m4a"
[2021-08-14 07:02:25.428 +00:00] [ERR] [73] MediaBrowser.Providers.Books.AudioBookMetadataService: Error in "Image Extractor"
System.Exception: ffmpeg image extraction failed for file:"/path/to/audio/file.m4a"
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImageInternal(String inputPath, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, Nullable`1 threedFormat, Nullable`1 offset, Boolean useIFrame, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ExtractImage(String[] inputFiles, String container, MediaStream videoStream, Nullable`1 imageStreamIndex, MediaProtocol protocol, Boolean isAudio, Nullable`1 threedFormat, Nullable`1 offset, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.AudioImageProvider.GetImage(Audio item, List`1 imageStreams, CancellationToken cancellationToken)
```

### PR DESCRIPTION
**Pull request by boolemancer**
**Changes**
The `map` parameter in the arguments passed to FFmpeg in MediaEncoder.ExtractImageInternal currently requires the `imageStreamIndex` to be the index of **video** streams within that file. For video files, we do extra work to figure out the correct index of the passed-in stream, but for audio files, we just use the absolute index of the stream (minus one, for some reason).

Instead of doing that, this change uses no stream specifier in the `map` parameter, and passes the absolute index for both audio and video files.

See here for more details about the `map` parameter syntax:

https://trac.ffmpeg.org/wiki/Map

The bug below goes into more detail.

**Issues**
Fixes #6424

### CODE REVIEW

File: MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs [hunk 1]
```diff
@@ -503,15 +503,7 @@ public Task<string> ExtractVideoImage(string inputFile, string container, MediaS
         {
             var inputArgument = GetInputArgument(inputFile, mediaSource);
 
-            if (isAudio)
-            {
-                if (imageStreamIndex.HasValue && imageStreamIndex.Value > 0)
-                {
-                    // It seems for audio files we need to subtract 1 (for the audio stream??)
```
Comment (boolemancer) [inline MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs:510]: As far as I can tell, all this did was mask the real issue with stream selection, since things would ultimately work fine for any audio files with 1 audio stream and 1 image stream, regardless of which order they're in. (If audio stream is 0 and image stream is 1, we subtract 1, and `-map 0:v0`, or the first video stream. If image stream is 0 and audio stream is 1, we don't subtract 1, and `-map 0:v:0`, and again extract the first video stream).

If there's other context for why this is being done, I'd be curious to know why, but it seems like this is probably a relic from before the Jellyfin fork?

File: MediaBrowser.Providers/MediaInfo/VideoImageProvider.cs [hunk 2]
```diff
@@ -88,30 +88,14 @@ public async Task<DynamicImageResponse> GetVideoImage(Video item, CancellationTo
 
             if (imageStream != null)
             {
-                // Instead of using the raw stream index, we need to use nth video/embedded image stream
```
Comment (boolemancer) [inline MediaBrowser.Providers/MediaInfo/VideoImageProvider.cs:91]: This is the logic that would cause us to have the correct behavior for video files. The video index is computed as the "Nth video stream".

By using the absolute index, we no longer need to perform this calculation.

File: MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs (hunk 1 above)
Comment (crobibero) [reply MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs:510]: It was added 3 years ago, right before Jellyfin forked.
https://github.com/jellyfin/jellyfin/blob/1d7d52ff9e42c3efb4bb2c65e82a4a82faf9decb/MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs#L636

**Review by cvium — APPROVED** [review]

File: MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs [hunk 3]
```diff
@@ -582,7 +574,7 @@ private async Task<string> ExtractImageInternal(string inputPath, string contain
                 _ => string.Empty
             };
 
-            var mapArg = imageStreamIndex.HasValue ? (" -map 0:v:" + imageStreamIndex.Value.ToString(CultureInfo.InvariantCulture)) : string.Empty;
+            var mapArg = imageStreamIndex.HasValue ? (" -map 0:" + imageStreamIndex.Value.ToString(CultureInfo.InvariantCulture)) : string.Empty;
```
Comment (boolemancer) [inline MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs:577]: Changing this from `-map 0:v:<index>` to `-map 0:<index>`, we tell `ffmpeg` to consider the `<index>` the absolute stream index, instead of the index in the list of video streams.

This means that we can use the `MediaStream.Index` already stored for the stream instead of having to calculate some other index to pass into `ffmpeg`.

**Review by crobibero — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]
