### PR TITLE
Fix empty image folder removal for legacy locations

### LINKED ISSUE #12023: [Issue]: Re-identifying media fails
### Please describe your bug

When media is incorrectly identified and I attempt to provide the correct TMDB ID it fails to apply the new image and only the blur hash is shown.

### Reproduction Steps

1. Go to any media that is identified, correctly or not.
2. Open identify function
3. Provide new TMDB ID

### Jellyfin Version

10.9.0

### if other:

10.9.6

### Environment

```markdown
- OS: Ubuntu 24.04
- Linux Kernel: 6.8.0-35-generic
- Virtualization: n/a
- Clients: Web
- Browser: Google Chrome
- FFmpeg Version: 6.0.1-7
- Playback Method: n/a
- Hardware Acceleration: Intel QSV
- GPU Model: Intel Arc A380
- Plugins: N/A
- Reverse Proxy: Nginx
- Base URL: n/a
- Networking: n/a
- Storage: NVMe for OS/Jellyfin, HDD RAIDZ1 for library
```

### Jellyfin logs

```shell
[2024-06-07 19:26:17.276 +00:00] [INF] Setting provider id's to item e97948ce-98f7-cb30-2217-5e9804532a35-"Your Name.": [("Tmdb": "372058"), ("Imdb": "tt5311514")]
[2024-06-07 19:26:17.289 +00:00] [ERR] Error processing request: "Directory not empty : '/var/lib/jellyfin/metadata/library/e9/e97948ce98f7cb3022175e9804532a35'". URL "POST" "/Items/RemoteSearch/Apply/e97948ce98f7cb3022175e9804532a35".
[2024-06-07 19:27:26.559 +00:00] [INF] WS "Client WAN" closed
[2024-06-07 19:27:27.859 +00:00] [INF] WS "Client WAN" request
[2024-06-07 19:27:28.397 +00:00] [INF] Creating image collage and saving to "/var/cache/jellyfin/temp/cf9a6fde1b364215848daa9a3197a083.png"
[2024-06-07 19:27:28.851 +00:00] [INF] Completed creation of image collage and saved to "/var/cache/jellyfin/temp/cf9a6fde1b364215848daa9a3197a083.png"
[2024-06-07 19:27:30.590 +00:00] [ERR] Error processing request: "Could not find file '/var/lib/jellyfin/metadata/library/e9/e97948ce98f7cb3022175e9804532a35/poster.jpg'". URL "GET" "/Items/e97948ce98f7cb3022175e9804532a35/Images/Primary".
[2024-06-07 19:27:43.864 +00:00] [ERR] Error processing request: "Could not find file '/var/lib/jellyfin/metadata/library/e9/e97948ce98f7cb3022175e9804532a35/poster.jpg'". URL "GET" "/Items/e97948ce98f7cb3022175e9804532a35/Images/Primary".
```

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

Capture

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Shadowghost**
Regression from #11934
Recursive removal is too wide scoped, so limit it to remove the legacy `metadata` directory for episodes

**Changes**
* Limit scope of empty directory removal after image removal
* Add helper class for recursive empty folder removal
* Do not remove images from items if they could not be removed from the file system

**Issues**
Fixes #12023 (potentially)

### CODE REVIEW

**Review by crobibero — APPROVED** [review]

File: MediaBrowser.Providers/Manager/ItemImageProvider.cs [hunk 1]
```diff
@@ -377,15 +376,17 @@ private void PruneImages(BaseItem item, IReadOnlyList<ItemImageInfo> images)
...
-                        }
-                    }
+                }
+            }
+
+            // Cleanup old metadata directory for episodes if empty
+            if (item is Episode)
+            {
+                var oldLocalMetadataDirectory = Path.Combine(item.ContainingFolderPath, "metadata");
+                var localImages = images.Where(i => i.Path.StartsWith(oldLocalMetadataDirectory, StringComparison.Ordinal)).ToList();
```
Comment (Bond-009) [inline MediaBrowser.Providers/Manager/ItemImageProvider.cs:386]: This is unused?

**Review by Bond-009 — CHANGES_REQUESTED** [review]

**Review by Bond-009 — APPROVED** [review]
