### PR TITLE
Fix SAMI UTF-16 Encoding Bug

### LINKED ISSUE #2859: Unicode problem with .smi
**Describe the bug**

Since 10.5.x, subtitles do not appear in most videos
Looking at the log, the video with subtitles is encoded as euc-kr, and the video with no subtitles is encoded as utf-16le.

**System (please complete the following information):** 
os : sysnology nas docker
ver : 10.5.4
web : chrome

**To Reproduce**

2 new videos that were not in the library (or rename the video) (maybe subtitle cache)
Same subtitle encoded asni or utf-8 and utf-16le
Video playback

asni, utf-8 video has subtitles
utf-16le video does not have subtitles

**Logs**

[Log.txt](https://github.com/jellyfin/jellyfin/files/4470293/Log.txt)
line 292, 306

[test-sub.zip](https://github.com/jellyfin/jellyfin/files/4470325/test-sub.zip)
Same subtitles with different encodings

**Additional context**

The easiest solution to add a character language setting to encode

It also loses the country mark in the process of converting subtitles.
Subtitle preference option is useless
캡처

And also Korean .ass problem like #2670 [web#934](https://github.com/jellyfin/jellyfin-web/issues/934)

### PR DESCRIPTION
**Pull request by HelloWorld017**
**Changes**
When it is UTF-16BE or UTF-16LE, we must not specify character encoding.
Previously, the jellyfin didn't specify when it is in UPPERCASE (by Pull-Request #1540) but we should not specify it even when it is lowercase, too.
This patch fixes the issue coming from the behaviour by making it not to specify even it is in lowercase.

**Issues**
Fixes #2859

### CODE REVIEW

File: MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs [hunk 1]
```diff
@@ -426,7 +426,13 @@ private async Task ConvertTextSubtitleToSrtInternal(string inputPath, string lan
...
             // FFmpeg automatically convert character encoding when it is UTF-16
             // If we specify character encoding, it rejects with "do not specify a character encoding" and "Unable to recode subtitle event"
-            if ((inputPath.EndsWith(".smi") || inputPath.EndsWith(".sami")) && (encodingParam == "UTF-16BE" || encodingParam == "UTF-16LE"))
+            if (
+                (inputPath.EndsWith(".smi") || inputPath.EndsWith(".sami")) &&
+                (
+                    encodingParam.Equals("UTF-16BE", StringComparison.OrdinalIgnoreCase) ||
+                    encodingParam.Equals("UTF-16LE", StringComparison.OrdinalIgnoreCase)
+                )
+            )
```
Comment (crobibero) [inline MediaBrowser.MediaEncoding/Subtitles/SubtitleEncoder.cs:435]:
```suggestion
            if ((inputPath.EndsWith(".smi") || inputPath.EndsWith(".sami")) &&
                (encodingParam.Equals("UTF-16BE", StringComparison.OrdinalIgnoreCase) ||
                 encodingParam.Equals("UTF-16LE", StringComparison.OrdinalIgnoreCase)))
```
