### PR TITLE
Fix for NVDEC decoder and improvements for VAAPI tonemap

### LINKED ISSUE #4879: Black/Green Screen (and other weird issues) while playback ( Nvidia HEVC Transcoding)
Just wanted to bring this up here aswell, as i reported the same Problem over at the Emby forums and it is fixed there now.

For some movies (i couldnt precisely tell or why, just some) playback results in a black screen that would turn into a normal screen sometime, going back to a black screen or green screen, split screen or some other weird variation of playback like video and audio desync. 

I checked everything (the hardware, software, movie, reinstalled everything and god knows what else i tried).
The solution over at Emby was to implement another Hardware Decoder (NVDEC.EX) in the latest Version, which instantly fixed the problem, so i assume its a problem with the decoder.

It would be nice, if this decoder, or some variation, could be implemented into Jellyfin aswell.

### LINKED ISSUE #4947: Playback is green/broken on some media but files are okay, playback comes good after several minutes, then goes green again
**Media Info of the file**
Title4K HEVC
CodecHEVC
ProfileMain 10
Level153
Resolution3840x2160
Aspect ratio16:9
InterlacedNo
Framerate23.976025
Bitrate55526 kbps
Pixel formatyuv420p10le
Ref frames1

TitleEng TRUEHD 7.1 Default
Languageeng
CodecTRUEHD
Layout7.1
Channels8 ch
Sample rate48000 Hz
Bit depth24 bit
DefaultYes

**Logs**
[09:05:15] [INF] [66] MediaBrowser.Api.Playback.Hls.DynamicHlsService: /usr/lib/jellyfin-ffmpeg/ffmpeg -c:v hevc_cuvid -resize 3840x2160 -i file:"/media/movies/Star.Wars.Episode.III.Revenge.of.the.Sith.2005.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT/Star.Wars.Episode.III.Revenge.of.the.Sith.2005.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -pix_fmt yuv420p -preset slow -b:v 79616000 -maxrate 79616000 -bufsize 159232000 -profile:v high  -g 72 -keyint_min 72 -sc_threshold 0 -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000 -af "volume=2" -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/transcodes/cc36e0d038097e4f13acb745ad00cf14%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/cc36e0d038097e4f13acb745ad00cf14.m3u8"
[09:05:15] [DBG] [99] MediaBrowser.Api.Playback.Hls.DynamicHlsService: Launched ffmpeg process
[09:05:15] [DBG] [99] MediaBrowser.Api.Playback.Hls.DynamicHlsService: Waiting for the creation of /config/transcodes/cc36e0d038097e4f13acb745ad00cf140.ts
[09:05:18] [DBG] [164] MediaBrowser.Api.Playback.Hls.DynamicHlsService: File /config/transcodes/cc36e0d038097e4f13acb745ad00cf140.ts created or transcoding has finished
[09:05:18] [DBG] [164] MediaBrowser.Api.Playback.Hls.DynamicHlsService: StartFfMpeg() finished successfully
[09:05:18] [DBG] [164] MediaBrowser.Api.Playback.Hls.DynamicHlsService: returning /config/transcodes/cc36e0d038097e4f13acb745ad00cf140.ts [general case]
[09:05:19] [DBG] [159] MediaBrowser.Api.Playback.Hls.DynamicHlsService: serving up /config/transcodes/cc36e0d038097e4f13acb745ad00cf140.ts as it deemed ready
[09:05:19] [DBG] [159] Emby.Server.Implementations.HttpServer.HttpResultFactory: Transmit file /config/transcodes/cc36e0d038097e4f13acb745ad00cf140.ts
[09:05:19] [DBG] [159] MediaBrowser.Api.Playback.Hls.DynamicHlsService: finished serving /config/transcodes/cc36e0d038097e4f13acb745ad00cf140.ts
[09:05:19] [DBG] [159] MediaBrowser.Api.ApiEntryPoint: OnTranscodeEndRequest job.ActiveRequestCount=0
[09:05:19] [DBG] [159] MediaBrowser.Api.ApiEntryPoint: Starting kill timer at 60000ms. JobId 8e51130d0bb147e2bf585cde3cc6afeb PlaySessionId c7ac2a3c48714a289e4fbd52f53cd175
[09:05:19] [WRN] [159] Emby.Server.Implementations.HttpServer.HttpListenerHost: HTTP Response 200 to 10.0.0.244. Time (slow): 0:00:03.8420791. http://jellyfin.pandanet.xyz/videos/5aacb369-a3f6-4dea-f1e7-752e4922651b/hls1/main/0.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODIuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84Mi4wfDE2MDU3ODg5NjM2MjM1&MediaSourceId=5aacb369a3f64deaf1e7752e4922651b&VideoCodec=h264&AudioCodec=mp3,aac&AudioStreamIndex=1&VideoBitrate=79616000&AudioBitrate=384000&PlaySessionId=c7ac2a3c48714a289e4fbd52f53cd175&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=6ad4cb7e3de5bcddbc875920b9ae2a49&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-deinterlace=true&TranscodeReasons=VideoCodecNotSupported
[09:05:19] [DBG] [164] MediaBrowser.Api.Playback.Hls.DynamicHlsService: returning /config/transcodes/cc36e0d038097e4f13acb745ad00cf141.ts [it exists, try 1]
[09:05:19] [DBG] [181] MediaBrowser.Api.Playback.Hls.DynamicHlsService: Starting transcoding because segmentGap is 443 and max allowed gap is 8. requestedIndex=444
[09:05:19] [DBG] [181] MediaBrowser.Api.ApiEntryPoint: KillTranscodingJob - JobId 8e51130d0bb147e2bf585cde3cc6afeb PlaySessionId c7ac2a3c48714a289e4fbd52f53cd175. Killing transcoding
[09:05:19] [INF] [181] MediaBrowser.Api.ApiEntryPoint: Stopping ffmpeg process with q command for /config/transcodes/cc36e0d038097e4f13acb745ad00cf14.m3u8
[09:05:19] [DBG] [164] Emby.Server.Implementations.HttpServer.HttpResultFactory: Transmit file /cache/images/resized-images/4/4ad4fcd8-f4bf-e7b1-07bd-a3360c2a7373.webp
[09:05:20] [DBG] [131] MediaBrowser.Api.Playback.Hls.DynamicHlsService: serving up /config/transcodes/cc36e0d038097e4f13acb745ad00cf141.ts as it deemed ready
[09:05:20] [DBG] [131] Emby.Server.Implementations.HttpServer.HttpResultFactory: Transmit file /config/transcodes/cc36e0d038097e4f13acb745ad00cf141.ts
[09:05:20] [DBG] [131] MediaBrowser.Api.Playback.Hls.DynamicHlsService: finished serving /config/transcodes/cc36e0d038097e4f13acb745ad00cf141.ts
[09:05:20] [DBG] [131] MediaBrowser.Api.ApiEntryPoint: OnTranscodeEndRequest job.ActiveRequestCount=0
[09:05:20] [DBG] [131] MediaBrowser.Api.ApiEntryPoint: Starting kill timer at 60000ms. JobId 8e51130d0bb147e2bf585cde3cc6afeb PlaySessionId c7ac2a3c48714a289e4fbd52f53cd175
[09:05:20] [ERR] [131] Emby.Server.Implementations.HttpServer.HttpListenerHost: Error processing request: A task was canceled. URL: http://jellyfin.pandanet.xyz/videos/5aacb369-a3f6-4dea-f1e7-752e4922651b/hls1/main/1.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODIuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84Mi4wfDE2MDU3ODg5NjM2MjM1&MediaSourceId=5aacb369a3f64deaf1e7752e4922651b&VideoCodec=h264&AudioCodec=mp3,aac&AudioStreamIndex=1&VideoBitrate=79616000&AudioBitrate=384000&PlaySessionId=c7ac2a3c48714a289e4fbd52f53cd175&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=6ad4cb7e3de5bcddbc875920b9ae2a49&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-deinterlace=true&TranscodeReasons=VideoCodecNotSupported
[09:05:20] [DBG] [131] Emby.Server.Implementations.HttpServer.HttpListenerHost: Sending HTTP Response 500 in response to http://jellyfin.pandanet.xyz/videos/5aacb369-a3f6-4dea-f1e7-752e4922651b/hls1/main/1.ts?DeviceId=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6ODIuMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC84Mi4wfDE2MDU3ODg5NjM2MjM1&MediaSourceId=5aacb369a3f64deaf1e7752e4922651b&VideoCodec=h264&AudioCodec=mp3,aac&AudioStreamIndex=1&VideoBitrate=79616000&AudioBitrate=384000&PlaySessionId=c7ac2a3c48714a289e4fbd52f53cd175&SubtitleMethod=Encode&TranscodingMaxAudioChannels=2&RequireAvc=false&Tag=6ad4cb7e3de5bcddbc875920b9ae2a49&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-deinterlace=true&TranscodeReasons=VideoCodecNotSupported
[09:05:20] [DBG] [181] MediaBrowser.Api.Playback.Hls.DynamicHlsService: Disposing stream resources
[09:05:20] [INF] [181] MediaBrowser.Api.Playback.Hls.DynamicHlsService: FFMpeg exited with code 0
[09:05:20] [DBG] [181] MediaBrowser.Api.Playback.Hls.DynamicHlsService: Deleting partial HLS file /config/transcodes/cc36e0d038097e4f13acb745ad00cf142.ts
[09:05:20] [INF] [181] MediaBrowser.Api.Playback.Hls.DynamicHlsService: Current HLS implementation doesn't support non-keyframe breaks but one is requested, ignoring that request
[09:05:20] [INF] [181] MediaBrowser.Api.Playback.Hls.DynamicHlsService: /usr/lib/jellyfin-ffmpeg/ffmpeg -ss 00:22:12.000 -c:v hevc_cuvid -resize 3840x2160 -noaccurate_seek -i file:"/media/movies/Star.Wars.Episode.III.Revenge.of.the.Sith.2005.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT/Star.Wars.Episode.III.Revenge.of.the.Sith.2005.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -pix_fmt yuv420p -preset slow -b:v 79616000 -maxrate 79616000 -bufsize 159232000 -profile:v high  -g 72 -keyint_min 72 -sc_threshold 0 -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000 -af "volume=2" -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 444 -hls_segment_filename "/config/transcodes/cc36e0d038097e4f13acb745ad00cf14%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/cc36e0d038097e4f13acb745ad00cf14.m3u8"

**FFmpeg Logs**
[09:05:15] [INF] [66] MediaBrowser.Api.Playback.Hls.DynamicHlsService: /usr/lib/jellyfin-ffmpeg/ffmpeg -c:v hevc_cuvid -resize 3840x2160 -i file:"/media/movies/Star.Wars.Episode.III.Revenge.of.the.Sith.2005.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT/Star.Wars.Episode.III.Revenge.of.the.Sith.2005.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -pix_fmt yuv420p -preset slow -b:v 79616000 -maxrate 79616000 -bufsize 159232000 -profile:v high  -g 72 -keyint_min 72 -sc_threshold 0 -start_at_zero -vsync -1 -codec:a:0 libmp3lame -ac 2 -ab 384000 -af "volume=2" -copyts -avoid_negative_ts disabled -f hls -max_delay 5000000 -hls_time 3 -individual_header_trailer 0 -hls_segment_type mpegts -start_number 0 -hls_segment_filename "/config/transcodes/cc36e0d038097e4f13acb745ad00cf14%d.ts" -hls_playlist_type vod -hls_list_size 0 -y "/config/transcodes/cc36e0d038097e4f13acb745ad00cf14.m3u8"
[09:05:15] [DBG] [99] MediaBrowser.Api.Playback.Hls.DynamicHlsService: Launched ffmpeg process
[09:05:15] [DBG] [99] MediaBrowser.Api.Playback.Hls.DynamicHlsService: Waiting for the creation of /config/transcodes/cc36e0d038097e4f13acb745ad00cf140.ts
[09:05:18] [DBG] [164] MediaBrowser.Api.Playback.Hls.DynamicHlsService: File /config/transcodes/cc36e0d038097e4f13acb745ad00cf140.ts created or transcoding has finished
[09:05:18] [DBG] [164] MediaBrowser.Api.Playback.Hls.DynamicHlsService: StartFfMpeg() finished successfully

**Stats for Nerds Screenshots**
https://imgur.com/gallery/Rv8RlvU

**Server System (please complete the following information):**
 - OS: Ubuntu 20.04
 - Jellyfin Version: 10.6.4
 - Hardware settings & device: Ryzen 2700X ( 2vCPU + 8GB RAM, NVIDIA Quadro P620 NVENC/NVDEC )
 - Reverse proxy: HAproxy HTTPS/TLS + local HTTP/8096 access
 - Other hardware notes: Media Mounted via NFS, download/local playback with another player works fine. 
 * cache/local disk: Samsung NVMe 970, NFS RAID10 Ironwolf 4TBs + 10Gig Ethernet
 
**Client System (please complete the following information):**
 - Device: Firefox/Chrome Latest/Chromecast
 - OS: Windows 10/Chomecast Stable, MacO, Android ( all clients )
 - Client: all
 - Browser (if Web client): all
 - Client and Browser Version: all

### PR DESCRIPTION
**Pull request by nyanmisaka**
Web changes:
https://github.com/jellyfin/jellyfin-web/pull/2350

ffmpeg fix:
https://github.com/jellyfin/jellyfin-ffmpeg/pull/59

**Changes**
- Add enhanced NVDEC decoder and format converter
fix green or corrupted frames when decoding some HDR contents. improve transcoding speed.

- Add VPP tonemapping for VAAPI  and QuickSync on Linux
 faster tonemapping speed, **70-120fps 1080p and 30-50fps 4k on HD630** when doing 4k H2S.
 Intel opencl runtime is not required by this method. only available on Intel VAAPI and QSV for now.
 as for AMD VAAPI see https://gitlab.freedesktop.org/mesa/mesa/-/issues/3865

|     | Prerequisites  |
|  ----  | ----  |
| 1  | Intel KabyLake/GeminiLake chips or newer, such as i3-7100 and J4105 |
| 2  | Intel media-driver(iHD) 20.1 or newer |
| 3  | libva 2.4 or newer |
| 4  | the ffmpeg fix linked above |
| 5  | HEVC videos with valid HDR10 metadata |

**Issues**
Fixes #4879
Fixes #4947
Fixes # https://github.com/jellyfin/jellyfin-meta/issues/1#issuecomment-739138464

### CODE REVIEW

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 1]
```diff
@@ -2590,14 +2701,56 @@ private string GetFixedSizeScalingFilter(Video3DFormat? threedFormat, int reques
...
+            // Full hardware based video post processing, faster than OpenCL but lacks fine tuning options.
+            if (isTonemappingSupportedOnVaapi && isVppTonemappingSupported)
+            {
+                filters.Add("tonemap_vaapi=format=nv12:transfer=bt709:matrix=bt709:primaries=bt709");
+            }
+
+            // Another case is when using Nvenc decoder.
+            if (isNvdecDecoder && !isTonemappingSupported)
+            {
+                var codec = videoStream.Codec.ToLowerInvariant();
```
Comment (crobibero) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2714]:
```suggestion
                var codec = videoStream.Codec;
```

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 2]
```diff
@@ -122,6 +129,25 @@ private bool IsTonemappingSupported(EncodingJobInfo state, EncodingOptions optio
...
+            var codec = videoStream.Codec;
+            if (string.Equals(options.HardwareAccelerationType, "vaapi", StringComparison.OrdinalIgnoreCase))
+            {
+                // Limited to HEVC for now since the filter doesn't accept master data from VP9.
+                return IsColorDepth10(state)
+                       && string.Equals(codec, "hevc", StringComparison.OrdinalIgnoreCase)
+                       && _mediaEncoder.SupportsHwaccel("vaapi")
+                       && options.EnableVppTonemapping
+                       && !string.IsNullOrEmpty(videoStream.ColorTransfer)
+                       && videoStream.ColorTransfer.Equals("smpte2084", StringComparison.OrdinalIgnoreCase);
```
Comment (cvium) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:144]: I think you can just use `string.Equals` here

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 3]
```diff
@@ -458,11 +482,13 @@ public string GetInputArgument(EncodingJobInfo state, EncodingOptions encodingOp
             var isVaapiEncoder = outputVideoCodec.IndexOf("vaapi", StringComparison.OrdinalIgnoreCase) != -1;
             var isQsvDecoder = videoDecoder.IndexOf("qsv", StringComparison.OrdinalIgnoreCase) != -1;
             var isQsvEncoder = outputVideoCodec.IndexOf("qsv", StringComparison.OrdinalIgnoreCase) != -1;
-            var isNvdecHevcDecoder = videoDecoder.IndexOf("hevc_cuvid", StringComparison.OrdinalIgnoreCase) != -1;
+            var isNvdecDecoder = videoDecoder.IndexOf("cuda", StringComparison.OrdinalIgnoreCase) != -1;
+            var isCuvidHevcDecoder = videoDecoder.IndexOf("hevc_cuvid", StringComparison.OrdinalIgnoreCase) != -1;
```
Comment (crobibero) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:486]:
```suggestion
            var isNvdecDecoder = videoDecoder.Contains("cuda", StringComparison.OrdinalIgnoreCase);
            var isCuvidHevcDecoder = videoDecoder.Contains("hevc_cuvid", StringComparison.OrdinalIgnoreCase);
```

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 4]
```diff
@@ -112,14 +112,38 @@ private bool IsVaapiSupported(EncodingJobInfo state)
             return _mediaEncoder.SupportsHwaccel("vaapi");
         }
 
+        private bool IsCudaSupported(EncodingJobInfo state)
```
Comment (crobibero) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:115]:
```suggestion
        private bool IsCudaSupported()
```

State is never used

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 5]
```diff
@@ -534,8 +560,17 @@ public string GetInputArgument(EncodingJobInfo state, EncodingOptions encodingOp
...
+                {
+                    if (isNvdecDecoder)
+                    {
+                        arg.Append("-hwaccel_output_format cuda ");
+                    }
+                }
+
+                if (state.IsVideoRequest
+                    && (string.Equals(encodingOptions.HardwareAccelerationType, "nvenc", StringComparison.OrdinalIgnoreCase) && (isNvdecDecoder || isCuvidHevcDecoder || isSwDecoder))
+                        || (string.Equals(encodingOptions.HardwareAccelerationType, "amf", StringComparison.OrdinalIgnoreCase) && (isD3d11vaDecoder || isSwDecoder)))
```
Comment (crobibero) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:573]:
```suggestion
                if ((state.IsVideoRequest
                    && string.Equals(encodingOptions.HardwareAccelerationType, "nvenc", StringComparison.OrdinalIgnoreCase)
                    && (isNvdecDecoder || isCuvidHevcDecoder || isSwDecoder))
                        || (string.Equals(encodingOptions.HardwareAccelerationType, "amf", StringComparison.OrdinalIgnoreCase) && (isD3d11vaDecoder || isSwDecoder)))
```

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 6]
```diff
@@ -534,8 +560,17 @@ public string GetInputArgument(EncodingJobInfo state, EncodingOptions encodingOp
...
                 if (state.IsVideoRequest
-                    && (string.Equals(encodingOptions.HardwareAccelerationType, "nvenc", StringComparison.OrdinalIgnoreCase) && isNvdecHevcDecoder || isSwDecoder)
-                        || (string.Equals(encodingOptions.HardwareAccelerationType, "amf", StringComparison.OrdinalIgnoreCase) && isD3d11vaDecoder || isSwDecoder))
+                    && string.Equals(encodingOptions.HardwareAccelerationType, "nvenc", StringComparison.OrdinalIgnoreCase))
+                {
+                    if (isNvdecDecoder)
+                    {
+                        arg.Append("-hwaccel_output_format cuda ");
+                    }
+                }
```
Comment (crobibero) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:569]:
```suggestion
                    && string.Equals(encodingOptions.HardwareAccelerationType, "nvenc", StringComparison.OrdinalIgnoreCase)
                    && isNvdecDecoder)
                {
                    arg.Append("-hwaccel_output_format cuda ");
                }
```

File: MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs [hunk 7]
```diff
@@ -199,6 +199,8 @@ internal bool ValidateVersionInternal(string versionOutput)
 
         public IEnumerable<string> GetHwaccels() => GetHwaccelTypes();
 
+        public bool CheckFilter(string filter, string option) => CheckFilterOption(filter, option);
+
```
Comment (crobibero) [inline MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs:203]:
```suggestion
```

File: MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs [hunk 8]
```diff
@@ -296,6 +298,38 @@ private IEnumerable<string> GetHwaccelTypes()
             return found;
         }
 
+        private bool CheckFilterOption(string filter, string option)
```
Comment (crobibero) [inline MediaBrowser.MediaEncoding/Encoder/EncoderValidator.cs:301]:
```suggestion
        public bool CheckFilter(string filter, string option)
```

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 9]
```diff
@@ -534,8 +560,16 @@ public string GetInputArgument(EncodingJobInfo state, EncodingOptions encodingOp
...
+                    && string.Equals(encodingOptions.HardwareAccelerationType, "nvenc", StringComparison.OrdinalIgnoreCase)
+                    && isNvdecDecoder)
+                {
+                    arg.Append("-hwaccel_output_format cuda ");
+                }
+
+                if ((state.IsVideoRequest
+                    && string.Equals(encodingOptions.HardwareAccelerationType, "nvenc", StringComparison.OrdinalIgnoreCase)
+                    && (isNvdecDecoder || isCuvidHevcDecoder || isSwDecoder))
+                        || (string.Equals(encodingOptions.HardwareAccelerationType, "amf", StringComparison.OrdinalIgnoreCase) && (isD3d11vaDecoder || isSwDecoder)))
```
Comment (crobibero) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:572]:
```suggestion
                if (state.IsVideoRequest
                    && ((string.Equals(encodingOptions.HardwareAccelerationType, "nvenc", StringComparison.OrdinalIgnoreCase)
                         && (isNvdecDecoder || isCuvidHevcDecoder || isSwDecoder))
                        || (string.Equals(encodingOptions.HardwareAccelerationType, "amf", StringComparison.OrdinalIgnoreCase) 
                            && (isD3d11vaDecoder || isSwDecoder))))
```

I think I suggested incorrect parenthesis, please confirm this suggestion gives the intended result

Comment (nyanmisaka) [reply MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:572]: It's time to rewrite the EncodingHelper to avoid such hassle.
HWA methods/pipelines should be separated into different classes.

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 10]
```diff
@@ -1912,12 +1975,19 @@ public MediaStream GetMediaStream(IEnumerable<MediaStream> allStream, int? desir
...
             var isVaapiHevcEncoder = outputVideoCodec.IndexOf("hevc_vaapi", StringComparison.OrdinalIgnoreCase) != -1;
+            var isQsvH264Encoder = outputVideoCodec.Contains("h264_qsv", StringComparison.OrdinalIgnoreCase);
+            var isQsvHevcEncoder = outputVideoCodec.Contains("hevc_qsv", StringComparison.OrdinalIgnoreCase);
+            var isNvdecDecoder = videoDecoder.Contains("cuda", StringComparison.OrdinalIgnoreCase);
+            var isNvencEncoder = outputVideoCodec.Contains("nvenc", StringComparison.OrdinalIgnoreCase);
             var isTonemappingSupported = IsTonemappingSupported(state, options);
+            var isVppTonemappingSupported = IsVppTonemappingSupported(state, options);
             var isTonemappingSupportedOnVaapi = string.Equals(options.HardwareAccelerationType, "vaapi", StringComparison.OrdinalIgnoreCase) && isVaapiDecoder && (isVaapiH264Encoder || isVaapiHevcEncoder);
+            var isTonemappingSupportedOnQsv = string.Equals(options.HardwareAccelerationType, "qsv", StringComparison.OrdinalIgnoreCase) && isVaapiDecoder && (isQsvH264Encoder || isQsvHevcEncoder);
+
```
Comment (crobibero) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:1986]:
```suggestion
```

**Review by crobibero — APPROVED** [review]

File: MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs [hunk 11]
```diff
@@ -50,6 +50,14 @@ public interface IMediaEncoder : ITranscoderSupport
         /// <returns><c>true</c> if XXXX, <c>false</c> otherwise.</returns>
         bool SupportsHwaccel(string hwaccel);
 
+        /// <summary>
+        /// Whether given filter is supported.
+        /// </summary>
+        /// <param name="filter">The filter.</param>
+        /// <param name="option">The option.</param>
+        /// <returns><c>true</c> if XXXX, <c>false</c> otherwise.</returns>
```
Comment (Ullmie02) [inline MediaBrowser.Controller/MediaEncoding/IMediaEncoder.cs:58]:
```suggestion
        /// <returns><c>true</c> if the filter is supported, <c>false</c> otherwise.</returns>
```

**Review by Ullmie02 — APPROVED** [review]

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 12]
```diff
@@ -2590,14 +2767,76 @@ private string GetFixedSizeScalingFilter(Video3DFormat? threedFormat, int reques
...
+                var isCudaFormatConversionSupported = _mediaEncoder.SupportsFilter("scale_cuda", "Output format (default \"same\")");
+
+                // Assert 10-bit hardware decodable
+                if (isColorDepth10 && (string.Equals(codec, "hevc", StringComparison.OrdinalIgnoreCase)
+                    || string.Equals(codec, "h265", StringComparison.OrdinalIgnoreCase)
+                    || string.Equals(codec, "vp9", StringComparison.OrdinalIgnoreCase)))
+                {
+                    if (isCudaFormatConversionSupported)
+                    {
+                        if (isLibX264Encoder || isLibX265Encoder || hasSubs)
```
Comment (cvium) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2791]: Very deep nesting :/

**Review by cvium — CHANGES_REQUESTED** [review]
Some indentation issues

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs (hunk 12 above)
Comment (nyanmisaka) [reply MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2791]: Need rewrite the whole class at some time, it contains too many different cases.

**Review by cvium — APPROVED** [review]
