### PR TITLE
Wait for the async authentication to finish when the JTW token expires

### LINKED ISSUE #1356: TvDbSharper.TvDbServerException: Your JWT token is missing or expired; Not authorized
**Describe the bug**
No new TVDB data. Lots of JWT token expiration messages in the log.

**Logs**
 

```
 [2019-05-05 19:31:19.418 -05:00] [ERR] Error in DummySeasonProvider
TvDbSharper.TvDbServerException: Your JWT token is missing or expired; Not authorized
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetAllEpisodesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.MissingEpisodeProvider.Run(Series series, Boolean addNewItems, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.SeriesMetadataService.AfterMetadataRefresh(Series item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[2019-05-05 19:31:19.557 -05:00] [INF] Creating Season "Season Unknown" entry for "The Simpsons"
[2019-05-05 19:31:20.057 -05:00] [ERR] Error in DummySeasonProvider
TvDbSharper.TvDbServerException: Your JWT token is missing or expired; Not authorized
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetAllEpisodesAsync(Int32 tvdbId, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.MissingEpisodeProvider.Run(Series series, Boolean addNewItems, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.SeriesMetadataService.AfterMetadataRefresh(Series item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
[2019-05-05 19:31:24.284 -05:00] [ERR] Failed to retrieve episode with id null
TvDbSharper.TvDbServerException: Your JWT token is missing or expired; Not authorized
   at TvDbSharper.Infrastructure.Parser.Parse[T](ApiResponse response, IReadOnlyDictionary`2 errorMap)
   at TvDbSharper.Clients.SeriesClient.GetEpisodesAsync(Int32 seriesId, Int32 page, EpisodeQuery query, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.TryGetValue[T](String key, String language, Func`1 resultFactory)
   at MediaBrowser.Providers.TV.TheTVDB.TvDbClientManager.GetEpisodeTvdbId(Int32 seriesTvdbId, EpisodeQuery episodeQuery, String language, CancellationToken cancellationToken)
   at MediaBrowser.Providers.TV.TheTVDB.TvdbEpisodeProvider.GetMetadata(EpisodeInfo searchInfo, CancellationToken cancellationToken)
```

**System (please complete the following information):**
 - OS: Docker
 - Jellyfin Version: 10.3.2

### PR DESCRIPTION
**Pull request by cvium**
**Changes**
The authentication calls were async but never awaited...

**Issues**
Fixes #1356

### CODE REVIEW

File: MediaBrowser.Providers/TV/TheTVDB/TvDbClientManager.cs [hunk 1]
```diff
@@ -24,24 +24,28 @@ public TvDbClientManager(IMemoryCache memoryCache)
         {
             _cache = memoryCache;
             _tvDbClient = new TvDbClient();
-            _tvDbClient.Authentication.AuthenticateAsync(TvdbUtils.TvdbApiKey);
-            _tokenCreatedAt = DateTime.Now;
         }
 
-        public TvDbClient TvDbClient
+        private TvDbClient TvDbClient
```
Comment (EraYaN) [inline MediaBrowser.Providers/TV/TheTVDB/TvDbClientManager.cs]: Any specific reason for this to be private instead of public? Does that have any effect on plugins?

Comment (cvium) [reply MediaBrowser.Providers/TV/TheTVDB/TvDbClientManager.cs]: Plugins dont have access to this class
