### PR TITLE
Don't write tagline in <outline> in nfo files

### LINKED ISSUE #3142: Tagline is saved in Tagline and Outline fields in .nfo file
**Describe the bug**
When a movie is scraped, the Tagline is saved in both Tagline and Outline fields in the nfo file. This is not good for other programs that use both Plot and Outline fields.

**System (please complete the following information):**
  - OS: Windows 10 1909
 - Virtualization: none
 - Clients: N/A
 - Browser: Firefox 
- Jellyfin Version: Stable 10.5.5
- Playback: N/A
 - Installed Plugins: N/A
 - Reverse Proxy: none
 - Base URL: 
 - Networking: N/A
 - Storage: local

**To Reproduce**
1. Scrape a movie
2. View the .nfo file in a text editor
3. See that Tagline and Outline fields are the same.

**Expected behavior**
Tagline should only be saved in Tagline field. Outline field should either be fetched or left blank.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Ullmie02**
**Changes**
Don't write `outline` tag for videos. It should only be scraped from IMDB according to the [Kodi wiki](https://kodi.wiki/view/NFO_files/Movies#nfo_Tags)

**Issues**
Fixes #3142

### CODE REVIEW

**Review by crobibero — APPROVED** [review]

**Review by barronpm — APPROVED** [review]

File: MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs [hunk 1]
```diff
@@ -450,15 +450,7 @@ public static void AddMediaInfo<T>(T item, XmlWriter writer)
...
-            if (item is Video)
-            {
-                var outline = (item.Tagline ?? string.Empty)
-                    .StripHtml()
-                    .Replace("&quot;", "'", StringComparison.Ordinal);
-
-                writer.WriteElementString("outline", outline);
-            }
-            else
+            if (!(item is Video))
```
Comment (Bond-009) [inline MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs:453]:
```suggestion
            if (item is not Video)
```

**Review by Bond-009 — APPROVED** [review]

File: MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs (hunk 1 above)
Comment (Ullmie02) [reply MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs]: Looks much better this way :D
