### PR TITLE
Fix attachment extraction of files without video or audio stream

### LINKED ISSUE #16303: Extraction of MKS attachments fails
### Description of the bug

While trying to debug jellyfin/jellyfin#15222 with @solidsnake1298 on Matrix, we ran into a little problem. The idea was to extract the attachments and see if the fonts are sent to the client. However, upon running the SubtitleExtractor plugins' "Extract Attachments" task, it eventually fails when encountering said MKS.

### Reproduction steps

1. Add an external MKS file to an item in the library
    * an example file can be found in the aforementioned issue
2. Run the "Extract Attachments" task

### What is the current _bug_ behavior?

The extraction eventually fails when encountering an MKS file (presumably also other file types, but I haven't come across any).

### What is the expected _correct_ behavior?

It should extract the attachments for later use.

### Jellyfin Server version

10.11.6

### Specify commit id

_No response_

### Specify unstable release number

_No response_

### Specify version number

_No response_

### Specify the build version

10.11.6

### Environment

```markdown
- OS: TrueNAS Scale
- Linux Kernel: 6.12.15
- Virtualization: Docker
- Clients: Web/Jellyfin Desktop
- Browser: Vivaldi
- FFmpeg Version: 7.1.3-ffmpeg
- Playback Method: -
- Hardware Acceleration: -
- CPU Model: Ryzen 2700X
- GPU Model: -
- Plugins: SubtitleExtract, IntroSkipper
- Reverse Proxy: -
- Base URL: -
- Networking: Docker
- Jellyfin Data Storage & Filesystem: SSD, ZFS
- Media Storage & Filesystem: HDD, ZFS
- External Integrations: -
```

### Jellyfin logs

```shell
[2026-02-26 16:54:53.104 +01:00] [INF] [120] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: "/usr/lib/jellyfin-ffmpeg/ffmpeg" "-dump_attachment:t \"\" -y  -i file:\"/mnt/media/anime/shows/Naruto Shippūden [tmdbid-31910]/Season 00/S00E99 - The Day Naruto Became Hokage - 1080p [nks].Himawari.mks\" -t 0 -f null null"
[2026-02-26 16:54:54.114 +01:00] [WRN] [120] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: Deleting extracted attachments "/config/data/attachments/d4/d4b7b787-d5ed-32d0-d1c1-d13d15b1b0b9" due to failure: 234
[2026-02-26 16:54:54.115 +01:00] [ERR] [120] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: Error deleting extracted attachments "/config/data/attachments/d4/d4b7b787-d5ed-32d0-d1c1-d13d15b1b0b9"
System.IO.IOException: Directory not empty : '/config/data/attachments/d4/d4b7b787-d5ed-32d0-d1c1-d13d15b1b0b9'
   at System.IO.FileSystem.RemoveEmptyDirectory(String fullPath, Boolean topLevel, Boolean throwWhenNotEmpty)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor.ExtractAllAttachmentsInternal(String inputFile, MediaSourceInfo mediaSource, Boolean isExternal, CancellationToken cancellationToken)
[2026-02-26 16:54:54.118 +01:00] [ERR] [120] MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor: ffmpeg attachment extraction failed for "file:\"/mnt/media/anime/shows/Naruto Shippūden [tmdbid-31910]/Season 00/S00E99 - The Day Naruto Became Hokage - 1080p [nks].Himawari.mks\"" to "/config/data/attachments/d4/d4b7b787-d5ed-32d0-d1c1-d13d15b1b0b9"
[2026-02-26 16:54:54.120 +01:00] [ERR] [120] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.InvalidOperationException: ffmpeg attachment extraction failed for file:"/mnt/media/anime/shows/Naruto Shippūden [tmdbid-31910]/Season 00/S00E99 - The Day Naruto Became Hokage - 1080p [nks].Himawari.mks" to /config/data/attachments/d4/d4b7b787-d5ed-32d0-d1c1-d13d15b1b0b9
   at MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor.ExtractAllAttachmentsInternal(String inputFile, MediaSourceInfo mediaSource, Boolean isExternal, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Attachments.AttachmentExtractor.ExtractAllAttachments(String inputFile, MediaSourceInfo mediaSource, CancellationToken cancellationToken)
   at Jellyfin.Plugin.SubtitleExtract.Tasks.ExtractAttachmentsTask.RunExtractionWithProgress(IProgress`1 progress, Nullable`1 parentId, IReadOnlyCollection`1 parentIds, Double startProgress, CancellationToken cancellationToken)
   at Jellyfin.Plugin.SubtitleExtract.Tasks.ExtractAttachmentsTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2026-02-26 16:54:54.124 +01:00] [INF] [120] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Extract Attachments" Failed after 0 minute(s) and 22 seconds
```

### FFmpeg logs

```shell

```

### Client / Browser logs

_No response_

### Relevant screenshots or videos

_No response_

### Additional information

I'm not sure what the deletion in the log is about, I assume some cleanup after a failed extract.

However, the problem is the extraction itself failing. I ran the command on my PC manually, and `ffmpeg` trips here:
```
❯ ffmpeg -dump_attachment:t "" -y -i 'S00E99 - The Day Naruto Became Hokage - 1080p [nks].Himawari.mks' -t 0 -f null null
ffmpeg version 7.1.2 Copyright (c) 2000-2025 the FFmpeg developers
  built with gcc 15 (GCC)
  configuration: --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 --optflags='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Wno-complain-wrong-lang -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer' --extra-ldflags='-Wl,-z,relro -Wl,--as-needed -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes ' --extra-cflags=' -I/usr/include/rav1e' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-version3 --enable-bzlib --enable-chromaprint --enable-fontconfig --enable-frei0r --enable-gcrypt --enable-gnutls --enable-ladspa --enable-lcms2 --enable-libaom --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libass --enable-libbluray --enable-libbs2b --enable-libcodec2 --enable-libcdio --enable-libdrm --enable-libjack --enable-libjxl --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libharfbuzz --enable-libilbc --enable-liblc3 --enable-libmp3lame --enable-libmysofa --enable-nvenc --enable-openal --enable-opencl --enable-opengl --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-libplacebo --enable-librsvg --enable-librav1e --enable-librubberband --enable-libqrencode --enable-libsmbclient --enable-version3 --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtesseract --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-version3 --enable-vapoursynth --enable-libvpx --enable-libvvenc --enable-vulkan --enable-libshaderc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libxml2 --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-avfilter --enable-libmodplug --enable-postproc --enable-pthreads --disable-static --enable-shared --enable-gpl --disable-debug --disable-stripping --shlibdir=/usr/lib64 --enable-lto --enable-libvpl --enable-runtime-cpudetect
  libavutil      59. 39.100 / 59. 39.100
  libavcodec     61. 19.101 / 61. 19.101
  libavformat    61.  7.100 / 61.  7.100
  libavdevice    61.  3.100 / 61.  3.100
  libavfilter    10.  4.100 / 10.  4.100
  libswscale      8.  3.100 /  8.  3.100
  libswresample   5.  3.100 /  5.  3.100
  libpostproc    58.  3.100 / 58.  3.100
[matroska,webm @ 0x55af98ac6c00] Could not find codec parameters for stream 2 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55af98ac6c00] Could not find codec parameters for stream 3 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55af98ac6c00] Could not find codec parameters for stream 4 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
[matroska,webm @ 0x55af98ac6c00] Could not find codec parameters for stream 5 (Attachment: none): unknown codec
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, matroska,webm, from 'S00E99 - The Day Naruto Became Hokage - 1080p [nks].Himawari.mks':
  Metadata:
    encoder         : libebml v1.4.5 + libmatroska v1.7.1
    creation_time   : 2025-06-16T02:59:20.000000Z
  Duration: 00:10:19.76, start: 5.840000, bitrate: 14 kb/s
  Stream #0:0(eng): Subtitle: ass (ssa)
      Metadata:
        title           : Full
        BPS             : 129
        DURATION        : 00:10:19.760000000
        NUMBER_OF_FRAMES: 149
        NUMBER_OF_BYTES : 10043
        _STATISTICS_WRITING_APP: mkvmerge v92.0 ('Everglow') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2025-06-16 02:59:20
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Subtitle: ass (ssa)
      Metadata:
        title           : Title
        BPS             : 4
        DURATION        : 00:09:55.090000000
        NUMBER_OF_FRAMES: 4
        NUMBER_OF_BYTES : 307
        _STATISTICS_WRITING_APP: mkvmerge v92.0 ('Everglow') 64-bit
        _STATISTICS_WRITING_DATE_UTC: 2025-06-16 02:59:20
        _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2: Attachment: none
      Metadata:
        filename        : AurulentSans-Bold.otf
        mimetype        : font/otf
  Stream #0:3: Attachment: none
      Metadata:
        filename        : AurulentSans-BoldItalic.otf
        mimetype        : font/otf
  Stream #0:4: Attachment: none
      Metadata:
        filename        : times.ttf
        mimetype        : font/ttf
  Stream #0:5: Attachment: none
      Metadata:
        filename        : LeviBrush.ttf
        mimetype        : font/ttf
[aist#0:2/none @ 0x55af98ba5640] Wrote attachment (37392 bytes) to 'AurulentSans-Bold.otf'
[aist#0:3/none @ 0x55af98ba2f00] Wrote attachment (53436 bytes) to 'AurulentSans-BoldItalic.otf'
[aist#0:4/none @ 0x55af98acd880] Wrote attachment (834240 bytes) to 'times.ttf'
[aist#0:5/none @ 0x55af98acda00] Wrote attachment (182400 bytes) to 'LeviBrush.ttf'
Output #0, null, to 'null':
[out#0/null @ 0x55af98b5ea40] Output file does not contain any stream
Error opening output file null.
Error opening output files: Invalid argument

❯ echo $?
234
```

The issue is seemingly an assumption that there is always a video and/or audio stream. Since there isn't one, `ffmpeg` doesn't know what to put out and faceplants.

This same behaviour can be seen when doing an extraction on an MKV while dropping video and audio streams (`-vn -an`):
```
❯ ffmpeg -dump_attachment:t "" -y -i 'S00E99 - The Day Naruto Became Hokage - 1080p [nks].mkv' -vn -an -t 0 -f null null
ffmpeg version 7.1.2 Copyright (c) 2000-2025 the FFmpeg developers
…
[aist#0:7/otf @ 0x5638b302ea40] Wrote attachment (37392 bytes) to 'AurulentSans-Bold.otf'
Output #0, null, to 'null':
[out#0/null @ 0x5638b30a5b40] Output file does not contain any stream
Error opening output file null.
Error opening output files: Invalid argument
```

@solidsnake1298 then realised that this issue is solved when dropping the second `null`. However, this poses a different issue:

```
❯ ffmpeg -dump_attachment:t "" -y -i 'S00E99 - The Day Naruto Became Hokage - 1080p [nks].mkv' -t 0 -f null
…
At least one output file must be specified
❯ echo $?  
1
```

From my understanding of the extractor code here, this would break main file processing entirely though:
https://github.com/jellyfin/jellyfin/blob/b65daeca0baf7a447185205461b4a9d758bbeb26/MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs#L186-L195

Since `1` is only OK for `isExternal` files (and it seems this is always false, which is a different problem in itself), it would see main file extractions as failed.

I also brought up the possibility of adding `-an -vn` to the extraction and dropping the second `null` (i.e. filename). This would be a noop on MKS and other external files, but would drop audio and video streams on main items, which we don't use anyway.
However, this also results in the exit `1` problem above.

This `ffmpeg` behaviour is a bit of a contradictory headscratcher for me anyway. When we specify `-f null` we explicitly tell it that we don't want output, so why would it want an output file?
Furthermore, if you *do* specify an output file, it faceplants again with the original issue.

So for me the real question here is: Can we tell `ffmpeg` to exit `0` with `-f null`, and only exit `1` on actual errors? If there is, I haven't found it yet.

### PR DESCRIPTION
**Pull request by Shadowghost**
**Changes**
* Omit output file if we don't have video or audio stream
* Handle expected exit code if we only dump attachments

**Issues**
Fixes #16303

### CODE REVIEW

File: MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs [hunk 1]
```diff
@@ -142,11 +140,24 @@ private async Task ExtractAllAttachmentsInternal(
...
+                    ? string.Format(
+                        CultureInfo.InvariantCulture,
+                        "-dump_attachment:t \"\" -y {0} -i {1} -t 0 -f null null",
+                        inputPath.EndsWith(".concat\"", StringComparison.OrdinalIgnoreCase) ? "-f concat -safe 0" : string.Empty,
+                        inputPath)
+                    : string.Format(
+                        CultureInfo.InvariantCulture,
+                        "-dump_attachment:t \"\" -y {0} -i {1}",
+                        inputPath.EndsWith(".concat\"", StringComparison.OrdinalIgnoreCase) ? "-f concat -safe 0" : string.Empty,
+                        inputPath);
```
Comment (Bond-009) [inline MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs]: so much duplication just to add a few args
```suggestion
                var processArgs = string.Format(
                        CultureInfo.InvariantCulture,
                        "-dump_attachment:t \"\" -y {0} -i {1} {2}",
                        inputPath.EndsWith(".concat\"", StringComparison.OrdinalIgnoreCase) ? "-f concat -safe 0" : string.Empty,
                        inputPath
                        hasVideoOrAudioStream ? string.Empty : "-t 0 -f null null");
```

File: MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs [hunk 2]
```diff
@@ -267,12 +276,21 @@ private async Task ExtractAttachmentInternal(
...
+                    "-dump_attachment:{1} \"{2}\" -i {0} -t 0 -f null null",
+                    inputPath,
+                    attachmentStreamIndex,
+                    EncodingUtils.NormalizePath(outputPath))
+                : string.Format(
+                    CultureInfo.InvariantCulture,
+                    "-dump_attachment:{1} \"{2}\" -i {0}",
+                    inputPath,
+                    attachmentStreamIndex,
+                    EncodingUtils.NormalizePath(outputPath));
```
Comment (Bond-009) [inline MediaBrowser.MediaEncoding/Attachments/AttachmentExtractor.cs]: same here

**Review by Bond-009 — CHANGES_REQUESTED** [review]
