### PR TITLE
Process actor type in nfo files

### LINKED ISSUE #3686: NFO Reader/Writer Doesn't Process All Roles
**Describe the bug**
As reported on [the forums](https://forum.jellyfin.org/t/metadata-getting-overwritten/2456/19), the NFO Reader/Writer is clobbering metadata that is valid.
Part of this is the fact that it doesn't handle entries for crew properly (such as producer, composer). When reading these in, it treats them as "actor" since it doesn't have person types for those other positions. When it writes back, it adds a second entry for them as an actor, and thus modifies the user's correct info on disk.

**System (please complete the following information):**
 - Jellyfin Version: Verified on 10.5.5, and continues with 10.6.0

**To Reproduce**
* Disable all external metadata providers.
* Add media matching the example NFO provided here: https://forum.jellyfin.org/t/metadata-getting-overwritten/2456/16?u=anthonylavado
* Perform a refresh of the library to pick up this new media.
* Observe the NFO content is modified.

**Expected behavior**
Jellyfin should respect the data in the NFO if it is provided, and handle the additional information correctly. The controls for reading/writing NFO should be split and made clearer. I'll make a new issue for that.

**Additional context**
I know NFOs are just text files, but if there is a spec of some kind, we should look to fully support it.

### PR DESCRIPTION
**Pull request by Ullmie02**
**Changes**
Add support for reading `type` tag inside `actor` tag in nfo files. NfoSaver already saves the person type correctly.
Also added it to the movie parser test

**Issues**
Fixes #3686

### CODE REVIEW

File: MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs [hunk 1]
```diff
@@ -1030,6 +1030,45 @@ private PersonInfo GetPersonFromXmlNode(XmlReader reader)
...
+                                            type = PersonType.Writer;
+                                            break;
+                                        case PersonType.GuestStar:
+                                            type = PersonType.GuestStar;
+                                            break;
+                                        // unknown type --> actor
+                                        default:
+                                            type = PersonType.Actor;
+                                            break;
+                                    }
```
Comment (crobibero) [inline MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs:1066]:
```suggestion
                                    type = val switch
                                    {
                                        PersonType.Composer => PersonType.Composer,
                                        PersonType.Conductor => PersonType.Conductor,
                                        PersonType.Director => PersonType.Director,
                                        PersonType.Lyricist => PersonType.Lyricist,
                                        PersonType.Producer => PersonType.Producer,
                                        PersonType.Writer => PersonType.Writer,
                                        PersonType.GuestStar => PersonType.GuestStar,
                                        // unknown type --> actor
                                        _ => PersonType.Actor
                                    };
```

**Review by crobibero — APPROVED** [review]

**Review by barronpm — APPROVED** [review]
