### PR TITLE
Don't refresh playlists on album refresh

### LINKED ISSUE #3088: Album Art gets tiled (4 Squares) if Music Album folder contains playlist
**Describe the bug**
During the initial scan of my music library most Album art is set correctly (presumably from the Musicbrainz DB) in a satisfactory manor, however should there be a m3u (or likely m3u8) file in the directory the Album also gets populated into the playlist section of my music library of which the playlist section shows Album Art in a tiled 4 square pattern.

The issue is that the 4 square title version of the Album art becomes the *main* image for the Album rather than just the main image of the album cover that previous existed in full size.

**To Reproduce**

1. Add an Album to a Music Libarary that contains a m3u or m3u8 playlist (linking to the tracks of the album)
2. Scan your library (Likely the first time should Album art exist in Musicbrainz the art will be correct) 
3. After a while (perhaps the next scan after the Album art exists), you will receive the annoying tiled version of the Album art as well as it existing in your playlist section of your Music Library

**Expected behavior**

The album art remains the full, non-tiled, version.

**Logs**
N/A

**Screenshots**
Example: https://i.imgur.com/Ix5tKuB.png

**System (please complete the following information):**
 - OS: Debian
 - Browser: Firefox, Chrome (Shouldn't matter)
 - Jellyfin Version: 10.4.3

Might be more related to jellyfin proper (didn't realize I was in web when I posted this), not certain if the interface is causing it or just the scan

### PR DESCRIPTION
**Pull request by daullmer**
**Changes**
Change music album refresh to not refresh child playlists

Note: playlists created in Jellyfin containing songs from an album are not included in `items` and are not being refreshed. So this change should not affect custom playlists

**Issues**
Fixes #3088

### CODE REVIEW

**Review by crobibero — APPROVED** [review]

File: MediaBrowser.Controller/Entities/Audio/MusicAlbum.cs [hunk 1]
```diff
@@ -169,8 +170,8 @@ public async Task RefreshAllMetadata(MetadataRefreshOptions refreshOptions, IPro
 
             var childUpdateType = ItemUpdateType.None;
 
-            // Refresh songs
-            foreach (var item in items)
+            // Refresh songs only and not m3u files in album folder
+            foreach (var item in items.Where(i => i.GetType() != typeof(Playlist)))
```
Comment (cvium) [inline MediaBrowser.Controller/Entities/Audio/MusicAlbum.cs:174]: I prefer .OfType<>()

File: MediaBrowser.Controller/Entities/Audio/MusicAlbum.cs [hunk 2]
```diff
@@ -12,6 +12,7 @@
 using Jellyfin.Data.Enums;
 using MediaBrowser.Controller.Dto;
 using MediaBrowser.Controller.Library;
+using MediaBrowser.Controller.Playlists;
```
Comment (cvium) [inline MediaBrowser.Controller/Entities/Audio/MusicAlbum.cs:15]: Not necessary anymore, right?
```suggestion
```

**Review by cvium — APPROVED** [review]
