### PR TITLE
Display Extras With Unknown Types

### LINKED ISSUE #2484: Extras no longer work
I can no longer see Special features. This used to work and stopped working recently. I'm on a nightly about a week old.

My directory structure is MovieName/MovieName.mkv
and extras go to MovieName/Extras.

### LINKED ISSUE #2665: Only movie extras with suffixes are loaded in after 10.5.2
**Describe the bug**
In earlier versions, any video in a movie's 'extras' folder (along with a couple other specific names like 'behind the scenes') would load up as Special Features.  In 10.4.3 and 10.5.0, that was broken entirely (see #2484 ).  In 10.5.2, #2642 appears to have partially corrected the issue.  Based on a quick perusal, it appears that now files in 'extras', 'behind the scenes', and 'deleted scenes' that end in certain suffixes (e.g. -deleted, -featurette, -behindthescenes, etc.) are being loaded in as special features.  However, files that contain no suffix, or an inappropriate suffix (e.g. -other) are not being pulled in as special features.

I checked the docs and didn't find anything about how to name extras.  If this is an intentional design decision, feel free to close.  It's less about having a particular preference to how they're pulled and more about being consistent.  

**System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Virtualization: LXC
 - Clients: Web
 - Browser: Firefox 74
 - Jellyfin Version: 10.5.2
 - Playback: N/A
 - Installed Plugins: none
 - Reverse Proxy: none
 - Base URL: [e.g. none, yes: /example]
 - Networking: macvlan
 - Storage: local

**To Reproduce**
Place video in extras subfolder of movie, such as 
/Movies/MovieName/extras/SomeSpecialFeature1.mkv
/Movies/MovieName/extras/SomeSpecialFeature2-deleted.mkv

**Expected behavior**
Both files would be treated as special features.  Currently only '2' would be.

**Logs**
N/A

### PR DESCRIPTION
**Pull request by mark-monteiro**
The existing behavior for extras is to not display any extras where the `ExtraType` property could not be determined (i.e. is `null`). This changes that behavior to display those extras with unknown type.

There should likely be additional changes to improve/change how the extra type is parsed, but I think that should be in a separate PR and would be out of scope here.

**Changes**
* Include extras with an unknown type in the `SpecialFeatureCount` DTO property 
* Include extras with an unknown type in response to a `GetSpecialFeatures` request
* Fix an issue where the `ExtraType` is saved as `0` (an invalid enumeration value) instead of `null`

**Issues**
Fixes #2665 
Fixes #2484

### CODE REVIEW

File: MediaBrowser.Controller/Entities/BaseItem.cs [hunk 1]
```diff
@@ -1327,8 +1327,9 @@ protected virtual BaseItem[] LoadExtras(List<FileSystemMetadata> fileSystemChild
                         }
 
                         // Use some hackery to get the extra type based on foldername
-                        Enum.TryParse(extraFolderName.Replace(" ", ""), true, out ExtraType extraType);
-                        item.ExtraType = extraType;
+                        item.ExtraType = Enum.TryParse(extraFolderName.Replace(" ", ""), true, out ExtraType extraType)
+                            ? extraType
+                            : (ExtraType?)null;
```
Comment (mark-monteiro) [inline MediaBrowser.Controller/Entities/BaseItem.cs]: This assigns `null` instead of `0` (an invalid value for the enum) when the type cannot be parsed.

File: MediaBrowser.Controller/Entities/BaseItem.cs [hunk 2]
```diff
@@ -2918,8 +2929,20 @@ public virtual long GetRunTimeTicksForPlayState()
...
 
-        // Possible types of extra videos
-        public static readonly IReadOnlyCollection<ExtraType> DisplayExtraTypes = new[] { Model.Entities.ExtraType.BehindTheScenes, Model.Entities.ExtraType.Clip, Model.Entities.ExtraType.DeletedScene, Model.Entities.ExtraType.Interview, Model.Entities.ExtraType.Sample, Model.Entities.ExtraType.Scene };
+        /// <summary>
+        /// Extra types that should be counted and displayed as "Special Features" in the UI.
+        /// </summary>
+        public static readonly IReadOnlyCollection<ExtraType?> DisplayExtraTypes = new HashSet<ExtraType?>
+        {
+            null,
+            0,
```
Comment (mark-monteiro) [inline MediaBrowser.Controller/Entities/BaseItem.cs]: I don't think including `0` here should be required since I fixed the issue with the `ExtraType` being set to `0`, but I left it here anyways for future-proofing

Comment (dkanada) [reply MediaBrowser.Controller/Entities/BaseItem.cs]: Seems like we should just include a generic type rather than a null value.

File: Emby.Naming/Common/NamingOptions.cs [hunk 3]
```diff
@@ -505,7 +505,15 @@ public NamingOptions()
...
+                new ExtraRule { RuleType = ExtraRuleType.DirectoryName, MediaType = MediaType.Video, ExtraType = ExtraType.DeletedScene, Token = "deleted scenes" },
+                new ExtraRule { RuleType = ExtraRuleType.DirectoryName, MediaType = MediaType.Video, ExtraType = ExtraType.Interview, Token = "interviews" },
+                new ExtraRule { RuleType = ExtraRuleType.DirectoryName, MediaType = MediaType.Video, ExtraType = ExtraType.Scene, Token = "scenes" },
+                new ExtraRule { RuleType = ExtraRuleType.DirectoryName, MediaType = MediaType.Video, ExtraType = ExtraType.Sample, Token = "samples" },
+                new ExtraRule { RuleType = ExtraRuleType.DirectoryName, MediaType = MediaType.Video, ExtraType = ExtraType.Clip, Token = "shorts" },
+                new ExtraRule { RuleType = ExtraRuleType.DirectoryName, MediaType = MediaType.Video, ExtraType = ExtraType.Clip, Token = "featurettes" },
+                new ExtraRule { RuleType = ExtraRuleType.DirectoryName, MediaType = MediaType.Video, ExtraType = ExtraType.Unknown, Token = "extras" },
```
Comment (mark-monteiro) [inline Emby.Naming/Common/NamingOptions.cs:516]: The list of directory names that make up these rules comes from [here](https://github.com/jellyfin/jellyfin/pull/2696/files#diff-48c22801bc9377e3d7095b8486feda0aL2612) and [here](https://github.com/jellyfin/jellyfin/blob/377f9896ce65d4a29fe9d2198607ced2771b9abb/MediaBrowser.Controller/Entities/BaseItem.cs#L91)

File: MediaBrowser.Controller/Entities/BaseItem.cs [hunk 4]
```diff
@@ -1327,8 +1327,9 @@ protected virtual BaseItem[] LoadExtras(List<FileSystemMetadata> fileSystemChild
                         }
 
                         // Use some hackery to get the extra type based on foldername
-                        Enum.TryParse(extraFolderName.Replace(" ", ""), true, out ExtraType extraType);
-                        item.ExtraType = extraType;
+                        item.ExtraType = Enum.TryParse(extraFolderName.Replace(" ", ""), true, out ExtraType extraType)
+                            ? extraType
+                            : Model.Entities.ExtraType.Unknown;
```
Comment (mark-monteiro) [inline MediaBrowser.Controller/Entities/BaseItem.cs:1332]: Set the extra type as the new enum value `Unknown` instead of `null` when the type cannot be parsed

File: MediaBrowser.Controller/Entities/BaseItem.cs (hunk 2 above)
Comment (mark-monteiro) [reply MediaBrowser.Controller/Entities/BaseItem.cs]: Finally figured this out. I've added a new `ExtraType.Unknown` and set that value where appropriate. Also updated the `ExtraResolver` to try parsing the extra type based on the containing directory name

File: MediaBrowser.Controller/Entities/BaseItem.cs [hunk 5]
```diff
@@ -1327,8 +1327,9 @@ protected virtual BaseItem[] LoadExtras(List<FileSystemMetadata> fileSystemChild
                         }
 
                         // Use some hackery to get the extra type based on foldername
-                        Enum.TryParse(extraFolderName.Replace(" ", ""), true, out ExtraType extraType);
-                        item.ExtraType = extraType;
+                        item.ExtraType = Enum.TryParse(extraFolderName.Replace(" ", ""), true, out ExtraType extraType)
```
Comment (Bond-009) [inline MediaBrowser.Controller/Entities/BaseItem.cs:1330]:
```suggestion
                        item.ExtraType = Enum.TryParse(extraFolderName.Replace(" ", string.Empty), true, out ExtraType extraType)
```

File: Emby.Naming/Common/NamingOptions.cs (hunk 3 above)
Comment (Bond-009) [reply Emby.Naming/Common/NamingOptions.cs:516]: Use 1 line per property

File: Emby.Server.Implementations/Dto/DtoService.cs [hunk 6]
```diff
@@ -1056,30 +1056,19 @@ private void AttachBasicFields(BaseItemDto dto, BaseItem item, BaseItem owner, D
...
             if (options.ContainsField(ItemFields.LocalTrailerCount))
             {
-                int trailerCount = 0;
-                if (allExtras == null)
-                {
-                    allExtras = item.GetExtras().ToArray();
-                }
-
-                trailerCount += allExtras.Count(i => i.ExtraType.HasValue && i.ExtraType.Value == ExtraType.Trailer);
+                allExtras = allExtras ?? item.GetExtras().ToArray();
```
Comment (Bond-009) [inline Emby.Server.Implementations/Dto/DtoService.cs:1065]:
```suggestion
                allExtras ??= item.GetExtras().ToArray();
```

File: Emby.Naming/Video/ExtraResolver.cs [hunk 7]
```diff
@@ -80,6 +80,15 @@ private ExtraResult GetExtraInfo(string path, ExtraRule rule)
                     result.Rule = rule;
                 }
             }
+            else if (rule.RuleType == ExtraRuleType.DirectoryName)
+            {
+                var directoryName = Path.GetFileName(Path.GetDirectoryName(path));
+                if (string.Equals(directoryName, rule.Token, StringComparison.OrdinalIgnoreCase))
```
Comment (JustAMan) [inline Emby.Naming/Video/ExtraResolver.cs:86]: I would rather we do a more relaxed matching, like `behind the scenes` == `behind.the.scenes` or something similar

File: Emby.Naming/Video/ExtraRuleType.cs [hunk 8]
```diff
@@ -5,18 +5,23 @@ namespace Emby.Naming.Video
...
 
         /// <summary>
-        /// The filename
+        /// Match <see cref="ExtraRule.Token"/> against the file name.
         /// </summary>
         Filename = 1,
 
         /// <summary>
-        /// The regex
+        /// Match <see cref="ExtraRule.Token"/> against the a regex.
```
Comment (JustAMan) [inline Emby.Naming/Video/ExtraRuleType.cs:18]: `the a regex`? :) choose one article please
Also help string actually doesn't make much sense IMHO - what part is matched? File name, base file name, directory name, absolute path?..

File: Emby.Naming/Video/ExtraResolver.cs (hunk 7 above)
Comment (mark-monteiro) [reply Emby.Naming/Video/ExtraResolver.cs:86]: I was planning on improving this (and all extras matching) in a future PR :)
231ef226d0272feaed12836dbc933031a09b2afe

File: Emby.Naming/Video/ExtraRuleType.cs (hunk 8 above)
Comment (mark-monteiro) [reply Emby.Naming/Video/ExtraRuleType.cs]: Fixed

File: Emby.Naming/Video/ExtraRuleType.cs [hunk 9]
```diff
@@ -10,12 +10,12 @@ public enum ExtraRuleType
...
 
         /// <summary>
-        /// Match <see cref="ExtraRule.Token"/> against the file name.
+        /// Match <see cref="ExtraRule.Token"/> against the file name, excluding the file extension.
         /// </summary>
         Filename = 1,
 
         /// <summary>
-        /// Match <see cref="ExtraRule.Token"/> against the a regex.
+        /// Match <see cref="ExtraRule.Token"/> against the file name, including the file extension.
```
Comment (JustAMan) [inline Emby.Naming/Video/ExtraRuleType.cs:18]: Are you sure how it works? I haven't checked the code personally, so just asking...

Comment (mark-monteiro) [reply Emby.Naming/Video/ExtraRuleType.cs:18]: Yeah, the file name is extracted [here](https://github.com/jellyfin/jellyfin/blob/master/Emby.Naming/Video/ExtraResolver.cs#L73) using `Path.GetFileName()` which is [documented](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getfilename?view=netcore-3.1#System_IO_Path_GetFileName_System_String_) as 

> Returns the file name and extension of the specified path string.
