### PR TITLE
Catch external streams exceptions

### LINKED ISSUE #7710: [Issue]: Unable to get media info.
### Please describe your bug

I downloaded a video using a magnet link and moved it to the movies directory. All media libraries are then scanned and the video appears in the Movies library. But jellyfin can't get any media encoding information.

### Jellyfin Version

10.8.0

### if other:

_No response_

### Environment

```markdown
- OS:Ubuntu 22.04
- Virtualization: none
- Clients: Browser
- Browser: Edge101
- FFmpeg Version: 
- Playback Method: none
- Hardware Acceleration: QSV
- Plugins: 
- Reverse Proxy: none
- Base URL: none
- Networking: Host
- Storage: local
- Video Link: View edit history
```
[Warring](magnet:?xt=urn:btih:a9f884a4a92e7fd0327e62902ce74b2188ff322d)

### Jellyfin logs

```shell
[2022-05-05 21:01:29.152 +08:00] [ERR] Error in "ffprobe"
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.MediaInfoResolver.GetExternalStreamsAsync(Video video, Int32 startIndex, IDirectoryService directoryService, Boolean clearCache, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.AddExternalSubtitlesAsync(Video video, List`1 currentStreams, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.Fetch(Video video, CancellationToken cancellationToken, MediaInfo mediaInfo, BlurayDiscInfo blurayInfo, MetadataRefreshOptions options)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

### FFmpeg logs

```shell
None
```

### Please attach any browser or client logs here

none

### Please attach any screenshots here

image
image

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by nyanmisaka**
**Changes**
- Catch external streams exceptions (invalid or empty external streams will break the main video stream)

**Issues**
Closes #7710

### CODE REVIEW

File: MediaBrowser.Providers/MediaInfo/MediaInfoResolver.cs [hunk 1]
```diff
@@ -101,34 +101,41 @@ public abstract class MediaInfoResolver
...
+                                    mediaStream.Index = startIndex++;
+
+                                    mediaStreams.Add(MergeMetadata(mediaStream, pathInfo));
+                                }
+                            }
+                        }
+                    }
+                    catch
+                    {
+                        continue;
```
Comment (cvium) [inline MediaBrowser.Providers/MediaInfo/MediaInfoResolver.cs:138]: We should probably log here

**Comment by Shadowghost** [comment]
Just an FYI: the build error is also fixed by https://github.com/jellyfin/jellyfin/pull/7984/commits/34785542492d2db67eb82e1dfc2b141f2f9b5b2a

File: MediaBrowser.Providers/MediaInfo/MediaInfoResolver.cs (hunk 1 above)
Comment (nyanmisaka) [reply MediaBrowser.Providers/MediaInfo/MediaInfoResolver.cs:145]: Done.

**Comment by nyanmisaka** [comment]
> Just an FYI: the build error is also fixed by [3478554](https://github.com/jellyfin/jellyfin/commit/34785542492d2db67eb82e1dfc2b141f2f9b5b2a)

Alright, I remove the same fix from this PR.
Just ignore that debug error.

File: MediaBrowser.Providers/MediaInfo/FFProbeProvider.cs [hunk 2]
```diff
@@ -62,8 +62,8 @@ public class FFProbeProvider : ICustomMetadataProvider<Episode>,
             NamingOptions namingOptions)
         {
             _logger = logger;
-            _audioResolver = new AudioResolver(localization, mediaEncoder, fileSystem, namingOptions);
-            _subtitleResolver = new SubtitleResolver(localization, mediaEncoder, fileSystem, namingOptions);
+            _audioResolver = new AudioResolver(logger, localization, mediaEncoder, fileSystem, namingOptions);
```
Comment (cvium) [inline MediaBrowser.Providers/MediaInfo/FFProbeProvider.cs:65]: It should be `ILoggerFactory` instead of `ILogger<FFProbeProvider>` like this https://github.com/jellyfin/jellyfin/blob/dc8fdb154af7d0b71ca15a551b2acd4d2fe3dbd1/Emby.Dlna/DlnaManager.cs#L51

Comment (nyanmisaka) [reply MediaBrowser.Providers/MediaInfo/FFProbeProvider.cs]: fixed.

File: MediaBrowser.Providers/MediaInfo/SubtitleResolver.cs [hunk 3]
```diff
@@ -15,16 +16,19 @@ public class SubtitleResolver : MediaInfoResolver
         /// <summary>
         /// Initializes a new instance of the <see cref="SubtitleResolver"/> class for external subtitle file processing.
         /// </summary>
+        /// <param name="logger">The logger.</param>
         /// <param name="localizationManager">The localization manager.</param>
         /// <param name="mediaEncoder">The media encoder.</param>
         /// <param name="fileSystem">The file system.</param>
         /// <param name="namingOptions">The <see cref="NamingOptions"/> object containing FileExtensions, MediaDefaultFlags, MediaForcedFlags and MediaFlagDelimiters.</param>
         public SubtitleResolver(
+            ILogger logger,
```
Comment (cvium) [inline MediaBrowser.Providers/MediaInfo/SubtitleResolver.cs:25]:
```suggestion
            ILogger<SubtitleResolver> logger,
```

File: MediaBrowser.Providers/MediaInfo/FFProbeProvider.cs [hunk 4]
```diff
@@ -59,11 +59,12 @@ public class FFProbeProvider : ICustomMetadataProvider<Episode>,
             IChapterManager chapterManager,
             ILibraryManager libraryManager,
             IFileSystem fileSystem,
+            ILoggerFactory loggerFactory,
             NamingOptions namingOptions)
         {
             _logger = logger;
```
Comment (cvium) [inline MediaBrowser.Providers/MediaInfo/FFProbeProvider.cs:65]: You can get rid of one dependency in the constructor by using the factory here as well
```suggestion
            _logger = loggerFactory.CreateLogger<FFProbeProvider>();
```

**Comment by cvium** [comment]
With the new constructor signatures I think there may be some tests failing to build

**Comment by nyanmisaka** [comment]
> 

https://github.com/jellyfin/jellyfin/pull/7984/commits/34785542492d2db67eb82e1dfc2b141f2f9b5b2a

**Comment by cvium** [comment]
> > With the new constructor signatures I think there may be some tests failing to build
> 
> #7984 This will fix the build.

image

**Comment by nyanmisaka** [comment]
> image

Tests fixed.

**Review by cvium — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]

**Comment by Bond-009** [comment]
Debug build failed
