### PR TITLE
Remove DynamicImageResponse local image after saved to metadata folder

### LINKED ISSUE #12937: jellyfin make milions of temp files .jpg and fill inode linux
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our forum or chat rooms first to troubleshoot with volunteers, before creating a report. The links can be found [here](https://jellyfin.org/contact/).
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

with the latest jellyfin updates, the server creates millions of temporary .jpg files by filling the ext4 inode
when I reboot the system it takes hours to delete all the temporary files, and I have to delete them before the reboot otherwise the server stays booting for hours.
my next test is to put a memory disk in fstab for the /tmp folder
the logs show no errors on these files

### Reproduction steps

open folder /tmp/jellyfin/nnnnnnnnnn/*

### What is the current _bug_ behavior?

everyday

### What is the expected _correct_ behavior?

everyday

### Jellyfin Server version

10.10.0+

### Specify commit id

_No response_

### Specify unstable release number

_No response_

### Specify version number

_No response_

### Specify the build version

main

### Environment

- OS: arm64 ubuntu 22.04
- Linux Kernel: 5.10
- Virtualization: no
- Clients: jellyfinweb
- Browser: firefox
- FFmpeg Version: 
- Playback Method:
- Hardware Acceleration:
- GPU Model:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:

### Jellyfin logs

irrelevant

### FFmpeg logs

_No response_

### Client / Browser logs

_No response_

### Relevant screenshots or videos

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gnattu**
**Changes**

Previously, local images provided by DynamicImageResponse were never cleaned up until the server was restarted. This issue has become more severe in 10.10, as the default is now set to use the system's native temp folder, which might be a RAM backed tmpfs. This behavior could lead to resource starvation for long-running servers performing multiple library scans.

Metadata plugins prefer the old behavior should do its own backup.

**Issues**

Fixes #12937

### CODE REVIEW

**Review by Shadowghost — APPROVED** [review]

File: MediaBrowser.Providers/Manager/ProviderManager.cs [hunk 1]
```diff
@@ -251,15 +251,23 @@ public Task SaveImage(BaseItem item, Stream source, string mimeType, ImageType t
...
             if (string.IsNullOrWhiteSpace(source))
             {
                 throw new ArgumentNullException(nameof(source));
             }
 
             var fileStream = AsyncFile.OpenRead(source);
-            return new ImageSaver(_configurationManager, _libraryMonitor, _fileSystem, _logger).SaveImage(item, fileStream, mimeType, type, imageIndex, saveLocallyWithMedia, cancellationToken);
+            await new ImageSaver(_configurationManager, _libraryMonitor, _fileSystem, _logger).SaveImage(item, fileStream, mimeType, type, imageIndex, saveLocallyWithMedia, cancellationToken);
+            try
+            {
```
Comment (JPVenson) [inline MediaBrowser.Providers/Manager/ProviderManager.cs:264]:
```suggestion
         try
         {
            await new ImageSaver(_configurationManager, _libraryMonitor, _fileSystem, _logger).SaveImage(item, fileStream, mimeType, type, imageIndex, saveLocallyWithMedia, cancellationToken);
   
```

**Review by JPVenson — APPROVED** [review]

File: MediaBrowser.Providers/Manager/ProviderManager.cs (hunk 1 above)
Comment (gnattu) [reply MediaBrowser.Providers/Manager/ProviderManager.cs:264]: Isn't throwing the exception more close to the old behavior?

Comment (JPVenson) [reply MediaBrowser.Providers/Manager/ProviderManager.cs:264]: I figure there are other things that might go wrong in the SaveImage method (external connection and stuff) and we would still cleanup even in the even of an error or?

Comment (JPVenson) [reply MediaBrowser.Providers/Manager/ProviderManager.cs:264]: oh i see the confusion

Comment (gnattu) [reply MediaBrowser.Providers/Manager/ProviderManager.cs:264]: The old behavior would be remove the temp file after saving to metadata folder. If the save failed just throw, at least that was the old implementation in `BaseDynamicImageProvider`. This PR made that also available for `ItemImageProvider`. From current implementation in both use cases the source files are temp files so should be safe enough to remove, but we still want to throw the exception so that the task will properly fail.

Comment (JPVenson) [reply MediaBrowser.Providers/Manager/ProviderManager.cs:264]: Ok i see that, but still in the case the SaveImage method throws, we still would want to delete the temp file or? So it should rather be:

```csharp
 	 try
	 {
	    await new ImageSaver(_configurationManager, _libraryMonitor, _fileSystem, _logger).SaveImage(item, fileStream, mimeType, type, imageIndex, saveLocallyWithMedia, cancellationToken);
            
      }
      catch (IOException ex)
      {
          _logger.LogError(ex, "Source file {Source} not found or in use, skip removing", source);
      }
      finally
      {
      	  if (File.Exists(source))
      	  {
      	  	      File.Delete(source);
      	  }
      }
```

If the delete fails, there aint much we can do anyway.

File: MediaBrowser.Providers/Manager/ProviderManager.cs [hunk 2]
```diff
@@ -251,15 +251,45 @@ public Task SaveImage(BaseItem item, Stream source, string mimeType, ImageType t
...
+            Exception? saveException = null;
+
+            try
+            {
+                var fileStream = AsyncFile.OpenRead(source);
+                await new ImageSaver(_configurationManager, _libraryMonitor, _fileSystem, _logger).SaveImage(item, fileStream, mimeType, type, imageIndex, saveLocallyWithMedia, cancellationToken);
+            }
+            catch (Exception ex)
+            {
+                saveException = ex;
```
Comment (JPVenson) [inline MediaBrowser.Providers/Manager/ProviderManager.cs:270]: Use [ExceptionDispatchInfo](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.exceptionservices.exceptiondispatchinfo?view=net-8.0).Capture to preserve stacktrace

**Review by JPVenson — CHANGES_REQUESTED** [review]

**Review by JPVenson — APPROVED** [review]

File: MediaBrowser.Providers/Manager/ProviderManager.cs [hunk 3]
```diff
@@ -251,15 +252,42 @@ public Task SaveImage(BaseItem item, Stream source, string mimeType, ImageType t
...
+            ExceptionDispatchInfo? saveException = null;
+
+            try
+            {
+                var fileStream = AsyncFile.OpenRead(source);
+                await new ImageSaver(_configurationManager, _libraryMonitor, _fileSystem, _logger).SaveImage(item, fileStream, mimeType, type, imageIndex, saveLocallyWithMedia, cancellationToken);
+            }
+            catch (Exception ex)
+            {
+                saveException = ExceptionDispatchInfo.Capture(ex);
```
Comment (cvium) [inline MediaBrowser.Providers/Manager/ProviderManager.cs:271]: Why not just let it throw? The finally block will get executed regardless. If `File.Delete` throws a non-IOException, the exception by ImageSaver will get swallowed

Comment (gnattu) [reply MediaBrowser.Providers/Manager/ProviderManager.cs]: I was not quite confident with the behavior of just throw without catching for such nested try catch. So we can still see if it is from the `ImageSaver` or from the `File.Delete` right? Because if the `ImageSaver` failed for some reason the `File.Delete` would also have a high chance to fail as well, we need to tell which one caused the failure.

**Review by cvium — APPROVED** [review]
