### PR TITLE
Use music metadata from ffprobe when TagLib fails

### LINKED ISSUE #11678: Not fetching metadata for more than half of my music library:
### Please describe your bug

After some problems I ended up uninstalling and reinstalling jellyfin twice while making sure there were no jellyfin files left. I set up my libraries and my movies are fetching just right, however the music isn't, I try searching with MusicBrainz and it finds it but it shows that there are no images or anything else to grab, also the metadata isn't getting filled properly and many albums I'd have to fill by hand, I think the MusicBrainz extension may have issues. And for the record, yes, my music was propperly tagged by Picard.

### Reproduction Steps

It was working in the previous version so probably update jellyfin and the musicbrainz extension and there will be the error.

### Jellyfin Version

10.9.0

### if other:

_No response_

### Environment

```markdown
- OS: Debian 12
- Linux Kernel: 6.1.0-21-amd64
- Virtualization: No
- Clients: Browser
- Browser: Firefox
- FFmpeg Version: 6-jellyfin
- Playback Method: Direct stream
- Hardware Acceleration: none
- GPU Model: Apollo Lake [HD Graphics 505]
- Plugins: Fanart, Ani-list, Cover Art Archive, Jellyfin-Ani-Sync, AudioDB, Discogs, MusicBrainz, OMDb, Sutdio Images, TMDb
- Reverse Proxy: nginx proxy manager
- Base URL: none
- Networking: Host
- Storage: local
```

### Jellyfin logs

```shell
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.Fanart.Providers.AlbumProvider.AddImages(List`1 list, String path, String releaseId, String releaseGroupId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Fanart.Providers.AlbumProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)
[2024-05-16 03:06:34.938 -06:00] [INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/media/music/Mystery Skulls/Ultra Rare, Vol. 1/06 Soul on Fire.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-16 03:06:36.503 -06:00] [INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/media/music/Mystery Skulls/Ultra Rare, Vol. 1/05 Keep It Together.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-16 03:06:39.051 -06:00] [INF] Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/media/music/Mystery Skulls/Ultra Rare, Vol. 1/04 In My Sleep.mp3\" -threads 0 -v warning -print_format json -show_streams -show_format"
[2024-05-16 03:06:40.466 -06:00] [ERR] "AlbumProvider" failed in GetImageInfos for type "MusicAlbum" at "/data/media/music/Mystery Skulls/Ultra Rare, Vol. 1"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jellyfin.Plugin.Fanart.Providers.AlbumProvider.AddImages(List`1 list, String path, String releaseId, String releaseGroupId, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Fanart.Providers.AlbumProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)
[2024-05-16 03:06:41.655 -06:00] [ERR] Error refreshing item
System.InvalidOperationException: Must add values for the following parameters: @Type2, @Value2, @CleanValue2
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements()+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at Emby.Server.Implementations.Data.SqliteItemRepository.InsertItemValues(Guid id, List`1 values, SqliteConnection db)
   at Emby.Server.Implementations.Data.SqliteItemRepository.UpdateItemValues(Guid itemId, List`1 values, SqliteConnection db)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTransaction(SqliteConnection db, IEnumerable`1 tuples)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IReadOnlyList`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.UpdateItemsAsync(IReadOnlyList`1 items, BaseItem parent, ItemUpdateType updateReason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.SaveItemAsync(MetadataResult`1 result, ItemUpdateType reason, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RefreshMetadata(BaseItem item, MetadataRefreshOptions refreshOptions, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Audio.MusicAlbum.RefreshAllMetadata(MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshAllMetadataForContainer(IMetadataContainer container, MetadataRefreshOptions refreshOptions, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass69_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.RefreshChildMetadata(BaseItem child, MetadataRefreshOptions refreshOptions, Boolean recursive, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.<>c__DisplayClass69_0`1.<<RunTasks>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at MediaBrowser.Controller.Entities.Folder.RunTasks[T](Func`3 task, IList`1 children, IProgress`1 progress, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshCollectionFolderChildren(MetadataRefreshOptions options, CollectionFolder collectionFolder, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.RefreshItem(BaseItem item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.StartProcessingRefreshQueue()
[2024-05-16 03:06:47.150 -06:00] [INF] Logging out access token "2fcad4e65cbc4daabcd3024e0003af12"
[2024-05-16 03:06:47.228 -06:00] [INF] Logging out access token "4bb8c35bd4de495b943ae955e17995bb"
[2024-05-16 03:06:47.228 -06:00] [INF] Logging out access token "bdd2ec421ec44d60b2ef52471b7cd3b5"
[2024-05-16 03:06:47.228 -06:00] [INF] Logging out access token "2a54313a850046d6b1f62949dc9d6200"
[2024-05-16 03:06:49.616 -06:00] [INF] Logging out access token "bd00b4182be44e90b9e2ed4b90c179aa"
[2024-05-16 03:06:49.997 -06:00] [INF] Logging out access token "81cc647cf1434671ad015f1ff1f0e977"
[2024-05-16 03:07:20.989 -06:00] [ERR] Provider "Discogs" failed to retrieve search results
System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Jellyfin.Plugin.Discogs.DiscogsApi.Request(HttpRequestMessage request, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Discogs.DiscogsApi.Search(String query, String type, CancellationToken cancellationToken)
   at Jellyfin.Plugin.Discogs.Providers.DiscogsAlbumProvider.GetSearchResults(AlbumInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
```

### FFmpeg logs

_No response_

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

image

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by gnattu**
TagLib has its own limitations, which cause it to fail on certain audio files or extract incomplete information from the tags. Use the information from ffprobe when TagLib fails to extract data.

**Changes**

- Use ffprobe's data when taglib fails.

**Issues**

Fixes #11678

Also forum: https://forum.jellyfin.org/t-mka-tags-recognized-by-jellyfin

### CODE REVIEW

**Review by Shadowghost — APPROVED** [review]

File: MediaBrowser.Providers/MediaInfo/AudioFileProber.cs [hunk 1]
```diff
@@ -151,198 +152,214 @@ public class AudioFileProber
...
+                else if (tagTypes.HasFlag(TagTypes.Id3v1))
+                {
+                    tags = file.GetTag(TagTypes.Id3v1);
+                }
             }
-            else if (tagTypes.HasFlag(TagTypes.AudibleMetadata))
+            catch (Exception e)
             {
-                tags = file.GetTag(TagTypes.AudibleMetadata);
+                _logger.LogWarning("TagLib-Sharp does not support this audio: {Exception}", e);
```
Comment (cvium) [inline MediaBrowser.Providers/MediaInfo/AudioFileProber.cs:192]:
```suggestion
                _logger.LogWarning(e, "TagLib-Sharp does not support this audio");
```

File: MediaBrowser.Providers/MediaInfo/AudioFileProber.cs [hunk 2]
```diff
@@ -151,198 +152,214 @@ public class AudioFileProber
...
             }
-            else if (tagTypes.HasFlag(TagTypes.Id3v1))
+            finally
```
Comment (cvium) [inline MediaBrowser.Providers/MediaInfo/AudioFileProber.cs:194]: Not that it matters, but it seems a little overkill with a finally-block

**Review by cvium — APPROVED** [review]

**Review by crobibero — APPROVED** [review]
