### PR TITLE
Fix default aspect ratio

### LINKED ISSUE #741: Under/overflow when browsing photos makes web interface non-functional
**Describe the bug**
This happens with the latest state of git master. After trying to browse my photo collection, an error was logged (overflow or underflow; see below for the log) and then, the following error appeared in the browser, on first reload:

```
Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
```

After that, there's no way to access the server anymore, not even with restarts. See the excerpt of the logs further below. The error seems to be triggered by another error when processing the thumbnails of one of my photo media galleries (see below as well):

**Logs**

The original error when browsing the photo gallery, which occurs at the time of extracting image sizes:

```
gen 27 19:11:24 palver.lan dotnet[23375]: [19:11:24] [ERR] Error processing request
gen 27 19:11:24 palver.lan dotnet[23375]: System.OverflowException: Value was either too large or too small for an Int32.
gen 27 19:11:24 palver.lan dotnet[23375]:    at System.Convert.ToInt32(Double value)
gen 27 19:11:24 palver.lan dotnet[23375]:    at MediaBrowser.Controller.Drawing.ImageHelper.GetSizeEstimate(ImageProcessingOptions options) in /home/emby/jellyfin/MediaBrowser.Controller/Drawing/ImageHelper.cs:line 38
gen 27 19:11:24 palver.lan dotnet[23375]:    at MediaBrowser.Controller.Drawing.ImageHelper.GetNewImageSize(ImageProcessingOptions options, Nullable`1 originalImageSize) in /home/emby/jellyfin/MediaBrowser.Controller/Drawing/ImageHelper.cs:line 19
gen 27 19:11:24 palver.lan dotnet[23375]:    at Emby.Drawing.ImageProcessor.ProcessImage(ImageProcessingOptions options) in /home/emby/jellyfin/Emby.Drawing/ImageProcessor.cs:line 233
gen 27 19:11:24 palver.lan dotnet[23375]:    at MediaBrowser.Api.Images.ImageService.GetImageResult(BaseItem item, Guid itemId, ImageRequest request, ItemImageInfo image, Boolean cropwhitespace, ImageFormat[] supportedFormats, IImageEnhancer[] enhancers, Nullable`1 cacheDuration, IDictionary`2 headers, Boolean isHeadRequest) in /home/emby/jellyfin/MediaBrowser.Api/Images/ImageService.cs:line 639
gen 27 19:11:24 palver.lan dotnet[23375]:    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /home/emby/jellyfin/Emby.Server.Implementations/Services/ServiceExec.cs:line 112
gen 27 19:11:24 palver.lan dotnet[23375]:    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /home/emby/jellyfin/Emby.Server.Implementations/Services/ServiceHandler.cs:line 95
gen 27 19:11:24 palver.lan dotnet[23375]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /home/emby/jellyfin/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 608
gen 27 19:11:24 palver.lan dotnet[23375]: [19:11:24] [INF] HTTP Response 500 to REDACTED. Time: 101ms. http://REDACTED:8096/emby/Items/3c337a14bc987275566ead39377b399f/Images/Primary?maxHeight=317&maxWidth=317&tag=c7f3004a26ba76bc70ec2313d2effe0b&quality=90
```

Subsequent attempts to load the service, no matter which address, result in this then:

```
gen 27 19:03:55 palver.lan dotnet[23375]: [19:03:55] [ERR] Error processing request
gen 27 19:03:55 palver.lan dotnet[23375]: System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
gen 27 19:03:55 palver.lan dotnet[23375]:    at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)
gen 27 19:03:55 palver.lan dotnet[23375]:    at System.Guid.TryParseGuidWithNoStyle(ReadOnlySpan`1 guidString, GuidResult& result)
gen 27 19:03:55 palver.lan dotnet[23375]:    at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidStyles flags, GuidResult& result)
gen 27 19:03:55 palver.lan dotnet[23375]:    at System.Guid..ctor(String g)
gen 27 19:03:55 palver.lan dotnet[23375]:    at Emby.Server.Implementations.HttpServer.HttpResultFactory.GetStaticResult(IRequest requestContext, StaticResultOptions options) in /home/emby/jellyfin/Emby.Server.Implementations/HttpServer/HttpResultFactory.cs:line 538
gen 27 19:03:55 palver.lan dotnet[23375]:    at MediaBrowser.WebDashboard.Api.DashboardService.Get(GetDashboardResource request) in /home/emby/jellyfin/MediaBrowser.WebDashboard/Api/DashboardService.cs:line 353
gen 27 19:03:55 palver.lan dotnet[23375]:    at Emby.Server.Implementations.Services.ServiceExecGeneral.GetTaskResult(Task task) in /home/emby/jellyfin/Emby.Server.Implementations/Services/ServiceExec.cs:line 112
gen 27 19:03:55 palver.lan dotnet[23375]:    at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost appHost, IRequest httpReq, IResponse httpRes, ILogger logger, String operationName, CancellationToken cancellationToken) in /home/emby/jellyfin/Emby.Server.Implementations/Services/ServiceHandler.cs:line 95
gen 27 19:03:55 palver.lan dotnet[23375]:    at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken) in /home/emby/jellyfin/Emby.Server.Implementations/HttpServer/HttpListenerHost.cs:line 608
gen 27 19:03:58 palver.lan dotnet[23375]: [19:03:58] [INF] HTTP GET http://REDACTED:8096/dlna/9d59fec0f5b14ca6b0d88bbc120af30b/description.xml. UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
gen 27 19:03:58 palver.lan dotnet[23375]: [19:03:58] [INF] HTTP Response 200 to REDACTED. Time: 82ms. http://REDACTED:8096/dlna/9d59fec0f5b14ca6b0d88bbc120af30b/description.xml
```

*

**System (please complete the following information):**
 - OS: openSUSE Tumbleweed
 - Browser: Firefox
 - Jellyfin Version: latest master

### PR DESCRIPTION
**Pull request by cvium**
**Changes**
Changed GetDefaultPrimaryImageAspectRatio back to its original behaviour. It used to be a `double?` though but that didn't work for some reason when serializing it.
**Issues**
Fixes #741

### CODE REVIEW

**Comment by lbeltrame** [comment]
Patched and built this PR: unfortunately once triggered this won't fix the second issue in #741 (once broken, it can't recover, it seems): it might however fix the "cause" of it.

File: MediaBrowser.Controller/Drawing/ImageHelper.cs [hunk 1]
```diff
@@ -63,7 +63,7 @@ private static double GetEstimatedAspectRatio(ImageType type, BaseItem item)
                 case ImageType.Logo:
                     return 2.58;
                 case ImageType.Primary:
-                    return item.GetDefaultPrimaryImageAspectRatio();
+                    return item.GetDefaultPrimaryImageAspectRatio() > 0 ? item.GetDefaultPrimaryImageAspectRatio() : 2.0 / 3;
```
Comment (Bond-009) [inline MediaBrowser.Controller/Drawing/ImageHelper.cs]: Store it in a var instead.

**Comment by cvium** [comment]
@lbeltrame It worked for me. Have you tried clearing the cache?

**Comment by lbeltrame** [comment]
@cvium Yeah, after cleaning the cache it works.
