### PR TITLE
Avoid printing stacktrace when bind to port 1900 fails

### LINKED ISSUE #417: Improve error message for failing to bind to port
Whenever Jellyfin fails to bind to UDP port 1900 the error isn't caught and a stacktrace printed instead, which doesn't even mention the relevant port.

I'm not sure if the web server ports are handled differently but IMHO these errors should be caught and a consistent message displays that includes which port is affected and what could be causing it.

### PR DESCRIPTION
**Pull request by Bond-009**
**Changes**
Only print stacktrace on unexpected errors.

**Issues**
Fixes #417

### CODE REVIEW

File: RSSDP/SsdpCommunicationsServer.cs [hunk 1]
```diff
@@ -126,6 +126,10 @@ public void BeginListeningForBroadcasts()
                         {
                             _BroadcastListenSocket = ListenForBroadcastsAsync();
                         }
+                        catch (SocketException)
+                        {
+                            _logger.LogError("Failed to bind to port 1900. DLNA will be unavailable");
```
Comment (JustAMan) [inline RSSDP/SsdpCommunicationsServer.cs]: Is this 1900 not available as a variable? I don't like how it's hardcoded in the message. Also I thought 1900 is for auto-discovery, not for DLNA?

Comment (Bond-009) [reply RSSDP/SsdpCommunicationsServer.cs]: `ListenForBroadcastsAsync` only binds port 1900 (const).
Don't know if what *exactly* the port is used for, but it has something to do with DLNA

Comment (hawken93) [reply RSSDP/SsdpCommunicationsServer.cs]: http://www.upnp-hacks.org/upnp.html
universal plug & play, this would be the upnp port mapping, but could possibly be more
