### PR TITLE
Handle es-419 in TMDb

### LINKED ISSUE #14743: Metadata language defaults to generic Spanish instead of es-MX
### This issue respects the following points:

- [x] This is a **bug**, not a question or a configuration issue; Please visit our [forum or chat rooms](https://jellyfin.org/contact/) first to troubleshoot with volunteers, before creating a report.
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin/issues?q=is%3Aopen+is%3Aissue) _(I've searched it)_.
- [x] I'm using an up to date version of Jellyfin Server stable, unstable or master; We generally do not support previous older versions. If possible, please update to the latest version before opening an issue.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Description of the bug

In Jellyfin 10.11(2025090105), when the metadata language for the server and libraries is set to Spanish (Mexico) ("es-MX"), the metadata for movies and series is still generated in generic Spanish ("es") instead of the expected regional Spanish ("es-MX"). Previously, Jellyfin generated metadata correctly in es-MX.

### Reproduction steps

1. Set the server and library metadata language to Spanish (Mexico) ("es-MX").
2. Add new items or refresh existing library items.
3. Observe that movie/series titles and descriptions are generated in generic Spanish ("es").

### What is the current _bug_ behavior?

Metadata is generated in generic Spanish ("es") even when both the server and library are configured to use Spanish (Mexico) ("es-MX").

### What is the expected _correct_ behavior?

Metadata should be generated in Spanish (Mexico) ("es-MX") if available from the provider.

### Jellyfin Server version

Unstable

### Specify commit id

_No response_

### Specify unstable release number

_No response_

### Specify version number

_No response_

### Specify the build version

2025090105

### Environment

```markdown
- Jellyfin version: 10.11
 - OS: Debian 12
 - Browser: Firefox
```

### Jellyfin logs

```shell
sep 04 13:10:28 debian jellyfin[1130]: [13:10:28] [INF] Setting provider id's to item 23c71626-f3ef-1436-3ba2-4e3f7349a8cb-樱桃琥珀: {"Tmdb": "261128"}
```

### FFmpeg logs

```shell

```

### Client / Browser logs

_No response_

### Relevant screenshots or videos

Image

### Additional information

This appears to be a regression from previous behavior where metadata was correctly generated in es-MX.  
Also, when metadata is not available in Spanish (es-Es), Jellyfin falls back to English even though Spanish Mexico (es-Mx) metadata does exist. This suggests the fallback logic may be ignoring es-MX.

### PR DESCRIPTION
**Pull request by Lampan-git**
**Changes**
Handle es-419 in TMDb. 

When selecting "Spanish; Latin" we now, in 10.11, store that as es-419 instead of es-MX. 

Checks if es-419 and then checks if the country is Argentina and select it otherwise fallback to es-MX. If there is no "es-AR" data "es" will be fetched. 

**Issues**
Fixes #14743

PS. I had to restart each time I changed the library metadata settings, I don't know if that is an issue or not or if my dev env is weird.
PPS. Its also really confusing to have two metadata library settings that is tiered, one in dashboard and one in normal browse.

### CODE REVIEW

File: MediaBrowser.Providers/Plugins/Tmdb/TmdbUtils.cs [hunk 1]
```diff
@@ -140,15 +141,22 @@ public static string GetImageLanguagesParam(string preferredLanguage)
...
             if (string.IsNullOrEmpty(language))
             {
                 return language;
             }
 
+            // Handle es-419 (Latin American Spanish) by converting to regional variant
+            if (language == "es-419" && !string.IsNullOrEmpty(countryCode))
+            {
+                language = countryCode == "AR" ? "es-AR" : "es-MX";
+            }
```
Comment (crobibero) [inline MediaBrowser.Providers/Plugins/Tmdb/TmdbUtils.cs]:
```suggestion
            if (string.Equals(language, "es-419", StringComparison.OrdinalIgnoreCase) && !string.IsNullOrEmpty(countryCode))
            {
                language = string.Equals(countryCode, "AR", StringComparison.OrdinalIgnoreCase)
                    ? "es-AR"
                    : "es-MX";
            }
```
