### PR TITLE
Enforce a specific folder structure for Extras to avoid misidentification

### LINKED ISSUE #1278: Movie grouping/Box Sets doesn't work
Grouping manually or with the TMDb Box Sets-Plugin does create the correct Movie Collection Folder but with no Movie-Files in it to select or to play. Adding the movie manually, jellyfin says "added" but in the Collection Folder are still no movies/content to play.
verifying the collection.xml file under /var/lib/jellyfin/data/collections/<movie>, the path is correct, but the single movies are not shown in the collection folder. 

**System (please complete the following information):**
 - OS: Debian
 - Browser: chrome
 - Jellyfin Version: Version: 10.3.0

### PR DESCRIPTION
**Pull request by cvium**
Fixes #1278 

**Caveat**: This change only fixes _newly added_ media

### CODE REVIEW

**Comment by cvium** [comment]
This will fix the library, I think

```
WITH owner AS
(
	select tbi1.guid, tbi1.path
	from TypedBaseItems tbi1
	inner join TypedBaseItems tbi2 ON tbi2.Path = tbi1.Path and tbi1.Guid <> tbi2.Guid
	where tbi2.ExtraType is not null
	  and tbi1.ExtraType is null
)
UPDATE TypedBaseItems
SET OwnerId = (SELECT guid FROM owner WHERE owner.Path = TypedBaseItems.Path)
WHERE ExtraType is not null;
```

**Comment by lukastribus** [comment]
Does not fix the issue fully.

While new movies now do show up in the collection after adding them, they show up without any metadata associated with it.

**Comment by cvium** [comment]
The fix has been changed to enforce a more sane folder structure similar to Plex and Emby

**Comment by lukastribus** [comment]
Patch LGTM for new movies.

Will check the database fix later.

File: MediaBrowser.Controller/Entities/BaseItem.cs [hunk 1]
```diff
@@ -82,6 +82,21 @@ protected BaseItem()
         public static string ThemeSongsFolderName = "theme-music";
         public static string ThemeSongFilename = "theme";
         public static string ThemeVideosFolderName = "backdrops";
+        public static string ExtrasFolderName = "extras";
```
Comment (Bond-009) [inline MediaBrowser.Controller/Entities/BaseItem.cs]: Why are/were these `static` instead of `const`?

File: MediaBrowser.Controller/Entities/BaseItem.cs [hunk 2]
```diff
@@ -82,6 +82,21 @@ protected BaseItem()
...
+        public static string BehindTheScenesFolderName = "behind the scenes";
+        public static string DeletedScenesFolderName = "deleted scenes";
+        public static string InterviewFolderName = "interviews";
+        public static string SceneFolderName = "scenes";
+        public static string SampleFolderName = "samples";
+
+        public static string[] AllExtrasTypesFolderNames = {
```
Comment (Bond-009) [inline MediaBrowser.Controller/Entities/BaseItem.cs]: This array is a mutable public field, wouldn't a readonly array be better?

File: MediaBrowser.Controller/Entities/BaseItem.cs [hunk 3]
```diff
@@ -1296,32 +1310,36 @@ private static Video[] LoadThemeVideos(IEnumerable<FileSystemMetadata> fileSyste
...
 
-            return LibraryManager.ResolvePaths(files, directoryService, null, new LibraryOptions())
-                .OfType<Video>()
-                .Select(item =>
-                {
-                    // Try to retrieve it from the db. If we don't find it, use the resolved version
-                    var dbItem = LibraryManager.GetItemById(item.Id) as Video;
+            foreach (var extraFolderName in AllExtrasTypesFolderNames)
+            {
+                var files = fileSystemChildren.Where(i => i.IsDirectory)
```
Comment (Bond-009) [inline MediaBrowser.Controller/Entities/BaseItem.cs]: This is executed for each folder, maybe move it out the loop?
Or use `IEnumerable.Contains` instead of a `foreach` loop and `string.Equals`

File: MediaBrowser.Controller/Entities/BaseItem.cs [hunk 4]
```diff
@@ -1481,7 +1499,10 @@ private async Task<bool> RefreshLocalTrailers(IHasTrailers item, MetadataRefresh
 
         private async Task<bool> RefreshExtras(BaseItem item, MetadataRefreshOptions options, List<FileSystemMetadata> fileSystemChildren, CancellationToken cancellationToken)
         {
-            var newExtras = LoadExtras(fileSystemChildren, options.DirectoryService).Concat(LoadThemeVideos(fileSystemChildren, options.DirectoryService)).Concat(LoadThemeSongs(fileSystemChildren, options.DirectoryService));
+            var newExtras = LoadExtras(fileSystemChildren, options.DirectoryService)
```
Comment (Bond-009) [inline MediaBrowser.Controller/Entities/BaseItem.cs]: The LINQ `Concat` method is terribly slow. Since all the functions return an array the total length is know and you could create a new array and use `.CopyTo`.

File: MediaBrowser.Controller/Entities/BaseItem.cs [hunk 5]
```diff
@@ -1493,7 +1514,16 @@ private async Task<bool> RefreshExtras(BaseItem item, MetadataRefreshOptions opt
 
                 var tasks = newExtras.Select(i =>
                 {
-                    return RefreshMetadataForOwnedItem(i, true, new MetadataRefreshOptions(options), cancellationToken);
+                    var subOptions = new MetadataRefreshOptions(options);
+                    if (i.OwnerId != ownerId ||
+                        !i.ParentId.Equals(Guid.Empty))
```
Comment (Bond-009) [inline MediaBrowser.Controller/Entities/BaseItem.cs]:
```suggestion
                        i.ParentId != Guid.Empty)
```
And use the `||` to the start of the newline

**Comment by lukastribus** [comment]
Would it be possible to block the 10.3.3 realease until this is merged? Thanks.

**Comment by cvium** [comment]
If someone can test my latest changes, that would be great

**Comment by lukastribus** [comment]
Works for me.

**Comment by kjlhgfds** [comment]
I'm using jellyfin in a docker on a Openmediavault NAS, and for me, the issue is still there : 
- can't add movie to a collection,
- can't delete old collection (actualy I can delete them but they keep coming back).
I can create new collection, but still not add movie to it.

**Comment by lukastribus** [comment]
@kjlhgfds that's expected because this fix is only about *new movies* added to the library. Your existing movie entries are already corrupted.

Use @oddstr13 [jellyfin-collection-fix.py](https://github.com/oddstr13/jellyfin-fixup-scripts/blob/master/jellyfin-collection-fix.py) to fix your database.

**Comment by 0ddb0d** [comment]
I'm running on a QNAP NAS and oddstr13's script worked fine using Entware's Python3. For anybody else on this platform make sure you change the DBFILE variable to point to the correct location and make sure procps-ng-ps is installed as the script won't work with Busybox ps.

Thanks @cvium, @oddstr13 and @lukastribus

**Comment by oddstr13** [comment]
> I'm running on a QNAP NAS and oddstr13's script worked fine using Entware's Python3. For anybody else on this platform make sure you change the DBFILE variable to point to the correct location and make sure procps-ng-ps is installed as the script won't work with Busybox ps.
> 
> Thanks @cvium, @oddstr13 and @lukastribus
> 
> **Edit:-** It only partially worked, my existing admin account is OK but any accounts that do not have access to all libraries still show collections with no items.

Could you please submit issues on https://github.com/oddstr13/jellyfin-fixup-scripts ?

Include the data location on QNAP.

Also, a link to QNAP setup instructions would be appreciated, so I can test there too (I'm assuming you've installed via App Center here).
