### PR TITLE
Specify required movflags when encoding M4A audio

### LINKED ISSUE #9248: [Issue]: Transcoding audio to M4A returns files without moov atoms
### Please describe your bug

When using `/Audio/{id}/Universal` with `transcodingContainer=m4a` set to M4A, the returned media is corrupt. When compared to the cached transcode in `/config/transcodes`, we can see that the moov header is missing.

(`test` is what is returned by the API, `jellyfin` is what was in `/config/transcodes`)

```
james@JamesPC-Linux ~/D/JellyfinExamples> diff test-moov-bad.m4a.hex jellyfin-moov-bad.m4a.hex
3c3
< 00000020  66 72 65 65 00 00 00 00  6d 64 61 74 de 02 00 4c  |free....mdat...L|
---
> 00000020  66 72 65 65 00 59 86 b0  6d 64 61 74 de 02 00 4c  |free.Y..mdat...L|
```

This makes the returned files unreadable.

```
james@JamesPC-Linux ~/D/JellyfinExamples [1]> mpv test-moov-bad.m4a
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
[lavf] avformat_open_input() failed
[ffmpeg/demuxer] mov,mp4,m4a,3gp,3g2,mj2: moov atom not found
[lavf] avformat_open_input() failed
Failed to recognize file format.

Exiting... (Errors when loading file)
```

### Jellyfin Version

Other

### if other:

10.8.9

### Environment

```markdown
- OS: Arch
- Virtualization: Docker
- Clients: N/A
- Browser: N/A
- FFmpeg Version: ffmpeg version 5.1.2-Jellyfin
- Playback Method: N/A
- Hardware Acceleration: N/A
- Plugins: None (fresh install)
- Reverse Proxy: None
- Base URL: localhost
- Networking: -p 127.0.0.1:8096:8096
- Storage: Basic Docker mounts
```

### Jellyfin logs

```shell
[02:08:25] [INF] [6] Main: Jellyfin version: 10.8.9
[02:08:25] [INF] [6] Main: Environment Variables: ["[JELLYFIN_CONFIG_DIR, /config/config]", "[JELLYFIN_DATA_DIR, /config]", "[JELLYFIN_WEB_DIR, /jellyfin/jellyfin-web]", "[JELLYFIN_CACHE_DIR, /cache]", "[JELLYFIN_LOG_DIR, /config/log]", "[JELLYFIN_FFMPEG, /usr/lib/jellyfin-ffmpeg/ffmpeg]", "[DOTNET_SYSTEM_GLOBALIZATION_INVARIANT, 1]"]
[02:08:25] [INF] [6] Main: Arguments: ["/jellyfin/jellyfin.dll"]
[02:08:25] [INF] [6] Main: Operating system: Linux
[02:08:25] [INF] [6] Main: Architecture: X64
[02:08:25] [INF] [6] Main: 64-Bit Process: True
[02:08:25] [INF] [6] Main: User Interactive: True
[02:08:25] [INF] [6] Main: Processor count: 24
[02:08:25] [INF] [6] Main: Program data path: /config
[02:08:25] [INF] [6] Main: Web resources path: /jellyfin/jellyfin-web
[02:08:25] [INF] [6] Main: Application directory: /jellyfin/
[02:08:25] [INF] [6] Jellyfin.Server.Migrations.MigrationRunner: Marking following migrations as applied because this is a fresh install: ["CreateNetworkConfiguration"]
[02:08:25] [INF] [6] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
[02:08:25] [INF] [6] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[02:08:25] [INF] [6] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[02:08:25] [INF] [6] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[02:08:25] [INF] [6] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[02:08:25] [INF] [6] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[02:08:25] [INF] [6] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
[02:08:26] [INF] [6] Jellyfin.Server.Implementations.JellyfinDbProvider: There are pending EFCore migrations in the database. Applying... (This may take a while, do not stop Jellyfin)
[02:08:27] [INF] [6] Jellyfin.Server.Implementations.JellyfinDbProvider: EFCore migrations applied successfully
[02:08:27] [INF] [6] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[02:08:27] [INF] [6] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
[02:08:27] [INF] [6] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: TMDb 10.8.9.0
[02:08:27] [INF] [6] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: Studio Images 10.8.9.0
[02:08:27] [INF] [6] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: OMDb 10.8.9.0
[02:08:27] [INF] [6] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: MusicBrainz 10.8.9.0
[02:08:27] [INF] [6] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: AudioDB 10.8.9.0
[02:08:27] [INF] [6] Jellyfin.Server.Migrations.MigrationRunner: Marking following migrations as applied because this is a fresh install: ["DisableTranscodingThrottling", "CreateLoggingConfigHeirarchy", "MigrateActivityLogDatabase", "RemoveDuplicateExtras", "MigrateUserDatabase", "MigrateDisplayPreferencesDatabase", "RemoveDownloadImagesInAdvance", "MigrateAuthenticationDatabase"]
[02:08:27] [INF] [6] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'AddDefaultPluginRepository'
[02:08:27] [INF] [6] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[02:08:27] [INF] [6] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
[02:08:27] [INF] [6] Jellyfin.Server.Migrations.MigrationRunner: Migration 'AddDefaultPluginRepository' applied successfully
[02:08:27] [INF] [6] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'ReaddDefaultPluginRepository'
[02:08:27] [INF] [6] Jellyfin.Server.Migrations.MigrationRunner: Migration 'ReaddDefaultPluginRepository' applied successfully
[02:08:27] [INF] [6] Jellyfin.Server.Migrations.MigrationRunner: Applying migration 'AddPeopleQueryIndex'
[02:08:27] [INF] [6] Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex: Creating index idx_TypedBaseItemsUserDataKeyType
[02:08:27] [INF] [6] Jellyfin.Server.Migrations.Routines.AddPeopleQueryIndex: Creating index idx_PeopleNameListOrder
[02:08:27] [INF] [6] Jellyfin.Server.Migrations.MigrationRunner: Migration 'AddPeopleQueryIndex' applied successfully
[02:08:27] [INF] [6] Main: Kestrel listening on Any IP4 Address
[02:08:27] [WRN] [6] Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository: Using an in-memory repository. Keys will not be persisted to storage.
[02:08:27] [WRN] [6] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
[02:08:28] [WRN] [6] Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager: No XML encryptor configured. Key {cd03ae80-155e-4a8c-bd20-90cb4abc0683} may be persisted to storage in unencrypted form.
[02:08:28] [INF] [6] Emby.Server.Implementations.ApplicationHost: Running startup tasks
[02:08:28] [INF] [6] Emby.Server.Implementations.ScheduledTasks.TaskManager: Daily trigger for Extract Chapter Images set to fire at 2023-02-05 02:00:00.000 +00:00, which is 23:51:31.8537186 from now.
[02:08:28] [INF] [6] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Found ffmpeg version 5.1.2
[02:08:28] [INF] [6] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available decoders: ["libdav1d", "av1", "av1_cuvid", "av1_qsv", "h264", "h264_qsv", "h264_cuvid", "hevc", "hevc_qsv", "hevc_cuvid", "mpeg2video", "mpeg2_qsv", "mpeg2_cuvid", "mpeg4", "mpeg4_cuvid", "msmpeg4", "vc1_qsv", "vc1_cuvid", "vp8", "libvpx", "vp8_cuvid", "vp8_qsv", "vp9", "libvpx-vp9", "vp9_cuvid", "vp9_qsv", "aac", "ac3", "flac", "mp3"]
[02:08:28] [INF] [6] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available encoders: ["libx264", "h264_amf", "h264_nvenc", "h264_qsv", "h264_v4l2m2m", "h264_vaapi", "libx265", "hevc_amf", "hevc_nvenc", "hevc_qsv", "hevc_vaapi", "mpeg4", "msmpeg4", "libvpx", "libvpx-vp9", "aac", "libfdk_aac", "ac3", "flac", "libmp3lame", "libopus", "libvorbis", "srt"]
[02:08:28] [INF] [6] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available filters: ["deinterlace_qsv", "deinterlace_vaapi", "hwupload_cuda", "hwupload_vaapi", "overlay_opencl", "overlay_qsv", "overlay_vaapi", "overlay_cuda", "procamp_vaapi", "scale_cuda", "scale_opencl", "scale_qsv", "scale_vaapi", "tonemap_cuda", "tonemap_opencl", "tonemap_vaapi", "vpp_qsv", "yadif_cuda", "zscale", "alphasrc"]
[02:08:28] [INF] [6] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Available hwaccel types: ["cuda", "vaapi", "qsv", "drm", "opencl", "vulkan"]
[02:08:28] [INF] [6] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: FFmpeg: /usr/lib/jellyfin-ffmpeg/ffmpeg
[02:08:28] [INF] [6] Emby.Server.Implementations.ApplicationHost: ServerId: 107b571ca9974a759755cc6d1ca7c423
[02:08:28] [INF] [7] Emby.Server.Implementations.ApplicationHost: Executed all pre-startup entry points in 0:00:00.0848
[02:08:28] [INF] [7] Emby.Server.Implementations.ApplicationHost: Core startup complete
[02:08:28] [INF] [7] Emby.Server.Implementations.ApplicationHost: Executed all post-startup entry points in 0:00:00.1492728
[02:08:28] [INF] [7] Main: Startup complete 0:00:03.2211425
[02:08:31] [INF] [7] Emby.Server.Implementations.ScheduledTasks.TaskManager: StartupTrigger fired for task: Update Plugins
[02:08:31] [INF] [7] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task PluginUpdateTask
[02:08:31] [INF] [6] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Update Plugins
[02:08:31] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: Update Plugins Completed after 0 minute(s) and 0 seconds
[02:08:31] [INF] [16] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[02:08:40] [INF] [7] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[02:08:40] [INF] [7] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
[02:08:40] [INF] [14] Emby.Server.Implementations.EntryPoints.ExternalPortForwarding: Stopping NAT discovery
[02:08:40] [WRN] [12] Jellyfin.Server.Implementations.Users.UserManager: No users, creating one with username MyJellyfinUser
[02:08:55] [WRN] [15] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'AccessSchedule' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:08:55] [WRN] [15] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ActivityLog' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:08:55] [WRN] [15] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'CustomItemDisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:08:55] [WRN] [15] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'DisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:08:55] [WRN] [15] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'HomeSection' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:08:55] [WRN] [15] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ImageInfo' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:08:55] [WRN] [15] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ItemDisplayPreferences' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:08:55] [WRN] [15] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Permission' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:08:55] [WRN] [15] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Preference' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:08:55] [WRN] [15] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'ApiKey' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:08:55] [WRN] [15] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'Device' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:08:55] [WRN] [15] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'DeviceOptions' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:08:55] [WRN] [15] Microsoft.EntityFrameworkCore.Model.Validation: The entity type 'User' is configured to use schema 'jellyfin', but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.
[02:08:58] [WRN] [24] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from http://localhost:8096/Library/VirtualFolders?collectionType=music&refreshLibrary=false&name=Music to 172.17.0.1 in 0:00:01.0665534 with Status Code 204
[02:09:00] [INF] [24] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[02:09:00] [INF] [24] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
[02:09:02] [INF] [12] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[02:09:02] [INF] [12] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : []
[02:09:02] [INF] [12] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: [10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]
[02:09:02] [INF] [12] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: []
[02:09:02] [INF] [12] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: []
[02:09:03] [INF] [14] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Saving system configuration
[02:09:03] [INF] [14] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: /cache
[02:09:03] [INF] [12] Emby.Server.Implementations.ScheduledTasks.TaskManager: Queuing task RefreshMediaLibraryTask
[02:09:03] [INF] [24] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Scan Media Library
[02:09:03] [INF] [12] Emby.Server.Implementations.EntryPoints.ExternalPortForwarding: Stopping NAT discovery
[02:09:03] [INF] [24] Emby.Server.Implementations.Library.LibraryManager: Validating media library
[02:09:05] [ERR] [28] Emby.Server.Implementations.Library.LibraryManager: Error running post-scan task
System.ArgumentException: Not enough valid pictures provided to create a splashscreen!
   at Jellyfin.Drawing.Skia.SplashscreenBuilder.GenerateCollage(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops)
   at Jellyfin.Drawing.Skia.SplashscreenBuilder.GenerateSplash(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops, String outputPath)
   at Jellyfin.Drawing.Skia.SkiaEncoder.CreateSplashscreen(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops)
   at Emby.Server.Implementations.Library.SplashscreenPostScanTask.Run(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.RunPostScanTasks(IProgress`1 progress, CancellationToken cancellationToken)
[02:09:05] [INF] [28] Emby.Server.Implementations.ScheduledTasks.TaskManager: Scan Media Library Completed after 0 minute(s) and 2 seconds
[02:09:05] [INF] [28] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[02:09:05] [INF] [6] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory /media
[02:09:06] [INF] [6] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for james has succeeded.
[02:09:06] [INF] [6] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user james: 0/0
[02:09:06] [INF] [6] Emby.Server.Implementations.Session.SessionManager: Creating new access token for user 5c53db54-cd38-48ce-911f-2cebb519fd0f
[02:09:06] [INF] [6] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 172.17.0.1 request
[02:09:39] [INF] [27] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[02:09:39] [INF] [27] Jellyfin.Api.Auth.CustomAuthenticationHandler: CustomAuthentication was not authenticated. Failure message: Invalid token.
[02:09:39] [INF] [27] Jellyfin.Api.Auth.CustomAuthenticationHandler: AuthenticationScheme: CustomAuthentication was challenged.
[02:09:50] [INF] [23] Jellyfin.Api.Controllers.UniversalAudioController: GetPostedPlaybackInfo profile: {"Name": null, "Id": null, "Identification": null, "FriendlyName": null, "Manufacturer": null, "ManufacturerUrl": null, "ModelName": null, "ModelDescription": null, "ModelNumber": null, "ModelUrl": null, "SerialNumber": null, "EnableAlbumArtInDidl": false, "EnableSingleAlbumArtLimit": false, "EnableSingleSubtitleLimit": false, "SupportedMediaTypes": "Audio,Photo,Video", "UserId": null, "AlbumArtPn": null, "MaxAlbumArtWidth": null, "MaxAlbumArtHeight": null, "MaxIconWidth": null, "MaxIconHeight": null, "MaxStreamingBitrate": 8000000, "MaxStaticBitrate": 8000000, "MusicStreamingTranscodingBitrate": 128000, "MaxStaticMusicBitrate": 8000000, "SonyAggregationFlags": null, "ProtocolInfo": null, "TimelineOffsetSeconds": 0, "RequiresPlainVideoItems": false, "RequiresPlainFolders": false, "EnableMSMediaReceiverRegistrar": false, "IgnoreTranscodeByteRangeRequests": false, "XmlRootAttributes": [], "DirectPlayProfiles": [], "TranscodingProfiles": [{"Container": "m4a", "Type": "Audio", "VideoCodec": "", "AudioCodec": "aac", "Protocol": "http", "EstimateContentLength": false, "EnableMpegtsM2TsMode": false, "TranscodeSeekInfo": "Auto", "CopyTimestamps": false, "Context": "Streaming", "EnableSubtitlesInManifest": false, "MaxAudioChannels": null, "MinSegments": 0, "SegmentLength": 0, "BreakOnNonKeyFrames": false, "Conditions": [], "$type": "TranscodingProfile"}], "ContainerProfiles": [], "CodecProfiles": [], "ResponseProfiles": [], "SubtitleProfiles": [], "$type": "DeviceProfile"}
[02:09:50] [INF] [23] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for james. EnableAudioPlaybackTranscoding: True
[02:09:51] [INF] [23] Jellyfin.Api.Helpers.TranscodingJobHelper: /usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M  -i file:"/media/My Chemical Romance/2022 - Foundations of Decay/01 - The Foundations of Decay.flac" -threads 0 -vn -ab 128000 -ac 2 -id3v2_version 3 -write_id3v1 1 -y "/config/transcodes/d9178aa9e9324bc56c6642435132b8ee.m4a"
[02:09:58] [INF] [24] Jellyfin.Api.Helpers.TranscodingJobHelper: FFmpeg exited with code 0
^C[02:15:27] [INF] [71] Main: Ctrl+C, shutting down
[02:15:27] [INF] [71] Main: Running query planner optimizations in the database... This might take a while
[02:15:27] [INF] [71] Emby.Server.Implementations.ApplicationHost: Disposing CoreAppHost
[02:15:27] [INF] [71] Emby.Server.Implementations.ApplicationHost: Disposing NotificationEntryPoint
[02:15:27] [INF] [71] Emby.Server.Implementations.ApplicationHost: Disposing UdpServerEntryPoint
[02:15:27] [INF] [71] Emby.Server.Implementations.ApplicationHost: Disposing DeviceAccessEntryPoint
[02:15:27] [INF] [71] Emby.Server.Implementations.ApplicationHost: Disposing LibraryChangedNotifier
[02:15:27] [INF] [71] Emby.Server.Implementations.ApplicationHost: Disposing ExternalPortForwarding
[02:15:27] [INF] [71] Emby.Server.Implementations.EntryPoints.ExternalPortForwarding: Stopping NAT discovery
[02:15:27] [INF] [71] Emby.Server.Implementations.ApplicationHost: Disposing DlnaEntryPoint
[02:15:27] [INF] [71] Emby.Dlna.Main.DlnaEntryPoint: Disposing PlayToManager
[02:15:27] [INF] [71] Emby.Dlna.Main.DlnaEntryPoint: Disposing DeviceDiscovery
[02:15:27] [INF] [71] Emby.Dlna.Main.DlnaEntryPoint: Disposing SsdpCommunicationsServer
[02:15:27] [INF] [71] Emby.Dlna.Main.DlnaEntryPoint: SsdpCommunicationsServer disposing _BroadcastListenSocket
[02:15:27] [INF] [71] Emby.Dlna.Main.DlnaEntryPoint: SsdpCommunicationsServer Disposing 3 sendSockets
[02:15:27] [INF] [71] Emby.Dlna.Main.DlnaEntryPoint: SsdpCommunicationsServer disposing sendSocket from 0.0.0.0
[02:15:27] [INF] [71] Emby.Dlna.Main.DlnaEntryPoint: SsdpCommunicationsServer disposing sendSocket from 172.17.0.2
[02:15:27] [INF] [71] Emby.Dlna.Main.DlnaEntryPoint: SsdpCommunicationsServer disposing sendSocket from 127.0.0.1
[02:15:27] [INF] [71] Emby.Server.Implementations.ApplicationHost: Disposing EmbyTV
[02:15:27] [INF] [71] Emby.Server.Implementations.ApplicationHost: Disposing UserDataChangeNotifier
[02:15:27] [INF] [71] Emby.Server.Implementations.ApplicationHost: Disposing MusicBrainzAlbumProvider
[02:15:27] [INF] [71] Emby.Server.Implementations.ApplicationHost: Disposing RecordingNotifier
[02:15:27] [INF] [71] Emby.Server.Implementations.ApplicationHost: Disposing LibraryMonitorStartup
[02:15:27] [INF] [71] Emby.Server.Implementations.ApplicationHost: Disposing EntryPoint
[02:15:27] [INF] [71] Emby.Server.Implementations.ApplicationHost: Disposing SchedulesDirect
[02:15:27] [INF] [71] Emby.Server.Implementations.ApplicationHost: Disposing EntryPoint
[02:15:27] [INF] [73] Emby.Server.Implementations.HttpServer.WebSocketManager: WS 172.17.0.1 closed
```

### FFmpeg logs

```shell
/Audio/5a6621ee6987d854c421a6b62064d84f/universal

{"Protocol":0,"Id":"5a6621ee6987d854c421a6b62064d84f","Path":"/media/My Chemical Romance/2022 - Foundations of Decay/01 - The Foundations of Decay.flac","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"flac","Size":42000284,"Name":"01 - The Foundations of Decay","IsRemote":false,"ETag":"9424ec70c7124ff837bf43436177a321","RunTimeTicks":3607600128,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"OpenToken":null,"RequiresClosing":false,"LiveStreamId":null,"BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":null,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"flac","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"DvVersionMajor":null,"DvVersionMinor":null,"DvProfile":null,"DvLevel":null,"RpuPresentFlag":null,"ElPresentFlag":null,"BlPresentFlag":null,"DvBlSignalCompatibilityId":null,"Comment":null,"TimeBase":"1/44100","CodecTimeBase":null,"Title":null,"VideoRange":null,"VideoRangeType":null,"VideoDoViTitle":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"FLAC - Stereo","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"stereo","BitRate":931373,"BitDepth":16,"RefFrames":null,"PacketLength":null,"Channels":2,"SampleRate":44100,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":null,"Type":0,"AspectRatio":null,"Index":0,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":931373,"Timestamp":null,"RequiredHttpHeaders":{},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":null,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 200M  -i file:"/media/My Chemical Romance/2022 - Foundations of Decay/01 - The Foundations of Decay.flac" -threads 0 -vn -ab 128000 -ac 2 -id3v2_version 3 -write_id3v1 1 -y "/config/transcodes/d9178aa9e9324bc56c6642435132b8ee.m4a"


ffmpeg version 5.1.2-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, flac, from 'file:/media/My Chemical Romance/2022 - Foundations of Decay/01 - The Foundations of Decay.flac':
  Metadata:
    GENRE           : Alternative
    track           : 1
    ALBUM           : The Foundations of Decay
    DATE            : 2022
    TITLE           : The Foundations of Decay
    ARTIST          : My Chemical Romance
  Duration: 00:06:00.76, start: 0.000000, bitrate: 931 kb/s
  Stream #0:0: Audio: flac, 44100 Hz, stereo, s16
Stream mapping:
  Stream #0:0 -> #0:0 (flac (native) -> aac (native))
Press [q] to stop, [?] for help
Output #0, ipod, to '/config/transcodes/d9178aa9e9324bc56c6642435132b8ee.m4a':
  Metadata:
    GENRE           : Alternative
    track           : 1
    ALBUM           : The Foundations of Decay
    DATE            : 2022
    TITLE           : The Foundations of Decay
    ARTIST          : My Chemical Romance
    encoder         : Lavf59.27.100
  Stream #0:0: Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s
    Metadata:
      encoder         : Lavc59.37.100 aac
size=       0kB time=00:00:00.04 bitrate=   7.6kbits/s speed=5.12x    
size=       0kB time=00:00:08.96 bitrate=   0.0kbits/s speed=17.5x    
size=     256kB time=00:00:16.76 bitrate= 125.1kbits/s speed=16.6x    
size=     256kB time=00:00:27.91 bitrate=  75.2kbits/s speed=18.4x    
size=     512kB time=00:00:44.44 bitrate=  94.4kbits/s speed=  22x    
size=    1024kB time=00:01:08.87 bitrate= 121.8kbits/s speed=27.3x    
size=    1536kB time=00:01:40.07 bitrate= 125.7kbits/s speed=33.1x    
size=    2048kB time=00:02:07.84 bitrate= 131.2kbits/s speed=36.2x    
size=    2304kB time=00:02:35.80 bitrate= 121.1kbits/s speed=38.6x    
size=    2816kB time=00:03:10.26 bitrate= 121.2kbits/s speed=  42x    
size=    3328kB time=00:03:41.93 bitrate= 122.8kbits/s speed=44.1x    
size=    4096kB time=00:04:21.13 bitrate= 128.5kbits/s speed=47.2x    
size=    4608kB time=00:04:57.16 bitrate= 127.0kbits/s speed=49.2x    
size=    5120kB time=00:05:25.31 bitrate= 128.9kbits/s speed=49.8x    
size=    5632kB time=00:05:56.05 bitrate= 129.6kbits/s speed=50.6x    
size=    5791kB time=00:06:00.76 bitrate= 131.5kbits/s speed=50.4x    
video:0kB audio:5730kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.078423%
[aac @ 0x55a5dbf81340] Qavg: 522.815
```

### Please attach any browser or client logs here

_No response_

### Please attach any screenshots here

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by jmshrv**
**Changes**

When the output container is [any valid MP4 extension](https://en.wikipedia.org/wiki/MP4_file_format#Filename_extensions), specify the same movflags that are also used in `GetProgressiveVideoAudioArguments`. I'm not 100% sure on the specifics, but this correctly returns an identical file to the one created in `/config/transcodes`.

(same as in the issue, `test` is what is returned from the API, `jellyfin` is what Jellyfin creates in `/config/transcodes`.

```
james@JamesPC-Linux ~/D/JellyfinExamples> sha256sum test-moov-fix.m4a jellyfin-moov-fix.m4a 
56059204973c1b52a3b1516ced84c52cd9a1204a4ef12352328a2ec77071ca64  test-moov-fix.m4a
56059204973c1b52a3b1516ced84c52cd9a1204a4ef12352328a2ec77071ca64  jellyfin-moov-fix.m4a
```

As expected, `test-moov-fix.m4a` can now be played correctly.

It may be worth using this implementation in `GetProgressiveVideoAudioArguments`, as it looks like requesting a `.m4v` file would not add the required flags.

Also, I've actually followed the [contributing guidelines](https://jellyfin.org/docs/general/contributing/development/) this time :upside_down_face: 

**Issues**

Fixes #9248

### CODE REVIEW

**Comment by jmshrv** [comment]
Side note - I believe that the core of this issue was caused by ffmpeg going back to fill in the moov header. Since Jellyfin starts returning the file as soon as it was written, it returned this incomplete header. A similar issue happens with `.caf` files, but sadly it looks like ffmpeg doesn't have any flags to fix that. Because of this, I can't implement transcoded Opus downloads on iOS :(

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 1]
```diff
@@ -5786,6 +5786,23 @@ public string GetProgressiveAudioFullCommandLine(EncodingJobInfo state, Encoding
...
+            // See #9248 and the associated PR for why this is needed
+            var mp4ContainerNames = new HashSet<string>
+            {
+                "mp4",
+                "m4a",
+                "m4p",
+                "m4b",
+                "m4r",
+                "m4v",
+            };
```
Comment (crobibero) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:5799]: This should be moved to the top and be `static readonly`

You should also initialize the hashset with a comparer instead of calling `.ToLower()`
```
new HashSet<string>(StringComparer.OrdinalIgnoreCase)
```

**Review by crobibero — CHANGES_REQUESTED** [review]

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs (hunk 1 above)
Comment (jmshrv) [reply MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs]: Resolved, that's a pretty nice C# feature :)

**Review by crobibero — APPROVED** [review]

**Review by Bond-009 — APPROVED** [review]

**Review by cvium — APPROVED** [review]

**Comment by Chaphasilor** [comment]
@jmshrv so does that mean there is no way to get OPUS/VORBIS transcoded audio to work on iOS? It sounds like OPUS doesn't work because of the issues with the CAF container, and VORBIS can't be played at all on iOS?
