### PR TITLE
Don't scale extracted images and ffmpeg improvements

### LINKED ISSUE #2345: Embedded images in audio files capped at 600px
**Describe the bug**

Artwork embedded in audio files of any format )is capped to a maximum 600x600 resolution, downscaling images in Jellyfin's library from the original sources.

**To Reproduce**
1. Add a song with an embedded artwork greater than 600x600
2. Wait for the library scan and open the "Edit images" option of the element

**Expected behavior**
Use original resolution images, extracting them from the metadata or directly reading them from the file during playback

**Screenshots**
* File in Jellyfin
Sin título
* File's metadata as read by MP3tag.

Sin título

**System (please complete the following information):**
 - OS: Debian Buster on Pi 3
 - Browser: Chrome
 - Jellyfin Version: 10.4.3

**Additional context**
Tested MP3 and FLAC, but I suppose this is unrelated and just depends on the music scanner/skia processing, so I believe all formats are affected.

### PR DESCRIPTION
**Pull request by ferferga**
**Changes**
* Don't scale images that are extracted from media files. Further processing (like cropping) for removing black borders from images taken from videos are left intact.
* Make ffmpeg use threads properly.

**Issues**
Fixes #2345

### CODE REVIEW

**Review by BaronGreenback — APPROVED** [review]

File: MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs [hunk 1]
```diff
@@ -64,6 +64,7 @@ public class MediaEncoder : IMediaEncoder, IDisposable
 
         private string _ffmpegPath = string.Empty;
         private string _ffprobePath;
+        private int threads = EncodingHelper.GetNumberOfThreads(null, _configurationManager.GetEncodingOptions(), null);
```
Comment (BaronGreenback) [inline MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs:67]: error CS0236: A field initializer cannot reference the non-static field, method, or property 'MediaEncoder._configurationManager'

**Review by BaronGreenback — APPROVED** [review]
Looks ok if you can get it to compile.

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 2]
```diff
@@ -2344,7 +2344,7 @@ public int GetNumberOfThreads(EncodingJobInfo state, EncodingOptions encodingOpt
             // Automatic
             if (threads <= 0 || threads >= Environment.ProcessorCount)
             {
-                return 0;
+                return Environment.ProcessorCount;
```
Comment (nyanmisaka) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2347]: `-threads 0` means auto, let ffmpeg decide.
I think threads <= 0 is an invalid value.

Comment (ferferga) [reply MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2347]: @nyanmisaka I think threads are ``<= 0`` when, in config, threads are set to ``Auto``. I'll check that.

Maybe this is the most optimal solution?

```
if (threads <= 0)
{
    return 0;
}
else if (threads >= Environment.ProcessorCount) 
{
    return Environment.ProcessorCount;
}
```

Comment (ferferga) [reply MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2347]: Btw, not for this PR, but I think we should make server send only the amount of cores that are available, instead of hardcoding them in client.

Comment (nyanmisaka) [reply MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2347]: That is most optimal for now.
The upper limit is 8 cores in jf-web, however ffmpeg can utilize 16 cores at most.

**Comment by ferferga** [comment]
@BaronGreenback Thought that it wasn't compiling in my PC because master was migrated to .NET 5 (that's what the console outputted) but in reality, it was because I need to update my SDK :)

I'm already building on Docker and testing that everything works correctly. Will rerequest you a review once it's done :).

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs (hunk 2 above)
Comment (ferferga) [reply MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2347]: @nyanmisaka After testing I can confirm you that 0 is returned when web is set to "Auto".

I'll make a commit with the proposed logic alongside the build fixes

**Comment by ferferga** [comment]
Now builds and it's working flawlesly at runtime.

image

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 3]
```diff
@@ -2329,22 +2329,25 @@ private string GetFixedSizeScalingFilter(Video3DFormat? threedFormat, int reques
...
+            if (outputVideoCodec != null && string.Equals(outputVideoCodec, "libvpx", StringComparison.OrdinalIgnoreCase))
             {
                 // per docs:
                 // -threads    number of threads to use for encoding, can't be 0 [auto] with VP8
                 //             (recommended value : number of real cores - 1)
                 return Math.Max(Environment.ProcessorCount - 1, 1);
             }
-
-            var threads = state.BaseRequest.CpuCoreLimit ?? encodingOptions.EncodingThreadCount;
+            var threads = state?.BaseRequest.CpuCoreLimit ?? encodingOptions.EncodingThreadCount;
```
Comment (nyanmisaka) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2341]: New line after braces.

**Review by nyanmisaka — CHANGES_REQUESTED** [review]

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs (hunk 3 above)
Comment (ferferga) [reply MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2342]: @nyanmisaka Done, thanks!

**Review by nyanmisaka — APPROVED** [review]

File: Jellyfin.Api/Controllers/VideoHlsController.cs [hunk 4]
```diff
@@ -359,7 +359,7 @@ public class VideoHlsController : BaseJellyfinApiController
         private string GetCommandLineArguments(string outputPath, StreamState state)
         {
             var videoCodec = _encodingHelper.GetVideoEncoder(state, _encodingOptions);
-            var threads = _encodingHelper.GetNumberOfThreads(state, _encodingOptions, videoCodec);
+            var threads = EncodingHelper.GetNumberOfThreads(state, _encodingOptions, videoCodec); // GetNumberOfThreads is static
```
Comment (BaronGreenback) [inline Jellyfin.Api/Controllers/VideoHlsController.cs:362]:
```suggestion
            var threads = EncodingHelper.GetNumberOfThreads(state, _encodingOptions, videoCodec); // GetNumberOfThreads is static.
```

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 5]
```diff
@@ -2329,22 +2329,26 @@ private string GetFixedSizeScalingFilter(Video3DFormat? threedFormat, int reques
         /// <summary>
         /// Gets the number of threads.
         /// </summary>
-        public int GetNumberOfThreads(EncodingJobInfo state, EncodingOptions encodingOptions, string outputVideoCodec)
+        public static int GetNumberOfThreads(EncodingJobInfo state, EncodingOptions encodingOptions, string outputVideoCodec)
         {
-            if (string.Equals(outputVideoCodec, "libvpx", StringComparison.OrdinalIgnoreCase))
+            if (outputVideoCodec != null && string.Equals(outputVideoCodec, "libvpx", StringComparison.OrdinalIgnoreCase))
```
Comment (BaronGreenback) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2334]: According to the docs, you don't need ```outputVideoCodec != null``` 

```
Parameters

a
    String

The first string to compare, or null.

b
    String

The second string to compare, or null.
```

https://docs.microsoft.com/en-us/dotnet/api/system.string.equals?view=net-5.0#System_String_Equals_System_String_System_String_

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 6]
```diff
@@ -2329,22 +2329,26 @@ private string GetFixedSizeScalingFilter(Video3DFormat? threedFormat, int reques
         /// <summary>
         /// Gets the number of threads.
         /// </summary>
-        public int GetNumberOfThreads(EncodingJobInfo state, EncodingOptions encodingOptions, string outputVideoCodec)
+        public static int GetNumberOfThreads(EncodingJobInfo state, EncodingOptions encodingOptions, string outputVideoCodec)
```
Comment (BaronGreenback) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2332]: if state can be null (line 2342), andd outputVideoCodec is passed null later in the code, shouldn't it be

```
public static int GetNumberOfThreads(EncodingJobInfo? state, EncodingOptions encodingOptions, string? outputVideoCodec)
```

**Review by BaronGreenback — CHANGES_REQUESTED** [review]

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs (hunk 5 above)
Comment (ferferga) [reply MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2334]: @BaronGreenback Oh true, that's some testing bits I left behind.

File: MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs [hunk 7]
```diff
@@ -2329,7 +2329,8 @@ private string GetFixedSizeScalingFilter(Video3DFormat? threedFormat, int reques
         /// <summary>
         /// Gets the number of threads.
         /// </summary>
-        public int GetNumberOfThreads(EncodingJobInfo state, EncodingOptions encodingOptions, string outputVideoCodec)
+#nullable enable
```
Comment (ferferga) [inline MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs:2332]: Not sure if this should be tabulated so it's in line with the function.

**Comment by PrplHaz4** [comment]
Any idea if this is going to impact DLNA or legacy devices that may not have the ability to display large or > 600px?  (or, is there some other safety net and this is irrelevant)

**Comment by ferferga** [comment]
@PrplHaz4 I'm not sure about DLNA because I don't use it but, for example, Web doesn't display images at full resolution: Web asks for the optimal size based on the screen resolution and server creates a version with the specified size and stores it in cache.

This prevents Jellyfin from altering the "masters": imagine every video you had in your library got processed and reescaled by Jellyfin with no choice (instead of, like it is right now, leaving originals intact and converting stuff when requested by clients). This is what was happening with embedded images and image extraction for no reason and what this PR fixes.

**Comment by PrplHaz4** [comment]
> 
> 
> @PrplHaz4 I'm not sure about DLNA because I don't use it but, for example, Web doesn't display images at full resolution: Web asks for the optimal size based on the screen resolution and server creates a version with the specified size and stores it in cache.
> 
> This prevents Jellyfin from altering the "masters": imagine every video you had in your library got processed and reescaled by Jellyfin when scanning, without any choice of avoiding that (instead of, like it is right now, leaving originals intact and converting stuff when requested by clients). This is what was happening with embedded images and image extraction for no reason and what this PR fixes.
> 
> If DLNA already does the same thing that web does, this doesn't change that.

Per [UMS ](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/6373d57e0d4461be95f5b9f9c8f536c7b21c1989/src/main/java/net/pms/dlna/DLNAImageProfile.java#L105) it looks like they define TN, SM, MED, LG, so in theory they could pull the size they want...so, hopefully that's what they do...

**Review by BaronGreenback — APPROVED** [review]
