### PR TITLE
Fixes zero byte nfo files.

### LINKED ISSUE #4826: Jellyfin cant create .nfo files on samba shares, instead  creates zero size .nfo files
**Describe the bug**
It ssounds to me that Jellyfin is not able to create .nfo files in the shared medias folders insetad it just creates 0 size .nfo files while throwing errors.

**System (please complete the following information):**
 - OS: Debian
 - Clients: Browser, Android
 - Browser:Firefox 76, Chrome 80
 - Jellyfin Version: 10.6.0.4 Systemd
 - Storage: local, Samba

I tested this also with Docker on Debian and it still has the same issue. 

**To Reproduce**

Enable .nfo storage in the media library
Set the media library path to a samba share

**Expected behavior**
It should not throw and error

The shares has fully r/w and even jellyfin user can create and remove files from those shares as I tested it manually 

like in those shared media folders

 `su - jellyfin && touch test.file`

Another point is that Jellyfin can actually delete media files from those shared media folders if the user asks for it. SO not sure how there can be a permission issue.

**Logs**

ls from the share (on the samba server
```
 users          0 Dec 19 11:50 #AskZBrush - “How can I load reference images into ZBrush as a separate subtools”.nfo       
users          0 Dec 19 11:50 #AskZBrush - “How can I increase the size of t~s created when using the Extractor Brush”.nfo

```

```
Dec 19 11:51:16 PC jellyfin[2565891]:    at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
Dec 19 11:51:16 PC jellyfin[2565891]:    at System.IO.FileStream.FlushWriteBuffer()
Dec 19 11:51:16 PC jellyfin[2565891]:    at System.IO.FileStream.Dispose(Boolean disposing)
Dec 19 11:51:16 PC jellyfin[2565891]:    at System.IO.Stream.Close()
Dec 19 11:51:16 PC jellyfin[2565891]:    at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveToFile(Stream stream, String path)
Dec 19 11:51:16 PC jellyfin[2565891]:    at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.Save(BaseItem item, CancellationToken cancellationToken)
Dec 19 11:51:16 PC jellyfin[2565891]:    at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadata(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
Dec 19 11:51:18 PC jellyfin[2565891]: [11:51:18] [ERR] [27] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
Dec 19 11:51:18 PC jellyfin[2565891]: System.UnauthorizedAccessException: Access to the path '/media/PLAY/media/029 ZBrush Surface Noise Dynamesh Boolean [_sShAmCLwMg].nfo' is denied.
Dec 19 11:51:18 PC jellyfin[2565891]:  ---> System.IO.IOException: Permission denied
Dec 19 11:51:18 PC jellyfin[2565891]:    --- End of inner exception stack trace ---
Dec 19 11:51:18 PC jellyfin[2565891]:    at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
Dec 19 11:51:18 PC jellyfin[2565891]:    at System.IO.FileStream.FlushWriteBuffer()
Dec 19 11:51:18 PC jellyfin[2565891]:    at System.IO.FileStream.Dispose(Boolean disposing)
Dec 19 11:51:18 PC jellyfin[2565891]:    at System.IO.Stream.Close()
Dec 19 11:51:18 PC jellyfin[2565891]:    at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveToFile(Stream stream, String path)
Dec 19 11:51:18 PC jellyfin[2565891]:    at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.Save(BaseItem item, CancellationToken cancellationToken)
Dec 19 11:51:18 PC jellyfin[2565891]:    at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadata(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
Dec 19 11:51:19 PC jellyfin[2565891]: [11:51:19] [ERR] [16] MediaBrowser.Providers.Manager.ProviderManager: Error in metadata saver
Dec 19 11:51:19 PC jellyfin[2565891]: System.UnauthorizedAccessException: Access to the path '/media/PLAY/media/03 - OpenCV with Python - Imshow in OpenCV and Matplotlib.nfo' is denied.
Dec 19 11:51:19 PC jellyfin[2565891]:  ---> System.IO.IOException: Permission denied
Dec 19 11:51:19 PC jellyfin[2565891]:    --- End of inner exception stack trace ---
Dec 19 11:51:19 PC jellyfin[2565891]:    at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
Dec 19 11:51:19 PC jellyfin[2565891]:    at System.IO.FileStream.FlushWriteBuffer()
Dec 19 11:51:19 PC jellyfin[2565891]:    at System.IO.FileStream.Dispose(Boolean disposing)
Dec 19 11:51:19 PC jellyfin[2565891]:    at System.IO.Stream.Close()
Dec 19 11:51:19 PC jellyfin[2565891]:    at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.SaveToFile(Stream stream, String path)
Dec 19 11:51:19 PC jellyfin[2565891]:    at MediaBrowser.XbmcMetadata.Savers.BaseNfoSaver.Save(BaseItem item, CancellationToken cancellationToken)
Dec 19 11:51:19 PC jellyfin[2565891]:    at MediaBrowser.Providers.Manager.ProviderManager.SaveMetadata(BaseItem item, ItemUpdateType updateType, IEnumerable`1 savers)
^C



```

### PR DESCRIPTION
**Pull request by BaronGreenback**
Fixes #4826 and bypasses dotnet bug. (https://github.com/dotnet/runtime/issues/42790)

May be other occurrences of this bug in JF.

From Dotnet Documentation
Filemode.Create - Specifies that the operating system should create a new file.

If the file already exists, it will be overwritten. This requires Write permission. 

FileMode.Create is equivalent to requesting that if the file does not exist, use CreateNew;
otherwise, use Truncate. (0 byte file)
If the file already exists but is a hidden file, an UnauthorizedAccessException exception is thrown.

### CODE REVIEW

**Review by Ladette19 — APPROVED** [review]

**Comment by kn-f** [comment]
@BaronGreenback works like a charm, thank you!

**Comment by BaronGreenback** [comment]
is there any other areas where this issue is being seen?

**Comment by kn-f** [comment]
@gerroon mentioned in one of his comments that the problem was also on NFS shares.
Unfortunately I don't have one so I cannot support testing on this.

**Comment by gerroon** [comment]
I tested it with Samba and Nfs shares on Linux and  Jellyfin has this issue with both filesystems . I do not have a Windows way of testing the issue.

**Review by crobibero — APPROVED** [review]

**Review by Ullmie02 — APPROVED** [review]

File: MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs [hunk 1]
```diff
@@ -203,10 +203,10 @@ private void SaveToFile(Stream stream, string path)
             var directory = Path.GetDirectoryName(path) ?? throw new ArgumentException($"Provided path ({path}) is not valid.", nameof(path));
             Directory.CreateDirectory(directory);
 
-            // On Windows, savint the file will fail if the file is hidden or readonly
+            // On Windows, saving the file will fail if the file is hidden or readonly
             FileSystem.SetAttributes(path, false, false);
 
-            using (var filestream = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.Read))
+            using (var filestream = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.None))
```
Comment (Bond-009) [inline MediaBrowser.XbmcMetadata/Savers/BaseNfoSaver.cs:209]: Maybe add a comment explaining why and add a link to the dotnet issue?

**Review by Bond-009 — APPROVED** [review]
